### ISSUE TITLE
yarn dev报错

### ISSUE THREAD

**Issue by bend2046** [nocobase/nocobase#1004]
## Describe the bug
\packages\core\server\src\plugin-manager\PluginManager.ts:207
      throw new Error(`${plugin} plugin already exists`);
Error: error-handler plugin already exists

## Version
0.8.0

**Comment by chenos** [comment]
能否提供更详细的信息呢
什么方式安装
什么数据库
什么版本
是安装过程中还是升级过程中，什么版本升级到什么版本
错误日志
运行流程或复现流程

**Comment by bend2046** [comment]
什么方式安装：git拉取代码
什么数据库：mysql8
什么版本：nocobase:0.8.0-alpha.5
是安装过程中还是升级过程中，什么版本升级到什么版本：安装过程中出现
错误日志

运行流程或复现流程：按官方提供的方式部署即会复现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nocobase/nocobase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 中午11:49
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [nocobase/nocobase] yarn dev报错 (Issue #1004)





 
能否提供更详细的信息呢
 什么方式安装
 什么数据库
 什么版本
 是安装过程中还是升级过程中，什么版本升级到什么版本
 错误日志
 运行流程或复现流程

**Comment by chenos** [comment]
v0.8.0-alpha.5 的版本的确有问题，后续修复了，拉取最新代码再试试，最新版 v0.8.0-alpha.9

**Comment by bend2046** [comment]
v0.8.0-alpha.9能正常启动了


Excel导入的功能预计什么时候开放？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nocobase/nocobase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 中午1:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [nocobase/nocobase] yarn dev报错 (Issue #1004)





 
v0.8.0-alpha.5 的版本的确有问题，后续修复了，拉取最新代码再试试，最新版 v0.8.0-alpha.9
