### ISSUE TITLE
v0.7.7-alpha.1后git源码升级版本失败

### ISSUE THREAD

**Issue by justwho** [nocobase/nocobase#1016]
## Describe the bug

v0.7.7-alpha.1 git源码升级到任意一个版本都无法正常成功升级

## Version

当前版本：v0.7.7-alpha.1
欲升级版本：最新

## How To Reproduce

遵循官网升级方法先git pull，然后yarn nocobase upgrade，就看到报错如下图所示：

![源码升级报错](https://user-images.githubusercontent.com/22259834/199628816-08d1ac6c-7880-485f-8300-67c39cacaf19.jpg)

**Comment by chenos** [comment]
3. 更新依赖
```bash
yarn install
```
更新依赖了吗？如果有问题，node_moduels 删掉再 yarn install，然后继续
