### ISSUE TITLE
按照插件开发文档，我新建了hello插件为何一直报错“plugin does not exist”

### ISSUE THREAD

**Issue by aiwenForGit** [nocobase/nocobase#1018]
## Describe the bug
如题：
![image](https://user-images.githubusercontent.com/241340/199635202-e6c3c49d-853e-4f93-b68c-2d78e90ae814.png)

## Version
最新版0.8
NocoBase version that you are using.

**Comment by aiwenForGit** [comment]
![image](https://user-images.githubusercontent.com/241340/199635234-36e95b6d-e04e-447f-be01-d005873cc540.png)

**Comment by chenos** [comment]
create 了吗？

```bash
yarn pm create hello
```

如果是手动创建的插件，需要

```bash
yarn install
```

**Comment by aiwenForGit** [comment]
create写了，就是用文档里面创建的，然后用yarn pm add hello出错的

**Comment by aiwenForGit** [comment]
自定义名字的插件不支持么

**Comment by chenos** [comment]
@aiwenForGit
pm create 的日志方便提供一下吗，看 pm add 的错误，试试 `yarn install` 再 pm add

**Comment by chenos** [comment]
> 自定义名字的插件不支持么

插件包前缀 https://docs-cn.nocobase.com/api/env#plugin_package_prefix

**Comment by baizn** [comment]
> @aiwenForGit pm create 的日志方便提供一下吗，看 pm add 的错误，试试 `yarn install` 再 pm add

使用源码方式安装 Nocobase，然后 yarn install 后再 pm add 就是正常的，使用 create-nocobase-app 后再 yarn install 后，使用 pm add 就是报如下错误：
![image](https://user-images.githubusercontent.com/9443867/199672424-8509572d-c593-46c7-bfc7-6af01de86036.png)

**Comment by MathArtist2** [comment]
我有完全相同的问题。也是同一个版本。

**Comment by chenos** [comment]
create-nocobase-app 安装的的确有这个问题，最新版已修复
