### ISSUE TITLE
重新安装 nocobase 报 plugin already exist

### ISSUE THREAD

**Issue by baizn** [nocobase/nocobase#1025]
## Version
0.8.0-alpha.9

NocoBase version that you are using.

## How To Reproduce
按照文档中的方式操作：https://docs-cn.nocobase.com/welcome/getting-started/installation/create-nocobase-app

yarn install 时候会报如下错误：

1. yarn nocobase install -f
2. 报错：plugin already exist
![image](https://user-images.githubusercontent.com/9443867/199675419-9a0cde4b-b5cf-47b2-ae39-a5e7a0cdcec2.png)

**Comment by baizn** [comment]
使用 yarn nocobase install -c 可以重新安装，但设置的 env 貌似没起作用
![image](https://user-images.githubusercontent.com/9443867/199676072-3c389f01-2dd5-428f-8eb6-bc41f17af314.png)

**Comment by chenos** [comment]
重装和 pm add 的问题最新版已修复
