### ISSUE TITLE
昨天拉取最新正常运行，今天看到更新后，在拉取最新运行就出现这个错误了

### ISSUE THREAD

**Issue by sbkmlvb** [nocobase/nocobase#1026]
![微信截图_20221103174015](https://user-images.githubusercontent.com/54029752/199688850-0be5009d-ca01-43dd-a67a-2ac063e187f8.png)
是用源码安装的

**Comment by sbkmlvb** [comment]
![微信截图_20221103174127](https://user-images.githubusercontent.com/54029752/199689038-79d2f44c-fb79-40c5-a9dc-ba9e8c6b38b0.png)

**Comment by chenos** [comment]
看报错是端口被占用了

**Comment by sbkmlvb** [comment]
> 看报错是端口被占用了

但是我查看了确实没有被占用， 只有启动后报错了才会出现端口在任务管理器里面，如果终止程序后端口就没有占用了

**Comment by chenos** [comment]
第一个截图是端口被占用的报错
![Snipaste_2022-11-04_15-53-11](https://user-images.githubusercontent.com/2993310/199921360-90d02fdc-3863-4d3b-b16c-f27d2ba22abd.jpg)
第二个截图看还在 Starting
还有问题可以试试更新最新版
```bash
git pull
yarn nocobase upgrade
```
