### ISSUE TITLE
附件太大上传出错

### ISSUE THREAD

**Issue by blogwy** [nocobase/nocobase#1030]
描述：
附件类别指定的是mp4，上传一个300mb的视频，结果报413：Request Entity Too Large

版本：
v0.8.0-alpha.9

部署方式：
docker

存储类型：
本地存储

系统/浏览器：
Chrome 107 macOS

**Comment by mytharcher** [comment]
可以尝试将容器内的 nginx 配置文件映射出来进行修改：

```
  volumes:
    - ./config/nocobase.conf:/etc/nginx/sites-enabled/nocobase.conf
```

修改文件内容：

```
client_max_body_size 20M; # 改成需要的大小，最大不超过 1G（目前的程序限制）
```

**Comment by blogwy** [comment]
> 可以尝试将容器内的 nginx 配置文件映射出来进行修改：
> 
> ```
>   volumes:
>     - ./config/nocobase.conf:/etc/nginx/sites-enabled/nocobase.conf
> ```
> 
> 修改文件内容：
> 
> ```
> client_max_body_size 20M; # 改成需要的大小，最大不超过 1G（目前的程序限制）
> ```

搞定了，先从容器里面复制出conf文件，然后映射。谢谢
