### ISSUE TITLE
docker 升级版本到0.8.0-alpha.9失败

### ISSUE THREAD

**Issue by chenjiao322** [nocobase/nocobase#1036]
原docker版本：0.7.4-alpha.7 
升级版本：0.8.0-alpha.9

操作步骤：
1、修改docker-compose.yml 中版本为nocobase/nocobase:0.8.0-alpha.9
2、移除原环境： docker-compose down -v
3、启动环境： docker-compose up -d
错误信息如下：
![1667545286497_86D90C5C-10B5-48b3-8407-37B76B96C0DE](https://user-images.githubusercontent.com/17329051/199914771-2c88672a-6031-4cb4-afd7-c10dfff46baf.png)

**Comment by chenos** [comment]
试试 0.8.0-alpha.13

**Comment by chenjiao322** [comment]
@chenos 感觉还是一样的报错
![image](https://user-images.githubusercontent.com/17329051/200219110-2db838c7-3e83-4e39-88b8-eb88ef9a2d94.png)
