### ISSUE TITLE
0.8.0-alpha.9 数据表管理 打开空，新增表也无法显示

### ISSUE THREAD

**Issue by cgssve** [nocobase/nocobase#1038]
## Describe the bug
![1234](https://user-images.githubusercontent.com/108384478/199925077-d2a28354-6e28-4b13-ab40-68d4e04384c1.png)

## Version

NocoBase version that you are using.

**Comment by chenos** [comment]
已修复，升级最新版就可以了
https://docs-cn.nocobase.com/welcome/getting-started/upgrading
