### ISSUE TITLE
为什么我根据教程连项目都起不来 T_T

### ISSUE THREAD

**Issue by xiaobaicaio** [nocobase/nocobase#105]
![image](https://user-images.githubusercontent.com/81469389/142375755-06f3d32b-ec86-4817-801e-d75d73264f29.png)

**Comment by chenos** [comment]
需要提供完整的终端日志，如果不行，推荐使用 docker

**Comment by xiaobaicaio** [comment]
搞定了 官方文档有问题写的nodejs是Node.js 12.20+就可以 但是其中有一个需要特定的两个node版本或者是15以上
