### ISSUE TITLE
多表关联时，主<->明相互建立关联，对主表记录进行编辑（非新增）时，服务侧JSON序列化循环引用错误。

### ISSUE THREAD

**Issue by bonashen** [nocobase/nocobase#1059]
## Describe the bug
多表关联时，主<->明相互建立关联，对主表记录进行编辑（非新增）时，报错。
错误如下：
<html>
<body>

TypeError: Converting circular structure to JSON
--
Tue, Nov 8 2022 8:02:25 pm | --> starting at object with constructor 'Sequelize'
Tue, Nov 8 2022 8:02:25 pm | \| property 'dialect' -> object with constructor 'PostgresDialect'
Tue, Nov 8 2022 8:02:25 pm | --- property 'sequelize' closes the circle
Tue, Nov 8 2022 8:02:25 pm | at JSON.stringify (<anonymous>)
Tue, Nov 8 2022 8:02:25 pm | at respond (/app/nocobase/node_modules/koa/lib/application.js:279:15)
Tue, Nov 8 2022 8:02:25 pm | at handleResponse (/app/nocobase/node_modules/koa/lib/application.js:166:34)
Tue, Nov 8 2022 8:02:25 pm | at runMicrotasks (<anonymous>)
Tue, Nov 8 2022 8:02:25 pm | at processTicksAndRejections (node:internal/process/task_queues:96:5)

</body>
</html>

## Version

nocobase:0.8.0-alpha.13

**Comment by hongboji** [comment]
请问是什么数据库，环境是部署新的还是升级上来的，关系类型是怎么配置的 ，具体的是哪种 ，例如： a 关联 b ，a 一对一 has one b , 一对多 ，是使用了json字段类型 ？

**Comment by bonashen** [comment]
database dialect: PostgresDialect
order->orderDetails (one to many)
orderDetails->order(many to one)
无JSON字段
