### ISSUE TITLE
能否考虑在未来加入流程引擎？

### ISSUE THREAD

**Issue by JackyGuo** [nocobase/nocobase#106]
最近偶然发现nocobase，太棒了！非常看好这个项目～
但我目前项目中涉及到流程审批，不止作者及开发团队是否有计划在未来把这个作为插件加入到项目中
非常感谢～

**Comment by zhouyanliang** [comment]
Hi，流程引擎在计划中，基础打好之后就会安排

**Comment by gj-zhang** [comment]
@zhouyanliang 流程引擎有什么进展吗

**Comment by zhouyanliang** [comment]
基础版本已经提供
