### ISSUE TITLE
升级到0.8.0-alpha.13，api/app:getLang显示Not Found

### ISSUE THREAD

**Issue by zhzhyaya** [nocobase/nocobase#1062]
## Describe the bug

程序正常启动，但api显示not found

## Version

0.8.0-alpha.13

## Expected behavior

启动进不去页面

## Screenshots
![image](https://user-images.githubusercontent.com/19954642/200718834-174ba9c1-3d54-4e87-b3bb-ce2cfb1571ff.png)

## Desktop (please complete the following information)

- OS: [windows]
- Browser [google]

**Comment by hongboji** [comment]
是源码安装的吗？ 是按照官网升级拉取代码的吗 ？ 可以执行  yarn nocobase install --lang=zh-CN   再启动看看

**Comment by vfasky** [comment]
执行 `yarn nocobase install --lang=zh-CN`

会提示清空数据。。。  不敢操作啊

```bash
$ yarn nocobase install -f

This operation will clear the database!!!
```
