### ISSUE TITLE
Doubt dropbox with decision

### ISSUE THREAD

**Issue by joaoguariglia** [nocobase/nocobase#1092]
Hello,
My doubt is simple, how do I put a dropbox where I have a decision?

For example:
[ S.O ]
 [Windows]
   [Windows 2022 standard]
   [Windows 2022 Essentials]
 [Linux]
  [RHEL 8.5]
  [RHEL 8.4]

**Comment by hongboji** [comment]
Thank you for your feedback, please use the report template to provide more information in order to pinpoint the problem!
