### ISSUE TITLE
windows 最新代码 yarn dev报错

### ISSUE THREAD

**Issue by RollwayBourne** [nocobase/nocobase#1121]
yarn dev
yarn run v1.22.19
$ nocobase dev
WAIT: TypeScript compiling...
Connection has been established successfully.
Connection has been established successfully.
starting server 13001
starting client 13000
[INFO] 09:41:11 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.5.5)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
VERSION:  0.8.0-alpha.13
Starting the development server...

× Webpack

* @nocobase/client in ./packages/app/client/src/pages/index.tsx

To install it, you can run: npm install --save @nocobase/client

This relative module was not found:

* ./lib/client in ./packages/plugins/audit-logs/client.js, ./packages/plugins/china-region/client.js and 5 others
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\DumpStack.log.tmp'
Connection has been established successfully.

按照Git 源码安装 一步步执行下来的。
node -v: v14.9.2
npm -v: 6.14.17
yarn -v: 1.22.19
**同样的配置 mac可以启动。请问这样的问题如何排查解决呢** ？
参考 上面 执行完  npm install --save @nocobase/client 再执行yarn dev 报: 'nocobase' 不是内部或外部命令，也不是可运行的程序

之后再执行 yarn install
则报:
error D:\work\master\my-nocobase-app\node_modules\sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: D:\work\master\my-nocobase-app\node_modules\sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@14.19.2 | win32 | x64
node-pre-gyp info check checked for "D:\work\master\my-nocobase-app\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node" (not found)
node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-win32-unknown-x64.tar.gz
node-pre-gyp ERR! install request to https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-win32-unknown-x64.tar.gz failed, reason: read ECONNRESET
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.8 and node@14.19.2 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error request to https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.8/napi-v6-win32-unknown-x64.tar.gz failed, reason: read ECONNRESET
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@14.19.2 | win32 | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@14.19.2 | win32 | x64
gyp info find Python using Python version 3.11.0 found at "C:\Users\rollway\AppData\Local\Programs\Python\Python311\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2022 (17.4.33110.190) found at:
gyp ERR! find VS "D:\develop\vs"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - missing any VC++ toolset
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (D:\work\master\my-nocobase-app\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at D:\work\master\my-nocobase-app\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\work\master\my-nocobase-app\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at D:\work\master\my-nocobase-app\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at D:\work\master\my-nocobase-app\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at D:\work\master\my-nocobase-app\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at D:\work\master\my-nocobase-app\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\work\\master\\my-nocobase-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\work\\master\\my-nocobase-app\\node_modules\\sqlite3\\lib\\binding\
\napi-v6-win32-unknown-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\work\\master\\my-nocobase-app\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-unknown-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd D:\work\master\my-nocobase-app\node_modules\sqlite3
gyp ERR! node -v v14.19.2
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\work\master\my-nocobase-app\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\work\master\my-nocobase-app\node_modules\sqlite3\lib\b
inding\napi-v6-win32-unknown-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\work\master\my-nocobase-app\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\work\master\my-nocobase-app\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1088:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
node-pre-gyp ERR! System Windows_NT 10.0.22000
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\work\\master\\my-nocobase-app\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\work\master\my-nocobase-app\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.19.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.9

**Comment by RollwayBourne** [comment]
windows死活起不来，用wsl Ubuntu起来了

**Comment by jeeinn** [comment]
使用 power shell 运行时可以看到有一个未检测到 WSL 的提示：WSL is not installed, so could not detect WSL profiles
```
PS F:\pub-projects\my-nocobase-app> yarn dev
yarn run v1.22.21
$ nocobase dev
WAIT: TypeScript compiling...
starting server 13001
starting client 13000

[main 2024-01-06T08:31:39.531Z] update#setState idle
VERSION:  0.18.0-alpha.1
[main 2024-01-06T08:31:42.870Z] WSL is not installed, so could not detect WSL profiles
VERSION:  0.18.0-alpha.1
info  - Umi v4.0.89
info  - Preparing...
[HPM] Proxy created: /api/  -> http://127.0.0.1:13001
[HPM] Proxy rewrite rule created: "^/api/" ~> "/api/"
[HPM] Proxy created: /storage/uploads/  -> http://127.0.0.1:13001
[HPM] Proxy created: /static/  -> http://127.0.0.1:13001
            ╔════════════════════════════════════════════════════╗
            ║ App listening at:                                                                                                           ║
            ║  >   Local: http://localhost:13000                                                                                 ║
ready - ║  > Network: http://10.6.0.24:13000                                                                              ║
            ║                                                                                                                                       ║
            ║ Now you can open browser with the above addresses↑                                             
```

我最后是使用`docker`方式来启动
