### ISSUE TITLE
自开发插件时，使用useResource钩子报错

### ISSUE THREAD

**Issue by bonashen** [nocobase/nocobase#1128]
https://github.com/nocobase/nocobase/blob/7bffc94b807c23619598a9fd888138509f653330/packages/core/sdk/src/APIClient.ts#L226

上面是关联代码，没有考虑API axios baseURL及/api相关的设定。

```js

const WechatSetting=()=>{
    const settingRes = useResource('wechatSetting'); // 写成useResource('/api/wechatSetting')反而可以成功访问
    useMount(()=>{
      settingRes.get(); // 此时访问的URL 变成主机头 wechatSetting:get
});

}

```

**Comment by chenos** [comment]
建议使用 useRequest  

https://github.com/nocobase/nocobase/blob/7bffc94b807c23619598a9fd888138509f653330/packages/core/client/src/api-client/index.md#userequest

```ts
const {  data } = useRequest({ resource: 'wechatSetting', action: 'get' });
```
