### ISSUE TITLE
现在开发插件 总是要build才起作用

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1147]
## Describe the bug
比如 hello 插件 开发完src 源代码不起作用
必须yarn nocobase build samples/hello   重新yarn dev 才起作用

感觉跟这次提交有关https://github.com/nocobase/nocobase/commit/9ad4bff62b4219ce41b2dc48d5e75f53c9be9d04

麻烦核查一下
## Version

git 最新版

**Comment by chenos** [comment]
@baiheinet 看起来 Windows 平台下的路径有点问题
