### ISSUE TITLE
跑 test 会清空数据库

### ISSUE THREAD

**Issue by zysam** [nocobase/nocobase#1148]
<img width="699" alt="Screen Shot 2022-11-27 at 00 10 41" src="https://user-images.githubusercontent.com/1755427/204098220-75dd221c-f74d-4951-9c23-a41bc639354e.png">

mockData 默认是 `storage: ':memory:'`，
然而，这段代码的逻辑，根据 .env 获取 DB_STORAGE 变量，覆盖默认。
这是开发和测试不能兼顾吗？

**Comment by mytharcher** [comment]
可以使用 `.env.test` 作为测试用的环境变量定义文件，以做区分。

**Comment by zysam** [comment]
> 

看了 cli 入口判断，算是 hack 吧。安装时，是不是也该默认生成 .env.test 文件呢？

**Comment by chenos** [comment]
> 看了 cli 入口判断，算是 hack 吧。安装时，是不是也该默认生成 .env.test 文件呢？

@zysam 感谢反馈，已改进
