### ISSUE TITLE
源码安装git pull更新升级后无法正常打开页面

### ISSUE THREAD

**Issue by justwho** [nocobase/nocobase#1161]
版本：git源码安装，git pull源码同步升级至11月26号是正常的。
问题：11月27号git pull源码同步升级至最新后yarn nocobase upgrade均无异常，但是网页一直无法正常访问。
表现现象：如下截图所示，打开页面左上角有个蓝色四点一直旋转加载样式，但无法正常显示正常页面。按F12调试显示为右侧部分，并附上黑色部分为yarn start后的log打印部分。
![Snipaste_2022-11-30_09-07-01](https://user-images.githubusercontent.com/22259834/204683860-86d9d2c6-a0fa-45bd-a184-95a8a0bb3d88.jpg)

**Comment by justwho** [comment]
@chenos 可以帮忙看看是什么问题吗？

**Comment by mytharcher** [comment]
尝试 `yarn build` 一次再 `start` 看看？

**Comment by chenos** [comment]
@justwho 是 Windows 系统吗？更新到最新版再试试

**Comment by justwho** [comment]
> 尝试 `yarn build` 一次再 `start` 看看？

我试了两次yarn install后执行yarn build，最后yarn start成功进入页面了。谢谢了！



> @justwho 是 Windows 系统吗？更新到最新版再试试

  不是Windows，就是Linux环境下。问题已经在mytharcher的建议中解决了。再次感谢两位的帮助。谢谢！

**Comment by justwho** [comment]
问题已经解决，谢谢！
