### ISSUE TITLE
oldValue.sort is not a function when adding a single select to a form

### ISSUE THREAD

**Issue by rafik24** [nocobase/nocobase#1167]
## Describe the bug

When adding a single select to a form and submitting the error message "oldValue.sort is not a function"  appears and it is impossible to 
save/submit the form.

## Version

NocoBase 0.8 Alpha 13

## How To Reproduce

1. Create a collection with a single select field
2. Create a form
3. Add an entry
4. Select the single select field
5. press submit

## Expected behavior

The form should save

#

![image](https://user-images.githubusercontent.com/27220284/204868471-d252ca3e-efa8-44aa-a97d-5bc3448e28d9.png)

## Desktop (please complete the following information)

- OS: Win 10
- Browser: Chrome
- Version Version 107.0.5304.108

**Comment by hongboji** [comment]
The following information can be provided for diagnosing the problem.
1. Is the system newly deployed or is it an upgraded version?
2. Has the content of the drop-down menu been modified since the form was created?
3. Screenshot of the data table, screenshot of the content of the drop-down menu

Try to solve the problem by.
1. Clear the browser cache
2. Re-create the form

**Comment by hongboji** [comment]
Please provide the detailed logs

**Comment by rafik24** [comment]
> Please provide the detailed logs

Hi @hongboji,

Thank you for your prompt response.

I have looked in the chrome devtools cannot see anything when doing the POST.

I looked around and could not find anything related in the logs.

Can you please point me to where I should look ?

Thank you in advance,
Rafik

**Comment by hongboji** [comment]
> @rafik24 What is the way you start nocobase, please?

**Comment by hongboji** [comment]
@rafik24  What is the way you start nocobase, please?

**Comment by rafik24** [comment]
Hi @hongboji,

I am running on docker and I have changed the docker file to run yarn dev instead of yarn start.

I did not manage to replicate this issue on a new build so I will blame the build.

Thank you for your prompt support.

Rafik
