### ISSUE TITLE
docker install error: ConnectionRefusedError

### ISSUE THREAD

**Issue by alexcool2016** [nocobase/nocobase#1185]
## Describe the bug

follow the docker install guide, cannot be done, and check logs shows the mysql  ConnectionRefusedError, and other errors.

## Version

[NocoBase version that you are using.](nocobase:0.8.0-alpha.13)

## How To Reproduce

1. cd docker/app-mysql
2. docker-compose up -d
3. docker-compose logs app
4. Error logs as below:
app_1    | nginx started
app_1    | copying...
app_1    | yarn run v1.22.19
app_1    | $ nocobase db:auth --retry=30
app_1    | /app/nocobase/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92
app_1    |           throw new SequelizeErrors.ConnectionRefusedError(err);
app_1    |                 ^
app_1    | 
app_1    | ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 172.19.0.2:3306
app_1    |     at ConnectionManager.connect (/app/nocobase/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
app_1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1    |     at async ConnectionManager._connect (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:220:24)
app_1    |     at async /app/nocobase/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
app_1    |     at async ConnectionManager.getConnection (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
app_1    |     at async /app/nocobase/node_modules/sequelize/lib/sequelize.js:304:26
app_1    |     at async MySQLQueryInterface.showAllTables (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:147:24) {
app_1    |   parent: Error: connect ECONNREFUSED 172.19.0.2:3306
app_1    |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
app_1    |     errno: -111,
app_1    |     code: 'ECONNREFUSED',
app_1    |     syscall: 'connect',
app_1    |     address: '172.19.0.2',
app_1    |     port: 3306,
app_1    |     fatal: true
app_1    |   },
app_1    |   original: Error: connect ECONNREFUSED 172.19.0.2:3306
app_1    |       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
app_1    |     errno: -111,
app_1    |     code: 'ECONNREFUSED',
app_1    |     syscall: 'connect',
app_1    |     address: '172.19.0.2',
app_1    |     port: 3306,
app_1    |     fatal: true
app_1    |   }
app_1    | }

## Expected behavior

nocobase installed and startup successfully.

## Screenshots
[the log.txt](https://github.com/nocobase/nocobase/files/10139299/the.log.txt)

## Desktop (please complete the following information)

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 107.0.5304.107 (Official Build) (64-bit)

**Comment by chenos** [comment]
Please check the database information.

**Comment by alexcool2016** [comment]
May I know how? as the mysql was also in the docker, and I used the default settings of the yml file.

**Comment by rouhu** [comment]
I got same error after default docker install. For some reason (config ?) the APP container is not in the same network as the MySQL. After APP container was added to the same network, it was able to connect to MySQL.

**Comment by chenos** [comment]
Example：https://github.com/nocobase/nocobase/blob/main/docker/app-mysql/docker-compose.yml

<img width="655" alt="image" src="https://user-images.githubusercontent.com/2993310/205807559-bffb32a1-9d7d-453a-bc5f-7e05b2eb9ca4.png">

**Comment by rouhu** [comment]
After the container "app-mysql_app_1" is added to network "app-mysql_nocobase" the container is able to start. However, when the page http://myserver.com:13000 is called it gives javascript errors:
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
:13000/api/app:getPlugins:1          Failed to load resource: the server responded with a status of 502 (Bad Gateway)
umi.37f475d7.js:1 Uncaught (in promise) Error: Request failed with status code 502
    at LYNF.e.exports (umi.37f475d7.js:1:1624480)
    at Rn+g.e.exports (umi.37f475d7.js:1:3775050)
    at XMLHttpRequest.w (umi.37f475d7.js:1:6177327)
