### ISSUE TITLE
window下git源码安装方式，本地存储成功上传，但是无法正常显示，链接有误？

### ISSUE THREAD

**Issue by aiwenForGit** [nocobase/nocobase#1190]
最新版的git源码安装的，但是上传图片是正常的，文件存储是默认设置的，就是无法显示，不知道怎么改？求助@ @zhouyanliang @chenos
![image](https://user-images.githubusercontent.com/241340/205433098-55b5a6ee-edd9-4737-88bf-2a28e7ddbc7a.png)
自己设置一个myfile目录，创建了另外一个本地存储，上传后也是显示不出来的。
![image](https://user-images.githubusercontent.com/241340/205433135-c5c495d5-55d5-4f8a-aa5d-e003655bb2ee.png)
无法访问链接，如图
![image](https://user-images.githubusercontent.com/241340/205433163-dd3f38ca-100b-4063-a0a7-8e611f63b48c.png)
请各位大师帮忙下，谢谢！

**Comment by aiwenForGit** [comment]
![image](https://user-images.githubusercontent.com/241340/205433098-55b5a6ee-edd9-4737-88bf-2a28e7ddbc7a.png)
自己设置一个myfile目录，创建了另外一个本地存储，上传后也是显示不出来的。
![image](https://user-images.githubusercontent.com/241340/205433135-c5c495d5-55d5-4f8a-aa5d-e003655bb2ee.png)
无法访问链接，如图
![image](https://user-images.githubusercontent.com/241340/205433163-dd3f38ca-100b-4063-a0a7-8e611f63b48c.png)
请各位大师帮忙下，谢谢！

**Comment by baiheinet** [comment]
我觉得跟这个问题的原理一致https://github.com/nocobase/nocobase/discussions/1150

**Comment by mytharcher** [comment]
与 #1137 类似，会一起跟踪，重复的就先关闭了。

**Comment by mytharcher** [comment]
#1226 中已修复， @aiwenForGit 可以看下 main 分支是否还有问题。
