### ISSUE TITLE
Feature request: Database dump from the demo host

### ISSUE THREAD

**Issue by rafik24** [nocobase/nocobase#1202]
Hi All,

To start I really like nocobase and how intuitive you guys have made it.

I have registered for a trial and got a host up and running and I am wondering if it would be possible to have a dump of the database used to create the demo host so I can use it without having to create it all manually. 

It would help other users too if we had the dump somewhere in the codebase like in examples.

Thanks in advance,
Rafik

**Comment by zhouyanliang** [comment]
We'll release export&import plugin this month.

**Comment by rafik24** [comment]
@zhouyanliang thank you for the update !

Closing
