### ISSUE TITLE
链接类菜单，能不能不弹窗新窗口显示，而显示再当前窗口的工作区

### ISSUE THREAD

**Issue by minitiger1974** [nocobase/nocobase#1206]
![image](https://user-images.githubusercontent.com/74164203/205831265-e86e78dc-f063-4803-9029-8ffac36e41db.png)

**Comment by chenos** [comment]
可以加一个页面，然后页面里再加一个iframe区块，每个页面都放一个iframe，也能达到效果。iframe可以放markdown区块里，也可以扩展个 iframe 区块来配置iframe

**Comment by minitiger1974** [comment]
谢谢
