### ISSUE TITLE
bug(plugin-workflow):变量复制 不起作用

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1215]
![screenshots](https://user-images.githubusercontent.com/900786/206347411-a8a8e9cf-b8ab-4f2b-83dc-c016aa521a61.gif)

**Comment by mytharcher** [comment]
看录像现在只选了“触发器变量/触发数据”，是不是还要先选一下字段？

**Comment by lyf-coder** [comment]
复制框这里要是有值的时候说明是可以复制使用的，否则就需要确认是否选择可用变量，现在看录像的确是需要先选择一下具体字段的

**Comment by baiheinet** [comment]
字段也不行啊
![screenshots](https://user-images.githubusercontent.com/900786/206354353-d4be074c-655f-4810-8100-4a7ec3a3caa6.gif)

**Comment by lyf-coder** [comment]
方便看一下是哪个版本吗？
<img width="322" alt="image" src="https://user-images.githubusercontent.com/58352715/206354633-61daf3ce-f697-4e9e-a6bf-3547fc3e8318.png">

**Comment by lyf-coder** [comment]
main分支目前确认存在此问题，是一个bug

**Comment by aiwenForGit** [comment]
也碰到同样问题，复制不成功，为空。
