### ISSUE TITLE
error An unexpected error occurred: "EPERM: operation not permitted, open 'D:\\Program Files\\nodejs\\node_global\\bin\\create-nocobase-app'".

### ISSUE THREAD

**Issue by Lc-6017203168** [nocobase/nocobase#122]
error An unexpected error occurred: "EPERM: operation not permitted, open 'D:\\Program Files\\nodejs\\node_global\\bin\\create-nocobase-app'".

**Comment by chenos** [comment]
能不能描述的更完整、清晰一点？
