### ISSUE TITLE
plugin-workflow:HTTP 请求<%=ctx.data%> 会转换成 "body": "[object Object]",

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1227]
![image](https://user-images.githubusercontent.com/900786/206825254-1c9e8c07-bc25-4736-9b54-b8fa35a23017.png)

![image](https://user-images.githubusercontent.com/900786/206825278-bebf5b3c-e331-4c75-a660-1812c40591d9.png)

**Comment by aiwenForGit** [comment]
> ![image](https://user-images.githubusercontent.com/900786/206825254-1c9e8c07-bc25-4736-9b54-b8fa35a23017.png)
> 
> ![image](https://user-images.githubusercontent.com/900786/206825278-bebf5b3c-e331-4c75-a660-1812c40591d9.png)

需要对json对象反序列化。可以这么写
<%=JSON.stringify(ctx.data)%>就可以了

**Comment by baiheinet** [comment]
> > ![image](https://user-images.githubusercontent.com/900786/206825254-1c9e8c07-bc25-4736-9b54-b8fa35a23017.png)
> > ![image](https://user-images.githubusercontent.com/900786/206825278-bebf5b3c-e331-4c75-a660-1812c40591d9.png)
> 
> 需要对json对象反序列化。可以这么写 <%=JSON.stringify(ctx.data)%>就可以了

不行 这样 就ok <%- JSON.stringify(ctx.data) %>
