### ISSUE TITLE
工作流编辑后，无法保存，出错

### ISSUE THREAD

**Issue by aiwenForGit** [nocobase/nocobase#1228]
如图：
![image](https://user-images.githubusercontent.com/241340/206827709-af43ab7e-90b5-4400-b581-4b843bfbfd46.png)

修改了任何数据，点击提交按钮，出错了。

**Comment by mytharcher** [comment]
提示信息暂时没有翻译，“已执行过的工作流不可修改”，可以选择复制到新版本再修改。

**Comment by aiwenForGit** [comment]
谢谢
