### ISSUE TITLE
(plugin-workflow): 开启 数据变动 http 后 新建数据就会弹出错误，还像是权限还是什么

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1240]
## Describe the bug
本地yarn dev 没有问题， 上传主机后 yarn start 就会出错

## Screenshots
![image](https://user-images.githubusercontent.com/900786/207220024-d52882f4-0111-4c0c-846d-1542061caeaf.png)

![207219801-e58678c6-f8b9-4634-a835-17194239c85b](https://user-images.githubusercontent.com/900786/207250501-4b9f95b2-423f-4688-93dd-c6db1e08e892.png)

**Comment by mytharcher** [comment]
看下请求怎么配置的？`Cannot read properties of undefiend (reading 'run')` 这个应该是找不到指令的问题，不过这个报错在 main 没有复现出来。

**Comment by baiheinet** [comment]
tks 提醒后 明白了 workflow 也需要build 我一直是那个修改了build那个
