### ISSUE TITLE
前段页面静态文件使用相对路径访问

### ISSUE THREAD

**Issue by imtos** [nocobase/nocobase#1269]
使用nginx反向代理nocobase-server时，location 为二级路经，无法正常访问静态文件。

如访问http://nginx-eip/nocobase/
现状：页面返回的静态文件路径为绝对地址，http://nginx-eip/umi.37f475d7.js
期望：页面返回的静态文件路径为相对地址，http://nginx-eip/nocobase/umi.37f475d7.js

谢谢。

**Comment by chenos** [comment]
https://github.com/nocobase/nocobase/blob/main/packages/app/client/.umirc.ts#L8

这个位置加个 publicPath

```ts
export default defineConfig({
  publicPath: process.env.NODE_ENV === 'production' ? '/foo/' : '/',
});
```
