### ISSUE TITLE
bug(plugin-workflow): 数据表事件 对关联字段 不产生触发器变量

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1271]
RT

**Comment by mytharcher** [comment]
麻烦给出更详细的信息，关联字段指的是？期待的情况是？

**Comment by baiheinet** [comment]
关联字段Area
![image](https://user-images.githubusercontent.com/900786/209021822-2d7e7740-5561-4d7e-97a2-356526d689d9.png)
触发器变量 里没有关联字段 Area
![image](https://user-images.githubusercontent.com/900786/209021957-fbc37959-cd9a-42ff-ba4d-07b1978d22c5.png)

**Comment by mytharcher** [comment]
“关联”对应的底层实现是多对多，在触发数据中只有多对一（belongsTo）可以直接被引用，也就是只有当前表数据可以被引用。如果流程中需要其他数据，暂时可以加一个查询节点查出后另行使用。

**Comment by baiheinet** [comment]
> “关联”对应的底层实现是多对多，在触发数据中只有多对一（belongsTo）可以直接被引用，也就是只有当前表数据可以被引用。如果流程中需要其他数据，暂时可以加一个查询节点查出后另行使用。

可是 多对多 会出现在触发器变量里
![image](https://user-images.githubusercontent.com/900786/209070858-c913158e-8f2a-49c9-87cd-922c3e605acb.png)

**Comment by mytharcher** [comment]
触发数据里没有的话可能是其他问题，不过工作流这里主要是暂时不提供对多的变量选择，所以暂时也只能对一的变量。

**Comment by baiheinet** [comment]
如果多对多 我按添加一部查询，可是中间表不支持查询
![image](https://user-images.githubusercontent.com/900786/211511856-ede0e9c8-ce16-45f0-8691-8fe248703d6b.png)
