### ISSUE TITLE
Fresh start with sequalize error

### ISSUE THREAD

**Issue by nerkn** [nocobase/nocobase#1273]
## Describe the bug

started docker compose, warn: Cannot read properties of undefined (reading 'field') rised and app exited

## Version
 
0.8

## How To Reproduce

1. Addded nocobase to my docker-compose file
  nocobase:
    image: nocobase/nocobase:main
    environment:
      - DB_DIALECT=mysql
      - DB_HOST=db
      - DB_DATABASE=nocobase
      - DB_USER=user
      - DB_PASSWORD=pass
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "8880:80"

3. docker-compose up nocobase
4.Error
Recreating wedding_nocobase_1 ... done
Attaching to wedding_nocobase_1
nocobase_1  | nginx started
nocobase_1  | copying...
nocobase_1  | yarn run v1.22.19
nocobase_1  | $ nocobase start --quickstart
nocobase_1  | Connection has been established successfully.
nocobase_1  | Start installing NocoBase
nocobase_1  | Database dialect: mysql
nocobase_1  | Initialize all built-in plugins
nocobase_1  | Reload the application configuration
nocobase_1  | Connection has been established successfully.
nocobase_1  | upgrading...
nocobase_1  | Reload the application configuration
nocobase_1  | warn: Cannot read properties of undefined (reading 'field') {"stack":"TypeError: Cannot read properties of undefined (reading 'field')\n    at new BelongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/belongs-to-many.js:81:69)\n    at Function.belongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/mixin.js:43:25)\n    at BelongsToManyField.bind (/app/nocobase/node_modules/@nocobase/database/lib/fields/belongs-to-many-field.js:84:42)\n    at Collection.<anonymous> (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:193:13)\n    at Collection.emit (node:events:527:28)\n    at Collection.emit (node:domain:475:12)\n    at Collection.setField (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:240:10)\n    at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:141:25\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:34:103)","timestamp":"2022-12-20T16:00:46.800Z"}
nocobase_1  | /app/nocobase/node_modules/sequelize/lib/associations/belongs-to-many.js:81
nocobase_1  |     this.sourceKeyField = this.source.rawAttributes[this.sourceKey].field || this.sourceKey;
nocobase_1  |                                                                     ^
nocobase_1  | 
nocobase_1  | TypeError: Cannot read properties of undefined (reading 'field')
nocobase_1  |     at new BelongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/belongs-to-many.js:81:69)
nocobase_1  |     at Function.belongsToMany (/app/nocobase/node_modules/sequelize/lib/associations/mixin.js:43:25)
nocobase_1  |     at BelongsToManyField.bind (/app/nocobase/node_modules/@nocobase/database/lib/fields/belongs-to-many-field.js:84:42)
nocobase_1  |     at Collection.<anonymous> (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:193:13)
nocobase_1  |     at Collection.emit (node:events:527:28)
nocobase_1  |     at Collection.emit (node:domain:475:12)
nocobase_1  |     at Collection.setField (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:240:10)
nocobase_1  |     at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:141:25
nocobase_1  |     at Generator.next (<anonymous>)
nocobase_1  |     at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/lib/models/field.js:34:103)
nocobase_1  | /app/nocobase/node_modules/execa/lib/error.js:60
nocobase_1  | 		error = new Error(message);
nocobase_1  | 		        ^
nocobase_1  | 
nocobase_1  | Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
nocobase_1  |     at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
nocobase_1  |     at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
nocobase_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
nocobase_1  |     at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/start.js:46:9) {
nocobase_1  |   shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
nocobase_1  |   command: 'node ./packages/app/server/lib/index.js upgrade',
nocobase_1  |   escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
nocobase_1  |   exitCode: 1,
nocobase_1  |   signal: undefined,
nocobase_1  |   signalDescription: undefined,
nocobase_1  |   stdout: undefined,
nocobase_1  |   stderr: undefined,
nocobase_1  |   failed: true,
nocobase_1  |   timedOut: false,
nocobase_1  |   isCanceled: false,
nocobase_1  |   killed: false
nocobase_1  | }
nocobase_1  | error Command failed with exit code 1.
nocobase_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
wedding_nocobase_1 exited with code 1

## Expected behavior
Start normally

## Additional context
Some config mistake?

**Comment by chenos** [comment]
Try this
https://github.com/nocobase/nocobase/blob/main/docker/app-sqlite/docker-compose.yml
https://docs.nocobase.com/welcome/getting-started/installation/docker-compose
