### ISSUE TITLE
列表超长内容显示错误

### ISSUE THREAD

**Issue by zhanghpro** [nocobase/nocobase#1300]
## Describe the bug

列表中某一列内容超长，无法通知指定列宽修改该列展示宽度，同时该列内容超出列宽与下一列内容重叠

## Version

0.8.0 alpha。13

## How To Reproduce

对于列表内容进行超长配置，同时修改列表列宽属性，查看列表展示效果

## Expected behavior

列宽根据配置变化，内容超出列宽部分隐藏.

## Screenshots

![捕获](https://user-images.githubusercontent.com/20272909/210051225-f7cd4aff-0c69-439e-962b-9e36ed464bc4.PNG)
## Desktop (please complete the following information)

- OS: win10

- Browser edge

**Comment by Dunqing** [comment]
designer可以设置列框

**Comment by zhanghpro** [comment]
我使用了设置列宽的功能的，但是存在两个问题：
1、设置列宽不生效，如图所示，不管我把列宽设置成小于或大于默认值200，在页面上都看不出效果
2、超长部分超出列宽显示与后面列中的内容重叠了，只有在鼠标滑过时，才会隐藏超长部分

**Comment by zhangzhonghe** [comment]
#1415 修复了内容溢出的问题。
