### ISSUE TITLE
数据选择器筛选问题

### ISSUE THREAD

**Issue by breathsoft** [nocobase/nocobase#1323]
编辑表单时，（一对多字段的）数据选择器里的记录不能筛选，点击筛选记录会导致记录不显示（跟踪后发现数据关联本记录的ID作为条件导致）不点击筛选正常显示所有记录（未关联的）。

**Comment by breathsoft** [comment]
另外来源跟踪里发现fields列表里有很多个createdById字段，不知道什么原因。

info: END: GET /api/t_CheckRecord:list?sort%5B%5D=-id&pageSize=20&appends%5B%5D=f_plant&appends%5B%5D=f_product&page=1&filter=%7B%22%24and%22%3A%5B%7B%22%24and%22%3A%5B%7B%22f_auditMark%22%3A%7B%22%24eq%22%3A%220%22%7D%7D%2C%7B%22f_enabledMark%22%3A%7B%22%24eq%22%3A%221%22%7D%7D%2C%7B%22f_product%22%3A%7B%22f_checkType%22%3A%7B%22%24eq%22%3A%22%E7%94%9F%E4%BA%A7%22%7D%7D%7D%2C%7B%22f_status%22%3A%7B%22%24ne%22%3A1%7D%7D%5D%7D%2C%7B%22%24and%22%3A%5B%7B%22f_product%22%3A%7B%22f_productName%22%3A%7B%22%24includes%22%3A%22%E7%A1%9D%E8%8B%AF%E5%9C%B0%E5%B9%B3%E6%8E%A7%E9%87%8A%E7%89%87%22%7D%7D%7D%2C%7B%22f_product%22%3A%7B%22f_storageLife%22%3A%7B%22%24eq%22%3A0%7D%7D%7D%5D%7D%5D%7D {"req":{"action":{"actionName":"list","params":{"actionName":"list","appends":["f_plant","f_product","createdBy","f_4fq445o530c","f_auditor","f_checkPlan","f_f2i0jpepag3","f_lxt9hebdwoi","f_operator","f_origin","f_plan","f_plant","f_product","f_vry5n4916xj","f_xx71ivl1147","updatedBy"],"fields":["createdAt","createdBy","f_4fq445o530c","f_Caption","f_KeepQty","f_KeepTime","f_KeepUser","f_MatPurpose","f_ProAddr","f_ProPurpose","f_auditMark","f_auditTime","f_auditor","f_auditor2","f_auditorId","f_batchNo","f_batchNumber","f_batchQuantity","f_checkDate","f_checkNo","f_checkPlan","f_checkPlanId","f_checkResult","f_checkUserIds2","f_copyMark","f_enabledMark","f_endDate","f_exprDate","f_f2i0jpepag3","f_flowStatus","f_idcopy","f_lxt9hebdwoi","f_manuDate","f_manuMemo","f_num","f_operator","f_operatorDate","f_operatorId","f_operatorOpinion","f_operatorStep","f_operatorType","f_origin","f_originid","f_passDate","f_passQty","f_plan","f_planId","f_plant","f_plantId","f_printCount","f_producers","f_product","f_productId","f_purpose","f_quantityDesc","f_retuneMark","f_sampAudit","f_sampAuditDate","f_sampBy","f_sampDate","f_sampQuantity","f_sampQuantity2","f_sampSenDate","f_sampleItem","f_sampleQty","f_sampleSender","f_spec","f_startDate","f_status","f_storageLife","f_supplier","f_unitSpec","f_vry5n4916xj","f_xx71ivl1147","id","updatedAt","updatedBy","id","createdAt","updatedAt","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById","createdById"],"filter":{"$and":[{"$and":[{"$and":[{"f_auditMark":{"$eq":"0"}},{"f_enabledMark":{"$eq":"1"}},{"f_product":{"f_checkType":{"$eq":"生产"}}},{"f_status":{"$ne":1}}]},{"$and":[{"f_product":{"f_productName":{"$includes":"轴承"}}},{"f_product":{"f_storageLife":{"$eq":0}}}]}]},{"$and":[],"$or":[{"f_plant":{"f_factory":{"f_factoryName":{"$includes":"大华"}}}}]}]},"own":false,"page":"1","pageSize":"20","resourceName":"t_CheckRecord","sort":["-id"]},"resourceName":"t_CheckRecord"},"header":{"x-hostname":"192.168.0.135","x-locale":"zh-CN","x-role":"r_factoryManage","x-timezone":"+08:00"}},"reqId":"2d0cb42f-a533-4a98-a7b6-26a1c5ef33d4","res":{"status":200},"responseTime":106,"timestamp":"2023-01-03T08:04:09.744Z"}

**Comment by chenos** [comment]
试试最新版本
