### ISSUE TITLE
How update to the last version ? Docker-compose.

### ISSUE THREAD

**Issue by betgamesnetwork** [nocobase/nocobase#1342]
Hello, I'm having problems with the userID and I need to update to the latest version as passed in the ticket I had opened, however, I don't know how to update..

docker-compose.yml

services:
   app:
     image: nocobase/nocobase:main

How should I update?

**Comment by Narizgnaw** [comment]
1、cd the folder where your docker-compose.yml in;
example: `cd /nocobase/docker/app-mysql`
2、Execute command `docker-compose pull`;
3、Execute command `docker-compose up -d app`;
![QQ截图20230110133407](https://user-images.githubusercontent.com/26055055/211470080-001ef892-b117-4eaf-acca-d3cf7af106b6.jpg)
4、Upgrade complete,wait 1 to 2 minutes for the service to start.
