### ISSUE TITLE
NocoBase demo站点在48小时没有自动删除，可能产生服务器资源消耗

### ISSUE THREAD

**Issue by Narizgnaw** [nocobase/nocobase#1345]
在1月6日创建了demo站点https://aumbsxx3hfe3.v6.demo-cn.nocobase.com/ ，但是48小时后demo站点仍未自动删除，可能导致不必要的服务器资源消耗。

**Comment by zhouyanliang** [comment]
暂时发版时才删除。后续随时会改为48小时删除。
