### ISSUE TITLE
数据表格里的column对齐问题

### ISSUE THREAD

**Issue by huchuansai** [nocobase/nocobase#1358]
如图，姓名和年龄这一列一个靠左对齐一个靠右对齐，能调整成统一的对齐方式吗？或者表格单独开放出一个对齐属性？

<img width="1649" alt="image" src="https://user-images.githubusercontent.com/50079978/212229803-f8db3769-4112-4fe6-b661-cb34c27ef067.png">

**Comment by zhouyanliang** [comment]
文本左对齐，数字右对齐
