### ISSUE TITLE
bug：数据字段多对一bug

### ISSUE THREAD

**Issue by huchuansai** [nocobase/nocobase#1369]
bug1：新建了一个客户表和合同表，合同表建立一个关联字段到客户表，字段类型是多对一(一个合同仅一个客户，一个客户下会有多个合同)。当勾选【在目标数据表里创建反向关系字段】时会报错，只能先不勾选等到字段创建好后再去重新编辑字段勾选上【在目标数据表里创建反向关系字段】，主要错误信息如下： string violation: key cannot be an array or an object

bug2：多对一关系筛选报错，主要报错信息：
![image](https://user-images.githubusercontent.com/50079978/212526858-9b2ce420-b2d6-4b48-b67b-cf384bb1432e.png)

![image](https://user-images.githubusercontent.com/50079978/212526871-7f2af0ee-61f0-4405-b0dd-6529588dc8ad.png)

**Comment by chenos** [comment]
@huchuansai 升级最新版

**Comment by huchuansai** [comment]
> @huchuansai 升级最新版

经验证，升级版本并没有解决(docker部署版，更新docker的时候发现有重新拉去新的镜像)

**Comment by chenos** [comment]
这个 commit 之后的版本 https://github.com/nocobase/nocobase/commit/f33c63ac01c72b47bd1e7acf367d3231c7523651
docker  镜像是 v0.9.0-alpha.2

**Comment by huchuansai** [comment]
> 这个 commit 之后的版本 [f33c63a](https://github.com/nocobase/nocobase/commit/f33c63ac01c72b47bd1e7acf367d3231c7523651) docker 镜像是 v0.9.0-alpha.2

预计多久会更新main对应的镜像

**Comment by chenos** [comment]
@huchuansai 实时更新的，现在 main 镜像是这个版本（经测试筛选的问题这个版本已经修复了）

<img width="405" alt="image" src="https://user-images.githubusercontent.com/2993310/212531147-587e259d-81d7-4120-9ba9-c58e88da7296.png">
