### ISSUE TITLE
Excel formula字段引用问题

### ISSUE THREAD

**Issue by Narizgnaw** [nocobase/nocobase#1376]
Excel formula中，仅能引用类型为数字的字段，无法引用其他类型字段，如下图所示，创建了数字字段和单行文本字段，但在Excel formula中设置数据类型为String后，仅能选择数字字段。
![QQ截图20230116144810](https://user-images.githubusercontent.com/26055055/212615386-0082612a-51b9-4729-8b39-f41829d0bdd2.jpg)

**Comment by imtos** [comment]
希望Math Formula能引用一对多的外键，方便做子任务统计、分类的统计等。

**Comment by zhouyanliang** [comment]
公式已支持所有类型的字段（除了关系字段）
