### ISSUE TITLE
Error when adding field to collection

### ISSUE THREAD

**Issue by rouhu** [nocobase/nocobase#1388]
Version used in 0.9.0-alpha.2

One of my custom Collections (t_requests) gives error when trying to add a field to it. Fields can be deleted and updated but not added. Any advice how to solve this would be great. I don't know how and why it started to give this error.

Here is the log:
app_1 | info: acl parsedParams {
	"reqId": "b508ced5-4ce1-4a1f-ab3b-9721ce5fd8d3",
	"timestamp": "2023-01-25T16:15:07.228Z"
}
app_1 | Executing(917b06c8 - 65de - 4269 - b406 - cea9e6d9583b): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'users' AND TABLE_SCHEMA = 'nocobase'
	app_1 | Executing(917b06c8 - 65de - 4269 - b406 - cea9e6d9583b): SHOW FULL COLUMNS FROM `users`;
app_1 | Executing(917b06c8 - 65de - 4269 - b406 - cea9e6d9583b): SELECT CONSTRAINT_NAME as constraint_name, CONSTRAINT_NAME as constraintName, CONSTRAINT_SCHEMA as constraintSchema, CONSTRAINT_SCHEMA as constraintCatalog, TABLE_NAME as tableName, TABLE_SCHEMA as tableSchema, TABLE_SCHEMA as tableCatalog, COLUMN_NAME as columnName, REFERENCED_TABLE_SCHEMA as referencedTableSchema, REFERENCED_TABLE_SCHEMA as referencedTableCatalog, REFERENCED_TABLE_NAME as referencedTableName, REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'users' AND CONSTRAINT_NAME != 'PRIMARY' AND CONSTRAINT_SCHEMA = 'nocobase' AND REFERENCED_TABLE_NAME IS NOT NULL;
app_1 | Executing(917b06c8 - 65de - 4269 - b406 - cea9e6d9583b): SHOW INDEX FROM `users`
app_1 | TypeError: Cannot read properties of undefined(reading '_modelAttribute')
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 646: 20)
app_1 | at MySQLQueryGenerator. < anonymous > (/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 642: 21)
app_1 | at Array.forEach( < anonymous > )
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 641: 27)
app_1 | at MySQLQueryGenerator.getQueryOrders(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 1532: 34)
app_1 | at MySQLQueryGenerator.selectQuery(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 987: 27)
app_1 | at MySQLQueryInterface.select(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - interface.js: 407: 59)
app_1 | at Function.findAll(/app/nocobase / node_modules / sequelize / lib / model.js: 1134: 47)
app_1 | at runMicrotasks( < anonymous > )
app_1 | at processTicksAndRejections(node: internal / process / task_queues: 96: 5)
app_1 | error: Cannot read properties of undefined(reading '_modelAttribute') {
	"headers": {
		"Access-Control-Allow-Origin": "https://approval-tool.mysite.site",
		"Access-Control-Expose-Headers": "content-disposition",
		"vary": "Origin"
	},
	"reqId": "b508ced5-4ce1-4a1f-ab3b-9721ce5fd8d3",
	"stack": "TypeError: Cannot read properties of undefined (reading '_modelAttribute')\n    at MySQLQueryGenerator.quote (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:646:20)\n    at MySQLQueryGenerator.<anonymous> (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:642:21)\n    at Array.forEach (<anonymous>)\n    at MySQLQueryGenerator.quote (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:641:27)\n    at MySQLQueryGenerator.getQueryOrders (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1532:34)\n    at MySQLQueryGenerator.selectQuery (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:987:27)\n    at MySQLQueryInterface.select (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)\n    at Function.findAll (/app/nocobase/node_modules/sequelize/lib/model.js:1134:47)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
	"timestamp": "2023-01-25T16:15:07.259Z"
}
app_1 | TypeError: Cannot read properties of undefined(reading '_modelAttribute')
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 646: 20)
app_1 | at MySQLQueryGenerator. < anonymous > (/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 642: 21)
app_1 | at Array.forEach( < anonymous > )
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 641: 27)
app_1 | at MySQLQueryGenerator.getQueryOrders(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 1532: 34)
app_1 | at MySQLQueryGenerator.selectQuery(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 987: 27)
app_1 | at MySQLQueryInterface.select(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - interface.js: 407: 59)
app_1 | at Function.findAll(/app/nocobase / node_modules / sequelize / lib / model.js: 1134: 47)
app_1 | at runMicrotasks( < anonymous > )
app_1 | at processTicksAndRejections(node: internal / process / task_queues: 96: 5) {
	app_1 | headers: {
		app_1 | 'Access-Control-Allow-Origin': 'https://approval-tool.mysite.site',
		app_1 | 'Access-Control-Expose-Headers': 'content-disposition',
		app_1 | vary: 'Origin'
		app_1 |
	},
	app_1 | level: 'error',
	app_1 | [Symbol(level)]: 'error'
	app_1 |
}
app_1 | error: END: POST / api / collections / t_requests / fields: create {
	"errors": [{
			"message": "Cannot read properties of undefined (reading '_modelAttribute')"
		}
	],
	"req": {
		"action": {
			"actionName": "create",
			"params": {
				"actionName": "create",
				"associatedIndex": "t_requests",
				"associatedName": "collections",
				"resourceName": "fields",
				"updateAssociationValues": ["uiSchema", "reverseField"],
				"values": {
					"interface": "checkbox",
					"name": "f_Cancelled",
					"type": "boolean",
					"uiSchema": {
						"title": "Cancel",
						"type": "boolean",
						"x-component": "Checkbox"
					}
				}
			},
			"resourceName": "collections.fields",
			"resourceOf": "t_requests"
		},
		"header": {
			"x-hostname": "approval-tool.mysite.site",
			"x-locale": "en-US",
			"x-role": "admin",
			"x-timezone": "+01:00"
		}
	},
	"reqId": "b508ced5-4ce1-4a1f-ab3b-9721ce5fd8d3",
	"res": {
		"status": 500
	},
	"responseTime": 46,
	"timestamp": "2023-01-25T16:15:07.259Z"
}
app_1 | info: BEGIN: POST / api / collections / t_requests / fields: create {
	"reqId": "24fdfeac-0a14-4a39-84d8-2483ca66eb3b",
	"timestamp": "2023-01-25T16:15:32.909Z"
}
app_1 | info: Current user id: 1 {
	"reqId": "24fdfeac-0a14-4a39-84d8-2483ca66eb3b",
	"timestamp": "2023-01-25T16:15:32.924Z"
}
app_1 | info: ctx permission {
	"can": {
		"action": "create",
		"resource": "collections.fields",
		"role": "admin"
	},
	"reqId": "24fdfeac-0a14-4a39-84d8-2483ca66eb3b",
	"timestamp": "2023-01-25T16:15:32.927Z"
}
app_1 | info: acl params {
	"reqId": "24fdfeac-0a14-4a39-84d8-2483ca66eb3b",
	"timestamp": "2023-01-25T16:15:32.928Z"
}
app_1 | info: acl parsedParams {
	"reqId": "24fdfeac-0a14-4a39-84d8-2483ca66eb3b",
	"timestamp": "2023-01-25T16:15:32.928Z"
}
app_1 | Executing(79cb0c80 - 423f - 4c1b - 97d2 - fa6ee5f81d85): SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'users' AND TABLE_SCHEMA = 'nocobase'
	app_1 | Executing(79cb0c80 - 423f - 4c1b - 97d2 - fa6ee5f81d85): SHOW FULL COLUMNS FROM `users`;
app_1 | Executing(79cb0c80 - 423f - 4c1b - 97d2 - fa6ee5f81d85): SELECT CONSTRAINT_NAME as constraint_name, CONSTRAINT_NAME as constraintName, CONSTRAINT_SCHEMA as constraintSchema, CONSTRAINT_SCHEMA as constraintCatalog, TABLE_NAME as tableName, TABLE_SCHEMA as tableSchema, TABLE_SCHEMA as tableCatalog, COLUMN_NAME as columnName, REFERENCED_TABLE_SCHEMA as referencedTableSchema, REFERENCED_TABLE_SCHEMA as referencedTableCatalog, REFERENCED_TABLE_NAME as referencedTableName, REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'users' AND CONSTRAINT_NAME != 'PRIMARY' AND CONSTRAINT_SCHEMA = 'nocobase' AND REFERENCED_TABLE_NAME IS NOT NULL;
app_1 | Executing(79cb0c80 - 423f - 4c1b - 97d2 - fa6ee5f81d85): SHOW INDEX FROM `users`
app_1 | TypeError: Cannot read properties of undefined(reading '_modelAttribute')
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 646: 20)
app_1 | at MySQLQueryGenerator. < anonymous > (/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 642: 21)
app_1 | at Array.forEach( < anonymous > )
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 641: 27)
app_1 | at MySQLQueryGenerator.getQueryOrders(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 1532: 34)
app_1 | at MySQLQueryGenerator.selectQuery(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 987: 27)
app_1 | at MySQLQueryInterface.select(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - interface.js: 407: 59)
app_1 | at Function.findAll(/app/nocobase / node_modules / sequelize / lib / model.js: 1134: 47)
app_1 | at runMicrotasks( < anonymous > )
app_1 | at processTicksAndRejections(node: internal / process / task_queues: 96: 5)
app_1 | error: Cannot read properties of undefined(reading '_modelAttribute') {
	"headers": {
		"Access-Control-Allow-Origin": "https://approval-tool.mysite.site",
		"Access-Control-Expose-Headers": "content-disposition",
		"vary": "Origin"
	},
	"reqId": "24fdfeac-0a14-4a39-84d8-2483ca66eb3b",
	"stack": "TypeError: Cannot read properties of undefined (reading '_modelAttribute')\n    at MySQLQueryGenerator.quote (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:646:20)\n    at MySQLQueryGenerator.<anonymous> (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:642:21)\n    at Array.forEach (<anonymous>)\n    at MySQLQueryGenerator.quote (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:641:27)\n    at MySQLQueryGenerator.getQueryOrders (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1532:34)\n    at MySQLQueryGenerator.selectQuery (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:987:27)\n    at MySQLQueryInterface.select (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)\n    at Function.findAll (/app/nocobase/node_modules/sequelize/lib/model.js:1134:47)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
	"timestamp": "2023-01-25T16:15:32.956Z"
}
app_1 | TypeError: Cannot read properties of undefined(reading '_modelAttribute')
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 646: 20)
app_1 | at MySQLQueryGenerator. < anonymous > (/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 642: 21)
app_1 | at Array.forEach( < anonymous > )
app_1 | at MySQLQueryGenerator.quote(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 641: 27)
app_1 | at MySQLQueryGenerator.getQueryOrders(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 1532: 34)
app_1 | at MySQLQueryGenerator.selectQuery(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - generator.js: 987: 27)
app_1 | at MySQLQueryInterface.select(/app/nocobase / node_modules / sequelize / lib / dialects / abstract / query - interface.js: 407: 59)
app_1 | at Function.findAll(/app/nocobase / node_modules / sequelize / lib / model.js: 1134: 47)
app_1 | at runMicrotasks( < anonymous > )
app_1 | at processTicksAndRejections(node: internal / process / task_queues: 96: 5) {
	app_1 | headers: {
		app_1 | 'Access-Control-Allow-Origin': 'https://approval-tool.mysite.site',
		app_1 | 'Access-Control-Expose-Headers': 'content-disposition',
		app_1 | vary: 'Origin'
		app_1 |
	},
	app_1 | level: 'error',
	app_1 | [Symbol(level)]: 'error'
	app_1 |
}
app_1 | error: END: POST / api / collections / t_requests / fields: create {
	"errors": [{
			"message": "Cannot read properties of undefined (reading '_modelAttribute')"
		}
	],
	"req": {
		"action": {
			"actionName": "create",
			"params": {
				"actionName": "create",
				"associatedIndex": "t_requests",
				"associatedName": "collections",
				"resourceName": "fields",
				"updateAssociationValues": ["uiSchema", "reverseField"],
				"values": {
					"interface": "textarea",
					"name": "f_Description",
					"type": "text",
					"uiSchema": {
						"title": "Description",
						"type": "string",
						"x-component": "Input.TextArea"
					}
				}
			},
			"resourceName": "collections.fields",
			"resourceOf": "t_requests"
		},
		"header": {
			"x-hostname": "approval-tool.mysite.site",
			"x-locale": "en-US",
			"x-role": "admin",
			"x-timezone": "+01:00"
		}
	},
	"reqId": "24fdfeac-0a14-4a39-84d8-2483ca66eb3b",
	"res": {
		"status": 500
	},
	"responseTime": 48,
	"timestamp": "2023-01-25T16:15:32.957Z"
}

**Comment by rouhu** [comment]
and also the docker container does not start anymore with same error:

app_1    | nginx started
app_1    | yarn run v1.22.19
app_1    | $ nocobase start --quickstart
app_1    | Connection has been established successfully.
app_1    | Application installed
app_1    | Connection has been established successfully.
app_1    | upgrading...
app_1    | Reload the application configuration
app_1    | The version number before upgrade is 0.9.0-alpha.2
app_1    | /app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:646
app_1    |     if (collection._modelAttribute) {
app_1    |                    ^
app_1    |
app_1    | TypeError: Cannot read properties of undefined (reading '_modelAttribute')
app_1    |     at MySQLQueryGenerator.quote (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:646:20)
app_1    |     at MySQLQueryGenerator.<anonymous> (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:642:21)
app_1    |     at Array.forEach (<anonymous>)
app_1    |     at MySQLQueryGenerator.quote (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:641:27)
app_1    |     at MySQLQueryGenerator.getQueryOrders (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1532:34)
app_1    |     at MySQLQueryGenerator.selectQuery (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-generator.js:987:27)
app_1    |     at MySQLQueryInterface.select (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)
app_1    |     at Function.findAll (/app/nocobase/node_modules/sequelize/lib/model.js:1134:47)
app_1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1    | /app/nocobase/node_modules/execa/lib/error.js:60
app_1    |              error = new Error(message);
app_1    |                      ^
app_1    |
app_1    | Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
app_1    |     at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
app_1    |     at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
app_1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
app_1    |     at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/start.js:46:9) {
app_1    |   shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
app_1    |   command: 'node ./packages/app/server/lib/index.js upgrade',
app_1    |   escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
app_1    |   exitCode: 1,
app_1    |   signal: undefined,
app_1    |   signalDescription: undefined,
app_1    |   stdout: undefined,
app_1    |   stderr: undefined,
app_1    |   failed: true,
app_1    |   timedOut: false,
app_1    |   isCanceled: false,
app_1    |   killed: false
app_1    | }
app_1    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1    | error Command failed with exit code 1.

**Comment by chareice** [comment]
Thank you for alerting us to the issue. We have addressed it and the fix can be found in the commit at  https://github.com/nocobase/nocobase/commit/ecf618783e39c104aa6afb225840b81f89fb2ca9 . We appreciate your feedback and support, and if you have any other issues or suggestions, please don't hesitate to contact us. Thank you again for your contribution!
