### ISSUE TITLE
Calendar date problem

### ISSUE THREAD

**Issue by betgamesnetwork** [nocobase/nocobase#1391]
Hello, I have a problem with the nocobase calendar, when I click on the date 01/23/2023, the system always informs the field one day earlier.

A demonstration follows in the attached image, where I clicked on 01/23/2023 and the system launched the date 01/22/2023 in the "Last result" field.

I'm using Google chrome and the nocobase version is 0.9.0-alpha.2.

I changed the docker-compose.xml for the Brazil timezone to see if there was a problem with that but it didn't solve it.

docker-compose.xml
version: "3"
networks:
   nocobase:
     driver: bridge
services:
   app:
     image: nocobase/nocobase:latest
     networks:
       - nocobase
     depends_on:
       - mysql
     environment:
       - DB_DIALECT=mysql
       - DB_HOST=mysql
       - DB_DATABASE=nocobase
       - DB_USER=test
       - DB_PASSWORD=test
       - LOCAL_STORAGE_BASE_URL=0.0.0.0/storage/uploads
       - TZ=America/Sao_Paulo
     volumes:
       - ./storage:/app/nocobase/storage
     ports:
       - "13000:80"
   mysql:
     image: mysql:8
     environment:
       MYSQL_DATABASE: nocobase
       MYSQL_USER: test
       MYSQL_PASSWORD: test
       MYSQL_ROOT_PASSWORD: test
     restart: always
     networks:
       - nocobase

![problema](https://user-images.githubusercontent.com/71851022/215091752-80b7c9ba-ef7a-4d1a-94f2-66a2a360b963.jpg)
![problema2](https://user-images.githubusercontent.com/71851022/215091766-34fe6356-30eb-4f54-a4c0-98573f0ac6a5.jpg)

**Comment by hongboji** [comment]
Please check whether there is any inconsistency in the time zone settings of your database, server, and nocobase link database

**Comment by betgamesnetwork** [comment]
Docker container mysql:8                    "docker-entrypoint.s…"   4 days ago   Up 9 minutes   3306/tcp, 33060/tcp                       app-mysql_mysql_1
bash-4.4# date
Tue Jan 31 12:02:53 UTC 2023
bash-4.4# exit

Docker container nocobase/nocobase:latest   "docker-entrypoint.s…"   3 days ago   Up 9 minutes   0.0.0.0:13000->80/tcp, :::13000->80/tcp   app-mysql_app_1
root@d07ee217a217:/app/nocobase# date
Tue Jan 31 09:03:05 -03 2023
root@d07ee217a217:/app/nocobase# exit

Host date
root@gestaoambiental:/home/ghc/nocobase/docker/app-mysql# date
Tue Jan 31 09:04:55 AM -03 2023

Docker-compose.yml
version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
    image: nocobase/nocobase:latest
    networks:
      - nocobase
    depends_on:
      - mysql
    environment:
      - DB_DIALECT=mysql
      - DB_HOST=mysql
      - DB_DATABASE=
      - DB_USER=
      - DB_PASSWORD=
      - LOCAL_STORAGE_BASE_URL=172.16.253.229/storage/uploads
    volumes:
      - ./storage:/app/nocobase/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "13000:80"
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    restart: always
    networks:
      - nocobase

**Comment by betgamesnetwork** [comment]
Any suggestion ?

**Comment by betgamesnetwork** [comment]
Any suggestion?

**Comment by betgamesnetwork** [comment]
Please..

**Comment by hongboji** [comment]
Please use Version 0.13.0-alpha.4, which has been fixed.
