### ISSUE TITLE
NocoBase用户交流群

### ISSUE THREAD

**Issue by zhlf2008** [nocobase/nocobase#1418]
为方便大家交流nocobase的应用，特建立此群功能供大家交流，此群为非官方群，由用户自发建立，请大家自愿加入！
QQ群：427407113

**Comment by sudongyuer** [comment]
感谢社区的小伙伴自发建立的交流群交流nocobase💗，这里还有一个官方开发人员建立的一个微信交流群，感兴趣的小伙伴也可以扫码加入，peace and love ～
![image](https://user-images.githubusercontent.com/76603360/217999108-4bdffd2a-0158-49e9-a0e6-21ab0b9656e4.png)
