### ISSUE TITLE
Bug: 增加 Datetime 类型的 field 时填入默认值，提交后会报错

### ISSUE THREAD

**Issue by zhangzhonghe** [nocobase/nocobase#1420]
## Describe the bug

在 Collection manager 页面为用户增加一个 ```Datetime``` 类型的 field 时，当设置了默认值后再提交会报 Invalid default value for 'f_gztr9ow3vd3' 的错误。

## Version

nocobase: 0.9.0-alpha.2

## How To Reproduce

1. 在 Collection manager 页面点击下面所示的按钮配置 fields:
<img width="1280" alt="1675410483452" src="https://user-images.githubusercontent.com/38434641/216542335-5981145a-ee7a-44f3-a5a4-04b3b5de8afc.png">

2. 添加一个 ```Datetime``` 类型的 field:

![image](https://user-images.githubusercontent.com/38434641/216542475-a2c18484-06c3-4748-a380-def48be9320b.png)

4. 设置默认值：

![image](https://user-images.githubusercontent.com/38434641/216543375-d1c0d2b8-75a2-4e7d-badc-ac4c8572b821.png)

6. 然后点击提交，会显示报错信息：

![image](https://user-images.githubusercontent.com/38434641/216543571-a6380c82-cf0f-4308-8498-bcb0366b414f.png)

## Expected behavior

正常添加新的 field

## Desktop (please complete the following information)

- OS: [Windows 11]
- Browser [Edge]
- Version [109.0.1518.70 (正式版本) (64 位)]
- Database [mysql 8.0.32]

## Additional context

虽然点击```提交```按钮后会报错，但是当刷新 fields 列表时候会显示刚才添加的字段。

![image](https://user-images.githubusercontent.com/38434641/216545895-a5ef8c7d-1c36-462a-9e8b-8c1d5db213f5.png)

**Comment by hongboji** [comment]
mysql无时区不支持默认值

**Comment by Alex-Programmer-Bro** [comment]
> mysql无时区不支持默认值

用 chatGPT 分析过插入时的 sql 语句，原因在于时间的处理上。mysql 不支持插入 YYYY-MM-DD HH:mm:ss 的日期数据，传参的时候，应该把后面的时分秒去掉也许就可以了？
