### ISSUE TITLE
docker 启动0.9.0报错

### ISSUE THREAD

**Issue by huaimutou** [nocobase/nocobase#1427]
C:\Users\Sun\Documents>git clone https://gitee.com/nocobase/nocobase.git nocobase
Cloning into 'nocobase'...
remote: Enumerating objects: 72369, done.
remote: Total 72369 (delta 0), reused 0 (delta 0), pack-reused 72369
Receiving objects: 100% (72369/72369), 97.17 MiB | 7.42 MiB/s, done.
Resolving deltas: 100% (50400/50400), done.
Updating files: 100% (3084/3084), done.

C:\Users\Sun\Documents

C:\Users\Sun\Documents>cd nocobase

C:\Users\Sun\Documents\nocobase>cd docker/app-sqlite

 C:\Users\Sun\Documents\nocobase\docker\app-sqlite 的目录

2023-02-04  17:50    <DIR>          .
2023-02-04  17:50    <DIR>          ..
2023-02-04  17:50               297 docker-compose.yml
               1 个文件            297 字节
               2 个目录 127,466,020,864 可用字节

[+] Running 13/13ments\nocobase\docker\app-sqlite>docker-compose pull
 - app Pulled                                                                                                     96.4s
   - bff3e048017e Pull complete                                                                                   42.0s
   - 126dbb4e8fc0 Pull complete                                                                                   42.0s
   - 2daf78eeb282 Pull complete                                                                                   42.8s
   - 1dc472aca539 Pull complete                                                                                   42.9s
   - 150bc8d386a3 Pull complete                                                                                   42.9s
   - 6bb9fe9374b6 Pull complete                                                                                   43.4s
   - 3fb59008091e Pull complete                                                                                   43.5s
   - f7ea43856823 Pull complete                                                                                   43.5s
   - 38419699690f Pull complete                                                                                   77.7s
   - 33ae7136b00b Pull complete                                                                                   77.7s
   - 1c10aaf0502a Pull complete                                                                                   77.8s
   - 2f241052c8c4 Pull complete                                                                                   77.8s

C:\Users\Sun\Documents\nocobase\docker\app-sqlite>docker-compose up -d
[+] Running 2/2
 - Network app-sqlite_nocobase  Created                                                                            0.0s
 - Container app-sqlite-app-1   Started                                                                            0.4s

C:\Users\Sun\Documents\nocobase\docker\app-sqlite>docker-compose logs app
app-sqlite-app-1  | nginx started
app-sqlite-app-1  | copying...
app-sqlite-app-1  | yarn run v1.22.19
app-sqlite-app-1  | $ nocobase start --quickstart
app-sqlite-app-1  | Connection has been established successfully.
app-sqlite-app-1  | Start installing NocoBase
app-sqlite-app-1  | Database dialect: sqlite
app-sqlite-app-1  | Initialize all built-in plugins
app-sqlite-app-1  | Reload the application configuration

C:\Users\Sun\Documents\nocobase\docker\app-sqlite>docker-compose logs app
app-sqlite-app-1  | nginx started
app-sqlite-app-1  | copying...
app-sqlite-app-1  | yarn run v1.22.19
app-sqlite-app-1  | $ nocobase start --quickstart
app-sqlite-app-1  | Connection has been established successfully.
app-sqlite-app-1  | Start installing NocoBase
app-sqlite-app-1  | Database dialect: sqlite
app-sqlite-app-1  | Initialize all built-in plugins
app-sqlite-app-1  | Reload the application configuration
app-sqlite-app-1  | Connection has been established successfully.
app-sqlite-app-1  | upgrading...
app-sqlite-app-1  | Reload the application configuration
app-sqlite-app-1  | The version number before upgrade is 0.9.0-alpha.2.20230204080429
app-sqlite-app-1  | { event: 'migrating', name: 'nocobase/2022-del-sample-plugins' }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'nocobase/2022-del-sample-plugins',
app-sqlite-app-1  |   durationSeconds: 0.028
app-sqlite-app-1  | }
app-sqlite-app-1  | { event: 'migrating', name: 'acl/20221214072638-set-role-snippets' }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'acl/20221214072638-set-role-snippets',
app-sqlite-app-1  |   durationSeconds: 0.044
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'math-formula-field/20230110103214-alert-field'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'math-formula-field/20230110103214-alert-field',
app-sqlite-app-1  |   durationSeconds: 0.02
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'collection-manager/20220613103214-alert-sub-table'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'collection-manager/20220613103214-alert-sub-table',
app-sqlite-app-1  |   durationSeconds: 0.02
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'collection-manager/20220704225714-drop-foreign-keys'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'collection-manager/20220704225714-drop-foreign-keys',
app-sqlite-app-1  |   durationSeconds: 0.021
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'collection-manager/20221101111110-update-foreign-fields'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'collection-manager/20221101111110-update-foreign-fields',
app-sqlite-app-1  |   durationSeconds: 0.02
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'collection-manager/20221104151410-update-collections-hidden'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'collection-manager/20221104151410-update-collections-hidden',
app-sqlite-app-1  |   durationSeconds: 0.021
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'collection-manager/20221121111110-update-fk-type'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'collection-manager/20221121111110-update-fk-type',
app-sqlite-app-1  |   durationSeconds: 0.023
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'collection-manager/20221121111113-update-id-to-bigint'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'collection-manager/20221121111113-update-id-to-bigint',
app-sqlite-app-1  |   durationSeconds: 0.023
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'collection-manager/20221221103220-timestamps'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'collection-manager/20221221103220-timestamps',
app-sqlite-app-1  |   durationSeconds: 0.02
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'sequence-field/20221207022250-sequence-field-key'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'sequence-field/20221207022250-sequence-field-key',
app-sqlite-app-1  |   durationSeconds: 0.019
app-sqlite-app-1  | }
app-sqlite-app-1  | { event: 'migrating', name: 'users/20220818072639-add-users-phone' }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'users/20220818072639-add-users-phone',
app-sqlite-app-1  |   durationSeconds: 0.018
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'workflow/20221129153547-calculation-variables'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'workflow/20221129153547-calculation-variables',
app-sqlite-app-1  |   durationSeconds: 0.021
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrating',
app-sqlite-app-1  |   name: 'workflow/20230115032941-change-request-body-type'
app-sqlite-app-1  | }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'workflow/20230115032941-change-request-body-type',
app-sqlite-app-1  |   durationSeconds: 0.019
app-sqlite-app-1  | }
app-sqlite-app-1  | { event: 'migrating', name: 'audit-logs/202206160949-logging' }
app-sqlite-app-1  | {
app-sqlite-app-1  |   event: 'migrated',
app-sqlite-app-1  |   name: 'audit-logs/202206160949-logging',
app-sqlite-app-1  |   durationSeconds: 0.02
app-sqlite-app-1  | }
app-sqlite-app-1  | ✨  NocoBase has been upgraded to v0.9.0-alpha.2.20230204080429
app-sqlite-app-1  | 2023-02-04T09:55:43: PM2 log: Launching in no daemon mode

**Comment by chenos** [comment]
看起来没报错，正在启动中，等会儿就好了

**Comment by huaimutou** [comment]
@chenos  一直在这个界面  没有继续启动

**Comment by GittenHub** [comment]
我离线环境下部署也碰到了这个问题，一直停在这个界面没有动，Docker version 20.10.22

**Comment by GittenHub** [comment]
经排查，我没能成功启动的原因是在windows中使用了hyper-v版的docker，更换wsl2后可正常启动，项目好像是不支持windows，但wsl2可以启动
