### ISSUE TITLE
Dynamic customize request

### ISSUE THREAD

**Issue by lonnychetrit** [nocobase/nocobase#1428]
### Discussed in https://github.com/nocobase/nocobase/discussions/1410

<div type='discussions-op-text'>

<sup>Originally posted by **lonnychetrit** February  1, 2023</sup>
Hey guys,

I'd like to use the Customize Request action to send trigger to a third party but this part is not documented...
How can I use the data from my bloc or from my list in the Request query parameters?

Let's say that I have a table with all my users and that I add the customize request at the row level (for each user like the "View" or "Edit" button) I'd like to send the ID of the user through the POST request, how can I do it?

Thanks</div>

**Comment by quangbahoa** [comment]
+1 I'm interesting too

**Comment by zhouyanliang** [comment]
This feature still needs to be improved.

**Comment by sudeeshr** [comment]
+1
