### ISSUE TITLE
Suggestion - Show colors according to what was registered in collections and fields

### ISSUE THREAD

**Issue by betgamesnetwork** [nocobase/nocobase#1440]
Hello, I leave a suggestion for improvement. Colors were registered in collections and fields, however, when selecting records, the system does not show which colors, only after saving the record. It would be interesting to show the colors at the time of selection and not only after recording. Follow images.

![sugestão](https://user-images.githubusercontent.com/71851022/217546341-a36ba680-098a-4fa0-809c-d93961f7511a.jpg)
![sugestão2](https://user-images.githubusercontent.com/71851022/217546358-da140b38-3694-42e3-8c97-3cef461849c4.jpg)
![sugestão3](https://user-images.githubusercontent.com/71851022/217546376-797f67f4-c412-48f0-8747-9ef0e08a69dc.jpg)

**Comment by zhouyanliang** [comment]
It's not a good idea.
