### ISSUE TITLE
Problem exporting data.

### ISSUE THREAD

**Issue by betgamesnetwork** [nocobase/nocobase#1444]
Hello, I'm trying to export some data and I'm getting the following error "Sheet names cannot exceed 31 chars"

Google chrome version 109.0.5414.120
nocobase version 0.9.0-alpha.2

Images and log follow

app_1    | error: Sheet names cannot exceed 31 chars {"headers":{"Access-Control-Allow-Origin":"http://172.16.253.229:13000","Access-Control-Expose-Headers":"content-disposition","vary":"Origin"},"reqId":"6350cdab-0665-4658-8890-f2368be96a3a","stack":"Error: Sheet names cannot exceed 31 chars\n    at check_ws_name (/app/nocobase/node_modules/xlsx/xlsx.js:15759:51)\n    at /app/nocobase/node_modules/xlsx/xlsx.js:15770:3\n    at Array.forEach (<anonymous>)\n    at check_wb_names (/app/nocobase/node_modules/xlsx/xlsx.js:15769:4)\n    at check_wb (/app/nocobase/node_modules/xlsx/xlsx.js:15782:2)\n    at Object.writeSync [as write] (/app/nocobase/node_modules/xlsx/xlsx.js:22098:2)\n    at Object.build (/app/nocobase/node_modules/node-xlsx/lib/index.js:77:33)\n    at /app/nocobase/node_modules/@nocobase/plugin-export/lib/server/actions/export-xlsx.js:77:36\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-export/lib/server/actions/export-xlsx.js:24:103)","timestamp":"2023-02-09T13:01:31.620Z"}
app_1    | Error: Sheet names cannot exceed 31 chars
app_1    |     at check_ws_name (/app/nocobase/node_modules/xlsx/xlsx.js:15759:51)
app_1    |     at /app/nocobase/node_modules/xlsx/xlsx.js:15770:3
app_1    |     at Array.forEach (<anonymous>)
app_1    |     at check_wb_names (/app/nocobase/node_modules/xlsx/xlsx.js:15769:4)
app_1    |     at check_wb (/app/nocobase/node_modules/xlsx/xlsx.js:15782:2)
app_1    |     at Object.writeSync [as write] (/app/nocobase/node_modules/xlsx/xlsx.js:22098:2)
app_1    |     at Object.build (/app/nocobase/node_modules/node-xlsx/lib/index.js:77:33)
app_1    |     at /app/nocobase/node_modules/@nocobase/plugin-export/lib/server/actions/export-xlsx.js:77:36
app_1    |     at Generator.next (<anonymous>)
app_1    |     at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-export/lib/server/actions/export-xlsx.js:24:103) {
app_1    |   headers: {
app_1    |     'Access-Control-Allow-Origin': 'http://172.16.253.229:13000',
app_1    |     'Access-Control-Expose-Headers': 'content-disposition',
app_1    |     vary: 'Origin'
app_1    |   },
app_1    |   level: 'error',
app_1    |   [Symbol(level)]: 'error'
app_1    | }
app_1    | error: END: POST /api/ficha_descarte_residuos:export?title=Ficha%20de%20notifica%C3%A7%C3%A3o%20do%20descarte%20incorreto%20de%20res%C3%ADduos&appends=responsavel&sort%5B%5D=sort {"errors":[{"message":"Sheet names cannot exceed 31 chars"}],"req":{"action":{"actionName":"export","params":{"actionName":"export","appends":["responsavel"],"fields":["UH","createdAt","data_notificacao","data_ocorrencia","descricao_fato","especificar_acidente","grupo_residuo","houve_acidente","id","materais_encontrados","plano_de_acao","setor","updatedAt"],"resourceName":"ficha_descarte_residuos","sort":["sort"],"title":"Ficha de notificação do descarte incorreto de resíduos","values":{"columns":[{"dataIndex":["id"],"defaultTitle":"ID"},{"dataIndex":["createdAt"],"defaultTitle":"Created at"},{"dataIndex":["updatedAt"],"defaultTitle":"Last updated at"},{"dataIndex":["UH"],"defaultTitle":"Unidade Hospitalar","enum":[{"label":"Hospital Nossa Senhora da Conceição","value":"HNSC"},{"label":"Hospital Cristo Redentor","value":"HCR"},{"label":"Hospital Criança Conceição","value":"HCR"},{"label":"Hospital Fêmina","value":"HF"},{"label":"Unidade de Pronto Atendimento","value":"UPA"},{"label":"Saúde Comunitária","value":"Saúde Comunitária"}]},{"dataIndex":["data_ocorrencia"],"defaultTitle":"Data da ocorrência"},{"dataIndex":["data_notificacao"],"defaultTitle":"Data da notificação"},{"dataIndex":["setor"],"defaultTitle":"Setor"},{"dataIndex":["houve_acidente"],"defaultTitle":"Houve Acidente","enum":[{"label":"Sim","value":"Sim"},{"label":"Não","value":"Não"}]},{"dataIndex":["descricao_fato"],"defaultTitle":"Descrição do fato"},{"dataIndex":["grupo_residuo"],"defaultTitle":"Grupo do resíduo","enum":[{"label":"Biológico","value":"Biológico"},{"label":"Químico","value":"Químico"},{"label":"Reciclável","value":"Reciclável"},{"label":"Não reciclável","value":"Não reciclável"},{"label":"Perfurocortante","value":"Perfurocortante"}]},{"dataIndex":["materais_encontrados"],"defaultTitle":"Materiais encontrados","enum":[{"label":"Agulha","value":"Agulha"},{"label":"Medicamento","value":"Medicamento"},{"label":"Materiais com sangue","value":"Materiais com sangue"},{"label":"Embalagens","value":"Embalagens"},{"label":"Papel toalha","value":"Papel toalha"},{"label":"Papéis com informações sigilosas","value":"Papéis com informações sigilosas"},{"label":"Outros","value":"Outros"}]},{"dataIndex":["plano_de_acao"],"defaultTitle":"Plano de ação (Gestão ambiental)"},{"dataIndex":["especificar_acidente"],"defaultTitle":"Detalhes do acidente"}]}},"resourceName":"ficha_descarte_residuos"},"header":{"x-hostname":"172.16.253.229","x-locale":"pt-BR","x-role":"ghc_gestao_ambiental_residuos","x-timezone":"--3:00"}},"reqId":"6350cdab-0665-4658-8890-f2368be96a3a","res":{"status":500},"responseTime":32,"timestamp":"2023-02-09T13:01:31.621Z"}

![a](https://user-images.githubusercontent.com/71851022/217821007-546dbcf1-bbc3-4289-b83d-d7edb59c5f88.jpg)

**Comment by hongboji** [comment]
excel sheet name is too long, has been fixed, long will be intercepted, please use the latest version!
