### ISSUE TITLE
想问下useResource 是在哪里封装的 还是formily自带的 在formily中没有找到这个属性

### ISSUE THREAD

**Issue by xiaobaicaio** [nocobase/nocobase#145]
properties: {
                    modal: {
                      type: 'void',
                      title: "{{t('Create collection')}}",
                      'x-decorator': 'Form',
                      'x-decorator-props': {
                        **useResource**: useCollectionResource,
                      },
                      'x-component': 'Action.Drawer',
                      'x-component-props': {
                        useOkAction: '{{ Table.useTableCreateAction }}',
                      },
                      // 创建数据表弹窗
                      properties: {
                        title: {
                          type: 'string',
                          title: "{{t('Collection display name')}}",
                          'x-component': 'Input',
                          'x-decorator': 'FormilyFormItem',
                        },
                        name: {
                          type: 'string',
                          title: "{{t('Collection name')}}",
                          'x-component': 'Input',
                          'x-decorator': 'FormilyFormItem',
                          description:
                            "{{t('Randomly generated and can be modified. Support letters, numbers and underscores, must start with an letter.')}}",
                        },

**Comment by chenos** [comment]
useResource 是 `x-decorator-props` 的参数，需要见对应的  `x-decorator`，比如上面代码的，是 Form 里的参数。
