### ISSUE TITLE
workflow cannot approve

### ISSUE THREAD

**Issue by kennisyoung** [nocobase/nocobase#1554]
## Describe the bug

[A clear and concise description of what the bug is.](error: Bad Request {"headers":{"Access-Control-Allow-Origin":"http://10.2.10.207:8888","Access-Control-Expose-Headers":"content-disposition","vary":"Origin"},"reqId":"aaf578e2-9c8c-4a7b-9320-7612d772b7cb","stack":"BadRequestError: Bad Request\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at /app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/instructions/manual/actions.js:64:31\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/instructions/manual/actions.js:20:103)\n    at _next (/app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/instructions/manual/actions.js:22:194)","timestamp":"2023-03-09T13:29:59.616Z"})

## Version

0.9.1-alpha.2

**Comment by mytharcher** [comment]
Possibly your workflow is not enabled or the job/execution's status is not manipulatable.

**Comment by kennisyoung** [comment]
nocobase:main is fixed
thx
