### ISSUE TITLE
git clone yarn dev 错误 

### ISSUE THREAD

**Issue by fulus06** [nocobase/nocobase#1570]
## Describe the bug
从main分支拉取，运行 （2023年03月15日15:12:52）
Error occurred while trying to proxy request /api/app:getLang from localhost:13000 to http://127.0.0.1:13001/

## Version
当前main分支

## How To Reproduce

1. git clone xxx
2. 更改.env配置（只改动了这一个地方）
```
#DB_DIALECT=sqlite
#DB_STORAGE=storage/db/nocobase.sqlite
DB_TABLE_PREFIX=t_
DB_DIALECT=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=nocobase
DB_USER=root
DB_PASSWORD=my-secret-pw
DB_LOGGING=on
DB_UNDERSCORED=false
```
3. 报错
[HPM] Error occurred while trying to proxy request /api/app:getLang from localhost:13000 to http://127.0.0.1:13001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

## Desktop (please complete the following information)

- OS:  macos 13.2.1
- nodejs v16.15.1
- Browser chrome

**Comment by fu-yan** [comment]
+1
刚刚拉了最新代码后运行报错：/api/app:getLang和/api/app:getPlugins 504
```
[HPM] Error occurred while trying to proxy request /api/app:getLang from localhost:13000 to http://127.0.0.1:13001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/app:getPlugins from localhost:13000 to http://127.0.0.1:13001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by fu-yan** [comment]
重新install好像可以正常运行了，但是前几次的install并不能正常出发，都是`success Already up-to-date.`，所以报错，必须真正install有安装进度条才行

**Comment by zhangzhonghe** [comment]
https://docs-cn.nocobase.com/welcome/getting-started/installation/git-clone
请按照这个步骤重新试一下？应该是没问题的。
