### ISSUE TITLE
workflow人工处理时提示“Forbidden”

### ISSUE THREAD

**Issue by liboafa** [nocobase/nocobase#1572]
工作流中“人工处理”环节，继续流程提示“Forbidden”，如下图所示：
![image](https://user-images.githubusercontent.com/8638763/225297296-98edee57-fc4b-43b0-8c9a-c3037517e838.png)

使用的nocobase版本：0.9.1-alpha.2.20230315081725

查看日志信息，有如下错误：
app_1    | error: Forbidden {"headers":{"Access-Control-Allow-Origin":"http://test.freetowork.cn:13000","Access-Control-Expose-Headers":"content-disposition","vary":"Origin"},"reqId":"e508aac6-c534-447e-986d-716119595d3a","stack":"ForbiddenError: Forbidden\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at /app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/instructions/manual/actions.js:75:31\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/instructions/manual/actions.js:20:103)\n    at _next (/app/nocobase/node_modules/@nocobase/plugin-workflow/lib/server/instructions/manual/actions.js:22:194)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2023-03-15T11:26:06.543Z"}
app_1    | warn: END: POST /api/users_jobs:submit?filterByTk=1 {"errors":[{"message":"Forbidden"}],"req":{"action":{"actionName":"submit","params":{"actionName":"submit","filterByTk":"1","resourceName":"users_jobs","values":{"result":{"approve_result":"success"},"status":1}},"resourceName":"users_jobs"},"header":{"x-hostname":"test.freetowork.cn","x-locale":"zh-CN","x-role":"admin","x-timezone":"+08:00"}},"reqId":"e508aac6-c534-447e-986d-716119595d3a","res":{"status":403},"responseTime":33,"timestamp":"2023-03-15T11:26:06.544Z"}

**Comment by mytharcher** [comment]
通常因为提交人不是指派的负责人，可以检查一下。

**Comment by liboafa** [comment]
后来验证发现，“人工处理”节点的负责人，必须要有配置工作流插件的权限，才能正常处理工作流，否则提示No Permission。但这样用户也就有了更改工作流的权限。

**Comment by liboafa** [comment]
> 通常因为提交人不是指派的负责人，可以检查一下。

后来验证发现，“人工处理”节点的负责人，必须要有配置工作流插件的权限，才能正常处理工作流，否则提示No Permission。但这样用户也就有了更改工作流的权限。
