### ISSUE TITLE
sqlite数据库导入设备excel表后，工作流里一直显示进行中

### ISSUE THREAD

**Issue by fanghao1028** [nocobase/nocobase#1627]
sqlite数据库导入设备excel表后，工作流里一直显示进行中，日志显示内容如下
 SQLITE_BUSY: database is locked SQLITE_BUSY: database is locked

**Comment by mytharcher** [comment]
麻烦详细描述遇到问题的步骤，以及相关数据，最好有一份最小复现的 demo 数据，以便排查问题。

**Comment by hongboji** [comment]
sqlite不支持并发写，会导致死锁 ，可以使用最新版，优化此问题
