### ISSUE TITLE
关联字段 设置标题字段 不可解释错误

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1629]
## Describe the bug
标题字段 莫名就会空白
![screenshots](https://user-images.githubusercontent.com/900786/229258615-83a0449b-c54d-4f57-86a7-1bd0dc8b2e6b.gif)

## Version

github 最新版

**Comment by chenos** [comment]
姓名这一列有数据吗？

**Comment by baiheinet** [comment]
> 姓名这一列有数据吗？

必须有
