### ISSUE TITLE
Application incomplete

### ISSUE THREAD

**Issue by daniellubryka** [nocobase/nocobase#1697]
## Describe the bug
application starts up but misses the left bar.
![image](https://user-images.githubusercontent.com/18213487/231466157-1cc35f52-0d50-44b6-a3e7-119d9acef09c.png)

## Version
Docker image: nocobase/nocobase:main 

## How To Reproduce

https://docs.nocobase.com/welcome/getting-started/installation/docker-compose - I followed this instruction, tried both mysql and sqlite version

**Comment by zhouyanliang** [comment]
After installation it is an empty application and you need to switch to the root role to configure the application.
