### ISSUE TITLE
多对多对多的表格数据筛选bug

### ISSUE THREAD

**Issue by elicip** [nocobase/nocobase#1709]
## Describe the bug

假设有5个表，他们的关系分为别：
A表 <多对多> B表
A表 <多对多> C表
A表 <多对多> D表
E表 <一对多> A表

默认每个表都有一个字段，叫做名称。

我现在需要对E表做数据筛选：
有这么一个条件，A表下的B表下的名称字段为b，不报错。
增加一个条件，A标下的C表下的名称字段为c，报错。
也就是说只能筛选一个，当有多个筛选条件时就会报错。

## Version

Version 0.9.1-alpha.2

## How To Reproduce

1. 建立一个表，叫做A表，创建一个单行文本字段，叫做名称，其他保持默认。
2. 创建一个表，叫做B表，创建一个单行文本字段，叫做名称，其他保持默认。再创建一个多对多字段，叫做A表，关联A表，并建立反向关联。
3. 创建一个表，叫做C表，创建一个单行文本字段，叫做名称，其他保持默认。再创建一个多对多字段，叫做A表，关联A表，并建立反向关联。
4. 创建一个表，叫做D表，创建一个单行文本字段，叫做名称，其他保持默认。再创建一个多对多字段，叫做A表，关联A表，并建立反向关联。
5. 创建一个表，叫做E表，创建一个单行文本字段，叫做名称，其他保持默认。再创建一个一对多字段，叫做A表，关联A表，并建立反向关联。
6. 创建一个页面，显示E表信息。
7. 筛选设置如图所示 
![截屏2023-04-16 13 23 27](https://user-images.githubusercontent.com/8703880/232272884-e23f6f23-93a8-47dd-bd43-89ce7c3d70ec.png)
按照图上这样设置筛选条件会报错。报错Internal Server Error
去掉其中任何一个条件都不报错。

**Comment by hongboji** [comment]
试试Version 0.13.0-alpha.4，不会报错
