### ISSUE TITLE
图形化配置数据表的时候，数据表类型无法显示

### ISSUE THREAD

**Issue by 1004789224** [nocobase/nocobase#1738]
## Version
0.9.2-alpha.2

## How To Reproduce
图形化配置数据表的时候，
![image](https://user-images.githubusercontent.com/32547368/233422387-b556a6ac-92a4-4b9a-88e4-58fe70974096.png)

**Comment by xiaobai-Coding** [comment]
请问这个图形化配置界面使用的第三方库是什么？
