### ISSUE TITLE
Getting error while selecting filter at createdAt field to today from set data scope

### ISSUE THREAD

**Issue by zhouyanliang** [nocobase/nocobase#1771]
### Discussed in https://github.com/nocobase/nocobase/discussions/1767

<div type='discussions-op-text'>

<sup>Originally posted by **syedketto** April 26, 2023</sup>
we get this error, 
We have IST timezone which gives +5.5:00 as offset but it is appending more than one time and still date is not getting set after debugging

![Screenshot 2023-04-26 115441](https://user-images.githubusercontent.com/130733683/234488742-ba0bfd52-458b-476d-80a1-071fb341aa7b.png)

Steps to recreate:
1. Choose any collection and create a table to show data for it, then set data scope for the table from here 

![Screenshot 2023-04-26 115820](https://user-images.githubusercontent.com/130733683/234489187-182c8740-d245-49a1-912c-c4ad1d5789c8.png)

2. Set date value of createdAt to today using date variables

![Screenshot 2023-04-26 115653](https://user-images.githubusercontent.com/130733683/234489509-c0f1519f-67f6-4a8c-a682-05d57387ade7.png)

3. Click Ok.

The Table will get refreshed and the above mention error will occur

I might be loosing some configuration, maybe

It works for field which I made by editing it from configure fields in admin panel inside collection and fields menu and checking Use the same time zone (GMT) for all users
but it wont work on existing created and updated fields

Please Help
</div>

**Comment by hongboji** [comment]
Date variables have been refactored in Version 0.13.0-alpha.4 for fixes

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3732
