### ISSUE TITLE
v0.9.2-alpha.3 浏览器访问首页报错：Unhandled Rejection (TypeError)

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#1773]
## Describe the bug

v0.9.2-alpha.3 浏览器访问首页报错：

```
Unhandled Rejection (TypeError): _client2(...).default.getEntities is not a function
```

## Version

NocoBase version: v0.9.2-alpha.3

## How To Reproduce

通过 git clone 方式，通过 create nocobase-app 都会出现相同的报错。

### git clone 方式

```bash
git clone https://github.com/nocobase/nocobase.git
cd nocobase
git checkout v0.9.2-alpha.3
yarn
yarn nocobase install --lang=zh-CN
yarn dev
```

然后浏览器访问：http://localhost:13000 时报错：

```
Unhandled Rejection (TypeError): _client2(...).default.getEntities is not a function
./node_modules/@nocobase/plugin-formula-field/lib/client/interfaces/formula.js
./node_modules/@nocobase/plugin-formula-field/lib/client/interfaces/formula.js:168
__webpack_require__
./webpack/bootstrap:837
...
```

### create nocobase-app 方式

```bash
yarn create nocobase-app my-nocobase -d sqlite
cd my-nocobase
yarn
yarn nocobase install --lang=zh-CN
yarn dev
```

然后浏览器访问：http://localhost:13000 时报错：

```
Unhandled Rejection (TypeError): _client2(...).default.getEntities is not a function
./node_modules/@nocobase/plugin-formula-field/lib/client/interfaces/formula.js
./node_modules/@nocobase/plugin-formula-field/lib/client/interfaces/formula.js:168
__webpack_require__
./webpack/bootstrap:837
...
```

### 浏览器的处理

浏览器:

 - 更换了 chrome/edge/safari
 - 尝试无痕模式
 - 手动清除浏览器应用的本地存储
 - 强制刷新加载页面 `cmd+shift+r`

报错依然都是相同的

## Expected behavior

能正常访问首页。

## Screenshots

![image](https://user-images.githubusercontent.com/931976/234574982-9d3f3543-e23e-4d9e-946a-f07da6ac5ec0.png)

## Desktop (please complete the following information)

- Browser chrome
- Version 版本 112.0.5615.49（正式版本） (x86_64)

**Comment by chenos** [comment]
Node 什么版本？
重新安装依赖试试
```bash
rm -rf node_modules
yarn install
```
还不行试试清空缓存再试试
```bash
yarn cache clean
rm -rf node_modules
yarn install
```

**Comment by an-quodai** [comment]
Temporary solution is remove plugin formula field by `yarn pm remove formula-field`

**Comment by MarshalW** [comment]
我的 node.js 版本是：v18.13.0

在尝试过 `yarn cache clean` 后，再次执行问题解决。

另外，我之前也多次重复 `rm -rf node_modules`，因此目前看 `yarn cache clean` 可能是解决问题的操作。

@an-quodai , 可以试试 `yarn cache clean` 再执行，至少对我是有效的。
