### ISSUE TITLE
关联字段携带的文本字段使用“包含”匹配时与纯文本字段使用“包含”匹配的结果不同

### ISSUE THREAD

**Issue by waylonwang** [nocobase/nocobase#1793]
1.两个文本字段之间使用“包含”匹配时，“abc”可以正确的“包含”匹配出“abc”或“bc”
2.两个关联字段携带的文本字段之间使用“包含”匹配时，“abc”无法正确的“包含”匹配出“abc”或“bc”
3.文本字段与关联字段携带的文本字段之间使用“包含”匹配时，“abc”无法正确的“包含”匹配出“abc”或“bc”

![image](https://user-images.githubusercontent.com/7424276/235913302-f4b0edbd-a7cd-48c0-861e-6e72ca6876f3.png)
![image](https://user-images.githubusercontent.com/7424276/235913333-c61a3be6-f608-4772-9cb1-34d3e01f442d.png)
![image](https://user-images.githubusercontent.com/7424276/235913352-84d733cf-7b1f-4ac2-aec7-99a34fd98926.png)
![image](https://user-images.githubusercontent.com/7424276/235913383-1e2d94e0-bf16-42f4-a250-c64b8fad793b.png)
![image](https://user-images.githubusercontent.com/7424276/235913398-6a876fe9-d3da-4a50-8430-a80b4ec64248.png)
![image](https://user-images.githubusercontent.com/7424276/235913430-cb1cf4cc-7241-43b8-9202-9aaa8c301907.png)

**Comment by katherinehhh** [comment]
该问题已修复
