### ISSUE TITLE
公式字段没有支持Formula.js的SPLIT函数

### ISSUE THREAD

**Issue by waylonwang** [nocobase/nocobase#1794]
SPLIT函数是Formula.js原生支持的，但是在公式字段定义时没有正确的解析，显示语法错误
![image](https://user-images.githubusercontent.com/7424276/235913931-9d3b4a8a-0e62-4e62-9b6b-0d71282f87e4.png)
![image](https://user-images.githubusercontent.com/7424276/235913942-7134c3b7-a6f0-48d0-855f-6ffa6a612e06.png)
![image](https://user-images.githubusercontent.com/7424276/235913955-4a262299-ad7c-4674-8cd7-ee847d6c25e3.png)

**Comment by mytharcher** [comment]
这些函数在新版本（4.2.0+）的 formula 引擎中已经不再被支持，详见：https://github.com/formulajs/formulajs/issues/79 。
