### ISSUE TITLE
一对多的关系字段在记录新增或编辑时没有触发新增或更新工作流事件

### ISSUE THREAD

**Issue by waylonwang** [nocobase/nocobase#1795]
表单新增或编辑时，如存在一对多的关系字段，同时新增或编辑该关系字段的内容，不会触发该关系自动模型的新增或更新工作流事件

![image](https://user-images.githubusercontent.com/7424276/235914309-e58371f5-f364-4664-be6c-4e285af63e28.png)
![image](https://user-images.githubusercontent.com/7424276/235914322-4f57a906-1ec0-4b70-b002-5c301b41d207.png)

**Comment by hongboji** [comment]
工作流不支持
