### ISSUE TITLE
建议是否可以替换  bcrypt 为 bcryptjs

### ISSUE THREAD

**Issue by leoner** [nocobase/nocobase#180]
就是目前发现非 mac 平台打包的时候， bcrypt 安装会出现各种编译错误，看项目实际上使用 bcrypt 很简单， 就是一个 hash 方法， 那是否可以直接替换为原生的 js 版本呢？

**Comment by chenos** [comment]
bcryptjs 已经 5 年没更新了，下个版本打算使用 crypto.scrypt 重构密码算法，使用内置的，就不会有编译问题了。
https://nodejs.org/api/crypto.html#cryptoscryptpassword-salt-keylen-options-callback

**Comment by leoner** [comment]
👍🏻， 毕竟我看用 bcrypt 就一个方法， 原生最好呀。

**Comment by leoner** [comment]
那等发布了， 再关把

**Comment by chenos** [comment]
@leoner 好的，v0.6 版本的已经改了，不过这个版本还在持续开发中
https://github.com/nocobase/nocobase/blob/nocobase-next/packages/database/src/fields/password-field.ts

**Comment by zhouyanliang** [comment]
0.7 已发布
