### ISSUE TITLE
Render Failed in table block when dispalying a Formula Field  from association fields

### ISSUE THREAD

**Issue by mz0in** [nocobase/nocobase#1805]
## Version
the up to date daily version 

## How To Reproduce
make a calculated filed and put a formula in a collection that is linked to another collection 
 like for example 
customer table : name , gender , birthdate 
order : customer id , order no , order date .. 

--- 
so now if I added a calculated field to customer table to calculate the age in year : YEAR(createdat) - birthdate 
and tried to display the results in a table Block that contain the order tables with the association fields from customer it will work fine unless if I added the calculated filed (Customer Age ) , which will cause the app to a Render Fail 
after a refresh the app will retain render , but when trying too navigate in the table it will cause the app to render fail again

**Comment by hongboji** [comment]
Thank you for your feedback, it will be fixed in the near future

**Comment by mz0in** [comment]
Thanks

**Comment by mytharcher** [comment]
Fixed in #1911.
