### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/mathjs/-/mathjs-10.6.4.tgz: ESOCKETTIMEDOUT".

### ISSUE THREAD

**Issue by zsdili** [nocobase/nocobase#1815]
## Version

NocoBase version that you are using.

## Expected behavior

yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/mathjs/-/mathjs-10.6.4.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "D:\\!通达产控\\jsq\\my-nocobase-app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...

**Comment by chenos** [comment]
There appears to be trouble with your network connection. Retrying...

网络问题，多试几次，或者更换 npm 源
