### ISSUE TITLE
Linkage Rule submit button issue

### ISSUE THREAD

**Issue by Rex-sama** [nocobase/nocobase#1840]
I have a form inside a drawer , form contains some fields one of the field is radio buttons and last we have submit button. I have added a linkage rule in submit button where if lets say radio option 1 is selected then submit button should be hidden and if option 2 is selected submit button should be visible. Even adding this linkage rules , it still not working ,button remains in visible state only.
Anyone knows how to fix it???

**Comment by hongboji** [comment]
The button linkage rule gets the data already in the database to control its own properties and does not change in real time according to the form data. The usage scenario is to approve the data.
