### ISSUE TITLE
已经上传的附件，再次查看或编辑时会丢失，也没有返回数据

### ISSUE THREAD

**Issue by hexiaomo** [nocobase/nocobase#1855]
## Describe the bug

某个记录有附件类型的字段，在上传附件成功后，（经检查/storage/uploads/文件夹权限和文件夹内容，已确认上传成功），当再次想要编辑/查看该附件时，页面附件内容变为空。Version 0.9.2-alpha.2 上传后可以正常查看编辑附件， Version 0.9.3-alpha.1.20230514085014 上传附件后，再次查看/编辑该条记录时，附件显示为空。  查看了返回结果，并未返回附件字段的数据，请看两个版本的对比图片

详见附件

## Version
docker部署的nocobase/nocobase:latest 正常
Version 0.9.2-alpha.2

docker部署的nocobase/nocobase:main 出现该问题
Version 0.9.3-alpha.1.20230514085014

## How To Reproduce

1. 数据表有 附件 类型的字段
2. 添加一条数据，上传任意附件
3. 启用 操作列，打开 编辑 和 查看 ，设置好 表单 和 详情
4. Version 0.9.3-alpha.1.20230514085014  编辑表单 或者查看 数据记录详情页时，看不到附件。

## Expected behavior

近期几个版本出现该情况

## Desktop (please complete the following information)

- OS: Windows / ubutun
- Browser Chrome / Firefox
- Version 101

## Additional context

详情页两个版本一条记录的对比图  和 返回的数据：
![2023-05-14_160311](https://github.com/nocobase/nocobase/assets/34914097/01ae0119-fd62-4e0f-abdb-d47af04b02eb)
![2023-05-14_160344](https://github.com/nocobase/nocobase/assets/34914097/2d53d9c9-fcf9-43a1-890c-6a5244294ed5)

**Comment by cvcvcvlp** [comment]
我也碰到这个问题了 ，不知道咋解决

**Comment by zhangzhonghe** [comment]
应该是在这里修复了： https://github.com/nocobase/nocobase/pull/1856

**Comment by zhouyanliang** [comment]
更新最新版
