### ISSUE TITLE
用0.9.2版本设计父子表单正确，但用0.9.3设计界面不是原来的样子。【选择的都是同样的子表单】

### ISSUE THREAD

**Issue by zhouqingjian70** [nocobase/nocobase#1863]
## Describe the bug

用0.9.2版本设计父子表单正确，但用0.9.3设计界面不是原来的样子。【选择的都是同样的子表单。】

## Version

NocoBase version 0.9.2-alpha.4.20230508055550 和 0.9.3-alphaXXX

## How To Reproduce

0.9.2版本界面是这样子的:
![image](https://github.com/nocobase/nocobase/assets/92328605/9fdb1bea-5be5-4fa6-a948-d68f2d45feff)

0.9.3界面变成这样了：
![image](https://github.com/nocobase/nocobase/assets/92328605/e6655301-a626-46ce-9eb5-9d81fa89ef5f)

## Expected behavior

服务器端的信息分别是这样的：
0.9.2版本：
info: Current user id: 2 {"reqId":"5a0c9679-4c91-4e09-bb56-3cea18218fc0","timestamp":"2023-05-16T01:31:36.063Z"}
info: ctx permission {"can":null,"reqId":"5a0c9679-4c91-4e09-bb56-3cea18218fc0","skip":true,"timestamp":"2023-05-16T01:31:36.069Z"}
info: acl params {"reqId":"5a0c9679-4c91-4e09-bb56-3cea18218fc0","timestamp":"2023-05-16T01:31:36.069Z"}
info: acl parsedParams {"reqId":"5a0c9679-4c91-4e09-bb56-3cea18218fc0","timestamp":"2023-05-16T01:31:36.069Z"}
info: END: GET /api/t_orders:list?pageSize=20 {"req":{"action":{"actionName":"list","params":{"actionName":"list","pageSize":"20","resourceName":"t_orders"},"resourceName":"t_orders"},"header":{"x-hostname":"192.168.1.221","x-locale":"zh-CN","x-role":"root","x-timezone":"+08:00"}},"reqId":"5a0c9679-4c91-4e09-bb56-3cea18218fc0","res":{"status":200},"responseTime":29,"timestamp":"2023-05-16T01:31:36.081Z"}
info: BEGIN: GET /api/t_orders:get?appends%5B%5D=f_custid&appends%5B%5D=f_orderlist&filterByTk=2 {"reqId":"afc68b16-8d81-4bd9-b69c-ce8e80795ffb","timestamp":"2023-05-16T01:31:38.022Z"}

0.9.3版本：
info: Current user id: 2 {"reqId":"afc68b16-8d81-4bd9-b69c-ce8e80795ffb","timestamp":"2023-05-16T01:31:38.033Z"}
info: ctx permission {"can":null,"reqId":"afc68b16-8d81-4bd9-b69c-ce8e80795ffb","skip":true,"timestamp":"2023-05-16T01:31:38.039Z"}
info: acl params {"reqId":"afc68b16-8d81-4bd9-b69c-ce8e80795ffb","timestamp":"2023-05-16T01:31:38.039Z"}
info: acl parsedParams {"reqId":"afc68b16-8d81-4bd9-b69c-ce8e80795ffb","timestamp":"2023-05-16T01:31:38.039Z"}
info: END: GET /api/t_orders:get?appends%5B%5D=f_custid&appends%5B%5D=f_orderlist&filterByTk=2 {"req":{"action":{"actionName":"get","params":{"actionName":"get","appends":["f_custid","f_orderlist"],"filterByTk":"2","resourceName":"t_orders"},"resourceName":"t_orders"},"header":{"x-hostname":"192.168.1.221","x-locale":"zh-CN","x-role":"root","x-timezone":"+08:00"}},"reqId":"afc68b16-8d81-4bd9-b69c-ce8e80795ffb","res":{"status":200},"responseTime":33,"timestamp":"2023-05-16T01:31:38.055Z"}

**Comment by hongboji** [comment]
关系字段子表单 子表格在重构，可以下周升级看看

**Comment by zhouqingjian70** [comment]
> 关系字段子表单 子表格在重构，可以下周升级看看

好的，谢谢告知！

**Comment by GuoEdward** [comment]
这个问题有解决方案了吗？希望也能支持打印功能。

**Comment by jetiny** [comment]
Version 0.9.4-alpha.2
还是不行啊。。。之前的不是挺好的吗？

**Comment by baiheinet** [comment]
> Version 0.9.4-alpha.2 还是不行啊。。。之前的不是挺好的吗？
> 
> 子表单都被干掉了？

应该在重构中https://github.com/nocobase/nocobase/pull/1862

**Comment by zhouqingjian70** [comment]
升级到V.10之后的版本，已经正常了。
