### ISSUE TITLE
文件数据库 在普通数据库 编辑页面 无法显示。

### ISSUE THREAD

**Issue by aiastia** [nocobase/nocobase#1874]
一个普通数据库 关联 一个文件数据库

 然后添加表格。“编辑” 选项 看不到文件 
但是“查看” 可以 表格也可。![image](https://github.com/nocobase/nocobase/assets/19776350/21ed50bc-0452-4465-b5b5-34ae7e1afdb0)

**Comment by aiastia** [comment]
Version 0.9.3-alpha.1.20230517053806

**Comment by katherinehhh** [comment]
是说表单编辑里没有出来数据？是一对一的关联关系吗

**Comment by zhouqingjian70** [comment]
比如：主表-普通数据表（合同），子表-文件数据表（合同附件文件），主子表一对多。
BUG：
1、在合同编辑页面上传附件后，不显示；在子表的编辑界面可以看到上传的文件数据。
2、打开主表编辑界面不做任何修改，【注意：这里上传的附件没有显示】，直接提交，主子表间附件记录关联消失了。

**Comment by aiastia** [comment]
> 是说表单编辑里没有出来数据？是一对一的关联关系吗

我的是“关联”

**Comment by aiastia** [comment]
> 辑界面不做任何修改，【注意：这里上传的附件没有显示】，直接提交，主子表间附件记录关联消失了

你也碰到了吗

**Comment by aiastia** [comment]
> 比如：主表-普通数据表（合同），子表-文件数据表（合同附件文件），主子表一对多。 BUG： 1、在合同编辑页面上传附件后，不显示；在子表的编辑界面可以看到上传的文件数据。 2、打开主表编辑界面不做任何修改，【注意：这里上传的附件没有显示】，直接提交，主子表间附件记录关联消失了。

我发现了解决办法  你新建一个页面 然后添加表单 重新配置下 这个就出来了

**Comment by aiastia** [comment]
这个是上一版本配置的  

点击查看 
![截图_20230517174249](https://github.com/nocobase/nocobase/assets/19776350/933961d8-1510-4713-82f8-b749aed21fe4)

点击编辑

**Comment by aiastia** [comment]
这个是重新配置的 
![截图_20230517174505](https://github.com/nocobase/nocobase/assets/19776350/13d06bb4-90d1-4847-8ff9-27cda0e973fb)

**Comment by hongboji** [comment]
“关联” nocobase已经取消，请改变为多对一 多对多
