### ISSUE TITLE
筛选中树表格的数据不能匹配下级

### ISSUE THREAD

**Issue by cn-src** [nocobase/nocobase#1897]
## Describe the bug
筛选中树表格的数据不能匹配下级

## Version

nocobase:main

## How To Reproduce
1. 创建一个普通表格
2. 创建多对多管理字段，字段目标表为树表格
3. 普通表格的筛选功能，筛选树表格字段，只能精准匹配id，无法查询下级数据。

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
功能暂不支持该场景
