### ISSUE TITLE
系统启动时出现错误

### ISSUE THREAD

**Issue by zhouqingjian70** [nocobase/nocobase#1935]
## How To Reproduce

  App running at:
  - Local:   http://localhost:13002 (copied to clipboard)
  - Network: http://192.168.1.125:13002
[HPM] Error occurred while trying to proxy request /api/app:getLang?locale= from 127.0.0.1:13002 to http://127.0.0.1:13002 (EADDRINUSE) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/app:getPlugins from 127.0.0.1:13002 to http://127.0.0.1:13002 (EADDRINUSE) (https://nodejs.org/api/errors.html#errors_common_system_errors)

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by zhouqingjian70** [comment]
问题出现在Git 源码安装。Docker 版没有这个问题。

**Comment by chenos** [comment]
全新安装
https://docs-cn.nocobase.com/welcome/getting-started/installation/git-clone
升级
https://docs-cn.nocobase.com/welcome/getting-started/upgrading/git-clone

看看是否少了啥步骤，看报错是后端没正常启动

**Comment by zhouqingjian70** [comment]
谢谢！我换了一台机器Git 源码安装成功了。

> 全新安装 https://docs-cn.nocobase.com/welcome/getting-started/installation/git-clone 升级 https://docs-cn.nocobase.com/welcome/getting-started/upgrading/git-clone
> 
> 看看是否少了啥步骤，看报错是后端没正常启动
