### ISSUE TITLE
为什么关联字段，有的字段就是不能显示，上次issue给我关了，我以为修好了

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1936]
![screenshots](https://github.com/nocobase/nocobase/assets/900786/a5af2621-b65c-4d9a-875d-69a4d1f8d387)

上次issue  https://github.com/nocobase/nocobase/issues/1629

**Comment by zhangzhonghe** [comment]
感谢反馈，方便提供一个复现链接吗？

**Comment by chenos** [comment]
姓名是什么字段？

**Comment by baiheinet** [comment]
![image](https://github.com/nocobase/nocobase/assets/900786/1d1f93aa-da29-4b12-ab71-8d4b690c8131)

**Comment by baiheinet** [comment]
我为了做实验 新建了一个 昵称字段 配置跟姓名 一样
结果好使  不知为何
![screenshots](https://github.com/nocobase/nocobase/assets/900786/9120bbb2-2553-44d4-a477-6dd5c4d2ff3f)
