### ISSUE TITLE
associated fields some times are displaying wrongly , and links between collection has issues ! 

### ISSUE THREAD

**Issue by mz0in** [nocobase/nocobase#1939]
Having bugs with displaying associated fields? Some fields are wrongly displayed.

Version 0.9.4-alpha.1

**Comment by mz0in** [comment]
also having the same issue #1936
@zhangzhonghe is this the same issue in #1937

**Comment by zhangzhonghe** [comment]
Maybe [this](https://github.com/nocobase/nocobase/pull/1811) PR can fix your problem. You can wait until the PR has been merged and then try again, or you can clone the code from this [branch](https://github.com/nocobase/nocobase/tree/fix/relationship-blocks) to your local machine and run it to see if there are any problems.

> Note: You will need to delete and recreate the blocks in the pop-up window as this PR is not compatible with previously created blocks.

**Comment by mz0in** [comment]
Ok, Thanks a lot  I will try
