### ISSUE TITLE
yarn pm enable 会报错 Cannot read properties of undefined (reading 'requiredPlugins')

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1944]
## Describe the bug

我就是一步步开始的 https://docs-cn.nocobase.com/development/your-fisrt-plugin

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/f238263e-b099-4136-8d5a-37a51ae4242c)

**Comment by baiheinet** [comment]
还有一个问题 例如，有一名为 my-nocobase-app 的项目，新增了 hello 插件，包名为 @my-nocobase-app/plugin-hello。

yarn pm add hello

就会有cannot find 
![image](https://github.com/nocobase/nocobase/assets/900786/ca8459f9-e91a-4bb7-8a44-6f94f26809c4)

**Comment by linlai163** [comment]
需要 cd 到对应的 plugin 目录运行 `yarn pm enable xxx` 命令。
