### ISSUE TITLE
Error reported after upgrading to the latest code version

### ISSUE THREAD

**Issue by cvcvcvlp** [nocobase/nocobase#1949]
Firstly, I would like to express my sincere gratitude to the open-source project, which is definitely the most useful tool in building low code systems,

However, I recently encountered an issue where after upgrading to the latest version of the code, editing a form information error [**Cannot read properties of undefined (reading 'associationType')** ] was reported as follows

Not all cases in this situation will report errors, only one data table has an issue, and this data table has a many to many relationship, a one to many relationship 

![1685328291239](https://github.com/nocobase/nocobase/assets/14797574/98127b8b-eeb6-4581-979a-ca956bb12480)

**Comment by Subp66** [comment]
nocobase是国内团队开发的，用中文描述不是更好？
建议你可以删除这个编辑按钮，重新添加并配置测试下
