### ISSUE TITLE
主表company关联statistics视图，对视图中的字段进行排序提示Unable to find a valid association for model

### ISSUE THREAD

**Issue by ytl003** [nocobase/nocobase#1969]
## Describe the bug

主表company关联statistics视图；主表和视图是一对一关联的；视图作用主要是加了一些关联其他表的统计计算。
1、statistics中字段排序报错如下
2、希望支持company表 内容根据 statistics 字段进行筛选（包含默认筛选和筛选表单）
![image](https://github.com/nocobase/nocobase/assets/26764888/a84c9710-9b82-4dd3-a111-fafc209d65ec)
![image](https://github.com/nocobase/nocobase/assets/26764888/87bb6993-9b75-4c65-a841-c9740bff06b1)
![image](https://github.com/nocobase/nocobase/assets/26764888/df2df12e-3b25-4595-9127-5e43585b7811)
![image](https://github.com/nocobase/nocobase/assets/26764888/4f2d34ef-55d0-4247-bff8-0175f287f89d)

## How To Reproduce

如上图

**Comment by chareice** [comment]
目前不支持按关系字段排序，暂时可以把字段都整合进视图中进行处理 @mdumu

**Comment by mdumu** [comment]
> 目前不支持按关系字段排序，暂时可以把字段都整合进视图中进行处理 @mdumu

可能还是需要支持一下；整合视图中虽然可以实现查询功能，但是不能对主数据进行操作（如：新增修改等，还有就是会导致页面配置复杂度增加，需要维护两个model的页面配置）
