### ISSUE TITLE
表单行政区划筛选结果错误；导出无行政区划内容

### ISSUE THREAD

**Issue by ytl003** [nocobase/nocobase#1981]
## Describe the bug

表单行政区划筛选结果错误；导出无行政区划内容
## Version

0.9.4-2

## How To Reproduce

1、配置行程区划并筛选
2、四川和阿坝藏族羌族自治州都出来了

1、导出结果没有行政区划

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/26764888/4c4e9faf-2fef-40bf-8d44-a25316f7546c)
![image](https://github.com/nocobase/nocobase/assets/26764888/0c97715c-b53c-4c1e-930f-c1ab3eccd90e)

**Comment by hongboji** [comment]
已知待修复缺陷
