### ISSUE TITLE
升级后 执行 yarn nocobase upgrade 时候报错

### ISSUE THREAD

**Issue by cvcvcvlp** [nocobase/nocobase#1985]
git方式升级的
执行 yarn nocobase upgrade 命令后 报错

![image](https://github.com/nocobase/nocobase/assets/14797574/7304ad18-3bb8-41b4-93a5-b7bd9768fe09)

**Comment by chareice** [comment]
smallCycleAttrMap 这个表是自己关联了自己吗，存在环依赖

**Comment by cvcvcvlp** [comment]
抱歉，刚看到信息 ，smallCycleAttrMap&nbsp; 这个表是一个 多对多关联的中间表 存的是&nbsp; &nbsp; A表的ID&nbsp; 和 B表ID的对应关系



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ChengLei ***@***.***&gt;; 
发送时间: 2023年6月6日(星期二) 晚上10:44
收件人: ***@***.***&gt;; 
抄送: "cvcvcvc ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nocobase/nocobase] 升级后 执行 yarn nocobase upgrade 时候报错 (Issue #1985)





 
smallCycleAttrMap 这个表是自己关联了自己吗，存在环依赖

**Comment by hongboji** [comment]
由于nocobase迭代块，这个问题在新的版本中已经优化，请使用最新版本，这个问题将被关闭
