### ISSUE TITLE
bug(plugin-workflow):增加循环后，就会一直运行中，去掉后正常

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#1991]
![image](https://github.com/nocobase/nocobase/assets/900786/446a11ea-47c8-430d-b89b-cbbefad285d4)
![image](https://github.com/nocobase/nocobase/assets/900786/5faf67a8-1244-456b-b450-edd11f07baa3)

**Comment by mytharcher** [comment]
没有成功复现，看能否提供一个最小复现？可以是一个 sqlite。
