### ISSUE TITLE
附件上传后无法查看

### ISSUE THREAD

**Issue by maxmaosir** [nocobase/nocobase#2062]
本地文件服务，默认配置，附件上传后，无法访问，通过ssh访问查看文件路径正常（0.9.4-alpha.2）
![image](https://github.com/nocobase/nocobase/assets/16662736/d28f252d-6838-456f-8964-55f5abea7e9d)

**Comment by maxmaosir** [comment]
路径显示正常，页面加载不到。

**Comment by mytharcher** [comment]
未能复现，你的安装方式是什么样的？

**Comment by maxmaosir** [comment]
create-nocobase-app 方式安装的

**Comment by mytharcher** [comment]
还是未能复现，更新到 0.10+ 试试？

**Comment by maxmaosir** [comment]
已更新，多谢支持，测试中，配图之前报错的版本（如果未能复现那就可能和本地install有关），此外想了解下我换一台电脑部署，迁移是否只迁移数据库即可。
![image](https://github.com/nocobase/nocobase/assets/16662736/ed2ee441-26be-4595-a8d3-0ac57d758b1d)

**Comment by maxmaosir** [comment]
我的问题，我附件服务器配置的是localhost，应该设置为服务器地址，谢谢老师

**Comment by maxmaosir** [comment]
还有想咨询个问题：我第一台服务器安装了，mysql数据源，想换一台服务器如何迁移。

**Comment by mytharcher** [comment]
导出数据库，并迁移 `storage` 目录，如果配置了环境变量，`.env` 文件也需要迁移。
