### ISSUE TITLE
yarn build 报错

### ISSUE THREAD

**Issue by ytl003** [nocobase/nocobase#2080]
## Describe the bug

`yarn build core/client` 
在执行到`@nocobase/client: Transform to cjs for src/schema-component/antd/markdown/util.js`时报错（这个错不会终止编译，可以对`packages/core/build/lib/babel.js` 中 `_signale.default.error(`\``Compiled faild: ${file.path}`\``);`打断点检测）
<img width="600" alt="image" src="https://github.com/nocobase/nocobase/assets/26764888/cd53a171-31bf-40bf-be2e-51e01f895b57">

进行如下修改后，没有报错了
![image](https://github.com/nocobase/nocobase/assets/26764888/eb941fd0-8ab2-474e-abc2-8e5857c11468)
## Version

[v0.9.4-alpha.2](https://github.com/nocobase/nocobase/compare/v0.9.4-alpha.1...v0.9.4-alpha.2) - 2023-05-26

**Comment by hongboji** [comment]
新版插件构建已经重构，关闭此问题
