### ISSUE TITLE
Workflow Error: Cannot access 'typeTitle' before initialization

### ISSUE THREAD

**Issue by Baron2011** [nocobase/nocobase#2112]
when create workflow the error below occured.  Version 0.10.0-alpha.2, installed via create-nocobase-app.

![image](https://github.com/nocobase/nocobase/assets/34494958/87499ebd-02d2-4b7e-b861-6d47b2f24bb0)

![image](https://github.com/nocobase/nocobase/assets/34494958/4ac9c1c4-1e2a-457e-883d-86a03aa358e7)

**Comment by mytharcher** [comment]
You could have a try to run on source code mode to check if this still happens. There is a fix on main branch, however the version of `create-nocobase-app` will be a little delay from source.

**Comment by Baron2011** [comment]
Ok. Thanks. I'll try it right away.
