### ISSUE TITLE
升级到V.10后yarn dev之后访问时报错

### ISSUE THREAD

**Issue by zhouqingjian70** [nocobase/nocobase#2114]
## How To Reproduce

按照规定步骤从V.094升级到V.10后，yarn dev之后访问时报错：
1、客户端：
Failed to compile
Module parse failed: Unexpected token (95:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   defineProperties($RangeIterator.prototype, {
|     start: getter(function () {
>       return
This error occurred during the build time and cannot be dismissed.
![image](https://github.com/nocobase/nocobase/assets/92328605/4d65d466-b468-415c-9070-69bf4b20bdc3)

2、服务器端：
Connection has been established successfully.
error - ./node_modules/core-js/internals/numeric-range-iterator.js:95:13
Module parse failed: Unexpected token (95:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   defineProperties($RangeIterator.prototype, {
|     start: getter(function () {
>       return

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by dream2023** [comment]
执行了以下命令了吗？

```bash
# Remove .umi cache
yarn rimraf -rf "./**/{.umi,.umi-production}"
# Delete compiled files
yarn rimraf -rf "./packages/*/*/{lib,esm,es,dist,node_modules}"
# Remove dependencies
yarn rimraf -rf node_modules
```

**Comment by zhouqingjian70** [comment]
> 

执行了的。我在其它机器上试了一下，没有报错。估计是我装的python版本不一样，原来3.7报错，python升级到3.11后就对了。

**Comment by zhouqingjian70** [comment]
升级到V.10.5版本后，没有报错了。
