### ISSUE TITLE
demo site crash due to 502 error

### ISSUE THREAD

**Issue by link89** [nocobase/nocobase#2122]
## Describe the bug

Unable to open demo site: https://demo.nocobase.com/new

The following requests return with 502 error could be found in the dev console

* https://demo.nocobase.com/api/app:getLang
* https://demo.nocobase.com/api/app:getPlugins

## Version

Unknow

## How To Reproduce

Access https://demo.nocobase.com/new

**Comment by zhouyanliang** [comment]
Fixed
