### ISSUE TITLE
[多应用管理]新建子应用后，现有用户在子应用中 默认都有Admin，Root,Member三种权限

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2156]
## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by woodcoal** [comment]
nocobase 在创建子应用其实相当于复制了一份数据到新库中，两应用是独立的。比如用户不是公用的，而是单独隔离的。所以权限也同时也创建了一份，其实原因是这些基础数据没有共享
插件中应用数据共享支持 pgsql，我没有测试过，不知道这些基础数据是否可以共享。

其实我觉得只要 nocobase 用租户的模式来处理多应用应该很好解决，比如说：基础数据用户权限是通用的表，在主库中，而如果增加应用可以通过不同的数据库前缀来区分；又或者通过租户字段来区分。如果非要使用不同库来区分的，权限数据只存在主库就可以了
