### ISSUE TITLE
linkage rules don't work

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2180]
I'm trying to make linking rules, but it doesn't work. (alpha-5)
![ScreenFlow](https://github.com/nocobase/nocobase/assets/2558467/75b19bb4-d507-44ff-8d14-a826250a45c2)

**Comment by alexkash** [comment]
linkage rules don't work
I'm trying to make linking rules, but it doesn't work. 
PS Cleaned browser and application cache, even rebooted

**Comment by JoGosGitHub** [comment]
@alexkash to me this looks like the normal and desired results.
I guess you want to display the interview field only for those events. So you need to create two linkage rules, one for visible and one vor hidden.

**Comment by hongboji** [comment]
Linkage rules change the state of the component when the match is successful, here the behavior is normal
