### ISSUE TITLE
Can't map correct data type in database view collection

### ISSUE THREAD

**Issue by JoGosGitHub** [nocobase/nocobase#2184]
## Describe the bug

I have files from the data type double (numbers in Nocobase) when I use them in the data base view they are displayed as float and my only option as field interface is percent (see screenshot).

## Version

Version 0.10.0-alpha.4

## How To Reproduce

1. Create General Collection with a numbers field
2. Create database view
3. Connect to database view
4. try to select field interface for this field

There should be the option to select numbers as field interface

<img width="685" alt="screenshot_nocobase" src="https://github.com/nocobase/nocobase/assets/10085077/bfd30623-2392-4aa5-8f24-0b407fdd51c7">

## Desktop (please complete the following information)

- OS: MacOS
- Browser: Chrome 114

## Additional context

- DB: MySQL 8.0.32

**Comment by JoGosGitHub** [comment]
> Hi! Noticed your issue, started looking where you can do it. Might come in handy :) I am a user, not a developer. But I have not found where I can Create database view?

Creating a database view is currently not a feature of Nocobase. You need to create a database view directly in the database via a SQL query and once the view is created you can use it within Nocobase.

**Comment by hongboji** [comment]
Currently not supported, nocobase will support linking to third-party databases in the near future to support more in database data types, the problem will be solved!

**Comment by JoGosGitHub** [comment]
@hongboji I'm not talking about third-party databases, this happens with a view created based on the internal mysql DB.
