### ISSUE TITLE
文件数据表上传附件的大小10m限制可以设置吗【版本0.11.0-alpha1】

### ISSUE THREAD

**Issue by sprdlh** [nocobase/nocobase#2215]
![企业微信截图_16888173203639](https://github.com/nocobase/nocobase/assets/6218991/e6820160-5820-4cd4-b61a-d2c0a0eeb103)
【版本0.11.0-alpha1】

**Comment by mytharcher** [comment]
提示文字有误，目前上传文件大小默认限制是 1GB。

**Comment by sprdlh** [comment]
您发来的邮件我已经收到...

**Comment by sprdlh** [comment]
> 

![image](https://github.com/nocobase/nocobase/assets/6218991/db27a299-45f4-4785-9f4f-7ea413d26aa5)
我在尝试上传一个128m的文件时确实会限制上传。
