### ISSUE TITLE
子表单和子详情打印模式下不显示

### ISSUE THREAD

**Issue by Zynismus16** [nocobase/nocobase#2218]
## Describe the bug

子表单和子详情打印模式下不显示

## Version

v0.11.0-alpha.1

![企业微信截图_20230710125722.png](https://img1.imgtp.com/2023/07/10/fSPZFVF4.png)
![企业微信截图_20230710125700.png](https://img1.imgtp.com/2023/07/10/QphU1pgm.png)

**Comment by zhouyanliang** [comment]
暂时无计划

**Comment by hongboji** [comment]
已经修复
