### ISSUE TITLE
[workflows] 选批量更新 流程会一直进行中

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2223]
## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/9fa4f876-f8f0-4fbc-a51b-8cf0b22bd810)
![image](https://github.com/nocobase/nocobase/assets/900786/143e0793-3911-4336-84b5-964fdcc7fca8)

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by mytharcher** [comment]
能否提供更多信息，比如当前运行的版本，最好能提供一下 56 这个工作流在触发当日的日志信息（位置在 `storage/logs/workflows/<date>/56.log`）。

**Comment by baiheinet** [comment]
`{"level":"error","message":"execution (8643) error: current transaction is aborted, commands ignored until end of transaction block current transaction is aborted, commands ignored until end of transaction block","name":"SequelizeDatabaseError","original":{"code":"25P02","file":"postgres.c","length":145,"line":"1428","name":"error","parameters":["2023-07-10 09:51:03.549 +00:00","2023-07-10 09:51:03.549 +00:00",8643,189,14774,-2,"{\"message\":\"column \\\"f_92ntgj8fj9i->t_x3zj5oxdcs8.createdAt\\\" must appear in the GROUP BY clause or be used in an aggregate function\",\"stack\":\"Error\\n `

**Comment by baiheinet** [comment]
> 有用到聚合查询节点么？或者方便的话可以私下给我更多的信息，微信群可以联系到我。

没有 非常简单  就三个节点
![image](https://github.com/nocobase/nocobase/assets/900786/a3611b76-7bf2-4687-986a-9394f9830246)

**Comment by mytharcher** [comment]
日志的上下文信息可以再多一些么？error 之前应该有一部分是对应节点的信息。更新数据的配置最好也看下。

**Comment by baiheinet** [comment]
隐私处理了一下 这是全的

`{"level":"info","message":"new event triggered, now events: 1","timestamp":"2023-07-10T09:51:03.301Z"}
{"level":"info","message":"execution (8643) starting...","timestamp":"2023-07-10T09:51:03.324Z"}
{"level":"info","message":"execution (8643) run instruction [request] for node (190)","timestamp":"2023-07-10T09:51:03.332Z"}
{"level":"info","message":"request (#190) sent to \"https://www.baidu.com", waiting for response...","timestamp":"2023-07-10T09:51:03.343Z"}
{"level":"info","message":"execution (8643) exiting with status 0","timestamp":"2023-07-10T09:51:03.344Z"}
{"level":"info","message":"execution (8643) finished with status: 0","timestamp":"2023-07-10T09:51:03.347Z"}
{"level":"info","message":"request (#190) response received, status: 1","timestamp":"2023-07-10T09:51:03.522Z"}
{"level":"info","message":"execution (8643) resuming...","timestamp":"2023-07-10T09:51:03.526Z"}
{"level":"info","message":"execution (8643) run instruction [request] for node (190)","timestamp":"2023-07-10T09:51:03.538Z"}
{"level":"info","message":"execution (8643) run instruction [request] for node (190) finished as status: 1","timestamp":"2023-07-10T09:51:03.541Z"}
{"level":"info","message":"execution (8643) run instruction [update] for node (189)","timestamp":"2023-07-10T09:51:03.542Z"}
{"error":{"name":"SequelizeDatabaseError","original":{"code":"42803","file":"parse_agg.c","length":201,"line":"1413","name":"error","position":"25","routine":"check_ungrouped_columns_walker","severity":"ERROR","sql":"SELECT \"employee\".\"id\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"createdAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.createdAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"updatedAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.updatedAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_zttmaj1ru5b\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.f_zttmaj1ru5b\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_esygqvdlvu1\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.f_esygqvdlvu1\" FROM \"employee\" AS \"employee\" LEFT OUTER JOIN ( \"t_x3zj5oxdcs8\" AS \"f_92ntgj8fj9i->t_x3zj5oxdcs8\" INNER JOIN \"check\" AS \"f_92ntgj8fj9i\" ON \"f_92ntgj8fj9i\".\"id\" = \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_esygqvdlvu1\") ON \"employee\".\"id\" = \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_zttmaj1ru5b\" WHERE (\"f_92ntgj8fj9i\".\"id\" = 17616) GROUP BY \"employee\".\"id\";"},"parameters":{},"parent":{"code":"42803","file":"parse_agg.c","length":201,"line":"1413","name":"error","position":"25","routine":"check_ungrouped_columns_walker","severity":"ERROR","sql":"SELECT \"employee\".\"id\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"createdAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.createdAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"updatedAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.updatedAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_zttmaj1ru5b\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.f_zttmaj1ru5b\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_esygqvdlvu1\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.f_esygqvdlvu1\" FROM \"employee\" AS \"employee\" LEFT OUTER JOIN ( \"t_x3zj5oxdcs8\" AS \"f_92ntgj8fj9i->t_x3zj5oxdcs8\" INNER JOIN \"check\" AS \"f_92ntgj8fj9i\" ON \"f_92ntgj8fj9i\".\"id\" = \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_esygqvdlvu1\") ON \"employee\".\"id\" = \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_zttmaj1ru5b\" WHERE (\"f_92ntgj8fj9i\".\"id\" = 17616) GROUP BY \"employee\".\"id\";"},"sql":"SELECT \"employee\".\"id\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"createdAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.createdAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"updatedAt\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.updatedAt\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_zttmaj1ru5b\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.f_zttmaj1ru5b\", \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_esygqvdlvu1\" AS \"f_92ntgj8fj9i.t_x3zj5oxdcs8.f_esygqvdlvu1\" FROM \"employee\" AS \"employee\" LEFT OUTER JOIN ( \"t_x3zj5oxdcs8\" AS \"f_92ntgj8fj9i->t_x3zj5oxdcs8\" INNER JOIN \"check\" AS \"f_92ntgj8fj9i\" ON \"f_92ntgj8fj9i\".\"id\" = \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_esygqvdlvu1\") ON \"employee\".\"id\" = \"f_92ntgj8fj9i->t_x3zj5oxdcs8\".\"f_zttmaj1ru5b\" WHERE (\"f_92ntgj8fj9i\".\"id\" = 17616) GROUP BY \"employee\".\"id\";"},"level":"error","message":"execution (8643) run instruction [update] for node (189) failed: ","timestamp":"2023-07-10T09:51:03.548Z"}
{"level":"error","message":"execution (8643) error: current transaction is aborted, commands ignored until end of transaction block current transaction is aborted, commands ignored until end of transaction block","name":"SequelizeDatabaseError","original":{"code":"25P02","file":"postgres.c","length":145,"line":"1428","name":"error","parameters":["2023-07-10 09:51:03.549 +00:00","2023-07-10 09:51:03.549 +00:00",8643,189,14774,-2,"{\"message\":\"column \\\"f_92ntgj8fj9i->t_x3zj5oxdcs8.createdAt\\\" must appear in the GROUP BY clause or be used in an aggregate function\",\"stack\":\"Error\\n    at Query.run (xxx/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\\n    at xxx/node_modules/sequelize/lib/sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async PostgresQueryInterface.select (xxx/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\\n    at async employee.findAll (xxx/node_modules/sequelize/lib/model.js:1140:21)\"}"],"routine":"exec_parse_message","severity":"ERROR","sql":"INSERT INTO \"jobs\" (\"id\",\"createdAt\",\"updatedAt\",\"executionId\",\"nodeId\",\"upstreamId\",\"status\",\"result\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING \"id\",\"createdAt\",\"updatedAt\",\"executionId\",\"nodeId\",\"upstreamId\",\"status\",\"result\";"},"parameters":["2023-07-10 09:51:03.549 +00:00","2023-07-10 09:51:03.549 +00:00",8643,189,14774,-2,"{\"message\":\"column \\\"f_92ntgj8fj9i->t_x3zj5oxdcs8.createdAt\\\" must appear in the GROUP BY clause or be used in an aggregate function\",\"stack\":\"Error\\n    at Query.run (xxx/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\\n    at xxx/node_modules/sequelize/lib/sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async PostgresQueryInterface.select (xxx/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\\n    at async employee.findAll (xxx/node_modules/sequelize/lib/model.js:1140:21)\"}"],"parent":{"code":"25P02","file":"postgres.c","length":145,"line":"1428","name":"error","parameters":["2023-07-10 09:51:03.549 +00:00","2023-07-10 09:51:03.549 +00:00",8643,189,14774,-2,"{\"message\":\"column \\\"f_92ntgj8fj9i->t_x3zj5oxdcs8.createdAt\\\" must appear in the GROUP BY clause or be used in an aggregate function\",\"stack\":\"Error\\n    at Query.run (xxx/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\\n    at xxx/node_modules/sequelize/lib/sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async PostgresQueryInterface.select (xxx/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)\\n    at async employee.findAll (xxx/node_modules/sequelize/lib/model.js:1140:21)\"}"],"routine":"exec_parse_message","severity":"ERROR","sql":"INSERT INTO \"jobs\" (\"id\",\"createdAt\",\"updatedAt\",\"executionId\",\"nodeId\",\"upstreamId\",\"status\",\"result\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING \"id\",\"createdAt\",\"updatedAt\",\"executionId\",\"nodeId\",\"upstreamId\",\"status\",\"result\";"},"sql":"INSERT INTO \"jobs\" (\"id\",\"createdAt\",\"updatedAt\",\"executionId\",\"nodeId\",\"upstreamId\",\"status\",\"result\") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING \"id\",\"createdAt\",\"updatedAt\",\"executionId\",\"nodeId\",\"upstreamId\",\"status\",\"result\";","stack":"Error\n    at Query.run (xxx/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at xxx/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.insert (xxx/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n    at async model.save (xxx/node_modules/sequelize/lib/model.js:2490:35)\n    at async jobs.create (xxx/node_modules/sequelize/lib/model.js:1362:12)","timestamp":"2023-07-10T09:51:03.552Z"}
`
![image](https://github.com/nocobase/nocobase/assets/900786/d6e35524-4a0d-4d8a-bc7c-0c399e23433e)

**Comment by mytharcher** [comment]
看起来 `SequelizeDatabaseError` 这段报错是更新节点的错误结果（执行历史界面）是吧？就是确认一下。

**Comment by baiheinet** [comment]
反正 我换成逐条更新就好了 ， 换成批量更新 就不行

**Comment by mytharcher** [comment]
> 反正 我换成逐条更新就好了 ， 换成批量更新 就不行

好的，大概定位到问题区域了，解决后会在这边更新。

**Comment by mytharcher** [comment]
@baiheinet 可以更新 main 再试试还有没有报错？

**Comment by baiheinet** [comment]
已ok
