### ISSUE TITLE
Set default value for checkbox set wrong payload

### ISSUE THREAD

**Issue by antran511** [nocobase/nocobase#2238]
## Describe the bug
When I set a default value for check box, it set the wrong value for payload:

## Version
v0.11.0-alpha-1
## How To Reproduce
1. Create a field checkbox in any collection
2. Make a form with checkbox input and set default value for it
3. Submit the form

## Expected behavior
payload should be `{isSupplier: true}` instead of `{isSupplier: {isSupplier: true}}`

## Screenshots

<img width="1199" alt="Screen Shot 2023-07-12 at 11 13 20" src="https://github.com/nocobase/nocobase/assets/19794620/f837b817-c986-4b54-bbed-b93a1a091990">

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by antran511** [comment]
Adding more info, if we set default value of checkbox in the collections and fields page. And then change the default value of it in a particular form, it won't work

**Comment by antran511** [comment]
On investigation, the first bug I found that whenever i change the value of check box, it doesn't trigger onChange function
<img width="734" alt="Screen Shot 2023-07-12 at 14 36 17" src="https://github.com/nocobase/nocobase/assets/19794620/827982db-f201-4b66-9dd8-f4eedb2918be">

**Comment by Niko030303** [comment]
I didn't recurrent this scene

**Comment by hongboji** [comment]
nocobase refactors the way variables and default values are obtained.
