### ISSUE TITLE
Render Failed in table block when displaying window (tab) is not in full screen mode

### ISSUE THREAD

**Issue by OP-BRO** [nocobase/nocobase#2245]
## Describe the bug

Hello @mytharcher @zhouyanliang 
Would you like to look into this issue as you have solved related issue #1805 https://github.com/nocobase/nocobase/issues/1805

rendering failed error in table while in tab is not in full screen, usually this error occurs in the beginning of the launch of the site. And is very uncertain error, some time it occurs for some user some time its not and also depends on browser the user is using.

## Version

yarn run v1.22.4
$ nocobase --version
0.9.3-alpha.1

## How To Reproduce

it may or may not reproduce i have tried on different pc, on some it showed error on some its not.
step:
got to tab where there is table to view and make sure that tab is not full screen and try different browser.

## Expected behavior

to show the data of table but it try to load table for some time and render failed came and then it crashes.

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/91185325/4aad7f89-b2d7-4799-81a9-931af5cd26c2)
![image](https://github.com/nocobase/nocobase/assets/91185325/d4589d20-17af-4a86-b282-073c2b575f9a)
after a sec that it crashed and show this
![image](https://github.com/nocobase/nocobase/assets/91185325/6b04dc73-8c30-453c-80ee-3694ff58dc7c)

## Desktop (please complete the following information)

- OS: window 10 , 11
- Browser: Chrome , edge

## Smartphone (please complete the following information)

didn't tried on smartphone.

## Additional context

this error may or may not occurs sometime. 
error logs:
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
▼ 3 stack frames were expanded.
checkForNestedUpdates
./node_modules/react-dom/cjs/react-dom.development.js:23093
scheduleUpdateOnFiber
./node_modules/react-dom/cjs/react-dom.development.js:21164
dispatchAction
./node_modules/react-dom/cjs/react-dom.development.js:15660
▲ 3 stack frames were expanded.
(anonymous function)
./packages/core/client/src/schema-component/hooks/useTableSize.ts:19
  16 |    const paginationHeight = paginationRect
  17 |      ? paginationRect.y - tableContentRect.height - tableContentRect.y + paginationRect.height
  18 |      : 0;
> 19 |    setTableWidth(clientRect.width);
     | ^  20 |    setTableHeight(tableHeight - headerHeight - paginationHeight);
  21 |  }, []);
  22 | 
View compiled
tableSizeRefCallback
./packages/core/client/src/schema-component/hooks/useTableSize.ts:25
  22 | 
  23 |  const tableSizeRefCallback: React.RefCallback<HTMLDivElement> = (ref) => {
  24 |    elementRef.current = ref;
> 25 |    calcTableSize();
     | ^  26 |  };
  27 | 
  28 |  useEventListener('resize', calcTableSize);
View compiled
▼ 24 stack frames were expanded.
commitAttachRef
./node_modules/react-dom/cjs/react-dom.development.js:20023
commitLayoutEffects
./node_modules/react-dom/cjs/react-dom.development.js:22808
HTMLUnknownElement.callCallback
./node_modules/react-dom/cjs/react-dom.development.js:188
invokeGuardedCallbackDev
./node_modules/react-dom/cjs/react-dom.development.js:237
invokeGuardedCallback
./node_modules/react-dom/cjs/react-dom.development.js:292
commitRootImpl
./node_modules/react-dom/cjs/react-dom.development.js:22541
unstable_runWithPriority
./node_modules/scheduler/cjs/scheduler.development.js:653
runWithPriority$1
./node_modules/react-dom/cjs/react-dom.development.js:11039
commitRoot
./node_modules/react-dom/cjs/react-dom.development.js:22381
finishSyncRender
./node_modules/react-dom/cjs/react-dom.development.js:21807
performSyncWorkOnRoot
./node_modules/react-dom/cjs/react-dom.development.js:21793
(anonymous function)
./node_modules/react-dom/cjs/react-dom.development.js:11089
unstable_runWithPriority
./node_modules/scheduler/cjs/scheduler.development.js:653
runWithPriority$1
./node_modules/react-dom/cjs/react-dom.development.js:11039
flushSyncCallbackQueueImpl
./node_modules/react-dom/cjs/react-dom.development.js:11084
flushSyncCallbackQueue
./node_modules/react-dom/cjs/react-dom.development.js:11072
scheduleUpdateOnFiber
./node_modules/react-dom/cjs/react-dom.development.js:21199
dispatchAction
./node_modules/react-dom/cjs/react-dom.development.js:15660
Fetch.subscribe
./node_modules/ahooks/es/useUpdate/index.js:7
Fetch.setState
./node_modules/ahooks/es/useRequest/src/Fetch.js:29
Fetch.<anonymous>
./node_modules/ahooks/es/useRequest/src/Fetch.js:86
step
./node_modules/tslib/tslib.es6.js:147
next
./node_modules/tslib/tslib.es6.js:128
fulfilled
./node_modules/tslib/tslib.es6.js:118
▲ 24 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

after clicking on view compiled:
http://localhost:13000/umi.js:687451:5
  687448 |   if (!tableContentRect) return;
  687449 |   var paginationRect = (_elementRef$current$q3 = elementRef.current.querySelector('.ant-table-pagination')) === null || _elementRef$current$q3 === void 0 ? void 0 : _elementRef$current$q3.getBoundingClientRect();
  687450 |   var paginationHeight = paginationRect ? paginationRect.y - tableContentRect.height - tableContentRect.y + paginationRect.height : 0;
> 687451 |   setTableWidth(clientRect.width);
         |   ^  687452 |   setTableHeight(tableHeight - headerHeight - paginationHeight);
  687453 | }, []);
  687454 | 
View source
tableSizeRefCallback
http://localhost:13000/umi.js:687457:5
  687454 | 
  687455 | var tableSizeRefCallback = ref => {
  687456 |   elementRef.current = ref;
> 687457 |   calcTableSize();
         |   ^  687458 | };
  687459 | 
  687460 | Object(ahooks__WEBPACK_IMPORTED_MODULE_1__["useEventListener"])('resize', calcTableSize);
View source

**Comment by hongboji** [comment]
We have fixed the issue of infinite loop calculation for page rendering, you can verify it with the latest version, thanks!
