### ISSUE TITLE
Calendar Block will delete itself when drag & drop inside itself at UI editor mode

### ISSUE THREAD

**Issue by SouthpawGoblin** [nocobase/nocobase#2265]
## Describe the bug

Calendar Block will delete itself when drag & drop inside itself in UI editor mode, see screenshots below.

## Version

Newly deployed demo site

## How To Reproduce

apply for a new demo site, then:
1. Go to 任务 -> 任务日历
2. use the top-right drag button to try moving the block
3. release mouse inside the calendar itself
4. the calendar vanishes and a "saved successfully" message popped up

## Expected behavior

dropping inside the block itself should do nothing like other block types
## Screenshots

<img width="1686" alt="image" src="https://github.com/nocobase/nocobase/assets/9673067/b42375b8-9c7a-4397-9c1e-eff7e602509b">
<img width="1688" alt="image" src="https://github.com/nocobase/nocobase/assets/9673067/e568850f-bb09-4861-9e6a-4a2c5a99d0b2">

## Desktop (please complete the following information)

- OS: macOS Ventura 13.2.1
- Browser: Microsoft Edge 114.0.1823.79

**Comment by hongboji** [comment]
The demo site version is too old and has been fixed on the new version
