### ISSUE TITLE
数据表配置中的字段配置问题

### ISSUE THREAD

**Issue by zanderpu** [nocobase/nocobase#228]
在添加字段->系统信息->最后更新日期

这个“最后更新日期”对应的字段实际上是“最后更新人”，应该是页面文字写错了

![123](https://user-images.githubusercontent.com/13461974/157364676-75c41d39-aca9-4385-908f-1761d68e91eb.png)

**Comment by zhouyanliang** [comment]
感谢反馈。近期将发布的公测版本已修复该问题。
