### ISSUE TITLE
Nothing exists

### ISSUE THREAD

**Issue by troykelly** [nocobase/nocobase#2287]
## Describe the bug

When creating a sub-app, nothing seems to exist. APPNAME.`themeConfig` does not exist; APPNAME.`localizationTexts` does not exist.

## Version

nocobase/nocobase:main@sha256:2354ad42cdf555627d547ad8c01e8d9e80849a41b68cb30100ebbdd4a0de33ed

## How To Reproduce

Steps to reproduce the behaviour:

1. Go to dashboard
2. Click on `multi-app-manager/applications`
3. Create a new app
5. View app
6. See errors

## Expected behavior

The app should work

## Screenshots

<img width="981" alt="Screenshot 2023-07-20 at 15 29 40" src="https://github.com/nocobase/nocobase/assets/4564803/c9de970d-71b1-4383-a0a3-8059847e4c20">

**Comment by hongboji** [comment]
Creating a sub-application is equivalent to creating a brand new application, a brand new application is no content, the main ability of the main sub-application is login-free; in the case of the database is postgresql, the main application of the Collection can be shared to the sub-application, the sub-application only need to focus on the UI, permissions can be used to share a common set of database tables; screenshots of the error exists in the two plug-ins can not be used in the sub-application, the theme of the plug-ins, please update to the latest version of the plug-ins in multilanguage issues are being repaired

**Comment by troykelly** [comment]
@hongboji 
Can I confirm this was fixed overnight? I was using the latest container versions.

**Comment by hongboji** [comment]
Please use the latest version, it has been fixed
