### ISSUE TITLE
Problem with API keys

### ISSUE THREAD

**Issue by S3Coloris** [nocobase/nocobase#2327]
When we used the Docker build (v0.11.0-alpha.1 - 2023-07-08), we created an API Key that we successfully used. Today, after updating the Docker container to the latest version (v0.11.1-alpha.3 - 2023-07-26), our API Key stopped working.
<img width="1324" alt="Screenshot 2023-07-26 at 16 14 54" src="https://github.com/nocobase/nocobase/assets/114476533/90344535-4015-414c-9c2c-9470db0df8a1">
<img width="857" alt="Screenshot 2023-07-26 at 16 18 48" src="https://github.com/nocobase/nocobase/assets/114476533/02931ac9-ba55-494f-8d68-dc583a3b0fa7">

**Comment by hongboji** [comment]
Please try changing POST to GET

**Comment by S3Coloris** [comment]
Error
<img width="850" alt="Screenshot 2023-07-27 at 16 21 52" src="https://github.com/nocobase/nocobase/assets/114476533/b8dc79b9-2580-4c7a-854c-c81a4cde13a2">
