### ISSUE TITLE
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full

### ISSUE THREAD

**Issue by boychina** [nocobase/nocobase#2368]
## Describe the bug

<img width="906" alt="image" src="https://github.com/nocobase/nocobase/assets/20528499/bf1fd9ec-7664-47e1-add6-c0b36988059a">

## Version

v0.11.1-alpha.5

## Desktop (please complete the following information)

- OS: MacOS
- Browser: chrome 115.0.5790.114

**Comment by hongboji** [comment]
Could you please provide more information in accordance with the feedback question template in order to locate the problem?
