### ISSUE TITLE
Calendar - no translation for the names of the days

### ISSUE THREAD

**Issue by alexsidnenko** [nocobase/nocobase#2370]
## Version

Version 0.11.1-alpha.5.20230731051539

## Expected behavior

There is no translation for the names of the days of the week. It is not possible to translate in the Localization plugin  

## Screenshots

<img width="1099" alt="Screenshot 2023-08-01 at 12 33 49" src="https://github.com/nocobase/nocobase/assets/63589831/2b5be750-a3e3-45a5-9c56-ee923738c6da">
<img width="1109" alt="Screenshot 2023-08-01 at 12 35 20" src="https://github.com/nocobase/nocobase/assets/63589831/963b2045-d3d2-451f-a61c-880cede7ad71">

## Desktop (please complete the following information)

- OS: MacOS
- Browser: Safari Version 16.5.2

**Comment by Xilesun** [comment]
Hi, this is a component from [Antd](https://ant.design/docs/react/i18n) and currently not covered in the plugin. What locale do you use?

**Comment by alexkash** [comment]
Ukrainian

**Comment by hongboji** [comment]
nocobase has worked hard to solve the problem, please use the latest version of the
