### ISSUE TITLE
在工作流的查询中，如果选中了“允许结果是多条数据”，节点会报错。

### ISSUE THREAD

**Issue by liangyh2000** [nocobase/nocobase#2405]
## Describe the bug
在工作流的查询中，如果选中了“允许结果是多条数据”，节点会报错。
{
  "stack": "d:\\nocobase\\my-nocobase-app\\packages\\plugins\\workflow\\src\\server\\utils.ts:10\n  const result = data.get();\n                      ^\n\nTypeError: data.get is not a function\n    at toJSON (d:\\nocobase\\my-nocobase-app\\packages\\plugins\\workflow\\src\\server\\utils.ts:10:23)\n    at Array.map (<anonymous>)\n    at toJSON (d:\\nocobase\\my-nocobase-app\\packages\\plugins\\workflow\\src\\server\\utils.ts:8:17)\n    at <anonymous> (d:\\nocobase\\my-nocobase-app\\packages\\plugins\\workflow\\src\\server\\utils.ts:13:21)\n    at Array.forEach (<anonymous>)\n    at toJSON (d:\\nocobase\\my-nocobase-app\\packages\\plugins\\workflow\\src\\server\\utils.ts:11:62)\n    at <anonymous> (d:\\nocobase\\my-nocobase-app\\packages\\plugins\\workflow\\src\\server\\utils.ts:13:21)\n    at Array.forEach (<anonymous>)\n    at toJSON (d:\\nocobase\\my-nocobase-app\\packages\\plugins\\workflow\\src\\server\\utils.ts:11:62)\n    at Array.map (<anonymous>)",
  "message": "data.get is not a function"
}

## Version

Version 0.12.0-alpha.3

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by mytharcher** [comment]
未能复现，可能需要提供更详细的数据表配置和工作流配置。

**Comment by liangyh2000** [comment]
好的，我再测试一下，看看是不是我的使用的方式不对。谢谢。

**Comment by mytharcher** [comment]
暂时先关了，如果再有复现可以重新打开。
