### ISSUE TITLE
Error when logging into a new application

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2408]
I got this error when I created a new app in multiapp while logging into it. After that, I turned off the new localization plugin and could log into the new app. 

<img width="459" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/67379958-8476-435f-8003-c9a44d33a5fb">
<img width="446" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/d2637471-f3cb-4376-8ffb-7b5341fde070">
But I got this error:
<img width="454" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/6aae19a1-8385-4d44-b15a-0d2873ccf268">
After closing these alerts continued to work.(cache cleaned). 

If you go to the theme editor in the new application, then 
<img width="429" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/1189e6eb-4737-46c9-b408-dd7a50435d89">

**Comment by pingxin403** [comment]
I have the same problem. 
1. After opening the theme editing plug-in. 
2.Then open the multi-application plug-in. 
3. Create a sub-application. 
4. Enter the sub-application page to report an error. Prompt that the themeConfig table does not exist. 
Cause of the problem: when creating a sub-application, the data table of the corresponding theme editing plug-in was not initialized
=======
我也遇到这样的问题
1. 开启主题编辑插件之后
2. 再开启多应用插件
3. 创建子应用
4. 进入子应用页面报错，提示themeConfig表不存在

问题原因：创建子应用时，没有把对应的主题编辑插件的数据表进行初始化

**Comment by pingxin403** [comment]
在未开启 **子应用的独立部署** 时会遇到这个问题，重新安装子应用的主题插件没有作用

临时修复的话需要安装主应用的主题插件

**Comment by alexkash** [comment]
感谢您的回复！我会尝试这样做的。自主部署和非自主部署有什么区别？

**Comment by alexkash** [comment]
没有关于主题的错误信息，但是有："relation "peoples.localisationTexts" 不存在"。

**Comment by pingxin403** [comment]
> 没有关于主题的错误信息，但是有："relation "peoples.localisationTexts" 不存在"。

也同样是子应用创建时插件的数据表创建的问题，临时修复方法也是需要重新安装主应用的插件Localization management

**Comment by Xilesun** [comment]
Sorry here, this is a known issue, the current solution is disable and re-enable theme and localization plugins.
