### ISSUE TITLE
关系数据库快照插件开启问题

### ISSUE THREAD

**Issue by gold-Kai** [nocobase/nocobase#2411]
## Describe the bug

使用mysql 情况下打开关系数据库快照插件，插件不显示。

## Version

0.12.0 alpha-3

## How To Reproduce

打开数据库快照插件后，所有插件配置页内不显示该插件

**Comment by hongboji** [comment]
快照字段出现在字段类型列表中

**Comment by hongboji** [comment]
使用Version 0.13.0-alpha.4试试
