### ISSUE TITLE
UTF 8 support when uploading files. 

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2416]
When uploading files, their names are converted to unreadable characters.

<img width="281" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/3a1e83ee-5bdb-491f-98e7-1eb3a32ab648">
 
In this case, the name was Cyrillic.

**Comment by hongboji** [comment]
link T-1232

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/2429
