### ISSUE TITLE
上传文件文件名乱码

### ISSUE THREAD

**Issue by maxmaosir** [nocobase/nocobase#2442]
![image](https://github.com/nocobase/nocobase/assets/16662736/ac5898e5-c237-4725-9749-5ef18defa56e)
![image](https://github.com/nocobase/nocobase/assets/16662736/7cb5545d-69b9-4b36-8e5f-0203aa3723eb)
你好，老师，求助，我使用 create-nocobase-app 方式安装，安装后上传文件文件名乱码，我需要检查哪里的配置。

**Comment by hongboji** [comment]
[https://github.com/nocobase/nocobase/pull/2429](url)

**Comment by hongboji** [comment]
更新或使用最新版本
