### ISSUE TITLE
(ACL)：自定义数据范围，报错

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2464]
## Describe the bug

![image](https://github.com/nocobase/nocobase/assets/900786/a42a50c4-f3a3-4524-9ed3-05ae3a722b6d)
![image](https://github.com/nocobase/nocobase/assets/900786/87552d08-9cba-4bca-b422-8676b217f9b8)
![image](https://github.com/nocobase/nocobase/assets/900786/56ada1e6-be6e-4047-992d-68dac74b72d0)

**Comment by hongboji** [comment]
已经修复 请使用最新版本

**Comment by baiheinet** [comment]
请问那个版本修复了

**Comment by hongboji** [comment]
Version 0.13.0-alpha.4

**Comment by baiheinet** [comment]
![image](https://github.com/nocobase/nocobase/assets/900786/e7f8dcc9-9f1e-40f1-8736-a3e55125b95e)
![image](https://github.com/nocobase/nocobase/assets/900786/1e2d6013-f62c-4ce7-a294-5c210c6b2335)

**Comment by hongboji** [comment]
是通过什么方式部署的？ 升级还是全新安装 ，数据库是哪种？

**Comment by baiheinet** [comment]
一直升级来的 Postgresql

**Comment by hongboji** [comment]
清除浏览器缓存试试

**Comment by baiheinet** [comment]
清理了 服务器也重启过

**Comment by hongboji** [comment]
是否方便可以发一个数据库备份到j414562100@qq.com

**Comment by baiheinet** [comment]
能限制那个表吗 整体不行 人员数据

**Comment by baiheinet** [comment]
👌
