### ISSUE TITLE
Does not show data in a tree table. 

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2478]
1) If you switch the table view to tree, the data disappears, if you return it, you can see it. They also become visible if you create a table below :)
2) The Collapse/Decollapse button doesn't work. 
![ScreenFlow](https://github.com/nocobase/nocobase/assets/2558467/711f19a8-bcaa-4498-bbe4-6b757de2539e)

**Comment by hongboji** [comment]
In this new version, we have cancelled this setting function for the time being, and we will provide better functions in the future.
