### ISSUE TITLE
🆘在线等  field = useField<ArrayField>()  为空，升级最新后，好多插件不能用

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2500]
## Version

最新git

## Screenshots
行政区插件
![image](https://github.com/nocobase/nocobase/assets/900786/9d0e5f33-ec10-4cb2-b1a7-0f5f3b831374)

导入插件

![image](https://github.com/nocobase/nocobase/assets/900786/c1a67b2b-4ac4-4ec8-bdfa-2fa695446b28)

工作流插件
![image](https://github.com/nocobase/nocobase/assets/900786/99fd33e4-4111-4a50-9068-7205f74226ea)

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by baiheinet** [comment]
需要 先build 才能dev

**Comment by dream2023** [comment]
问题还存在吗？

**Comment by baiheinet** [comment]
还在 没人提交修复啊

**Comment by dream2023** [comment]
你先拉一下最新代码，试试

**Comment by baiheinet** [comment]
![image](https://github.com/nocobase/nocobase/assets/900786/21a49982-70e7-4852-8357-705107c7d4fb)
我一般时时拉到最新，具体那个提交 我拉一下

**Comment by dream2023** [comment]
所以现在还有问题是吗，最新 commit

**Comment by baiheinet** [comment]
还在 没人提交修复啊

**Comment by dream2023** [comment]
> 还在 没人提交修复啊

好的，我用 main 分支跑一下

**Comment by dream2023** [comment]
![image](https://github.com/nocobase/nocobase/assets/19297757/64c8dbca-f0b4-4845-85f3-ebd168f325b1)

我这没法复现，你要不然重新 clone 一下，跑起来试试？

**Comment by baiheinet** [comment]
我试试啊

**Comment by baiheinet** [comment]
不行啊

**Comment by baiheinet** [comment]
我应该从哪儿了下手 debug一下了

**Comment by dream2023** [comment]
node 版本是多少？

**Comment by baiheinet** [comment]
v18.16.0

**Comment by dream2023** [comment]
> 我应该从哪儿了下手 debug一下了

@zhangzhonghe  这个 BUG 你有思路吗？

**Comment by zhangzhonghe** [comment]
@baiheinet 请问简单的复现步骤是什么？

我试了一下下面的步骤，没发现你所提的问题：
1. 清空本地数据库
2. 清空 node_modules
3. 运行 `yarn nocobase install`
4. 下载依赖 `yarn install`
5. 运行项目 `yarn dev`

![image](https://github.com/nocobase/nocobase/assets/38434641/9d295450-53bc-463a-8aea-44f4aed2970f)

**Comment by dream2023** [comment]
> 不行啊

没有别人反馈这个问题，换个电脑试试？

**Comment by dream2023** [comment]
```bash
git clone https://github.com/nocobase/nocobase.git && yarn install && yarn build && yarn nocobase install -f && yarn dev
```

**Comment by baiheinet** [comment]
ok
