### ISSUE TITLE
BUG: Table is deleted when deleting a block

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2504]
When trying to delete a block from a window, everything is deleted, I include the table with which the windows are linked to
![delete_block](https://github.com/nocobase/nocobase/assets/2558467/d2feb891-8809-4da9-8840-9558fdf89722)

**Comment by hongboji** [comment]
What is the version number of nocobase?

**Comment by alexkash** [comment]
This was on the last alpha 12. I haven't checked the latest version

**Comment by alexkash** [comment]
I made this table from a template, maybe there is a bug related to that?

**Comment by hongboji** [comment]
We have improved this feature and you can verify if it is resolved with a new release

**Comment by chenos** [comment]
fixed
