### ISSUE TITLE
Error auth:signIn

### ISSUE THREAD

**Issue by alexsidnenko** [nocobase/nocobase#2505]
## Describe the bug

If you perform authorization via Postman or a script, you get a 401 error. Everything worked up to a certain point, then during authorization it started showing the data of another user, and then it stopped working altogether. Authorization on the login form works, the login and password are correct, I use them in the login form and they work

## Version

Version 0.12.0-alpha.5

## Screenshots

<img width="860" alt="Screenshot 2023-08-22 at 21 54 21" src="https://github.com/nocobase/nocobase/assets/63589831/a9a284bf-698c-44fa-be08-67308833f3ca">

## Additional context

I'am use Docker container with PostgreSQL
Logs:
{"level":"info","message":"BEGIN: POST /api/auth:signIn","reqId":"b9ffc661-93ad-4b7c-ba44-3185f250b82e","timestamp":"2023-08-22T17:59:50.101Z"}
{"can":null,"level":"info","message":"ctx permission","reqId":"b9ffc661-93ad-4b7c-ba44-3185f250b82e","skip":true,"timestamp":"2023-08-22T17:59:50.106Z"}
{"level":"info","message":"acl params","reqId":"b9ffc661-93ad-4b7c-ba44-3185f250b82e","timestamp":"2023-08-22T17:59:50.107Z"}
{"level":"info","message":"acl parsedParams","reqId":"b9ffc661-93ad-4b7c-ba44-3185f250b82e","timestamp":"2023-08-22T17:59:50.108Z"}
{"level":"error","message":"The password is incorrect, please re-enter","reqId":"b9ffc661-93ad-4b7c-ba44-3185f250b82e","stack":"UnauthorizedError: The password is incorrect, please re-enter\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at /app/nocobase/node_modules/@nocobase/auth/lib/base/auth.js:71:25\n    at Generator.throw (<anonymous>)\n    at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/auth/lib/base/auth.js:8:103)\n    at _throw (/app/nocobase/node_modules/@nocobase/auth/lib/base/auth.js:9:291)","timestamp":"2023-08-22T17:59:50.171Z"}
{"errors":[{"message":"The password is incorrect, please re-enter"}],"level":"warn","message":"END: POST /api/auth:signIn","req":{"action":{"actionName":"signIn","params":{"actionName":"signIn","resourceName":"auth","values":{"email":"alexsidnenko77@gmail.com","password":"jfyQ9u6UcTLtY"}},"resourceName":"auth"}},"reqId":"b9ffc661-93ad-4b7c-ba44-3185f250b82e","res":{"status":401},"responseTime":72,"timestamp":"2023-08-22T17:59:50.173Z"}

**Comment by Xilesun** [comment]
Thanks. It will be fixed in #2515 . However, `email` is a deprecated parameter, it would be better to use `account` instead.

**Comment by alexsidnenko** [comment]
It's works with `account`, Thanks!
