### ISSUE TITLE
移动端启用底部标签栏bug

### ISSUE THREAD

**Issue by psbetter** [nocobase/nocobase#2533]
## Describe the bug

移动端设计页面，开启底部标签栏提示 “ PRIMARY 字段值是唯一的 ” 错误，底部标签栏会显现，但刷新后失效，无法设置。

## Version

0.13.2

**Comment by hongboji** [comment]
请问是什么方式安装 ，什么数据库 ，能否报错截图 ？

**Comment by psbetter** [comment]
docker安装，数据库mysql:8，报错信息如下：
`2023-08-27 20:19:00 error: Validation error {"app":"main","errors":[{"instance":null,"message":"PRIMARY must be unique","origin":"DB","path":"PRIMARY","type":"unique violation","validatorArgs":[],"validatorKey":"not_unique","validatorName":null,"value":"cdlu27chtk4"}],"fields":{"PRIMARY":"cdlu27chtk4"},"headers":{"Access-Control-Allow-Origin":"http://localhost:13000","Access-Control-Expose-Headers":"content-disposition","vary":"Origin"},"name":"SequelizeUniqueConstraintError","original":{"code":"ER_DUP_ENTRY","errno":1062,"sql":"INSERT INTO uiSchemas (`x-uid`, `name`, `schema`) VALUES ('mygw89afc7g', 'tabBar', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"MTabBar\\\",\\\"x-component-props\\\":{}}'),('sbd2oc8bj8g', '7mqji2eya2t', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"MTabBar.Item\\\",\\\"x-designer\\\":\\\"MTabBar.Item.Designer\\\",\\\"x-component-props\\\":{\\\"icon\\\":\\\"HomeOutlined\\\",\\\"title\\\":\\\"{{t(\\'Untitled\\', { ns: \\'mobile-client\\', nsMode: \\'fallback\\' })}}\\\"}}'),('cdlu27chtk4', 'page', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-designer\\\":\\\"MPage.Designer\\\",\\\"x-component\\\":\\\"MPage\\\",\\\"x-component-props\\\":{},\\\"x-index\\\":1}'),('6emip1vppgr', 'grid', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"Grid\\\",\\\"x-initializer\\\":\\\"MBlockInitializers\\\",\\\"x-component-props\\\":{\\\"showDivider\\\":false},\\\"x-index\\\":1}');","sqlMessage":"Duplicate entry 'cdlu27chtk4' for key 'uiSchemas.PRIMARY'","sqlState":"23000"},"parent":{"code":"ER_DUP_ENTRY","errno":1062,"sql":"INSERT INTO uiSchemas (`x-uid`, `name`, `schema`) VALUES ('mygw89afc7g', 'tabBar', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"MTabBar\\\",\\\"x-component-props\\\":{}}'),('sbd2oc8bj8g', '7mqji2eya2t', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"MTabBar.Item\\\",\\\"x-designer\\\":\\\"MTabBar.Item.Designer\\\",\\\"x-component-props\\\":{\\\"icon\\\":\\\"HomeOutlined\\\",\\\"title\\\":\\\"{{t(\\'Untitled\\', { ns: \\'mobile-client\\', nsMode: \\'fallback\\' })}}\\\"}}'),('cdlu27chtk4', 'page', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-designer\\\":\\\"MPage.Designer\\\",\\\"x-component\\\":\\\"MPage\\\",\\\"x-component-props\\\":{},\\\"x-index\\\":1}'),('6emip1vppgr', 'grid', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"Grid\\\",\\\"x-initializer\\\":\\\"MBlockInitializers\\\",\\\"x-component-props\\\":{\\\"showDivider\\\":false},\\\"x-index\\\":1}');","sqlMessage":"Duplicate entry 'cdlu27chtk4' for key 'uiSchemas.PRIMARY'","sqlState":"23000"},"reqId":"29f0d09b-d283-412b-8870-83b688c611c5","sql":"INSERT INTO uiSchemas (`x-uid`, `name`, `schema`) VALUES ('mygw89afc7g', 'tabBar', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"MTabBar\\\",\\\"x-component-props\\\":{}}'),('sbd2oc8bj8g', '7mqji2eya2t', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"MTabBar.Item\\\",\\\"x-designer\\\":\\\"MTabBar.Item.Designer\\\",\\\"x-component-props\\\":{\\\"icon\\\":\\\"HomeOutlined\\\",\\\"title\\\":\\\"{{t(\\'Untitled\\', { ns: \\'mobile-client\\', nsMode: \\'fallback\\' })}}\\\"}}'),('cdlu27chtk4', 'page', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-designer\\\":\\\"MPage.Designer\\\",\\\"x-component\\\":\\\"MPage\\\",\\\"x-component-props\\\":{},\\\"x-index\\\":1}'),('6emip1vppgr', 'grid', '{\\\"_isJSONSchemaObject\\\":true,\\\"version\\\":\\\"2.0\\\",\\\"type\\\":\\\"void\\\",\\\"x-component\\\":\\\"Grid\\\",\\\"x-initializer\\\":\\\"MBlockInitializers\\\",\\\"x-component-props\\\":{\\\"showDivider\\\":false},\\\"x-index\\\":1}');","stack":"Error\n    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async _UiSchemaRepository.insertNewSchema (/app/nocobase/node_modules/@nocobase/plugin-ui-schema-storage/dist/server/repository.js:579:5)\n    at async _UiSchemaRepository.descriptor.value (/app/nocobase/node_modules/@nocobase/plugin-ui-schema-storage/dist/server/repository.js:52:16)\n    at async _UiSchemaRepository.insertAdjacent (/app/nocobase/node_modules/@nocobase/plugin-ui-schema-storage/dist/server/repository.js:531:32)\n    at async _UiSchemaRepository.descriptor.value (/app/nocobase/node_modules/@nocobase/plugin-ui-schema-storage/dist/server/repository.js:44:27)\n    at async insertAdjacent (/app/nocobase/node_modules/@nocobase/plugin-ui-schema-storage/dist/server/actions/ui-schema-action.js:57:16)\n    at async middleware (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/triggers/form.js:25:5)\n    at async /app/nocobase/node_modules/@nocobase/plugin-china-region/dist/server/index.js:30:9","timestamp":"2023-08-27T12:18:59.998Z"}`
客户端错误显示如下：
![移动端报错](https://github.com/nocobase/nocobase/assets/67178850/c02bc547-a94b-44f1-84b6-9191f297fc05)
