### ISSUE TITLE
0.13.0-alpha.4 dump和restore功能如何使用

### ISSUE THREAD

**Issue by tian16300** [nocobase/nocobase#2541]
## Describe the bug

0.13.0-alpha.4 dump和restore功能如何使用
## Version

0.13.0-alpha.4

1、yarn dev 或者 start 服务未启动前 yarn nocobase dump 或  yarn nocobase restore 报错误信息
![image](https://github.com/nocobase/nocobase/assets/4832494/234f544c-d44a-444e-b854-068a3020fed9)

2、yarn dev 或者start服务 启动后 显示这个界面后，选择失效，按enter建后 服务被重启了 dump 未生成
![image](https://github.com/nocobase/nocobase/assets/4832494/b68183e4-cb24-40cb-8857-d5eb9ab86738)
3、yarn nocobase restore xxx.nbdump 服务重启数据未恢复成功。
![image](https://github.com/nocobase/nocobase/assets/4832494/f2b070c7-731e-4cb9-8387-805a09af14b6)
![image](https://github.com/nocobase/nocobase/assets/4832494/15580397-7e71-49cc-875a-5209d24cba0a)

所以想问下 0.13.0-alpha.4  dump和restore功能应该如何使用？

**Comment by zhouyanliang** [comment]
该插件仍在开发中，请暂时不要使用
