### ISSUE TITLE
用户退出登录功能是否还未完成

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#256]
https://github.com/nocobase/nocobase/blob/81978711e4ee910de9643a15470deb237d17e00b/packages/plugin-users/src/actions/users.ts#L46

看了最新分支的退出登录代码，是否还未完成？

比如，应该删除user记录的token，防止token泄漏的情况。

**Comment by chenos** [comment]
感谢反馈，已更新 https://github.com/nocobase/nocobase/commit/54ad1535d6480873190326870326572085808bcb

**Comment by MarshalW** [comment]
收到，谢谢！
