### ISSUE TITLE
Upgrading from 0.9 to 0.13 break main menu

### ISSUE THREAD

**Issue by MathArtist2** [nocobase/nocobase#2588]
## Describe the bug

I have a Problem at Upgrading form 0.9 to 0.13
The main menu on top and pages are missing.
Everything else works fine. the tables are listed, etc etc.

## Version

from 0.9.0-alpha.2 
to      0.13.0-alpha.5

## How To Reproduce

1. you install and configure a 0.9 instance
2. You do an Upgrade
3. actualize applicationPlugins Table to include authentication an localization plugins
4. enable those plugins from Command Line : yarn nocobase pm enable ...
5. DO nocobase DB:sync. 

## Expected behavior

it must work as usual

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/12837010/404e9f37-7a40-4c10-bb59-8db4df82d9e0)

## Desktop (please complete the following information)

- OS: Linux Manjaro
- Browser Vivaldi, chrome, Firefox

**Comment by MathArtist2** [comment]
Well, I make Some progress, I executed the 
`yarn nocobase migrator up`
Command.

And get this result:
![image](https://github.com/nocobase/nocobase/assets/12837010/b001bc2d-1981-4d7c-b9e0-1607b59dd94a)
The site navigation is restored

But the columns names and content is missing in the blocks.
Also clicking edit, opens the Editing view but it gets an error as soon as it start to load

![image](https://github.com/nocobase/nocobase/assets/12837010/ca0394f5-8875-4771-806f-55d9db653890)
This is the error I get.

I Think i'm very close to get it solved

**Comment by MathArtist2** [comment]
I find the following:
The fields information like title and x-component-props used to be located in table uiSchema and linked to the field by the uiSchemaUid column

But it look like now the uiSchema is stored inside the options JSON column in the field row itself.
Also the uiSchema structure vary a little for some field types.

Should this be foreseen in the migrations script?

is there a default way to update this?
Or do I need to make my own migration for it?

**Comment by chenos** [comment]
See the upgrade documentation
https://docs.nocobase.com/welcome/getting-started/upgrading

**Comment by MathArtist2** [comment]
> See the upgrade documentation https://docs.nocobase.com/welcome/getting-started/upgrading

I did read it before posting here.

I find there is uiSchema differences since 0.9 not contemplated in the CLI migrations script.
I'm making my own script for complete migration on this cases

**Comment by hongboji** [comment]
Sorry for the inconvenience.
Nocobase 0.9 version upgrade the first time you try to upgrade, please use the backup environment to upgrade, after the success of the upgrade in the production environment, and then do a good job of database backup before upgrade; Nocobase 0.9 version upgrade to the latest version, please try to use the following steps:
1. Download the latest code to a new folder
git clone https://github.com/nocobase/nocobase.git newmy-nocobase-app
2、Install the dependencies
yarn install
3, copy the history configuration file .env to overwrite the new folder .env
4. yarn nocobase upgrade
5. yarn nocobase db:sync
6.yarn nocobase upgrade

The above steps have successfully solved multiple 0.9 to 0.14 upgrades.
