### ISSUE TITLE
点击Collection功能选项，界面出错了，无法创建collection

### ISSUE THREAD

**Issue by ytz520** [nocobase/nocobase#2608]
## Describe the bug

点击Collection功能选项，界面出错了，无法操作
![image](https://github.com/nocobase/nocobase/assets/4470324/3a7046d8-786e-4ed6-a9b0-535dfcf4c805)

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/4470324/229d13f7-bafa-4f89-9539-a2f999a824fc)

## Desktop (please complete the following information)

- OS:win10 [e.g. iOS]
- Browser  chrome[e.g. chrome v102, safari]

**Comment by hongboji** [comment]
请问nocobase版本号是多少，什么方式部署的，升级还是全新应用，什么数据库？

**Comment by Alex-vice** [comment]
我也遇到这个问题，使用yarn部署的，升级过的，mysql8数据库

**Comment by Alex-vice** [comment]
> 请问nocobase版本号是多少，什么方式部署的，升级还是全新应用，什么数据库？

我也遇到这个问题，使用yarn部署的，升级过的，mysql8数据库

**Comment by ytz520** [comment]
这是通过create nocobase app 方式安装，最新的全新安装，然后启动，就有这个问题了。


docker安装没这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月7日(周四) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nocobase/nocobase] 点击Collection功能选项，界面出错了，无法创建collection (Issue #2608)




  
请问nocobase版本号是多少，什么方式部署的，升级还是全新应用，什么数据库？
  
我也遇到这个问题，使用yarn部署的，升级过的，mysql8数据库

**Comment by ytz520** [comment]
sqllite3



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月7日(周四) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nocobase/nocobase] 点击Collection功能选项，界面出错了，无法创建collection (Issue #2608)




  
请问nocobase版本号是多少，什么方式部署的，升级还是全新应用，什么数据库？
  
我也遇到这个问题，使用yarn部署的，升级过的，mysql8数据库

**Comment by hongboji** [comment]
可以先使用yarn start启动

**Comment by ytz520** [comment]
yarn start可以规避此问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月7日(周四) 中午11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nocobase/nocobase] 点击Collection功能选项，界面出错了，无法创建collection (Issue #2608)




 
可以先使用yarn start启动

**Comment by chenos** [comment]
最新版 [v0.13.0-alpha.9](https://github.com/nocobase/nocobase/tree/v0.13.0-alpha.9) 已修复

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/2610
