### ISSUE TITLE
表格 关联字段排序返回错误

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2613]
## Describe the bug

![screenshots](https://github.com/nocobase/nocobase/assets/900786/3aadbf5f-78d3-4c39-b8cd-194f11da8f11)
## Version

version 0.13.0-alpha.9

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/4c1a4ffe-1479-4cec-ba65-ba89baded56a)

![image](https://github.com/nocobase/nocobase/assets/900786/f3a10ff4-7c2e-41b1-ac84-14599675ada1)

**Comment by hongboji** [comment]
已知 不支持的功能
