### ISSUE TITLE
create-nocobase-app 无法执行备份和恢复命令

### ISSUE THREAD

**Issue by MarshallEriksen-shaomingyang** [nocobase/nocobase#2617]
```
 "dependencies": {
    "@nocobase/cli": "^0.13.0-alpha.9",
    "pg": "^8.7.3",
    "pg-hstore": "^2.3.4"
  },
  "devDependencies": {
    "@nocobase/devtools": "^0.13.0-alpha.9",
    "@nocobase/plugin-duplicator": "^0.13.0-alpha.9"
  }
```

` yarn nocobase dump
yarn run v1.22.19
$ nocobase dump
WAIT: TypeScript compiling...
add app main into supervisor
error: unknown command 'dump'
(Did you mean umi?)
Done in 8.36s.`

**Comment by MarshalW** [comment]
需要先启动 nocobase:

```bash
yarn dev
```

再打开另外的终端执行 `yarn nocobase dump` 才能正常使用。

我录了屏，供参考：

![Kapture 2023-09-07 at 19 36 13](https://github.com/nocobase/nocobase/assets/931976/0fe9d30e-7030-41ff-ac08-0b1d548aaba1)

**Comment by MarshallEriksen-shaomingyang** [comment]
谢谢 我备份成功了
