### ISSUE TITLE
yarn start 启动的实例无法正常执行 dump 和 restore

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#2618]
## Describe the bug

`yarn start` 启动的实例无法执行 `dump` 和 `restore`，因为终端不是交互模式。

另外，如果是 `yarn dev` 则可以执行 `dump` 和 `restore`。

因此判断是前者输出方式不支持交互模式造成的。

## Version

nocobase `v0.13.0-alpha.9`

## How To Reproduce

步骤：

- 第一个终端执行 `yarn start`，启动 nocobase
- 第二个终端执行 `yarn nocobase dump`
- 在第一个终端出现选择 dump 内容界面，但无法键盘操作

## Expected behavior

希望执行`yarn start` 时可正常键盘交互。

## Screenshots

`yarn start` 有问题的情况录屏：

![Kapture 2023-09-07 at 19 50 11](https://github.com/nocobase/nocobase/assets/931976/0a0d10c6-1fc5-43df-944b-52817f699cb8)

作为对比，`yarn dev` 是没有问题的：

![Kapture 2023-09-07 at 19 36 13](https://github.com/nocobase/nocobase/assets/931976/0fe9d30e-7030-41ff-ac08-0b1d548aaba1)

**Comment by chareice** [comment]
@MarshalW fixed
