### ISSUE TITLE
While SignIn as Admin its showing as "column 'nickname' does not exist", How to solve this

### ISSUE THREAD

**Issue by amitsaini1807** [nocobase/nocobase#2628]
## Describe the bug

While SignIn as Admin its showing as "column 'nickname' does not exist", How to solve this becasue i tried many times it it giving same error everytime

**Comment by justwho** [comment]
![image_5](https://github.com/nocobase/nocobase/assets/22259834/15087e28-c7b8-4eed-a3bb-473f74c300c0)
hope this will help you.

**Comment by amitsaini1807** [comment]
this interface comes after signin, but i am not able to signin although

**Comment by hongboji** [comment]
What is the version number of nocobase, how did you install and deploy it, what kind of database is it, what account did you use to log in, and can you take a screenshot of the error report?
