### ISSUE TITLE
git tag 包含“” 导致在windows环境不能 git fetch代码

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2630]
## Describe the bug

![image](https://github.com/nocobase/nocobase/assets/900786/07a18c7c-ffd2-42a6-a045-1627ab8f2720)

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/9a7e0412-cc74-48de-912b-f9f187f18a72)

**Comment by hongboji** [comment]
已经删除了
