### ISSUE TITLE
User can not change password except Super Admin[Bug]

### ISSUE THREAD

**Issue by psbetter** [nocobase/nocobase#2634]
## Describe the bug
the old password is right, but it's still report error.
![修改密码bug](https://github.com/nocobase/nocobase/assets/67178850/79f2bb37-e1cb-4e33-aeb8-3a73e5c4635c)

## error log
`error: 密码有误，请重新输入 {"app":"main","headers":{"Access-Control-Allow-Origin":"http://localhost:13000","Access-Control-Expose-Headers":"content-disposition","vary":"Origin"},"reqId":"8b60f067-dfbe-4fec-834d-7b3b4c95eecc","stack":"UnauthorizedError: 密码有误，请重新输入\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at changePassword (/app/nocobase/node_modules/@nocobase/plugin-users/dist/server/actions/users.js:169:14)\n    at async /app/nocobase/node_modules/@nocobase/plugin-multi-app-manager/dist/server/server.js:269:7\n    at async middleware (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/triggers/form.js:44:5)\n    at async /app/nocobase/node_modules/@nocobase/plugin-china-region/dist/server/index.js:48:9\n    at async /app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/server.js:274:7\n    at async /app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/server.js:248:7\n    at async /app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:441:7\n    at async dateTemplate (/app/nocobase/node_modules/@nocobase/server/lib/middlewares/data-template.js:27:3)\n    at async app.acl.use.after (/app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:541:9)","timestamp":"2023-09-12T06:32:42.081Z"}`

**Comment by hongboji** [comment]
Not sure about the accuracy of your password, but you can use a method of verification, you can create a new user set the password to 123456, in the database users table to compare the two users password field value is the same

**Comment by psbetter** [comment]
> Not sure about the accuracy of your password, but you can use a method of verification, you can create a new user set the password to 123456, in the database users table to compare the two users password field value is the same

The login function is normal with the correct or incorrect password. The following figure shows the queried user password. All user passwords are set to 123456, but the passwords in the database are different. Is this the reason?
![屏幕截图 2023-09-14 084420](https://github.com/nocobase/nocobase/assets/67178850/32aa79c0-41bb-4c93-9cee-c76bdf001019)

**Comment by hongboji** [comment]
Sorry, this doesn't solve your problem, it's bug
