### ISSUE TITLE
Problem updating version.

### ISSUE THREAD

**Issue by betgamesnetwork** [nocobase/nocobase#2636]
Hello, I tried to update to the latest version and I am unable to use the application. Below is the attached image, the docker-compose.yml file and the application logs.

version: "3"
networks:
   nocobase:
     driver: bridge
services:
   app:
     image: nocobase/nocobase:main
     networks:
       - nocobase
     depends_on:
       - mysql
     environment:
       - DB_DIALECT=mysql
       - DB_HOST=mysql
       - DB_DATABASE=nocobase
       - DB_USER=nocobase
       - DB_PASSWORD=password
       - LOCAL_STORAGE_BASE_URL=172.16.253.229/storage/uploads
     volumes:
       - ./storage:/app/nocobase/storage
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
     ports:
       - "80:80"
   mysql:
     image: mysql:8
     environment:
       MYSQL_DATABASE: nocobase
       MYSQL_USER: nocobase
       MYSQL_PASSWORD: password
       MYSQL_ROOT_PASSWORD: password
     restart:always
     networks:
       - nocobase

app_1    | error: No permissions {"app":"main","reqId":"0184155a-9d70-4a00-a8b8-dd43b22e00e5","stack":"ForbiddenError: No permissions\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at middlewares.add.tag (/app/nocobase/node_modules/@nocobase/acl/lib/acl.js:279:20)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at app.acl.use.before (/app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:522:15)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:464:14\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/acl/lib/allow-manager.js:99:13\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2023-09-12T15:07:08.508Z"}
app_1    | warn: END: GET /api/auth:check {"app":"main","errors":[{"message":"No permissions"}],"req":{"action":{"actionName":"check","params":{"actionName":"check","resourceName":"auth"},"resourceName":"auth"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"0184155a-9d70-4a00-a8b8-dd43b22e00e5","res":{"status":403},"responseTime":4,"timestamp":"2023-09-12T15:07:08.509Z"}
app_1    | info: BEGIN: GET /api/uiSchemaTemplates:list?appends%5B%5D=collection&paginate=false {"app":"main","reqId":"60f8dd80-4170-4c85-ae66-80ea6fb67fa7","timestamp":"2023-09-12T15:07:08.747Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:08.750Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"60f8dd80-4170-4c85-ae66-80ea6fb67fa7","timestamp":"2023-09-12T15:07:08.750Z"}
app_1    | error: No permissions {"app":"main","reqId":"60f8dd80-4170-4c85-ae66-80ea6fb67fa7","stack":"ForbiddenError: No permissions\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at middlewares.add.tag (/app/nocobase/node_modules/@nocobase/acl/lib/acl.js:279:20)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at app.acl.use.before (/app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:522:15)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:448:18\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/acl/lib/allow-manager.js:99:13\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2023-09-12T15:07:08.750Z"}
app_1    | warn: END: GET /api/uiSchemaTemplates:list?appends%5B%5D=collection&paginate=false {"app":"main","errors":[{"message":"No permissions"}],"req":{"action":{"actionName":"list","params":{"actionName":"list","appends":["collection"],"paginate":"false","resourceName":"uiSchemaTemplates"},"resourceName":"uiSchemaTemplates"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"60f8dd80-4170-4c85-ae66-80ea6fb67fa7","res":{"status":403},"responseTime":5,"timestamp":"2023-09-12T15:07:08.751Z"}
app_1    | info: BEGIN: GET /api/systemSettings:get/1?appends=logo {"app":"main","reqId":"5b253f91-a7f1-4437-9351-761d9bd49d69","timestamp":"2023-09-12T15:07:08.796Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:08.799Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"5b253f91-a7f1-4437-9351-761d9bd49d69","skip":true,"timestamp":"2023-09-12T15:07:08.799Z"}
app_1    | info: acl params {"app":"main","reqId":"5b253f91-a7f1-4437-9351-761d9bd49d69","timestamp":"2023-09-12T15:07:08.800Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"5b253f91-a7f1-4437-9351-761d9bd49d69","timestamp":"2023-09-12T15:07:08.800Z"}
app_1    | info: END: GET /api/systemSettings:get/1?appends=logo {"app":"main","req":{"action":{"actionName":"get","params":{"actionName":"get","appends":["logo"],"filterByTk":"1","resourceIndex":"1","resourceName":"systemSettings"},"resourceName":"systemSettings"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"5b253f91-a7f1-4437-9351-761d9bd49d69","res":{"status":200},"responseTime":22,"timestamp":"2023-09-12T15:07:08.818Z"}
app_1    | info: BEGIN: GET /api/app:getInfo {"app":"main","reqId":"d3074180-32aa-4b0a-981d-b1430d80daf2","timestamp":"2023-09-12T15:07:09.022Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:09.024Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"d3074180-32aa-4b0a-981d-b1430d80daf2","skip":true,"timestamp":"2023-09-12T15:07:09.024Z"}
app_1    | info: acl params {"app":"main","reqId":"d3074180-32aa-4b0a-981d-b1430d80daf2","timestamp":"2023-09-12T15:07:09.024Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"d3074180-32aa-4b0a-981d-b1430d80daf2","timestamp":"2023-09-12T15:07:09.024Z"}
app_1    | info: END: GET /api/app:getInfo {"app":"main","req":{"action":{"actionName":"getInfo","params":{"actionName":"getInfo","resourceName":"app"},"resourceName":"app"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"d3074180-32aa-4b0a-981d-b1430d80daf2","res":{"status":200},"responseTime":8,"timestamp":"2023-09-12T15:07:09.030Z"}
app_1    | info: BEGIN: GET /api/app:getInfo {"app":"main","reqId":"3d477c33-d050-4e23-beb7-5e18d7cce54e","timestamp":"2023-09-12T15:07:09.296Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:09.298Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"3d477c33-d050-4e23-beb7-5e18d7cce54e","skip":true,"timestamp":"2023-09-12T15:07:09.298Z"}
app_1    | info: acl params {"app":"main","reqId":"3d477c33-d050-4e23-beb7-5e18d7cce54e","timestamp":"2023-09-12T15:07:09.299Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"3d477c33-d050-4e23-beb7-5e18d7cce54e","timestamp":"2023-09-12T15:07:09.299Z"}
app_1    | info: END: GET /api/app:getInfo {"app":"main","req":{"action":{"actionName":"getInfo","params":{"actionName":"getInfo","resourceName":"app"},"resourceName":"app"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"3d477c33-d050-4e23-beb7-5e18d7cce54e","res":{"status":200},"responseTime":7,"timestamp":"2023-09-12T15:07:09.303Z"}
app_1    | info: BEGIN: POST /api/authenticators:publicList {"app":"main","reqId":"487a5efe-645e-4f62-ae4f-badc5a08f9fb","timestamp":"2023-09-12T15:07:09.368Z"}
app_1    | warn: END: POST /api/authenticators:publicList {"app":"main","req":{"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"487a5efe-645e-4f62-ae4f-badc5a08f9fb","res":{"status":404},"responseTime":12,"timestamp":"2023-09-12T15:07:09.380Z"}
app_1    | client disconnected 5kaQPWdpgtpbC8AgmWyJi
app_1    | info: BEGIN: GET /api/app:getLang?locale=pt-BR {"app":"main","reqId":"88ec1343-6b5b-41a4-880e-ff6dd5c4b069","timestamp":"2023-09-12T15:07:17.758Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:17.763Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"88ec1343-6b5b-41a4-880e-ff6dd5c4b069","skip":true,"timestamp":"2023-09-12T15:07:17.763Z"}
app_1    | info: acl params {"app":"main","reqId":"88ec1343-6b5b-41a4-880e-ff6dd5c4b069","timestamp":"2023-09-12T15:07:17.764Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"88ec1343-6b5b-41a4-880e-ff6dd5c4b069","timestamp":"2023-09-12T15:07:17.764Z"}
app_1    | info: END: GET /api/app:getLang?locale=pt-BR {"app":"main","req":{"action":{"actionName":"getLang","params":{"actionName":"getLang","locale":"pt-BR","resourceName":"app"},"resourceName":"app"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"88ec1343-6b5b-41a4-880e-ff6dd5c4b069","res":{"status":200},"responseTime":10,"timestamp":"2023-09-12T15:07:17.768Z"}
app_1    | new client connected f1zopD77AtHF9olwcrDcB
app_1    | client tags: app#main
app_1    | info: BEGIN: GET /api/app:getPlugins {"app":"main","reqId":"21b64868-7820-4c2b-be70-83eda68ac796","timestamp":"2023-09-12T15:07:17.818Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:17.820Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"21b64868-7820-4c2b-be70-83eda68ac796","skip":true,"timestamp":"2023-09-12T15:07:17.820Z"}
app_1    | info: acl params {"app":"main","reqId":"21b64868-7820-4c2b-be70-83eda68ac796","timestamp":"2023-09-12T15:07:17.821Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"21b64868-7820-4c2b-be70-83eda68ac796","timestamp":"2023-09-12T15:07:17.821Z"}
app_1    | info: END: GET /api/app:getPlugins {"app":"main","req":{"action":{"actionName":"getPlugins","params":{"actionName":"getPlugins","resourceName":"app"},"resourceName":"app"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"21b64868-7820-4c2b-be70-83eda68ac796","res":{"status":200},"responseTime":12,"timestamp":"2023-09-12T15:07:17.829Z"}
app_1    | info: BEGIN: GET /api/auth:check {"app":"main","reqId":"9625727e-3a3d-41c4-a31f-200920d84689","timestamp":"2023-09-12T15:07:18.060Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:18.062Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"9625727e-3a3d-41c4-a31f-200920d84689","timestamp":"2023-09-12T15:07:18.063Z"}
app_1    | error: No permissions {"app":"main","reqId":"9625727e-3a3d-41c4-a31f-200920d84689","stack":"ForbiddenError: No permissions\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at middlewares.add.tag (/app/nocobase/node_modules/@nocobase/acl/lib/acl.js:279:20)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at app.acl.use.before (/app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:522:15)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:464:14\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/acl/lib/allow-manager.js:99:13\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/server.js:225:7","timestamp":"2023-09-12T15:07:18.063Z"}
app_1    | warn: END: GET /api/auth:check {"app":"main","errors":[{"message":"No permissions"}],"req":{"action":{"actionName":"check","params":{"actionName":"check","resourceName":"auth"},"resourceName":"auth"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"9625727e-3a3d-41c4-a31f-200920d84689","res":{"status":403},"responseTime":4,"timestamp":"2023-09-12T15:07:18.064Z"}
app_1    | info: BEGIN: GET /api/uiSchemaTemplates:list?appends%5B%5D=collection&paginate=false {"app":"main","reqId":"5122d218-6a80-4272-839f-b41f852bcd50","timestamp":"2023-09-12T15:07:18.125Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:18.128Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"5122d218-6a80-4272-839f-b41f852bcd50","timestamp":"2023-09-12T15:07:18.128Z"}
app_1    | error: No permissions {"app":"main","reqId":"5122d218-6a80-4272-839f-b41f852bcd50","stack":"ForbiddenError: No permissions\n    at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n    at middlewares.add.tag (/app/nocobase/node_modules/@nocobase/acl/lib/acl.js:279:20)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at app.acl.use.before (/app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:522:15)\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/plugin-acl/dist/server/server.js:448:18\n    at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)\n    at /app/nocobase/node_modules/@nocobase/acl/lib/allow-manager.js:99:13\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/server.js:225:7","timestamp":"2023-09-12T15:07:18.129Z"}
app_1    | warn: END: GET /api/uiSchemaTemplates:list?appends%5B%5D=collection&paginate=false {"app":"main","errors":[{"message":"No permissions"}],"req":{"action":{"actionName":"list","params":{"actionName":"list","appends":["collection"],"paginate":"false","resourceName":"uiSchemaTemplates"},"resourceName":"uiSchemaTemplates"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"5122d218-6a80-4272-839f-b41f852bcd50","res":{"status":403},"responseTime":7,"timestamp":"2023-09-12T15:07:18.132Z"}
app_1    | info: BEGIN: GET /api/systemSettings:get/1?appends=logo {"app":"main","reqId":"e7ea23c7-ec1c-4db5-abef-cec04d9bf0a4","timestamp":"2023-09-12T15:07:18.215Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:18.217Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"e7ea23c7-ec1c-4db5-abef-cec04d9bf0a4","skip":true,"timestamp":"2023-09-12T15:07:18.217Z"}
app_1    | info: acl params {"app":"main","reqId":"e7ea23c7-ec1c-4db5-abef-cec04d9bf0a4","timestamp":"2023-09-12T15:07:18.218Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"e7ea23c7-ec1c-4db5-abef-cec04d9bf0a4","timestamp":"2023-09-12T15:07:18.218Z"}
app_1    | info: END: GET /api/systemSettings:get/1?appends=logo {"app":"main","req":{"action":{"actionName":"get","params":{"actionName":"get","appends":["logo"],"filterByTk":"1","resourceIndex":"1","resourceName":"systemSettings"},"resourceName":"systemSettings"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"e7ea23c7-ec1c-4db5-abef-cec04d9bf0a4","res":{"status":200},"responseTime":9,"timestamp":"2023-09-12T15:07:18.224Z"}
app_1    | info: BEGIN: GET /api/app:getInfo {"app":"main","reqId":"2ff2f2dd-ca20-4bd2-b6c7-0bed8348d95e","timestamp":"2023-09-12T15:07:18.285Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:18.290Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"2ff2f2dd-ca20-4bd2-b6c7-0bed8348d95e","skip":true,"timestamp":"2023-09-12T15:07:18.290Z"}
app_1    | info: acl params {"app":"main","reqId":"2ff2f2dd-ca20-4bd2-b6c7-0bed8348d95e","timestamp":"2023-09-12T15:07:18.291Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"2ff2f2dd-ca20-4bd2-b6c7-0bed8348d95e","timestamp":"2023-09-12T15:07:18.291Z"}
app_1    | info: END: GET /api/app:getInfo {"app":"main","req":{"action":{"actionName":"getInfo","params":{"actionName":"getInfo","resourceName":"app"},"resourceName":"app"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"2ff2f2dd-ca20-4bd2-b6c7-0bed8348d95e","res":{"status":200},"responseTime":13,"timestamp":"2023-09-12T15:07:18.298Z"}
app_1    | info: BEGIN: GET /api/app:getInfo {"app":"main","reqId":"9320c1fe-516a-4a19-b151-12b2617fa871","timestamp":"2023-09-12T15:07:18.362Z"}
app_1    | warn: auth, AuthManager.storer is not set. {"app":"main","timestamp":"2023-09-12T15:07:18.364Z"}
app_1    | info: ctx permission {"app":"main","can":null,"reqId":"9320c1fe-516a-4a19-b151-12b2617fa871","skip":true,"timestamp":"2023-09-12T15:07:18.365Z"}
app_1    | info: acl params {"app":"main","reqId":"9320c1fe-516a-4a19-b151-12b2617fa871","timestamp":"2023-09-12T15:07:18.365Z"}
app_1    | info: acl parsedParams {"app":"main","reqId":"9320c1fe-516a-4a19-b151-12b2617fa871","timestamp":"2023-09-12T15:07:18.365Z"}
app_1    | info: END: GET /api/app:getInfo {"app":"main","req":{"action":{"actionName":"getInfo","params":{"actionName":"getInfo","resourceName":"app"},"resourceName":"app"},"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"9320c1fe-516a-4a19-b151-12b2617fa871","res":{"status":200},"responseTime":8,"timestamp":"2023-09-12T15:07:18.370Z"}
app_1    | info: BEGIN: POST /api/authenticators:publicList {"app":"main","reqId":"010c5b51-1bd1-451c-8faf-11ddf6529708","timestamp":"2023-09-12T15:07:18.426Z"}
app_1    | warn: END: POST /api/authenticators:publicList {"app":"main","req":{"header":{"x-hostname":"notifica.ghc.com.br","x-locale":"pt-BR","x-timezone":"--3:00"}},"reqId":"010c5b51-1bd1-451c-8faf-11ddf6529708","res":{"status":404},"responseTime":4,"timestamp":"2023-09-12T15:07:18.429Z"}

![nocobase erro](https://github.com/nocobase/nocobase/assets/71851022/14963e1c-4c11-4ef7-99a4-39be4a1d0c1d)
![nocobase2](https://github.com/nocobase/nocobase/assets/71851022/8fe0b6e9-4e4c-4968-b758-2da6b0735a42)

**Comment by hongboji** [comment]
Try it, stop the docker container, start it again, reopen the browser and go to the
