### ISSUE TITLE
Error: add block Workflow todos

### ISSUE THREAD

**Issue by S3Coloris** [nocobase/nocobase#2641]
## Describe the bug

On page after Add block of Workflow todos get error

## Version

Version 0.14.0-alpha.1

## Screenshots

![Screenshot_123](https://github.com/nocobase/nocobase/assets/114476533/babccce8-f5af-4152-8347-f57a8a454545)
![Screenshot_122](https://github.com/nocobase/nocobase/assets/114476533/b9fb03bc-0ae9-4a70-8c6b-e924cd54d7a5)

**Comment by hongboji** [comment]
How did you install and deploy it and what kind of database is it?

**Comment by S3Coloris** [comment]
Oops, sorry.
I'm install app from Git source code, DB is default - sqlite
First, create collection and 2 workflows (on screenshot) then add block "Workflow todos" and get this error

![Screenshot_127](https://github.com/nocobase/nocobase/assets/114476533/00a497f8-2bd7-4d71-bffd-f9754f209975)

**Comment by hongboji** [comment]
It's fixed. Please use the latest code.

**Comment by S3Coloris** [comment]
ok, thanks
