### ISSUE TITLE
Login form is not displayed

### ISSUE THREAD

**Issue by S3Coloris** [nocobase/nocobase#2642]
## Describe the bug

I'm use NocoBase like Git source code.
After upgrading (as described in the documentation) from Version 0.14.0-alpha.1 to 0.14.0-alpha.2, login form is not displayed

## Version

Version 0.14.0-alpha.2

## Screenshots

![Screenshot_125](https://github.com/nocobase/nocobase/assets/114476533/884d8241-fba6-41dc-80ed-b47cc742fc06)

## Additional context

LOG:

info: BEGIN: GET /api/app:getLang?locale=en-US {"app":"main","reqId":"6aa6abfd-2299-41e1-b74b-94504bb655f1","timestamp":"2023-09-13T07:40:44.183Z"}
info: ctx permission {"app":"main","can":null,"reqId":"6aa6abfd-2299-41e1-b74b-94504bb655f1","skip":true,"timestamp":"2023-09-13T07:40:44.204Z"}
info: acl params {"app":"main","reqId":"6aa6abfd-2299-41e1-b74b-94504bb655f1","timestamp":"2023-09-13T07:40:44.239Z"}
info: acl parsedParams {"app":"main","reqId":"6aa6abfd-2299-41e1-b74b-94504bb655f1","timestamp":"2023-09-13T07:40:44.241Z"}
info: END: GET /api/app:getLang?locale=en-US {"app":"main","req":{"action":{"actionName":"getLang","params":{"actionName":"getLang","locale":"en-US","resourceName":"app"},"resourceName":"app"},"header":{"x-hostname":"localhost","x-locale":"en-US","x-timezone":"+03:00"}},"reqId":"6aa6abfd-2299-41e1-b74b-94504bb655f1","res":{"status":200},"responseTime":117,"timestamp":"2023-09-13T07:40:44.300Z"}
info: BEGIN: GET /api/pm:listEnabled {"app":"main","reqId":"206f6a8b-8431-4638-a9c7-63b6735359eb","timestamp":"2023-09-13T07:40:44.413Z"}
info: ctx permission {"app":"main","can":null,"reqId":"206f6a8b-8431-4638-a9c7-63b6735359eb","skip":true,"timestamp":"2023-09-13T07:40:44.433Z"}
info: acl params {"app":"main","reqId":"206f6a8b-8431-4638-a9c7-63b6735359eb","timestamp":"2023-09-13T07:40:44.435Z"}
info: acl parsedParams {"app":"main","reqId":"206f6a8b-8431-4638-a9c7-63b6735359eb","timestamp":"2023-09-13T07:40:44.437Z"}
info: END: GET /api/pm:listEnabled {"app":"main","req":{"action":{"actionName":"listEnabled","params":{"actionName":"listEnabled","resourceName":"pm"},"resourceName":"pm"},"header":{"x-hostname":"localhost","x-locale":"en-US","x-timezone":"+03:00"}},"reqId":"206f6a8b-8431-4638-a9c7-63b6735359eb","res":{"status":200},"responseTime":51,"timestamp":"2023-09-13T07:40:44.463Z"}
info: BEGIN: GET /api/auth:check {"app":"main","reqId":"fe8d43dd-2189-4c67-a08d-2f886ebb2e8c","timestamp":"2023-09-13T07:40:44.582Z"}
info: ctx permission {"app":"main","can":null,"reqId":"fe8d43dd-2189-4c67-a08d-2f886ebb2e8c","skip":true,"timestamp":"2023-09-13T07:40:44.609Z"}
info: acl params {"app":"main","reqId":"fe8d43dd-2189-4c67-a08d-2f886ebb2e8c","timestamp":"2023-09-13T07:40:44.611Z"}
info: acl parsedParams {"app":"main","reqId":"fe8d43dd-2189-4c67-a08d-2f886ebb2e8c","timestamp":"2023-09-13T07:40:44.614Z"}
info: END: GET /api/auth:check {"app":"main","req":{"action":{"actionName":"check","params":{"actionName":"check","resourceName":"auth"},"resourceName":"auth"},"header":{"x-hostname":"localhost","x-locale":"en-US","x-timezone":"+03:00"}},"reqId":"fe8d43dd-2189-4c67-a08d-2f886ebb2e8c","res":{"status":200},"responseTime":35,"timestamp":"2023-09-13T07:40:44.617Z"}
info: BEGIN: GET /api/uiSchemaTemplates:list?appends%5B%5D=collection&paginate=false {"app":"main","reqId":"59cfd8cf-23fc-49af-8770-32468076b9a0","timestamp":"2023-09-13T07:40:44.688Z"}
new client connected 8-7G2iDgLt5GWNCYSuYTL
client tags: app#main
info: ctx permission {"app":"main","can":null,"reqId":"59cfd8cf-23fc-49af-8770-32468076b9a0","timestamp":"2023-09-13T07:40:44.723Z"}
error: No permissions {"app":"main","reqId":"59cfd8cf-23fc-49af-8770-32468076b9a0","stack":"ForbiddenError: No permissions\n    at Object.throw (c:\\Users\\admin\\my-nocobase-app\\node_modules\\koa\\lib\\context.js:97:11)\n    at middlewares.add.tag (c:\\Users\\admin\\my-nocobase-app\\packages\\core\\acl\\src\\acl.ts:348:15)\n    at dispatch (c:\\Users\\admin\\my-nocobase-app\\node_modules\\koa-compose\\index.js:42:32)\n    at app.acl.use.before (c:\\Users\\admin\\my-nocobase-app\\packages\\plugins\\@nocobase\\plugin-acl\\src\\server\\server.ts:593:15)\n    at dispatch (c:\\Users\\admin\\my-nocobase-app\\node_modules\\koa-compose\\index.js:42:32)\n    at <anonymous> (c:\\Users\\admin\\my-nocobase-app\\packages\\plugins\\@nocobase\\plugin-acl\\src\\server\\server.ts:503:18)\n    at dispatch (c:\\Users\\admin\\my-nocobase-app\\node_modules\\koa-compose\\index.js:42:32)\n    at <anonymous> (c:\\Users\\admin\\my-nocobase-app\\packages\\core\\acl\\src\\allow-manager.ts:99:13)\n    at <anonymous> (c:\\Users\\admin\\my-nocobase-app\\packages\\plugins\\@nocobase\\plugin-collection-manager\\src\\server\\server.ts:248:7)\n    at <anonymous> (c:\\Users\\admin\\my-nocobase-app\\packages\\core\\auth\\src\\auth-manager.ts:114:7)","timestamp":"2023-09-13T07:40:44.731Z"}
warn: END: GET /api/uiSchemaTemplates:list?appends%5B%5D=collection&paginate=false {"app":"main","errors":[{"message":"No permissions"}],"req":{"action":{"actionName":"list","params":{"actionName":"list","appends":["collection"],"paginate":"false","resourceName":"uiSchemaTemplates"},"resourceName":"uiSchemaTemplates"},"header":{"x-hostname":"localhost","x-locale":"en-US","x-timezone":"+03:00"}},"reqId":"59cfd8cf-23fc-49af-8770-32468076b9a0","res":{"status":403},"responseTime":44,"timestamp":"2023-09-13T07:40:44.732Z"}
info: BEGIN: GET /api/systemSettings:get/1?appends=logo {"app":"main","reqId":"e0a9fe50-9e47-4886-a716-5ca797836948","timestamp":"2023-09-13T07:40:44.810Z"}
info: ctx permission {"app":"main","can":null,"reqId":"e0a9fe50-9e47-4886-a716-5ca797836948","skip":true,"timestamp":"2023-09-13T07:40:44.830Z"}
info: acl params {"app":"main","reqId":"e0a9fe50-9e47-4886-a716-5ca797836948","timestamp":"2023-09-13T07:40:44.831Z"}
info: acl parsedParams {"app":"main","reqId":"e0a9fe50-9e47-4886-a716-5ca797836948","timestamp":"2023-09-13T07:40:44.831Z"}
info: END: GET /api/systemSettings:get/1?appends=logo {"app":"main","req":{"action":{"actionName":"get","params":{"actionName":"get","appends":["logo"],"filterByTk":"1","resourceIndex":"1","resourceName":"systemSettings"},"resourceName":"systemSettings"},"header":{"x-hostname":"localhost","x-locale":"en-US","x-timezone":"+03:00"}},"reqId":"e0a9fe50-9e47-4886-a716-5ca797836948","res":{"status":200},"responseTime":76,"timestamp":"2023-09-13T07:40:44.886Z"}
info: BEGIN: POST /api/authenticators:publicList {"app":"main","reqId":"4a6dab65-1610-49e9-8188-dd87859ed395","timestamp":"2023-09-13T07:40:44.947Z"}
info: ctx permission {"app":"main","can":null,"reqId":"4a6dab65-1610-49e9-8188-dd87859ed395","skip":true,"timestamp":"2023-09-13T07:40:44.963Z"}
info: acl params {"app":"main","reqId":"4a6dab65-1610-49e9-8188-dd87859ed395","timestamp":"2023-09-13T07:40:44.964Z"}
info: acl parsedParams {"app":"main","reqId":"4a6dab65-1610-49e9-8188-dd87859ed395","timestamp":"2023-09-13T07:40:44.965Z"}
info: END: POST /api/authenticators:publicList {"app":"main","req":{"action":{"actionName":"publicList","params":{"actionName":"publicList","resourceName":"authenticators"},"resourceName":"authenticators"},"header":{"x-hostname":"localhost","x-locale":"en-US","x-timezone":"+03:00"}},"reqId":"4a6dab65-1610-49e9-8188-dd87859ed395","res":{"status":200},"responseTime":31,"timestamp":"2023-09-13T07:40:44.979Z"}

**Comment by hongboji** [comment]
Try it, stop the system, reboot it, reopen the browser to the system

**Comment by S3Coloris** [comment]
I'm tried, reboot PC and use another browser, but it didn't help...
Still, when I managed to log in, I saw that some plugins were not work - Workwlow, File manager, Verification, API doc (but it's enabled) ...
![Screenshot_128](https://github.com/nocobase/nocobase/assets/114476533/4888acf9-cf2c-4ec9-a3a3-ade4a8ca2515)
![Screenshot_129](https://github.com/nocobase/nocobase/assets/114476533/587bad2b-a77e-43c6-a28e-de2a9a0a193a)

**Comment by hongboji** [comment]
Can you please describe your upgrade process in detail, you can post the process of executing the command

**Comment by S3Coloris** [comment]
I'm used documentation to upgrade
1. cd my-nocobase-app
2. git pull (the command was completed without error)
3. yarn nocobase clean (the command was completed without error)
4. yarn rimraf -rf node_modules (the command was completed without error)
5. yarn install (the command was completed without error)
6. yarn nocobase upgrade (the command was completed without error)
7. yarn dev - app start, but login form is not displayed and error in terminal
