### ISSUE TITLE
Logon page - No Permission message

### ISSUE THREAD

**Issue by rouhu** [nocobase/nocobase#2647]
v0.14.0
Whenever the logon page http://mysite.com:13000 is called it is redirected to
http://mysite.com:13000/signin?redirect=/admin

Then it pops up an error "No Permission" but login actually works. Any advice how to remove the error ?

Log shows:
app_1 | error: No permissions {"reqId":"29da0ed0-ca8c-42c4-a64c-d8615363f28b","stack":"ForbiddenError: No permissions\n at Object.throw (/app/nocobase/node_modules/koa/lib/context.js:97:11)\n at /app/nocobase/node_modules/@nocobase/acl/lib/acl.js:358:20\n at Generator.next ()\n at asyncGeneratorStep (/app/nocobase/node_modules/@nocobase/acl/lib/acl.js:42:103)\n at _next (/app/nocobase/node_modules/@nocobase/acl/lib/acl.js:43:194)\n at /app/nocobase/node_modules/@nocobase/acl/lib/acl.js:43:364\n at new Promise ()\n at /app/nocobase/node_modules/@nocobase/acl/lib/acl.js:43:97\n at /app/nocobase/node_modules/@nocobase/acl/lib/acl.js:386:22\n at dispatch (/app/nocobase/node_modules/koa-compose/index.js:42:32)","timestamp":"2023-07-19T08:22:02.280Z"}

**Comment by mishoboss** [comment]
Same here.

**Comment by baiheinet** [comment]
this has been corrected
https://github.com/nocobase/nocobase/pull/2824
![image](https://github.com/nocobase/nocobase/assets/900786/a0f62c12-7b69-412f-ab6f-255a21379a89)
