### ISSUE TITLE
Old charts are not created.

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2657]
<img width="404" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/8dbb6aee-6a5f-4757-ac95-ab1881ce537d">

Old charts are not created.

I understand that there are new ones, but there is a big problem for me - you can't make a filter, for example, for the last X days. They use absolute values. SQL is easier in this sense.

**Comment by zhouyanliang** [comment]
Dynamic variables and SQL will be available soon.

**Comment by alexkash** [comment]
Thanks!
