### ISSUE TITLE
UI problem with displaying Details.

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2658]
There is a small but annoying UI problem: it's hard to read Details and non-editable fields, especially when there are a lot of fields. The label is bold and draws more attention than the data. This is not the right way to do it.

<img width="225" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/ab1c6d8f-33f8-4302-98e1-9f8ae80b1e2f">

I've seen how to do it in Ant Design and it's a bit different and reads better. 

<img width="147" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/c69c33d7-dfa0-4361-a1f3-e6e316a20fcf">

I would certainly prefer the other option, but I realize that it would be impractical to invest time in this development now. 

<img width="1126" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/0ef12e75-31c0-4873-9369-d4014fc81ffa">

But can you at least put the color setting of labels in the theme, font setting or just make them gray?

**Comment by zhouyanliang** [comment]
Thanks for the advice.
The current UI was carefully thought out and tried. It's a balance between readability and the possibilities of no-code configuration.
1. Field labels can be very long and it is more compatible to put them on a separate line.
2. Markdown or rich text field will bring various styles, bold label is more compatible.
