### ISSUE TITLE
yarn install process killed

### ISSUE THREAD

**Issue by alexsidnenko** [nocobase/nocobase#2661]
## Describe the bug

root@server_test1:~/my-nocobase-app# yarn install
......
warning "workspace-aggregator-669366cc-c222-4438-b853-74f6b48f24a1 > @nocobase/plugin-audit-logs > @formily/antd-v5@1.1.0" has unmet peer dependency "react-is@>=16.8.0 || >=17.0.0".
warning Workspaces can only be enabled in private projects.
[#--------------------------------------------------------------------] 69/4190Killed

## Version

v0.14.0-alpha.3

## How To Reproduce

1. git clone https://github.com/nocobase/nocobase.git my-nocobase-app
2. cd my-nocobase-app
3. yarn install

## Desktop (please complete the following information)

- OS: Ubuntu 22.10 x64
- Node.js v18.7.0
- yarn v1.22.19

## Additional context

If you perform the steps again, another error may occur

1. delete old my-nocobase-app
2. git clone https://github.com/nocobase/nocobase.git my-nocobase-app
3. cd my-nocobase-app
4. yarn install
<img width="568" alt="Screenshot 2023-09-15 at 14 32 45" src="https://github.com/nocobase/nocobase/assets/63589831/a14811aa-dabc-4954-ad4f-6a6a51840814">

6. yarn nocobase install
7. yarn dev
<img width="566" alt="Screenshot 2023-09-15 at 14 48 06" src="https://github.com/nocobase/nocobase/assets/63589831/2a7d25ad-75e7-4862-afbe-7859a51ff207">

**Comment by ChirayuXD** [comment]
how did u fix it?

**Comment by alexsidnenko** [comment]
The problem was the 2GB of RAM.
After switching to a new server with 8GB of RAM, everything started working. (8GB is the recommended amount of RAM from the Node.js or React documentation, I don't remember exactly)
