### ISSUE TITLE
编辑表单时，表单无变动直接保存表单提示“string violation”，添加没有这个问题

### ISSUE THREAD

**Issue by wafu7969** [nocobase/nocobase#2667]
**版本：** v0.13和v0.14两个版本测试都存在这个问题。
**表设计情况：**
目前有三张表：房屋（A表）、报价单（B表）、报价项目（C表）
报价项目表：保存报价的项目模版
房屋表：保存的是需要报价的房屋信息
报价单表：对应的是房屋的报价单
具体表结构如下：
房屋（A表）
![image](https://github.com/nocobase/nocobase/assets/26269988/b2a2627f-df63-4989-b361-8c8ff812a36e)
报价单（B表）
![image](https://github.com/nocobase/nocobase/assets/26269988/21366e9c-3c22-41a4-9aca-c2d0894201c5)
报价项目（C表）
![image](https://github.com/nocobase/nocobase/assets/26269988/aae03647-4a4e-43fe-b6ed-139faa8c6611)
**操作：**
给房屋添加报价表单时，采用“数据选择器”选择报价项，然后使用“数据联动”给报价单赋值，操作和设置如下：
![image](https://github.com/nocobase/nocobase/assets/26269988/4aa3bb14-1447-42f5-a702-c8120e8ccb1f)
![image](https://github.com/nocobase/nocobase/assets/26269988/e55e9d99-4458-48fb-8ac7-ab041a987e31)
![image](https://github.com/nocobase/nocobase/assets/26269988/413f988f-2021-433b-a66b-e64846704b69)
![image](https://github.com/nocobase/nocobase/assets/26269988/beede359-4a13-4f30-9fab-deb0cb92ea81)
![image](https://github.com/nocobase/nocobase/assets/26269988/9fe25501-0469-41c3-b5c5-fa0b7bf92bc3)
![image](https://github.com/nocobase/nocobase/assets/26269988/cf0f43a3-9001-46e8-9c46-af8009b8cdb3)
提交成功后，然后点击编辑，编辑的联动规则和添加时一致，如果直接打开编辑不做任何数据变动直接保存提示
![image](https://github.com/nocobase/nocobase/assets/26269988/ed7ec4b9-879b-41a5-b60a-952aef76f8bb)
编辑的联动规则
![image](https://github.com/nocobase/nocobase/assets/26269988/f55eea08-d365-4a46-8cb8-a1537fc6763a)
然后，重新选择报价项，点击保存，“string violation”错误提示消失，保存成功。

**Comment by hongboji** [comment]
可以使用最新版本检查问题是否粗在
