### ISSUE TITLE
版本0.14.0-alpha.3，字段类型为自动编码时报错

### ISSUE THREAD

**Issue by annen6um** [nocobase/nocobase#2676]
## Describe the bug

字段类型为自动编码时，点击添加规则报错

## Version

0.14.0-alpha.3

## How To Reproduce

点击添加规则

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/120312321/fced0cfd-0892-4be8-a8f3-8f8e8ccd579a)

**Comment by hongboji** [comment]
最新版已经修复
