### ISSUE TITLE
表格树形模式在member下失灵

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#2686]
## Describe the bug

有个前提，数据表权限单独配置

## Screenshots
![screenshots](https://github.com/nocobase/nocobase/assets/900786/367cf898-4247-48e6-a6a8-4ddab1c790d4)

**Comment by hongboji** [comment]
这个图片的信息看上去丢失很多信息，筛选是什么时候加上的 ？ 图片是循环的 不知道从什么时候开始 ，能否录个视频

**Comment by baiheinet** [comment]
我想复现 ，却不出来了😄
