### ISSUE TITLE
Workflow "Parallel branch" process got stuck

### ISSUE THREAD

**Issue by MisterKCloud** [nocobase/nocobase#2687]
## Describe the bug

I am using the "parallel branch" node in mode "Any succeeded". 
Each branch consists of two further nodes:

- Condition Node in mode "Continue when Yes"
- SQL Action Node

## Version

Nocobase: 0.13.0-alpha.7
MySQL: 8.1.0

## How To Reproduce

1. Build a workflow which is looping through an array
2. Within the loop there has to be a "parallel branch" node in "Any succeeded" mode
3. Create three branches as described above (see descripton)
4. Trigger workflow and see if it got stuck 

## Expected behavior

If one branch fails, the other branches should be started without the process to get stuck. 

## Screenshots

<img width="1040" alt="Screenshot 2023-09-20 at 16 50 37" src="https://github.com/nocobase/nocobase/assets/136599393/91083d9f-7d6e-4b31-a9c2-e2cd44f2fd62">

<img width="1085" alt="Screenshot 2023-09-20 at 16 50 45" src="https://github.com/nocobase/nocobase/assets/136599393/d811e9d2-0876-43a7-bf38-4e505ae150e2">

<img width="624" alt="Screenshot 2023-09-20 at 16 51 14" src="https://github.com/nocobase/nocobase/assets/136599393/cd75aa15-8b99-4c29-9889-5729a7acee33">

## Additional context

Please let me know, which details you require for further error analysis, or if it is a configurational failure please update the documentation.

**Comment by mytharcher** [comment]
Hi @MisterKCloud , I have made a fix on latest main, you may have a try to see if this issue still exists.

**Comment by MisterKCloud** [comment]
Many thanks @mytharcher it solved the issue! 👍
