### ISSUE TITLE
Unable to enable Mobile Client in Multi-App

### ISSUE THREAD

**Issue by offbase-solutions** [nocobase/nocobase#2698]
On enabling it says loading , but after page refresh the plugin is still disabled.

**Comment by hongboji** [comment]
What is the version of NocoBase, how is it deployed, what kind of database is it, and can you take a screenshot of the specific configuration of the new multi-application?

**Comment by offbase-solutions** [comment]
## Describe the bug

On enabling it says loading , but after page refresh the plugin is still disabled.

## Version

Nocobase: Version 0.14.0-alpha.3
Postgres: 15
Deployed: Docker

## How To Reproduce

Steps to reproduce the behavior:

1. Go to 'Plugin manager on Child App'
2. Click on enable 'Mobile Client' plugin
3. Scroll down to '....'
4. See error

## Expected behavior

Expected to see the the Mobile Client plugin enabled

## Screenshots

<img width="694" alt="Screenshot 2023-09-22 at 9 51 22 AM" src="https://github.com/nocobase/nocobase/assets/144357775/ca690033-fb7c-42cf-9de3-a3bc5c5081d5">
<img width="683" alt="Screenshot 2023-09-22 at 9 51 25 AM" src="https://github.com/nocobase/nocobase/assets/144357775/34170a27-7f8b-4f61-88fd-1d6ffda61d1b">
<img width="382" alt="Screenshot 2023-09-22 at 9 51 36 AM" src="https://github.com/nocobase/nocobase/assets/144357775/464f2403-9c4e-48b3-a203-3bddf5aeac25">


## Desktop (please complete the following information)

- OS: IOS
- Browser : Google Chrome Version 117.0.5938.88 (Official Build) (x86_64)

**Comment by hongboji** [comment]
Please try the latest version
