### ISSUE TITLE
API Documentation does not work

### ISSUE THREAD

**Issue by offbase-solutions** [nocobase/nocobase#2699]
After enabling and then navigating to module settings. See screenshot.
<img width="1928" alt="Screenshot 2023-09-21 at 12 33 06 PM" src="https://github.com/nocobase/nocobase/assets/144357775/335fc6b9-9ba9-47be-9fbe-8fc8f29bff24">

**Comment by hongboji** [comment]
What is the version of NocoBase, how is it deployed, and what kind of database is it?

**Comment by offbase-solutions** [comment]
## Describe the bug

On enabling it says loading , but after page refresh the plugin is still disabled.

## Version

Nocobase: Version 0.14.0-alpha.3
Postgres: 15
Deployed: Docker

## How To Reproduce

Steps to reproduce the behavior:

1. Go to 'All Plugin Settings'
2. Click on 'API documentation'

## Expected behavior

Expected to have access to api definitions.

## Screenshots


<img width="1597" alt="Screenshot 2023-09-22 at 10 01 01 AM" src="https://github.com/nocobase/nocobase/assets/144357775/c815e158-aafd-4ff6-b2bd-03b1bae7a8d7">


## Desktop (please complete the following information)

- OS: IOS
- Browser : Google Chrome Version 117.0.5938.88 (Official Build) (x86_64)

**Comment by hongboji** [comment]
Please use the latest version, it has been fixed
