### ISSUE TITLE
Build the plugin

### ISSUE THREAD

**Issue by S3Coloris** [nocobase/nocobase#2722]
## Describe the bug

After executing the build command, the plugin was not saved to storage/tar.

## Version

Version 0.14.0-alpha.2

## How To Reproduce

1. yarn pm create @my-project/plugin-hello
2. yarn pm add @my-project/plugin-hello
3. Do something in code plugin
4. yarn build plugins/@my-project/plugin-hello
5. yarn nocobase tar plugins/@my-project/plugin-hello

## Screenshots

![Screenshot_154](https://github.com/nocobase/nocobase/assets/114476533/313e513f-811e-486e-81f2-386654a8d10a)
![Screenshot_152](https://github.com/nocobase/nocobase/assets/114476533/e74f459c-6683-49ca-9ce0-dbfa1cc03a1b)
![Screenshot_153](https://github.com/nocobase/nocobase/assets/114476533/71551307-db23-44e0-a11b-7cc9f0aee447)

## Additional context

Install: Git source code
DB: sqlite

**Comment by Apkahym** [comment]
i have problem with plugins too. But in step:  `yarn pm enable @my/plugin-test`. I am using `yarn create nocobase-app my-nocobase-app -d sqlite` for my app

I executes step by step and get this

```shellscript
user@pc:appone$ yarn pm create @my/plugin-test
yarn run v1.22.21
$ nocobase pm create @my/plugin-test
WAIT: TypeScript compiling...
success
Done in 8.42s.

user@pc:appone$ yarn pm add @my/plugin-test
yarn run v1.22.21
$ nocobase pm add @my/plugin-test
WAIT: TypeScript compiling...
success
Done in 5.09s.

user@pc:appone$ yarn pm enable @my/plugin-test
yarn run v1.22.21
$ nocobase pm enable @my/plugin-test
WAIT: TypeScript compiling...
Failed to enable plugin: @my/plugin-test plugin does not exist
Done in 5.23s.
```

i have this folder structure

```plaintext
packages
        └── plugins
            ├── @apk
            │   └── plugin-test
            │       ├── src
            │       │   ├── client
            │       │   │   └── index.tsx
            │       │   ├── server
            │       │   │   ├── collections
            │       │   │   │   └── .gitkeep
            │       │   │   ├── index.ts
            │       │   │   └── plugin.ts
            │       │   └── index.ts
            │       ├── .npmignore
            │       ├── client.d.ts
            │       ├── client.js
            │       ├── package.json
            │       ├── README.md
            │       ├── server.d.ts
            │       └── server.js
            └── .gitkeep
```

someone can help me!

**Comment by dream2023** [comment]
![image](https://github.com/nocobase/nocobase/assets/19297757/136dff5b-92f9-4aa5-9f5f-571e5a9ef7c4)

```bash
yarn pm enable @apk/plugin-test
```

**Comment by dream2023** [comment]
![image](https://github.com/nocobase/nocobase/assets/19297757/27d0c8ff-b7fd-4cfa-b13f-bd55a37a7f4a)

Have you changed the folder name?

> i have problem with plugins too. But in step: `yarn pm enable @my/plugin-test`. I am using `yarn create nocobase-app my-nocobase-app -d sqlite` for my app
> 
> I executes step by step and get this
> 
> ```
> user@pc:appone$ yarn pm create @my/plugin-test
> yarn run v1.22.21
> $ nocobase pm create @my/plugin-test
> WAIT: TypeScript compiling...
> success
> Done in 8.42s.
> 
> user@pc:appone$ yarn pm add @my/plugin-test
> yarn run v1.22.21
> $ nocobase pm add @my/plugin-test
> WAIT: TypeScript compiling...
> success
> Done in 5.09s.
> 
> user@pc:appone$ yarn pm enable @my/plugin-test
> yarn run v1.22.21
> $ nocobase pm enable @my/plugin-test
> WAIT: TypeScript compiling...
> Failed to enable plugin: @my/plugin-test plugin does not exist
> Done in 5.23s.
> ```
> 
> i have this folder structure
> 
> ```
> packages
>         └── plugins
>             ├── @apk
>             │   └── plugin-test
>             │       ├── src
>             │       │   ├── client
>             │       │   │   └── index.tsx
>             │       │   ├── server
>             │       │   │   ├── collections
>             │       │   │   │   └── .gitkeep
>             │       │   │   ├── index.ts
>             │       │   │   └── plugin.ts
>             │       │   └── index.ts
>             │       ├── .npmignore
>             │       ├── client.d.ts
>             │       ├── client.js
>             │       ├── package.json
>             │       ├── README.md
>             │       ├── server.d.ts
>             │       └── server.js
>             └── .gitkeep
> ```
> 
> someone can help me!

Have you changed the folder name?

![image](https://github.com/nocobase/nocobase/assets/19297757/a91b86e2-b797-409d-b015-5421aa6568e0)
