### ISSUE TITLE
Change password show user menu

### ISSUE THREAD

**Issue by S3Coloris** [nocobase/nocobase#2723]
## Describe the bug

If you go to the user menu and select Change password, then clicking on the Show password icon again opens the user menu

## Version

Version 0.14.0-alpha.2
Version 0.14.0-alpha.6

## How To Reproduce

1. Go to 'User Menu'
2. Click on 'Change password'
3. Click on icon 'Show password'

## Screenshots

![Screenshot_155](https://github.com/nocobase/nocobase/assets/114476533/c5642a59-8fc8-4c0f-8ede-38ce58f14ba1)
![Screenshot_156](https://github.com/nocobase/nocobase/assets/114476533/7cb20eb6-e374-4000-b613-98b8e72ee3d3)

## Desktop (please complete the following information)

- Browser: Chrome v116.0.5845.188

## Additional context

Sometimes (if go to another tab and back to tab with nocobase) a User Menu opens when you move the mouse over an area Drawer.

**Comment by hongboji** [comment]
It was a bug caused by our refactoring and upgrading of dependencies, the problem has been solved, please use the latest version!
