### ISSUE TITLE
Error displaying data on the chart

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2724]
1) bar chart and column chart does not show some data. (Oleksandr Kashmenskyi - 60, but there is no graph for him)

2) If you look at the chart scale, there is something strange: 60, 0!, 29, 36.

<img width="1586" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/64b828e3-52a5-4e1f-ae33-9c69491974b0">

3) Is it possible to show columns and bars always in different colors, not only when the legend is enabled?

<img width="1579" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/5e003cd6-71fe-4329-8a8e-ef51c029adf0">
4) That's a very strange chart
<img width="1584" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/f18625b4-8f11-4a9e-b235-05f63b06eada">

**Comment by Xilesun** [comment]
Hi Alex,
1. Could your please show the configuration?
2. Sort or Data transform may helpful, what is the data type of "Closing time"? Configuration needed to inspect.
3. Currently not according to the doc of G2Plot.
4. Try to sort by "Vacancy Title"

**Comment by alexkash** [comment]
<img width="1581" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/77b08cfa-75ad-43b5-a8a2-50a4119b43a1">
 I already deleted those charts, made something similar

**Comment by alexkash** [comment]
Yes, sorting helped, but I think it's still an error?

**Comment by Xilesun** [comment]
> <img alt="image" width="1581" src="https://user-images.githubusercontent.com/2558467/270747577-77b08cfa-75ad-43b5-a8a2-50a4119b43a1.png"> I already deleted those charts, made something similar

What's your database and what's the type of "Closing time"

**Comment by Xilesun** [comment]
> Yes, sorting helped, but I think it's still an error?

For area chart, remove "Start Date", otherwise sorting is required for putting the data with the same "Vacancy Title" together.
