### ISSUE TITLE
Typo In Demo Environment "Home" Screen

### ISSUE THREAD

**Issue by Kaviarasan-Ak** [nocobase/nocobase#2729]
## Describe the bug

While using Demo instance of NocoBase, noticed there is a typo under "Home" >> "Latest Customers" wherein it is showing as "Genter" and it should be displayed as "Gender".

## Version

Demo Instance

## How To Reproduce

1. Go to 'Demo Instance' --> "Home"
2. Scroll down until you see "Latest Customers"
3. Under "Latest Customers" look for a field named "Genter" (next to "Name")

## Expected behavior

The field value should be displayed as "Gender" and not "Genter"

## Screenshots

![Screenshot 2023-09-27 at 8 55 43 AM](https://github.com/nocobase/nocobase/assets/130920236/dde54606-ac2e-4e47-b043-5531ab84ebb6)

## Desktop (please complete the following information)

- Browser [chrome Version 116.0.5845.187 (Official Build) (x86_64)]

**Comment by hongboji** [comment]
Thank you for the correction, the current demo environment is too old, is coming out with a new version of the demo environment!
