### ISSUE TITLE
URL type field in Details does not show as a link

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2740]
I can't get the URL field in Details to display as a link. It's kind of weird that I make links and they show up as just text. Does the user have to copy into the browser address bar?
<img width="1119" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/88f074e4-f22b-4b06-9bf4-6455056faedc">

**Comment by hongboji** [comment]
What are Messengers' field types in the data table?

**Comment by alexkash** [comment]
URL

**Comment by zhouyanliang** [comment]
It works well.

![Snipaste_2023-10-09_16-56-50](https://github.com/nocobase/nocobase/assets/1267426/5882c8f2-09ab-4a05-b6ca-9a284776e7c7)

**Comment by hongboji** [comment]
The screenshot uses a relational field, set the field title to be URL, not the URL field used, the URL field itself should be used, when setting the details, set the URL field to display the fields of the associated table.
