### ISSUE TITLE
Workflow trigger data block can not correctly configure sub-table fields.

### ISSUE THREAD

**Issue by sealday** [nocobase/nocobase#2758]
## Describe the bug

<img width="744" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/21fa2b31-a0f1-4981-8cf8-1c91c0d48e14">

"明细" field is a sub-table, but I can not configure table column.

## Version

commit-id  b4d2102e750057d9115f39a02d50407edf5d4bd7

## How To Reproduce

1. create a collection with one-to-many items.
2. create a workflow associate with it
3. create a manual node in the workflow, and add trigger data block.
4. add step 1 field, configure it to sub-table.

## Expected behavior

correctly display sub-table configuration options, like
<img width="975" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/595d5227-0472-4738-9b2c-14ecc26a2115">

## Desktop

- OS: macOS 13.4.1 (c) (22F770820d)
- Browser chrome 115.0.5790.170

**Comment by hongboji** [comment]
工作流中人工节点添加的是什么表单，明细字段对应的数据表结构是什么样子，可以都截图看看

**Comment by sealday** [comment]
<img width="818" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/7f78c483-d77c-4e0e-b292-a610ee1df3a7">

**Comment by sealday** [comment]
<img width="760" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/4855d3da-31d7-4b80-8364-fd4718023df5">

**Comment by sealday** [comment]
<img width="1246" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/73db16a3-572a-4c4f-8b42-174289a34bff">
When it serves as a form block, it functions properly and meets expectations.

**Comment by sealday** [comment]
Sorry for bothering you. After I cleared the cache, everything returned to normal. In fact, I encountered this issue before the National Day and had been trying to find a solution. However, it seems that one of your recent updates in the past two days has resolved this problem. @mytharcher

**Comment by sealday** [comment]
I will temporarily close this issue. If I encounter any related problems in the future, I will come back.

**Comment by sealday** [comment]
<img width="239" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/6c8ae76e-4851-4aee-9a7c-3d57183b522a">
I've noticed that when the role is set to "Admin," it doesn't seem to work. There might still be some issues here. If you switch the role to "Root," it works fine.

**Comment by sealday** [comment]
<img width="1325" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/b581eb47-390c-409b-bc0c-346595db0b41">
When switching to other roles, which are not the Root role (normal system users are not typically Root), the process cannot access its details at this point.

**Comment by sealday** [comment]
@mytharcher Thank you. Besides the configuration interface, it can only be used under the root role. From what I have observed, only the root role can view the sub-table, and other roles cannot see the content of the sub-table.

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3415
