### ISSUE TITLE
HELP!!! 

### ISSUE THREAD

**Issue by AnryHedgehog** [nocobase/nocobase#2775]
## Describe the bug

Everything was fine this morning, but after lunch my workflows stopped working

This workflow has been working for a month, but today it stopped working

## Version

NocoBase version 0.14.0.

## Expected behavior

According to the workflow, I had a user binding to the "Who Created" field (Not system) everything worked, but it stopped working this afternoon

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/146196537/877ae5e4-6a13-4efb-b805-6601a6e97a5f) 

![image](https://github.com/nocobase/nocobase/assets/146196537/31d5f1f1-6279-4bfb-a6f4-fe16fd1445f4)
![image](https://github.com/nocobase/nocobase/assets/146196537/361e6768-a9db-4628-88c8-a8172f621da5)
![image](https://github.com/nocobase/nocobase/assets/146196537/c9af877e-c343-45a2-917b-82e37229b47d)

## Desktop (please complete the following information)

- OS: [Windows 10 Pro]
- Browser [chrome v117, Yandex v - 23.9.1.967 , Edge v - 117.]

## Additional context

It all started around lunchtime, but on new workflows, nothing went beyond the collection event

**Comment by AnryHedgehog** [comment]
[4.log](https://github.com/nocobase/nocobase/files/12853475/4.log)


these are logs for a thrown-off problem, before that I experimented with a parallel branch

**Comment by mytharcher** [comment]
> [4.log](https://github.com/nocobase/nocobase/files/12853475/4.log)
> 
> these are logs for a thrown-off problem, before that I experimented with a parallel branch

Looks its triggers were not executed from `2023-10-09T11:05:56.698Z`. Did you do any upgrading for version of NocoBase?

Or could you help to make a minimal case via SQLite, and put it here? So that we could debug with your scenario.

**Comment by AnryHedgehog** [comment]
There were no updates, everything was created at v - 0.14

> > [4.войти](https://github.com/nocobase/nocobase/files/12853475/4.log)
> > это логи для выброшенной проблемы, до этого я экспериментировал с параллельной веткой
> 
> Похоже, его триггеры не выполнялись с `2023-10-09T11:05:56.698Z`. Вы делали какое-либо обновление для версии NocoBase?
> 
> Или не могли бы вы помочь составить минимальный вариант с помощью SQLite и поместить его сюда? Чтобы мы могли выполнять отладку по вашему сценарию.

There were no updates, everything was created at 0.14
Create a minimal precedent with SQLite I've never done, what do you need to do? I can describe what this trigger does and what I'm going through

**Comment by mytharcher** [comment]
MySQL is also OK. You could create a new empty NocoBase and configure the minimal app to reproduce your case. Then export the SQL file of that DB.

**Comment by AnryHedgehog** [comment]
[dump-nocobase-202310111204.zip](https://github.com/nocobase/nocobase/files/12867256/dump-nocobase-202310111204.zip)

**Comment by AnryHedgehog** [comment]
bd

**Comment by mytharcher** [comment]
Hi @AnryHedgehog , have you ever deleted any workflow? I found some workflows were deleted but left non-started executions, which `workflows.id` are `102` and `106`.

After I delete them in DB, and restart, other pending executions started and processed normally.

**Comment by AnryHedgehog** [comment]
Please help me, I don't see them in the GUI, where exactly did you find them?

**Comment by AnryHedgehog** [comment]
after the update, nothing has changed, please tell me the full path

**Comment by AnryHedgehog** [comment]
![image](https://github.com/nocobase/nocobase/assets/146196537/0cf882b1-5b71-4254-8629-95dd54024657)

I don't see these workflows ( 102 and 106 )

**Comment by mytharcher** [comment]
> I don't see these workflows ( 102 and 106 )

True, they are not existed. But I am not sure how you deleted them before.

Please wait for our next PR (#2080) to main shortly, it will let others run normally.

**Comment by AnryHedgehog** [comment]
Please tell me, do you have any ideas how to fix it?

**Comment by AnryHedgehog** [comment]
It's just that the system is already in operation

**Comment by AnryHedgehog** [comment]
The solution was to dump the database without workflows

**Comment by AnryHedgehog** [comment]
Thank you so much for your help

**Comment by mytharcher** [comment]
PR #2080 merged. You could check latest main branch (or do an upgrade if you are using docker) to see if your workflow still stucking.

**Comment by AnryHedgehog** [comment]
We reinstalled docker, filled in the dump without workflows and everything worked, thanks for the help again
