### ISSUE TITLE
在多层弹框中，点击 字段赋值 ，弹框立马被关掉，无法操作 

### ISSUE THREAD

**Issue by marsal1212** [nocobase/nocobase#2784]
## Describe the bug

在多层弹框中，点击 字段赋值 ，弹框立马被关掉，无法操作 
## Version
Version 0.14.0-alpha.7.20231009034019

## How To Reproduce

1. 添加第一层操作弹框
2. 弹框中配置操作，选择自定义>update record
3. 悬浮 update record button，悬着dropdown中的字段赋值按钮

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/20449902/1b2d6659-ffed-4247-84e8-a2afdcf1252a)
## Desktop (please complete the following information)

- OS: win11
- Browser chrome v116.0.5845.188

**Comment by hongboji** [comment]
已经修复
