### ISSUE TITLE
API文档中没办法测试添加用户和添加角色

### ISSUE THREAD

**Issue by wywfw** [nocobase/nocobase#2791]
![screenshot-20231010-192022](https://github.com/nocobase/nocobase/assets/147503355/00639789-5489-4ef6-afad-7acbf18f4f59)
你好，我使用api文档，添加用户、编辑用户和修改角色，但是没有输入参数的输入框，如果我调用这个api，参数是什么，怎么查看

**Comment by chareice** [comment]
https://github.com/nocobase/nocobase/pull/5391
