### ISSUE TITLE
Sub-form(Popover) does not display the name correctly

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2792]
<img width="935" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/1473b6c4-bf36-4cb7-ae66-9df05834889d">

NC version 14.6

**Comment by hongboji** [comment]
Can you take a screenshot of the field settings in the datasheet?

**Comment by alexkash** [comment]
It's a collection and a Candidates field and there's an associated messenger field in there
<img width="1335" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/315f710a-07ff-4761-86dc-1aabf930689f">
This is the Messengers collection that the form refers to
<img width="1163" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/c6e72d6e-075a-4a1d-8af3-c20b8b431d8c">

**Comment by hongboji** [comment]
It's not a bug.
