### ISSUE TITLE
Error during workflow execution

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2804]
1) I have an Active Vacancy collection:
<img width="720" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/d36282f7-5a7d-420c-9f62-03a57bf5f53c">

2) I want to write the Value of the Vacancy field into the Active Vacancy field after creating the record, but I am getting an error.
<img width="323" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/f3045360-5bb0-4661-b33d-c0c88f8a4765">

3) The calculation stage gives me the result:
<img width="316" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/ff17e312-a866-4d0b-bad2-33fc92021c10">

4) But this result is not recorded in the Active Vacancy String field

<img width="655" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/e8b72018-5194-4118-9337-3bc0aebbd85a">

Status
:
Error
Executed at
:
2023-10-11 13:22:18
Node result
:
{
  "message": "string violation: cand_vacancy cannot be an array or an object",
  "stack": "SequelizeValidationError: string violation: cand_vacancy cannot be an array or an object\n    at InstanceValidator._validate (/app/nocobase/node_modules/sequelize/lib/instance-validator.js:50:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async InstanceValidator._validateAndRunHooks (/app/nocobase/node_modules/sequelize/lib/instance-validator.js:60:7)\n    at async InstanceValidator.validate (/app/nocobase/node_modules/sequelize/lib/instance-validator.js:54:12)\n    at async Function.update (/app/nocobase/node_modules/sequelize/lib/model.js:1933:26)\n    at async _Repository.update (/app/nocobase/node_modules/@nocobase/database/lib/repository.js:409:24)\n    at async _Repository.descriptor.value (/app/nocobase/node_modules/@nocobase/database/lib/decorators/transaction-decorator.js:66:29)\n    at async Object.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/instructions/update.js:29:20)\n    at async Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:124:13)"
}

**Comment by mytharcher** [comment]
Could you please paste your calculation config?

**Comment by alexkash** [comment]
<img width="461" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/3141dd99-7434-4b37-82f9-d632aa32eda9">

**Comment by mytharcher** [comment]
Looks the variable of your trigger data pointing to a to-many field? So it was retrieved as an array:

```
[
  "Project Manager"
]
```

And the array can not be used to be a value of single line string field. So that the error was thrown as expected.

A workaround is to use a loop node to loop your to-many field result, and in each loop use the loop item to update should be OK.

**Comment by alexkash** [comment]
Thank you
we already found a way out and did with the query
