### ISSUE TITLE
Сan't disable the link in the column

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#2806]
1) If you add a sub table to the form, you can't disable the link in the column and you can't adjust which popup to display when clicked.

<img width="821" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/29e971b4-c61f-40d7-86ac-679032805ace">

<img width="335" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/216f2e27-dbef-4193-ad11-743e44928eb9">

2) If you click on the link in the panel that opens, you cannot call up templates

<img width="304" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/1d0da858-6122-4ee8-8a9f-5a9b0a4b272e">

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3390

**Comment by hongboji** [comment]
1、Links support disable, window size settings to be added subsequently
2、Can be added normally
