### ISSUE TITLE
Render Failed due to unavailable data and no way to fix

### ISSUE THREAD

**Issue by mishoboss** [nocobase/nocobase#2837]
## Describe the bug

The `Render Failed` screen shows when the view tries to get unavailable or wrongly formatted data. Basically on any data issue page crashes with `Render Failed` screen. This often happens during screen design and there's no way to just go back to that page and edit the problematic component. 

## Version
0.14.0-alpha.7

## How To Reproduce

1. Go to any page and create a visual component to render some data
2. Data must have missing data that the component expects to be there

## Expected behavior

To be able to close the `Render Failed` screen and edit the problematic part on the page.

## Screenshots

<img width="883" alt="image" src="https://github.com/nocobase/nocobase/assets/1629929/ed897c62-d413-4e08-88b7-f5eadddb59e8">

## Desktop (please complete the following information)

- OS: MacOS
- Browser: Chrome

**Comment by mishoboss** [comment]
Hey Nocobase team, this issue is really nasty. There should be way to go back and just fix the UI. Now the only way to "fix" it is to scrap the whole page and start from beginning.

---

嘿，Nocobase 团队，这个问题真的很糟糕。应该有一种方法可以返回并修复 UI。现在“修复”它的唯一方法是废弃整个页面并从头开始。

**Comment by hongboji** [comment]
Thanks for your feedback, we have made the following optimizations:
1. The view has added an "Unknown field type" group to display unsupported field types, which will not be displayed in the page configuration.
2. Errors on the front-end page are at the field level or a single block level, and try not to affect the entire page
You can use the latest code, and we apologize for the trouble you have caused

**Comment by hongboji** [comment]
The issues will be closed. If you have any questions, please continue to provide feedback.
