### ISSUE TITLE
Scale workflow execution

### ISSUE THREAD

**Issue by sudeeshr** [nocobase/nocobase#2854]
## Describe the bug

Need to scale workflow execution so that executions can run concurrently across multiple threads/workers. 

we have multiple workflow which are running "on after record create" and "record update" and if we import 10K records the workflow execution is taking time.

## Version

0.14

## How To Reproduce

1. have multiple workflows enabled on a collection - after record create and after record update
2. import 10k records

**Comment by mytharcher** [comment]
To optimize the performance in this scenario may not be in our short plan.

Close due to it is not a bug.
