### ISSUE TITLE
[Feat] Adding Elestio as new installation & deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [nocobase/nocobase#2860]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Nocobase application [as shown here](https://elest.io/open-source/nocobase). I think it would be a great idea if we can add it to official readme/documentation here.
In addition to this, if you are interested we provide collaboration opportunities with tools we support by revenue share upon addition of this method in docs. If you would like to collaborate, just drop me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

<img width="1426" alt="image" src="https://github.com/nocobase/nocobase/assets/53310847/bba51b2d-ae92-4102-ac33-e15654d8b03e">

**Comment by zhouyanliang** [comment]
Thank you Kaiwalya, let's talk more about it when we release 1.0.
