### ISSUE TITLE
Anomaly occurs when displaying the single-choice options in associated table fields.

### ISSUE THREAD

**Issue by sealday** [nocobase/nocobase#2863]
## Version
Version 0.13.0-alpha.10

## How To Reproduce

1. Create a table and its corresponding detail item table.
2. Then, in the main table, create a dropdown menu single-choice field. 
3. Create a table block and create a pop-up in the action column
4. Configure the details of the item and select the single-choice field of associated table.

## Expected behavior

1. Displaying normally.

## Screenshots

<img width="1062" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/7f4a8f11-ce36-44a0-b613-88c1df111c5a">

## Desktop (please complete the following information)

- OS: MacOS 14.0
- Browser： chrome v117

**Comment by hongboji** [comment]
The latest version has been fixed, please use the latest version
