### ISSUE TITLE
Cannot destructure property 'getActiveFieldsName' of 'useFormActiveFields(...)' as it is null. at useCustomizeRequestActionProps

### ISSUE THREAD

**Issue by MarshallEriksen-shaomingyang** [nocobase/nocobase#2871]
![image](https://github.com/nocobase/nocobase/assets/59674455/3b90f9a8-eb70-47ba-9e78-78a0f95ca5de)

nocobase 版本 ：v0.14.alpha.7

出现问题原因： 在点击操作 创建自定义请求后 还有在数据表内删除某个字段 而在页面内还保留未删除的字段会出现这个问题

**Comment by hongboji** [comment]
请问nocobase版本号是多少？

**Comment by hongboji** [comment]
请使用最新版本
