### ISSUE TITLE
Error with installation for creating plugins

### ISSUE THREAD

**Issue by DimaFill** [nocobase/nocobase#2886]
Hello, we have a problem installing additional software for working with plugins. When we try to install via "Get source code" we start having problems at step 5, and when we go through "create-nocobase-app" we have problems at step 4. We also have a problem with databases.
![image](https://github.com/nocobase/nocobase/assets/78826222/e463367b-d19f-4a34-b11a-c4a94467f0c1)

**Comment by hongboji** [comment]
Could you please provide more information in accordance with the feedback question template in order to locate the problem?
