### ISSUE TITLE
Form data in the request body of a custom request settings in any form not sending data

### ISSUE THREAD

**Issue by okcodey** [nocobase/nocobase#2895]
Hello @zhouyanliang it seems its only the initial image that you pushed out to introduce this feature that is working as it is supposed to. All others are not for me.

Associated fields relationship ie one to many (most especially), many to one does not get fired with the data in a webhook for example.

I was having this issue until i reverted back to that image of the 18th October 2023 that introduced this feature and resolved this attached discussion.

Please look into this.

_Originally posted by @zhouyanliang in https://github.com/nocobase/nocobase/discussions/1933#discussioncomment-7282935_

**Comment by Dunqing** [comment]
Thank you for the feedback, I will try to reproduce this problem

**Comment by Dunqing** [comment]
Can you record a reproduction of this problem? It will help us figure out what the problem is.

**Comment by okcodey** [comment]
It will be a bit hard to record the problem. But I can talk you through how to reproduce it:
- On a table block, Configure the "Actions" columns to include the "View" and "Edit".
- On the "View", make the modal open in "Dialog" and the pop-up size be in "Large" mode.
- When you click on "View", this below is what I have configured in the dialog:
![image](https://github.com/nocobase/nocobase/assets/147355081/ad2f1d45-5183-43c0-ad94-c1d06f19873a)
- I configured the "Send Email" button to automatically fire a webhook on n8n to send out emails with specific information including the Nomination ID and the Item ID in the table. The table is taking information from another table (Nomination Item ID table). The Nomination table that has the rest of the information in the form has a one-to-many relationship with the Nom Item ID table. Below is what I configured in the HTTP POST request:
- 
![image](https://github.com/nocobase/nocobase/assets/147355081/a56a8624-25c0-474e-8a2f-95a18e19d748)

- The webhook gets all other data that comes with the request except the "nomitemid" which is coming from the associated table described above.
- I have tried this POST request using Make also (apart from n8n) and I am getting the same result i.e. the "nomitemid" data does not come with the request.

Please let me know if you understand my points.

**Comment by Dunqing** [comment]
Is only the nomitemid data incorrect?

**Comment by okcodey** [comment]
Yes it is only the nomitemid data - which is an associated table (1 to many) to the nominations table that the data doesn't come with the webhook when it is fired.

For further context, the nomitemid data is an Array that is supposed to come with all the Item IDs and their information in the table below:
![image](https://github.com/nocobase/nocobase/assets/147355081/f2996769-7ab0-4a1c-892a-d7e99283c2fd)

**Comment by Dunqing** [comment]
So the expected value of the `nomitemid` is an array? like `['NIT100006', 'NIT100008', 'NIT100009', 'NIT100010']` ?

**Comment by okcodey** [comment]
Yes, basically this plus other info within the table that is supposed to come with it - but basically that's the format that it comes in with the image that is working.

**Comment by okcodey** [comment]
Hi @Dunqing another thing I noticed about those images (the ones not working) is that the workflows don't work there either. So maybe it's related.

If you have a working workflow and you deploy those current images on the main branch, the workflows attached to buttons (like submit) and the other issues described above are what you have. Thank you!!!

**Comment by okcodey** [comment]
Hi @Dunqing - some additional information from additional testing:

I tried calling a GET request on the associated table (nomitem) in question (which is an array) with n8n and i was getting an ERROR 403 with the main branch image that you have in the docker hub.
![image](https://github.com/nocobase/nocobase/assets/147355081/2dc68dfb-ba70-40a2-8fcd-5e556fb9ce85)

When I reverted back to the old working image, everything was working fine. So I think this is a very fundamental bug that affects how HTTP requests work in the system. Something for you to critically look at. Great platform.

**Comment by Dunqing** [comment]
What request settings do you configure?

**Comment by okcodey** [comment]
So i tried using a GET request https://mydomain.com/api/collection1:get?filterByTk=1&filter=%7B%7D&fields=field1,field2&append=nomitem

This worked on the working image that I have been talking about BUT when I pulled the image in the 'main' branch yesterday, it didnt work - gave me that error above.

**Comment by Dunqing** [comment]
This is strange, we have tested that the main branch is working correctly

**Comment by okcodey** [comment]
Thanks @Dunqing. I figured out why it wasn't working. Since that error was pointing to a permission issue, I changed the API keys for Nocobase and it started working. 

So anyone having the same issue, just regenerate another API key and it will be fixed. Seems it wasn't recognizing the previous API key again.

**Comment by Dunqing** [comment]
About this, you can see the warning in 
https://github.com/nocobase/nocobase/blob/main/packages/plugins/%40nocobase/plugin-api-keys/docs/en-US/usage.md

**Comment by Dunqing** [comment]
Also, If you just want to use your click user current user's token, you don't need to pass `Authorization` through `headers`, it will carry your token by default.
