### ISSUE TITLE
The problem with the instructions for the first plugin made by your own hand

### ISSUE THREAD

**Issue by AnryHedgehog** [nocobase/nocobase#2906]
## Describe the bug

<We decided to try the nocobase from the source, and put it not through the dock. When trying to create your own plugin, according to the instructions, such an error flies out at 2 steps
![276903538-e463367b-d19f-4a34-b11a-c4a94467f0c1](https://github.com/nocobase/nocobase/assets/146196537/702e6624-f2ff-413d-b79f-d43296fc0552)
>

## Version

<0.14.0 alpha 7>

## How To Reproduce

1. Go to Develop the first plugin
2. Click on yarn pm create @my-project/plugin-hello and next step yarn pm add @my-project/plugin-hello
3. See error
![276903538-e463367b-d19f-4a34-b11a-c4a94467f0c1](https://github.com/nocobase/nocobase/assets/146196537/cc9fc8b9-dec1-4563-8de8-82decb560245)

## Expected behavior

<I expect everything to go according to the instructions>

## Desktop (please complete the following information)

- OS: [Windows 10 Pro]
- Browser [edge, chrome, yandex]

**Comment by AnryHedgehog** [comment]
I apologize, the wrong screen is in the problem

![image](https://github.com/nocobase/nocobase/assets/146196537/5564cebb-0365-4c58-a442-1bd42e390a27)

Sorry again

**Comment by MarshallEriksen-shaomingyang** [comment]
run " yarn build plugins/@my-prioject/plugin-hello"

**Comment by AnryHedgehog** [comment]
![image](https://github.com/nocobase/nocobase/assets/146196537/249290e0-9f2b-46ba-9fd7-3db2a96e04ca)
Hello, it came out, honestly I'm not a developer and I don't understand much about it, can I please tell you in detail or write pictures why this is happening

**Comment by AnryHedgehog** [comment]
![image](https://github.com/nocobase/nocobase/assets/146196537/3842a3e8-567b-442d-9371-687280b3adaa)

**Comment by hongboji** [comment]
Execute yarn build all first, then yarn build your own plugin
