### ISSUE TITLE
build client package 没有包含less和字体文件

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#291]
使用版本分支是：nocobase_next

我注意到了[nocobase/packages/client 文件缺失 #79](https://github.com/nocobase/nocobase/issues/79)

是正常的构建次序，在 nocobase 根目录：

```bash
yarn
yarn bootstrap
yarn build 
```

但是相关目录下没有 *.less和字体文件，导致使用相关package时会提示编译错误，没有这些文件。

**Comment by MarshalW** [comment]
明白了，在 packages/app 中，less 通过 umi 配置打包到单一 css 文件中，字体文件放置在 dist/static 目录下了。

**Comment by chenos** [comment]
nocobase-next 分支的 `@nocobase/client` 还在开发中，打包还有些问题，暂时不支持直接使用。现在需要依赖 umi 来打包输出最终的 dist。

https://github.com/nocobase/nocobase/blob/e002777b639ac3c42accd0a0773e9f6a486ac13e/packages/app/.umirc.ts#L30-L45

**Comment by MarshalW** [comment]
好的，明白了。
