### ISSUE TITLE
the system throughput is very low

### ISSUE THREAD

**Issue by sangluocun** [nocobase/nocobase#2912]
## Describe the bug

The performance of the web API is not expectations, I got  87 tps. tried to setting connection max pool to 50, no significant improvement。 

## Version

nocobase：latest
db：postges
server：win10
installation：yarn start，create nocodb app
hardware: 8G RAM , 6core CPU

## How To Reproduce

1. create a collection with two colum : name, qty
2. invoking the post api for creating entity
3. using jmeter to do performance test， 20 threads， 5min，delay 1s
4. the throughput is very slow

## Expected behavior

using node-red， tps is 1700, so the hardware/database is the bottleneck。

## Screenshots
no

**Comment by sangluocun** [comment]
Using latest version:  yarn pm2 start benchmark/nocobase-server/index.js --name nocobase-server

the throughput is about 130 tps(create  user),  there is no privliage check in this benchmark app

I have tried add more pool connection, There was no significant improvement. I am sure the connction pool is setting correctly(pg admin show the connections are 20.

```
    const opts = {
      pool: {  
        max: 20,  
        min: 20,  
        idle: 30000, // 30 seconds  
        acquire: 30000 // 30 seconds  
      },
```

**Comment by sangluocun** [comment]
latest test result:  Version 0.17.0-alpha.1
add connection pool to 30, I got a good TPS 150/s, it's cover most of production scenarios
Great team！！！

**Comment by Xilesun** [comment]
Hi, @sangluocun 

Check out the latest version [v0.17.0-alpha.5](https://github.com/nocobase/nocobase/commit/35301358de824690ef4ede2a38a02e618b4c8bce), we did a round of performance optimization.  Refer to [First Optimization Process for NocoBase Server-Side APIs](https://blog.nocobase.com/posts/optimization-process-for-nocobase-apis/)

Feel free to test it out at your convenience. Any feedback or issues you encounter would be greatly appreciated.

Cheers!

**Comment by sangluocun** [comment]
latest test result: Version 0.17.0-alpha.5

No console output and log 352/s
![image](https://github.com/nocobase/nocobase/assets/3936345/638b013b-540d-4c4c-8d45-8e35b7b1263f)

Only log file  330/s
![image](https://github.com/nocobase/nocobase/assets/3936345/181d57db-b142-4188-a828-88f2a50ae2fd)

Both logfile and console log(default) 294/s
