### ISSUE TITLE
Percent input Can't input the decimal value

### ISSUE THREAD

**Issue by pc007007** [nocobase/nocobase#2930]
## Describe the bug

Percent input Can't input the decimal value

## Version

0.14

## Expected behavior

can input the decimal value in percent input.

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/13336244/5bfabfd4-f0e0-4f30-bdbd-57d1a63c82fd)

**Comment by katherinehhh** [comment]
Thank you for your feedback! The issue has been resolved.
