### ISSUE TITLE
Logo in upper left corner

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#2940]
## Describe the bug

I can not load a new image to be alogo in upper left corner
## Version
0.14.6 Alpha 6

## How To Reproduce
Files do not show

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/89129225/a74cb977-6cd0-4f8a-99d5-a258a636e9fe)

![image](https://github.com/nocobase/nocobase/assets/89129225/6b50383f-fae1-4325-aadb-2622c67c8d4d)

![image](https://github.com/nocobase/nocobase/assets/89129225/0fcfd666-cd9a-4ba8-bdd7-d8ed5de3de56)

## Desktop (please complete the following information)

- Browser chrome Version 118.0.5993.89 (Officiell version) (64 bitar)

## Additional context

According to previous mail conversation

**Comment by hongboji** [comment]
Is NocoBase installed in the app/nocobase directory, and are uploaded files in the app/nocobase/uploads directory?

**Comment by thomaswennersten** [comment]
App is istalled as seen in attachment:
![image](https://github.com/nocobase/nocobase/assets/89129225/6afb40eb-596a-4a50-96bc-6124c33a8df9)


And files like this:

![image](https://github.com/nocobase/nocobase/assets/89129225/66749a00-1d75-4b4b-baa4-026d0c2e74b5)

**Comment by hongboji** [comment]
Please set the Storage base URL to '/uploads', Destination to 'uploads', Path to empty, refresh the page and see if it works.

**Comment by thomaswennersten** [comment]
I have made the changes but I´m afraid it do not work anyway. I Try to upload files but I can not see that any new files is added. I have been able to do uploads before, but not been able to show them on the site. Now I can not upload either.

**Comment by thomaswennersten** [comment]
Now I can upload files correctly. I can upload files both using a file table block and suing the system settings function to upload a pic that should be used as a logo. But, the logo that resides in the folder (I have verified that) do not appear in the upper left corner.

Myabe a small problem, but I realy need this to be able to finish up.

**Comment by hongboji** [comment]
May I ask how the file manager is configured , is it possible to take a screenshot to see. The local service file manager has simplified the configuration in subsequent versions and solidified the initial folder, so that you can add custom folders within a fixed folder.

**Comment by thomaswennersten** [comment]
I do not undertsnad what you want me to try with the re-upload. I have tried several times to upload the same pic without luck. I can see that the file gets uploaded to the server but it do not appear as a logo.

here is a screenshot of the file manager setup

![image](https://github.com/nocobase/nocobase/assets/89129225/168fe26a-1cc4-4bbf-9151-558a114b63ee)

**Comment by zhouyanliang** [comment]
Hi Thomas,

Please use your browser's DevTools to see what the image URLs are in both places. The problem is really simple, it's a path error, and you can see where it's wrong from here.

![Snipaste_2023-11-03_08-40-34](https://github.com/nocobase/nocobase/assets/1267426/c284b6f5-9728-4544-b1fe-67578f94407d)

**Comment by thomaswennersten** [comment]
I see that the system settings refer to a strange location:

![image](https://github.com/nocobase/nocobase/assets/89129225/aecdabea-c5d3-47d7-b156-cc9f62503af2)


The file manager settings locks like below:

![image](https://github.com/nocobase/nocobase/assets/89129225/ad2f71a1-94d3-4316-87b8-70b4e01ef7ff)

The uploaded file resides here :

![image](https://github.com/nocobase/nocobase/assets/89129225/69beedd5-2a88-4227-9a67-31228bd8c50c)

It nmight be a simple problem, but seems hard for me to resolve...

**Comment by hongboji** [comment]
Please set the Storage base URL to '/storage/uploads', Destination to 'storage/uploads'，And re-upload the logo image to see if it displays properly

**Comment by thomaswennersten** [comment]
Hi,, since it has been a while since I addressed this issue I am not quite sure, but as I remember it the problem occured due to the file path set to the logo- file. When I have setup a new instance of Nocobase, now on version 0.19.0 Alpha 6, I have not had any problem with changing the logo just followed the steps:

1.Got System settings
2. Delete the old icon by clicking the image and the dustbin.
3. Upload a new image

![image](https://github.com/nocobase/nocobase/assets/89129225/066a7cf9-8205-4a2f-8c1f-56296737c921)
