### ISSUE TITLE
文件管理器如何配置oss

### ISSUE THREAD

**Issue by MarshallEriksen-shaomingyang** [nocobase/nocobase#2947]

**Comment by MarshallEriksen-shaomingyang** [comment]
![image](https://github.com/nocobase/nocobase/assets/59674455/162316ad-fdf5-42ca-bfe6-813c60cfd07d)
这是我配置字段的内容
目前总是出现
![image](https://github.com/nocobase/nocobase/assets/59674455/f2a66abe-18ea-44bb-95a2-88b02c8b2436)错误我不知道问题到底出现在哪

**Comment by chenos** [comment]
@MarshallEriksen-shaomingyang 确认一下 id 或者 secret 是否填写正确了
