### ISSUE TITLE
列表页的 filter 能否支持对 number 字段取区间范围

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#300]
使用版本分支是：nocobase_next

比如`价格`字段，取金额在某个范围之内。

看目前还没有支持。

![商品列表_-_NocoBase](https://user-images.githubusercontent.com/931976/163967111-6a0709bf-ec3f-4b72-a22c-59d2e99f6ffb.png)

**Comment by MarshalW** [comment]
行。

目前我刚开始看界面部分，如果有时间我就实现一下。

**Comment by chenos** [comment]
现在没有提供区间值的筛选条件，如果需要可以扩展。除此之外，也可以这样来过滤
<img width="589" alt="image" src="https://user-images.githubusercontent.com/2993310/163994508-4b59b833-7e58-4538-99fa-12699f313a28.png">

**Comment by MarshalW** [comment]
明白了。

我的数据类型选错了，文本类型了，因此没有大于这样的运算符。

之前我做了一次，还选择了数据精度，可能后来再做忘记设置了。

这个不算问题了，我关闭了先。
