### ISSUE TITLE
Invalid date with data scope

### ISSUE THREAD

**Issue by oarojas** [nocobase/nocobase#3000]
## Describe the bug

When trying to set a data scope on a block (table or kanban view) to only show the current (today) data, it drops an error of invalid data

## How To Reproduce

1. Create a collection
2. Add new item
3. Set data scope for block with values CreatedAt - is - Today
4. An error appears, as Invalid date

## Expected behavior

The block should filter de data based on the data scope filter.

## Screenshots

<img width="617" alt="Screenshot 2023-11-08 at 1 58 15 a m" src="https://github.com/nocobase/nocobase/assets/39339395/710a19cb-f13f-4cd2-af9e-4d68582a6362">
<img width="436" alt="Screenshot 2023-11-08 at 1 58 24 a m" src="https://github.com/nocobase/nocobase/assets/39339395/1cd599bb-ca07-4205-9a75-721f0b2a086b">

## Desktop (please complete the following information)

- OS: OSX
- Browser Chrome

## Additional context

Running with docker and postgres database

**Comment by zhouyanliang** [comment]
Fixed.
