### ISSUE TITLE
HTTP Post request do not transfer parameters

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#3017]
## Describe the bug

When I make a http post request to my postal server the defined parameters in the request do not seem to be transfered to postal, the answer i get back from postal says that no recipients have been specified.

## Version

Version 0.14.0-alpha.6
## How To Reproduce

Hard to share since I can not share credentials to my postal but I attach screenshots

## Expected behavior

A mail should be sent in the workflow

![image](https://github.com/nocobase/nocobase/assets/89129225/d3a4ba78-6a21-461c-899d-78deca72f5c9)

![image](https://github.com/nocobase/nocobase/assets/89129225/9b7c2a8e-b6aa-4ba8-801e-974ea834dc64)

## Desktop (please complete the following information)

Version 118.0.5993.120 (Officiell version) (64 bitar)

## Additional context

postal 2.1.4

**Comment by thomaswennersten** [comment]
Could someone please share an nexample of a POST request to a email server that realy works so I can see how you put it in the workflow. I do not seem to get it to work

**Comment by mytharcher** [comment]
I have just checked the Postal API document and found this:

<img width="695" alt="image" src="https://github.com/nocobase/nocobase/assets/525658/eb7da628-d8af-4f71-8f4f-4279f89b8c0d">

Which is saying:

> * Parameters should be encoded in the body of the request and application/json should be set as the Content-Type header.

Looks you put your parameters in query parameters part, not in body. You could make another try to put them in body JSON, and see if this works.

**Comment by thomaswennersten** [comment]
:)

@mytharcher

It works, I am very grateful for your idea, it really helped me out!

I removed all the parameters and included them in the body. I attach a screenshot for future referens if someone else get stuck.

![image](https://github.com/nocobase/nocobase/assets/89129225/8d6ac573-b993-48ac-9154-1c5e6e52f2d3)

**Comment by thomaswennersten** [comment]
Now it works with hard coded to: and from and so on, but I need to use trigger values from Nocobase and I can include that in the body, bur it is not accepted as a correct json call.

{
  "from": "info@sambruk.se",
  **"to": [{{$context.data.epost}}],**
  "subject": "Testmeddelande",
  "html_body": "<p>Det här är innehållet i ditt e-postmeddelande.</p>",
  "plain_body": "Det här är innehållet i ditt e-postmeddelande."
}

**Comment by mytharcher** [comment]
You need to change `"to": [{{$context.data.epost}}]` to `"to": "{{$context.data.epost}}"`.
