### ISSUE TITLE
SQL execution error in the workflow

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3022]
**I have tried all SQL variants and they all give an error. One of the latest variants:**

INSERT INTO t_ac2mdgfvzvz (createdAt, updatedAt, f_o69fha3awv5, f_u27l9leqgu7) 
VALUES (NOW(), NOW(), {{$context.data.vacancy.id}}, {{$context.data.candidate_key}})

**Error:**

Node result
:
{
  "message": "result.replace is not a function",
  "stack": "TypeError: result.replace is not a function\n    at /app/nocobase/node_modules/@nocobase/utils/lib/json-templates.js:113:25\n    at Array.reduce (<anonymous>)\n    at templateFn (/app/nocobase/node_modules/@nocobase/utils/lib/json-templates.js:95:24)\n    at Processor.getParsedValue (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:312:12)\n    at Object.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/instructions/sql.js:27:27)\n    at Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:126:19)\n    at Processor.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:165:17)\n    at Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:155:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}

**Comment by alexkash** [comment]
SQL:
INSERT INTO t_ac2mdgfvzvz (createdAt, updatedAt, f_o69fha3awv5, f_u27l9leqgu7) 
VALUES (NOW(), NOW(), 25, 169)

Error:
{
  "message": "column \"createdat\" of relation \"t_ac2mdgfvzvz\" does not exist",
  "stack": "Error\n    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/instructions/sql.js:33:20)\n    at async Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:126:13)\n    at async Processor.start (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:102:7)\n    at async WorkflowPlugin.process (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:321:7)\n    at async /app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:305:9"
}{
  "message": "column \"createdat\" of relation \"t_ac2mdgfvzvz\" does not exist",
  "stack": "Error\n    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/instructions/sql.js:33:20)\n    at async Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:126:13)\n    at async Processor.start (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:102:7)\n    at async WorkflowPlugin.process (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:321:7)\n    at async /app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:305:9"
}

<img width="812" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/19d6b39c-1572-4f76-b791-6ea9346b145b">

**Comment by alexkash** [comment]
I changed the script:
BEGIN;
INSERT INTO t_ac2mdgfvzvz (createdAt, updatedAt, f_o69fha3awv5, f_u27l9leqgu7) VALUES (NOW(), NOW(), 25, 169);
COMMIT;

Here's what I got (the process doesn't stop):

<img width="812" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/ae0f9c08-dc32-413f-ba6c-9cbbebd1100f">

**Comment by mytharcher** [comment]
> I changed the script: BEGIN; INSERT INTO t_ac2mdgfvzvz (createdAt, updatedAt, f_o69fha3awv5, f_u27l9leqgu7) VALUES (NOW(), NOW(), 25, 169); COMMIT;

Please make another try without transaction (`BEGIN` and `COMMIT`) statements to see if it works?

**Comment by mytharcher** [comment]
> SQL: INSERT INTO t_ac2mdgfvzvz (createdAt, updatedAt, f_o69fha3awv5, f_u27l9leqgu7) VALUES (NOW(), NOW(), 25, 169)
> 
> Error: { "message": "column "createdat" of relation "t_ac2mdgfvzvz" does not exist", "stack": "Error\n at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async Object.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/instructions/sql.js:33:20)\n at async Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:126:13)\n at async Processor.start (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:102:7)\n at async WorkflowPlugin.process (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:321:7)\n at async /app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:305:9" }{ "message": "column "createdat" of relation "t_ac2mdgfvzvz" does not exist", "stack": "Error\n at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async Object.run (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/instructions/sql.js:33:20)\n at async Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:126:13)\n at async Processor.start (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:102:7)\n at async WorkflowPlugin.process (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:321:7)\n at async /app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:305:9" }

Looks the case of column name is not correct. If you are using PG, you should use double quote for column names (especially when it contains upper case letters), such as `"createdAt"`.

**Comment by alexkash** [comment]
> > I changed the script: BEGIN; INSERT INTO t_ac2mdgfvzvz (createdAt, updatedAt, f_o69fha3awv5, f_u27l9leqgu7) VALUES (NOW(), NOW(), 25, 169); COMMIT;
> 
> Please make another try without transaction (`BEGIN` and `COMMIT`) statements to see if it works?
I tried it this way and replaced variables with constant numbers (int) - it doesn't work

**Comment by alexkash** [comment]
> Seems the case of column name is not correct. If you are using PG, you should use double quote for column names (especially when it contains upper case letters), such as `"createdAt"`.

Thank you! The double quotes worked. I was misled when I executed the script directly into the database and it worked without the quotes.
