### ISSUE TITLE
Contenter alpha 15.2 does not run 

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3035]
I updated my contenter in the doc and now the app won't start. Seems to be something with the translation. We have the interface in Ukrainian.

<img width="591" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/5a760b0d-dfb0-4663-be60-8044920f5e42">
<img width="727" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/47c5b3af-04c5-4050-aed5-5448d702260d">

**Comment by chenos** [comment]
How was it upgraded?
https://docs.nocobase.com/welcome/getting-started/upgrading

**Comment by alexkash** [comment]
Thanks for the quick reply, yes that's exactly what we did

**Comment by chenos** [comment]
What version did you upgrade from?
What are the upgrade steps?

**Comment by alexkash** [comment]
14.8 -> 15.2
We do everything as in these instructions, we have been doing this since alpha 10 and it has worked before

**Comment by dream2023** [comment]
![image](https://github.com/nocobase/nocobase/assets/19297757/f192363e-44fe-460e-990a-bc87a3eed561)

@alexkash 

What method did you use to upgrade?

**Comment by chenos** [comment]
@alexkash Try disabling the localization management plugin before upgrading?

**Comment by alexkash** [comment]
I tried it locally and it worked for me, then I did it on the server and it worked fine the second time. So that closes the question. Thank you!
