### ISSUE TITLE
Errors when loading some forms

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3080]
When I open forms in drawers in the console I get errors
<img width="467" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/fc6d24e8-e37a-4865-a53b-38f13d45b9d6">

<img width="529" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/6239f83f-e7cc-4609-b905-b3c7e24cd638">

also in the console there is this error:
<img width="1659" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/0de65b98-914c-47bf-bf58-8e102350762a">

Version 0.16.0-alpha.3.20231122125160
Docker

**Comment by ugurtam** [comment]
Yes, and calculations don't work anymore, in previous version I had no problems

**Comment by zhangzhonghe** [comment]
@itachiemashita89 Hi, could you provide a simple step by step reproduction?

**Comment by itachiemashita89** [comment]
Hi,
This a sample for related to the set rules.
Once user try to select, page will unresponsive.
Other example is the redirect a sub from like "edit" and go to another sub-form edit page also same issue.
All this is work find before update the latest version this week.
I believe have a bug in latest version.
Thanks.

![Screenshot 2023-11-27 164833](https://github.com/nocobase/nocobase/assets/91925990/efb023ba-8e7c-4a5b-b5b4-4e16c4d46c30)

![image](https://github.com/nocobase/nocobase/assets/91925990/04bf7785-3ede-4e84-843b-650cf262693c)

**Comment by zhangzhonghe** [comment]
@itachiemashita89  This has been fixed in the latest version.

**Comment by itachiemashita89** [comment]
@zhangzhonghe  great 👍, after update this issue solved. Thank you so much 😍
