### ISSUE TITLE
bug:[workflow] 嵌套条件判断 会跳过流程

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3082]
## Screenshots
![image](https://github.com/nocobase/nocobase/assets/900786/59455155-752b-4896-b4fd-6ae745743c79)

![image](https://github.com/nocobase/nocobase/assets/900786/dbeed589-d1eb-4615-b4b2-bfa25d3017ca)

**Comment by mytharcher** [comment]
<img width="600" alt="image" src="https://github.com/nocobase/nocobase/assets/525658/a93b28f0-7a3d-4672-ab60-b96691a4d8d2">

我这边尝试未能复现，能提供一个稳定复现的配置么？并需要提供当前版本信息。

**Comment by baiheinet** [comment]
不好意思 我复现不出来了
我删除重新建 就好了
![image](https://github.com/nocobase/nocobase/assets/900786/0ab684ab-87bc-4ed2-95f5-8be43ea9b9a8)

**Comment by baiheinet** [comment]
我只是改了一下http的请求地址，bug就出现了，别的啥都没干
![image](https://github.com/nocobase/nocobase/assets/900786/71669c9a-7831-4a54-a78e-b1e0433a678b)

**Comment by mytharcher** [comment]
看起来请求节点的关系比较大，跟请求响应的时间有关系么？

**Comment by baiheinet** [comment]
没关系 你改一下试试 别的不要动

**Comment by baiheinet** [comment]
系统外 https://open.feishu.cn/open-apis/bot/v2/hook

**Comment by mytharcher** [comment]
@baiheinet 找到问题并且已经修复了，可以更新 main 再看看。
