### ISSUE TITLE
配置完文件管理器后可以看到文件上到oss了，但是网页请求的文件仍然是基础存储的路径

### ISSUE THREAD

**Issue by MarshallEriksen-shaomingyang** [nocobase/nocobase#3086]
## Describe the bug

配置完文件管理器后可以看到文件上到oss了，但是网页请求的文件仍然是基础存储的路径

## Version

[v0.16.0-alpha.1](https://github.com/nocobase/nocobase/compare/v0.15.0-alpha.4...v0.16.0-alpha.1)

![image](https://github.com/nocobase/nocobase/assets/59674455/89d09088-ba45-4c2b-924f-60b2fba1022d)
![image](https://github.com/nocobase/nocobase/assets/59674455/7a7f17c4-7f7a-466b-a30c-d86de7ec2934)

**Comment by mytharcher** [comment]
OSS 的存储空间是否配置了正确的“访问 URL 基础”选项？如下：

<img width="393" alt="image" src="https://github.com/nocobase/nocobase/assets/525658/d59642ab-a181-44d8-9840-6b7bfea0d335">

**Comment by MarshallEriksen-shaomingyang** [comment]
![image](https://github.com/nocobase/nocobase/assets/59674455/906ef7c2-c109-4d83-87f6-7f4706f79c86)
我按照方法配置以后，访问文件的链接仍旧没有变化，而且我也清理了缓存暂时还不清楚哪里配置出错了。

**Comment by MarshallEriksen-shaomingyang** [comment]
谢谢 现在文件能正确的上传和显示了，请问有没有计划将oss上传的文件能够用特定的文件夹区分呢，否则所有的文件都在一个文件夹难以维护和管理。

**Comment by mytharcher** [comment]
有这个规划，不过暂时还没安排。
