### ISSUE TITLE
Insert error - Czech chars in single line text 

### ISSUE THREAD

**Issue by cybersmurf** [nocobase/nocobase#3113]
After submit form with czech chars error insert statement on nocobase.host

![image](https://github.com/nocobase/nocobase/assets/3642214/56bc20f3-f591-4637-950a-f52c885bfb8d)

**Comment by hongboji** [comment]
Is it possible to provide a log of errors reported on the backend console?

**Comment by chenos** [comment]
When creating a database, choose an appropriate COLLATE, such as
```sql
CREATE DATABASE `test` COLLATE 'utf8mb4_unicode_ci';
```
