### ISSUE TITLE
docker安装启动时报错

### ISSUE THREAD

**Issue by wulianyougithub** [nocobase/nocobase#3130]
## Describe the bug

docker安装程序启动报：
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
app_1  |  1: 0xb95b60 node::Abort() [node]
app_1  |  2: 0xb95bde  [node]
app_1  |  3: 0xc0447e  [node]
app_1  |  4: 0xc04561 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
app_1  |  5: 0xb50e03 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
app_1  |  6: 0xb5145b node::Start(int, char**) [node]
app_1  |  7: 0x7faf4d5061ca  [/lib/x86_64-linux-gnu/libc.so.6]
app_1  |  8: 0x7faf4d506285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
app_1  |  9: 0xacfdce _start [node]
app_1  | node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

## Version

最新版本

## How To Reproduce

1. 下载文档中的git clone https://gitee.com/nocobase/nocobase.git nocobase这个
2. 到nocobase/app-postgres下配置数据库
3. docker-compose up -d
4. app镜像没有启动成功，查看日志docker-compose logs app有如何下报错
node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
app_1  |  1: 0xb95b60 node::Abort() [node]
app_1  |  2: 0xb95bde  [node]
app_1  |  3: 0xc0447e  [node]
app_1  |  4: 0xc04561 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
app_1  |  5: 0xb50e03 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
app_1  |  6: 0xb5145b node::Start(int, char**) [node]
app_1  |  7: 0x7faf4d5061ca  [/lib/x86_64-linux-gnu/libc.so.6]
app_1  |  8: 0x7faf4d506285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
app_1  |  9: 0xacfdce _start [node]
app_1  | node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
尝试使用以下命令
git clone https://gitee.com/nocobase/nocobase.git nocobase
cd nocobase/docker/app-postgres
docker-compose pull
docker-compose up -d

**Comment by chenos** [comment]
```diff
version: "3"
networks:
  nocobase:
    driver: bridge
services:
  app:
-   image: nocobase/nocobase:main
+   image: nocobase/nocobase:latest
```

镜像换成 latest 的试试

**Comment by wulianyougithub** [comment]
> ```diff
> version: "3"
> networks:
>   nocobase:
>     driver: bridge
> services:
>   app:
> -   image: nocobase/nocobase:main
> +   image: nocobase/nocobase:latest
> ```
> 
> 镜像换成 latest 的试试

换成这个镜像，稍微有点问题，启动会报pg这个包没有按装
         throw new Error(`Please install ${moduleName} package manually`);
app_1  |         ^
app_1  | 
app_1  | Error: Please install pg package manually
app_1  |     at ConnectionManager._loadDialectModule (/nocobase/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81:15)
app_1  |     at new ConnectionManager (/nocobase/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:18:24)
app_1  |     at new PostgresDialect (/nocobase/app/node_modules/sequelize/lib/dialects/postgres/index.js:15:30)
app_1  |     at new Sequelize (/nocobase/app/node_modules/sequelize/lib/sequelize.js:340:20)
app_1  |     at new Database (/nocobase/app/node_modules/@nocobase/database/lib/database.js:152:22)
app_1  |     at Object.createDatabase (/nocobase/app/node_modules/@nocobase/server/lib/helper.js:76:12)
app_1  |     at new Application (/nocobase/app/node_modules/@nocobase/server/lib/application.js:84:24)
app_1  |     at Object.<anonymous> (/nocobase/app/lib/apis/index.js:10:13)
app_1  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
app_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
app_1  | error Command failed with exit code 1.

**Comment by chenos** [comment]
@wulianyougithub 换成 `nocobase/nocobase:0.16.0-alpha.6` 再试试呢

**Comment by wulianyougithub** [comment]
> nocobase/nocobase:0.16.0-alpha.6

这个版本包的问题和先前一样了
app_1  | node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
app_1  |  1: 0xb95b60 node::Abort() [node]
app_1  |  2: 0xb95bde  [node]
app_1  |  3: 0xc0447e  [node]
app_1  |  4: 0xc04561 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
app_1  |  5: 0xb50e03 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
app_1  |  6: 0xb5145b node::Start(int, char**) [node]
app_1  |  7: 0x7fa112e341ca  [/lib/x86_64-linux-gnu/libc.so.6]
app_1  |  8: 0x7fa112e34285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
app_1  |  9: 0xacfdce _start [node]
app_1  | node[1]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.

> 我的docker版本是19.03.12

**Comment by wulianyougithub** [comment]
@chenos 您好，上述问题需要怎么做能解决

**Comment by chenos** [comment]
@wulianyougithub 升级 docker 试试

**Comment by wulianyougithub** [comment]
打包镜像时，dockerfile 中node基础镜像选择node:18.16-bullseye-slim这个版本
`FROM node:18.16-bullseye-slim as builder

WORKDIR /app

RUN cd /app \
  && yarn config set network-timeout 600000 -g \
  && yarn config set registry https://registry.npm.taobao.org \
  && yarn create nocobase-app my-nocobase-app -a -e APP_ENV=production \
  && cd /app/my-nocobase-app \
  && yarn install --production

RUN cd /app \
  && rm -rf nocobase.tar.gz \
  && tar -zcf ./nocobase.tar.gz -C /app/my-nocobase-app .

FROM node:18.16-bullseye-slim
...
`

**Comment by chenos** [comment]
@wulianyougithub 最新版再试试呢
