### ISSUE TITLE
bug:workflow 按钮绑定到工作流全部错误

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3132]
## Describe the bug
![image](https://github.com/nocobase/nocobase/assets/900786/b70630f6-e819-4072-a5c9-90b9ebab9130)

TypeError: l.useCollectValuesToSubmit is not a function
at fn (/static/plugins/@nocobase/plugin-workflow/dist/client/index.js?version=0.16.0-alpha.6:400:6561)

## Version

version=0.16.0-alpha.6

**Comment by hongboji** [comment]
是采用什么方式部署，什么类型的数据库  启动命令是什么？
