### ISSUE TITLE
关系区块：关联数据的API是通过associationIndex 获取，如果关联字段不是ID，就会引起错误

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3142]
### Discussed in https://github.com/nocobase/nocobase/discussions/3138

<div type='discussions-op-text'>

<sup>Originally posted by **baiheinet** December  5, 2023</sup>

注意这里有个前提二层关联了

雇员关联流水 流水关联子记录

举个例子。

![image](https://github.com/nocobase/nocobase/assets/900786/f256c348-b4a3-4a22-b8e6-18614c5702cc)

![image](https://github.com/nocobase/nocobase/assets/900786/a275c0f3-f760-4d49-a0d1-ffb181b6552c)
/api/records/10028/children:lis
![image](https://github.com/nocobase/nocobase/assets/900786/5789cf4e-a58a-4b40-8d33-025cba725791)
根本获取不了数据，10028不是associationIndex 而是personUuid</div>

**Comment by hongboji** [comment]
详细说明下 雇员关联流水 流水关联子记录的关系字段类型 ，可以数据表关系字段截图看看，哪个表的什么区块 进入 ，创建什么区块，看不见什么数据 ， 整个流程可以详细说明可以截图
