### ISSUE TITLE
Mobile client height is wrong now.

### ISSUE THREAD

**Issue by sealday** [nocobase/nocobase#3152]
![WX20231207-001835@2x](https://github.com/nocobase/nocobase/assets/4080924/77434581-983e-4686-ade8-4b0b7c5de5ff)
![WX20231207-002021@2x](https://github.com/nocobase/nocobase/assets/4080924/fbd4c739-8ece-4784-9749-f43a3d3e57c9)

It added an App component without 'height: 100%', causing incorrect display on the mobile client

<img width="829" alt="image" src="https://github.com/nocobase/nocobase/assets/4080924/4d24ff02-c318-4eab-80ff-10a7eb68c143">

commitid: e418d31eb8861ff00d518669451df2ef2883c30f

**Comment by Dunqing** [comment]
I'll take a look at this

**Comment by sealday** [comment]
Click "open in new tab", then you will see it.

**Comment by mysongce** [comment]
Is there currently a solution for this?

**Comment by Dunqing** [comment]
We're working on it.
