### ISSUE TITLE
Can't update to version 0.17 alpha 3. 

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3153]
I did a base update (yarn nocobase upgrade), the result is that I could not start the application.
<img width="496" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/03f9a85b-3419-449f-984f-b91d44f53b08">
[migration_error.log](https://github.com/nocobase/nocobase/files/13588670/migration_error.log)

**Comment by hongboji** [comment]
https://docs.nocobase.com/breaking-changes/v0-17-0-alpha-1

**Comment by hongboji** [comment]
There are some incompatible changes, take a look at the documents
