### ISSUE TITLE
Exception in adding nested one-to-many relationship item.

### ISSUE THREAD

**Issue by sealday** [nocobase/nocobase#3160]
https://github.com/nocobase/nocobase/assets/4080924/022f9ca4-f2cc-4f03-9b9e-59f946bd4b6d

[nocobase.sqlite.zip](https://github.com/nocobase/nocobase/files/13598789/nocobase.sqlite.zip)

nocobase version: Version 0.17.0-alpha.3.20231207060930

**Comment by hongboji** [comment]
A bug related to this has recently been fixed and can be verified with the latest release

**Comment by sealday** [comment]
I try the latest release Version 0.19.0-alpha.3.20240118111139, not fixed yet

**Comment by hongboji** [comment]
Please use the latest code to check if it is resolved
