### ISSUE TITLE
 an error of the application display

### ISSUE THREAD

**Issue by jor2003** [nocobase/nocobase#3188]
## Describe the bug

The nocobase service is deployed by git code.
After upgrading and restarting the service, the application shows that it does not exist.
Only the application can be deleted, a new application with the same name were created, and when viewed again, the original data will be displayed and read.

How to avoid this situation?
Or, is there a way to upgrade main services on the web interface?

**Comment by hongboji** [comment]
I am a little confused.
Would it be possible to follow the feedback question template to provide more information in order to locate the problem, please.
