### ISSUE TITLE
The Form event gets in the queue and does not go any further

### ISSUE THREAD

**Issue by AnryHedgehog** [nocobase/nocobase#3221]
## Describe the bug

The Form event gets in the queue and does not go any further. I use forum events in my collections, before that there is a collection event that binds the users' full names to the application, and after that there is a Form event using the full name from the result. After launching, the Form event goes into the queue and does not go further, although there are no errors

## Version

Version 0.14.0-alpha.7.20231016070438

## How To Reproduce

1. Go to 'create a Form event and assign a workflow to the button'
2. Click on 'click on the button linked to Form event'
3. Scroll down to 'go to process view and process history'

## Expected behavior

On the other collection, everything is also configured and works without problems, from and to

## Screenshots

Problem

![image](https://github.com/nocobase/nocobase/assets/146196537/9db82fd4-5161-4ba0-9104-12f5fc807268)

No problem

![image](https://github.com/nocobase/nocobase/assets/146196537/352b316a-497a-47cc-809e-b5f9d5b188c6)

## Desktop (please complete the following information)

- OS: [Windows 10 Pro]
- Browser [Chrome. Yandex]

**Comment by mytharcher** [comment]
Could you help to provide some of your workflow and app logs on that time?

* Workflow logs location: `storage/logs/workflows/<date>/<id>.log`
* App logs location: `storage/logs/<date-hour>.log`

And I have noticed your NocoBase version may be a little legacy, could you upgrade to latest (0.17+) to do another try?

**Comment by AnryHedgehog** [comment]
Hello, there is no possibility of updating yet, we are carrying out technical work 

Here are the requested files

1 
[117.log](https://github.com/nocobase/nocobase/files/13713566/117.log)

[116.log](https://github.com/nocobase/nocobase/files/13713563/116.log)

2

[nocobase-2023-12-15-14.log](https://github.com/nocobase/nocobase/files/13713570/nocobase-2023-12-15-14.log)

**Comment by AnryHedgehog** [comment]
All processes with buttons are frozen

**Comment by mytharcher** [comment]
I have checked your log files, seems nothing abnormal.

There may be a few fixes for triggering workflow in newer versions. Could you just make another test app (on latest version) with your legacy data copy, to try to see if this still happens?

**Comment by AnryHedgehog** [comment]
We're doing this now, when we're done, I'll unsubscribe

**Comment by AnryHedgehog** [comment]
Cannot read properties of undefined (reading 'items')

What is this error

**Comment by AnryHedgehog** [comment]
![image](https://github.com/nocobase/nocobase/assets/146196537/96492e6b-dc3f-4ecd-93fe-212821842cc8)

I've lost something that used to work.

**Comment by mytharcher** [comment]
> Cannot read properties of undefined (reading 'items')
> 
> What is this error

Please be more specific. Like where you met the error, and what steps you did?

**Comment by AnryHedgehog** [comment]
when transferring the database dump along with the workflows, everything was fine at first, however, as soon as I turned on the triggers on the button, processing problems started, everything just went on hold and after I created a new trigger, it started working fine

a process that worked and stopped
[2.log](https://github.com/nocobase/nocobase/files/13749402/2.log)

one of the processes on the button
[130.log](https://github.com/nocobase/nocobase/files/13749414/130.log)

dispatcher
[dispatcher.log](https://github.com/nocobase/nocobase/files/13749424/dispatcher.log)

and nosobase logs for today

[nocobase-2023-12-22-06.log](https://github.com/nocobase/nocobase/files/13749427/nocobase-2023-12-22-06.log)
[nocobase-2023-12-22-07.log](https://github.com/nocobase/nocobase/files/13749428/nocobase-2023-12-22-07.log)
[nocobase-2023-12-22-05.log](https://github.com/nocobase/nocobase/files/13749429/nocobase-2023-12-22-05.log)

**Comment by AnryHedgehog** [comment]
> > Cannot read properties of undefined (reading 'items')
> > What is this error
> 
> Please be more specific. Like where you met the error, and what steps you did?

the same error occurred when creating a new forum event, immediately went into the queue

**Comment by AnryHedgehog** [comment]
Hello, do I need to drop something else?

**Comment by mytharcher** [comment]
> Hello, do I need to drop something else?

Could you help to make a minimal stable reproduction on our latest version? And export it's database files (sqlite/mysql/pg) here, then I could do some debugging on your scenario.

Form your log files I still can not determine what happened abnormally.

**Comment by AnryHedgehog** [comment]
The workflows are saved there, but the databases have been cleaned
[dumpGITHUB-nocobase-202312251044.zip](https://github.com/nocobase/nocobase/files/13764858/dumpGITHUB-nocobase-202312251044.zip)

**Comment by mytharcher** [comment]
> The workflows are saved there, but the databases have been cleaned [dumpGITHUB-nocobase-202312251044.zip](https://github.com/nocobase/nocobase/files/13764858/dumpGITHUB-nocobase-202312251044.zip) MYSQL

@AnryHedgehog Thank for your reproduction which helps me found what's wrong inside. And this issue is fixed in #3256, which you could have a try on latest main branch, or wait for building of the docker image.

**Comment by AnryHedgehog** [comment]
Okay, thanks for the help.
