### ISSUE TITLE
Duplicate not work correctly when we set data scope

### ISSUE THREAD

**Issue by sealday** [nocobase/nocobase#3238]
https://github.com/nocobase/nocobase/assets/4080924/cb7ed5e1-3b57-4844-9455-497422b3a8bb

[copy.zip](https://github.com/nocobase/nocobase/files/13725271/copy.zip)

nocobase version: Version 0.17.0-alpha.7.20231220060533

**Comment by sealday** [comment]
Without a specified data scope, it functions as expected. However, upon setting the data scope, it malfunctions.

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3239
