### ISSUE TITLE
yarn start 报错

### ISSUE THREAD

**Issue by GavinHome** [nocobase/nocobase#324]
![image](https://user-images.githubusercontent.com/5460850/165240156-6fa59b11-aa9d-4323-a387-aef93e75b907.png)

**Comment by chenos** [comment]
看错误信息是 mysql 连接有问题，检查一下 .env 里，DB 相关信息是不是填正确了。

**Comment by GavinHome** [comment]
@chenos 用命令创建指定DB_HOST为ip，会把ip拼接两遍，比如192.168.0.1，.env里就变成了192.168.0.1.168.0.1

**Comment by GavinHome** [comment]
@chenos 数据库需要提前创建吗？有没有编码要求？
![image](https://user-images.githubusercontent.com/5460850/165454794-ffa70485-0fc7-4ae8-ad73-5d7d31999ced.png)

**Comment by chenos** [comment]
最新版已修复，需要先安装并启动数据库。文档更新了 Docker 的安装教程，如果命令安装的问题较多，可以试一试 Docker 的。
https://github.com/nocobase/nocobase#create-a-project-with-docker-recommended

**Comment by GavinHome** [comment]
@chenos 可以启动了
