### ISSUE TITLE
Collection not visible when created without automatic ID

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#3240]
## Describe the bug

If I create a new collection and de select that ID should be created automatically. The Collection is not visible when I try to create a form or a table block for it.
## Version

Version 0.16.0 aplha 6

## How To Reproduce

Create a new colelction, de select that ID should be created automaticaly
Try to add a table block based on that collection

## Expected behavior
The collection will not be visible to select

## Desktop (please complete the following information)

Windows 10
Both Chrome and Firefox tested

**Comment by hongboji** [comment]
Currently add table block, collection must have ID
