### ISSUE TITLE
给角色配置数据表操作权限数据显示不正确

### ISSUE THREAD

**Issue by guanzhao** [nocobase/nocobase#3284]
## Describe the bug

角色添加数据表自定义限制不起作用
## Version
v0.18.0-alpha.4

## How To Reproduce

1. 用户表添加 一对一（has one）旅行社字段
2. 团长表添加 一对一（has one）旅行社字段
3. 添加旅行社角色配置角色数据表操作权限，配置自定义设置,添加条件,旅行社ID = 当前用户所属旅行社ID 不起作用,使用对应用户登录列表显示空白
4. 单独在列表中做相同的设置也不行 

希望设置完成,用户登录之后,看到相同旅行社的团长数据

![image](https://github.com/nocobase/nocobase/assets/4636457/e3693e7c-1857-471a-84cc-7de573eb55b8)

![image](https://github.com/nocobase/nocobase/assets/4636457/b572c4f4-ca8f-4270-a1ab-38dcae5c32c3)

![image](https://github.com/nocobase/nocobase/assets/4636457/026f8b2c-4492-4ba5-be00-1f193b054385)

**Comment by hongboji** [comment]
用户设置旅行社/团长设置旅行社的数据截图看看 ，数据显示不正确的页面截图看看，如果未设置也截图看看 可以做个对比

**Comment by guanzhao** [comment]
![image](https://github.com/nocobase/nocobase/assets/4636457/5b389461-8711-4ff5-8ff5-9045fa240f78)
![image](https://github.com/nocobase/nocobase/assets/4636457/7d2ae04f-d1b1-47f0-b761-f93dd5074721)
![image](https://github.com/nocobase/nocobase/assets/4636457/fe048538-7a59-4095-8b31-38f48d04c589)

**Comment by hongboji** [comment]
从截图上看  百里柳江的用户无数据 ，用户表未看见百里柳江的旅行社设置 截图不全
