### ISSUE TITLE
Bug Report - Issue with Selecting Province and District in Edit Operation

### ISSUE THREAD

**Issue by qui101672** [nocobase/nocobase#3286]
Description:
I am currently encountering an issue related to selecting province and district on a form. During the data addition process, the system functions as expected: when I select a province, the system automatically filters the list of districts accordingly.

However, when performing the data editing operation, I have identified a bug. When I reselect the province, the value of the district is not cleared, and it retains the previous district value that was assigned. This poses a serious problem during data saving, as the district data does not correspond to the newly selected province.

Steps to Reproduce:

Open the data editing form.
Select a different province from the province list.
Observe the district value; it is not cleared and retains the previous district value.
Expectation:
When I reselect the province in the data editing operation, the district value should be reset or cleared to ensure consistency between the selected province and district.
Thank you for your attention to this matter. We look forward to your prompt assistance in resolving this issue.

Attach file
https://github.com/nocobase/nocobase/assets/1473341/df8d362d-9793-4e3c-a4cf-572929ca31a9

**Comment by hongboji** [comment]
Can you take a screenshot to see how it's set up, is it using a data range filter?
Data range filtering does not exclude existing data, it is recommended to use a tree table to store data for provincial and regional linkage, and a relational field linkage component for forms.
