### ISSUE TITLE
docker liunx mysql error, Cannot read properties of undefined (reading 'field')

### ISSUE THREAD

**Issue by listener-He** [nocobase/nocobase#3312]
## Describe the bug

  数据库连接成功 访问页面时报错 You're offline
Please check the server status or network connection status

 查看日志发现提示 Cannot read properties of undefined (reading 'field')

## Version

 最新的main版本

## How To Reproduce

docker mysql 安装

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
是一个新环境部署还是升级nocobase ?

**Comment by listener-He** [comment]
新环境部署，我试着用sqlite启动就正常了，切换到mysql又不行。 我猜是不是mysql的版本问题？

**Comment by AnryHedgehog** [comment]
I found the same problem, but I managed to install it yesterday, but I didn't want to dump the database.

**Comment by AnryHedgehog** [comment]
I tried to install nosobase as an application and still the same error

**Comment by chareice** [comment]
You can try again with the latest version, and if there are any issues, please open a new issue.
