### ISSUE TITLE
Error: listen ENOTSUP: operation not supported on socket

### ISSUE THREAD

**Issue by nicky132** [nocobase/nocobase#3314]
## Describe the bug

![1704274365567_23E6B9A4-BF55-457a-BD77-2EBE6F95C9AC](https://github.com/nocobase/nocobase/assets/34881461/cdb6a3c2-ca2f-445a-8626-a9f76eb7529f)

## Version

1. git clone https://github.com/nocobase/nocobase.git my-nocobase-app
2. cd my-nocobase-app
3. yarn install
4. yarn nocobase install --lang=zh-CN
5. yarn dev

## Expected behavior

希望能不要报错，正常跑起来

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

## Smartphone (please complete the following information)

- Device: [win11]
- OS: [wsl,Centos7]
- Browser [chrome]
- Version [120.0.6099.130]

**Comment by chenos** [comment]
大概率是因为storage目录没有写的权限
