### ISSUE TITLE
自动编码字段BUG

### ISSUE THREAD

**Issue by jor2003** [nocobase/nocobase#3317]
## Describe the bug

创建新表，新增 “自动编码”字段，在设置固定文本、自增数字，点击配置时，配置字段没有显示在弹框的最上层，而是从浏览器页面开始的第一层开始，且多次点击就多次出现。

## Version
昨天发现，今天更新到 0.18.0-alpha.9，仍旧存在这个问题

## How To Reproduce

1. 创建表 '...'
2. 配置字段 '....'
3. 新增 '自动编码'字段
4. 在规则中选择 “固定文本或自动编号”，点击“设置”
5. 弹出框没有出现在最上层

## Expected behavior

希望弹出框能够在最上层

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/29227168/e99c0e2d-3664-43cc-b5ab-00018750395c)
![image](https://github.com/nocobase/nocobase/assets/29227168/9a96ef54-40c2-4744-a6da-3086b01714c4)
![image](https://github.com/nocobase/nocobase/assets/29227168/ccf81bcd-9fe1-4e8a-8099-8024a4432c34)

## Desktop (please complete the following information)

- OS: windows10 Pro
- Browser ：chrome120

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3313
