### ISSUE TITLE
Localization module error.

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3322]
I have on version 0.18.0-alpha.9 the previously translated names are not working. I have all translations in the module, I have tried Republish and resave each translation and field names, clean cache, restart the application. But no translation is produced. Translation of field names is not loading.

This is a screenshot with translations:
<img width="1383" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/86f874e3-07c5-4ebc-bb33-d7755109e6bb">

Это результат:
<img width="1641" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/eda9c207-fdc0-4064-b571-3799af6ba642">

P.S. >> It would be good to localize Block and Tab names as well

**Comment by Xilesun** [comment]
Hi, alex. Could you please check if the texts are in the correct namespaces? Refer to: https://docs.nocobase.com/breaking-changes/v0-17-0-alpha-3

**Comment by alexkash** [comment]
Hi, Xilesun. Yes, I checked, and the translations are in Collections & Fields (in Ukrainian - "Колекції та поля"). Suppose that's what you mean. I don't have translations for any fields. It used to work, but at some point, it stopped working.
<img width="1434" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/c0ad6ff3-90a3-46b7-b4d5-b36417d94869">

The translations are only for the collections and fields in the JSON translation file.
<img width="1367" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/2d42b24e-cf86-4642-b16e-425d163ba2b6">

I installed locally, a clean database and it doesn't work there either.

I can provide access to the sandbox if you need it.

**Comment by Xilesun** [comment]
@alexkash 
Thanks for your feedback. As I could not reproduce in my environment, it would be helpful that if you could provide a link to an accessible sandbox.

**Comment by alexkash** [comment]
https://demo.recuite.com/
ak@coloris.com.ua
12345678

Do whatever you need to do. This is our experimentation setup.

**Comment by alexkash** [comment]
By the way, can't you do a translation of tab and block titles? :)

**Comment by Xilesun** [comment]
Hi, @alexkash 
I've figured out the issue. You should remove the template syntax like `{{t(\"Vacancies\")}}` and use `Vacancies` directly.
<img width="348" alt="image" src="https://github.com/nocobase/nocobase/assets/3250534/2170cbe3-98fc-4616-9b14-8b6fe1b45bab">
It is no longer necessary for localization.

For tab and block titles, there are many details need to be addressed. We might consider supporting in the future.

**Comment by alexkash** [comment]
太好了 非常感谢！:)

**Comment by alexkash** [comment]
Do you plan to make it possible to translate the names of blocks and tabs?

**Comment by Xilesun** [comment]
> Do you plan to make it possible to translate the names of blocks and tabs?

Possibly in the future, but not in the short term.

**Comment by alexkash** [comment]
Hi Xilesun, I apologize for bothering you again, but I have a question. The header used to translate like the menu, now it doesn't. Is this the way it should be?

<img width="1118" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/23330eec-657c-4cea-8376-aa3b7767473e">

**Comment by Xilesun** [comment]
> Hi Xilesun, I apologize for bothering you again, but I have a question. The header used to translate like the menu, now it doesn't. Is this the way it should be?
> 
> <img alt="image" width="1118" src="https://private-user-images.githubusercontent.com/2558467/298012212-23330eec-657c-4cea-8376-aa3b7767473e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTkyMTQsIm5iZiI6MTcwNTY1ODkxNCwicGF0aCI6Ii8yNTU4NDY3LzI5ODAxMjIxMi0yMzMzMGVlYy02NTdjLTRjZWEtODM3Ni1hYTNiNzc2NzQ3M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMTAwODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNjNDFhMTJkOTQxMjk2OTFmZTRmNDE1NmE5MTdiOTQ4MDMyOTE3NmEzNmJiZGUyYmMwZjZiZDZlY2YwZTA5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jI2fHtoneNMOyDAlICvffdRqEO3YdoTPUCCyq2ePKqQ">

Yep, as the texts of menus were put in namespace `lm-menus` now to prevent unexpected translations. 
Actually, the translation of header was exactly the unexpected translation before.
I understand that the limitations of the localization management plugin might be annoying for you. 
We will explore more suitable solutions. Thanks for your supporting.
