### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by taddeo17** [nocobase/nocobase#3323]
## Describe the bug

After i uploaded an image, when i go to view section, it give me this error.

## Version

0.18.0 alpha 9

## How To Reproduce

1. Create an attachment field and create a record with an image
2. Go to view to see the attachment
3. Voilà

## Screenshots

![Profili Tariffari - FranMent-001](https://github.com/nocobase/nocobase/assets/144064982/31c3950a-fe49-4701-96ea-2bfca06fef34)

## Desktop (please complete the following information)

- OS: Windows Server
- Browser: Chrome

**Comment by hongboji** [comment]
Please update the latest version

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3318
