### ISSUE TITLE
Popovers are showing under the modals they are assigned to

### ISSUE THREAD

**Issue by BeatLink** [nocobase/nocobase#3334]
## Describe the bug

Interface elements opened from a dialog box do not show over them

## Version

nocobase/nocobase:0.17.0-alpha.7 (Docker)

## How To Reproduce

1. Create a menu item
2. Click on Icon
3. See error

## Expected behavior

Interface elements should show over the dialog box and be clickable

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/47278150/c08d0004-7177-41a7-955e-981fe555b4e0)

## Desktop (please complete the following information)

- OS: Linux Mint
- Browser Firefox

**Comment by zhouyanliang** [comment]
Please upgrade to the latest version

**Comment by BeatLink** [comment]
It worked, thanks!
