### ISSUE TITLE
自定义操作是否计划在近期版本发布

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#334]
这是在线演示版本，我看有这方面的规划，自定义操作：

![image](https://user-images.githubusercontent.com/931976/165737183-f31e78a0-a44f-40bf-9f5f-7f4bd02ba36f.png)

不过在当前开发分支 `nocobase-next`，看不到了：

![image](https://user-images.githubusercontent.com/931976/165737419-b956874e-8d6f-4252-921c-87320f74b83b.png)

是否计划在近期版本发布？

**Comment by zhouyanliang** [comment]
已经在准备中，优先级较高

**Comment by MarshalW** [comment]
目前已经能基本实现这个功能（临时性的解决方式）：

![image](https://user-images.githubusercontent.com/931976/167838592-ef40b337-04c0-4a65-8854-affb960e5e09.png)

nocobase 架构的扩展能力还是挺强的，只需要用自己的 TableActionColumnInitializers.tsx，覆盖内置的 `TableActionColumnInitializers`:

```ts
import { MenuOutlined } from "@ant-design/icons";
import { useFieldSchema } from "@formily/react";
import { useTranslation } from "react-i18next";
import {
  createDesignable,
  useDesignable,
  useAPIClient,
  SchemaInitializer,
  useCollection,
  SchemaInitializerItemOptions,
} from "@nocobase/client";

export const TableActionColumnInitializers = (props: any) => {
  const fieldSchema = useFieldSchema();
  const api = useAPIClient();
  const { refresh } = useDesignable();
  const { t } = useTranslation();
  const { name, title } = useCollection();

  const items: SchemaInitializerItemOptions[] = [
    {
      type: "itemGroup",
      title: t("Enable actions"),
      children: [
        {
          type: "item",
          title: t("View"),
          component: "ViewActionInitializer",
          schema: {
            "x-component": "Action.Link",
            "x-action": "view",
            "x-decorator": "ACLActionProvider",
          },
        },
        {
          type: "item",
          title: t("Edit"),
          component: "UpdateActionInitializer",
          schema: {
            "x-component": "Action.Link",
            "x-action": "update",
            "x-decorator": "ACLActionProvider",
          },
        },
        {
          type: "item",
          title: t("Delete"),
          component: "DestroyActionInitializer",
          schema: {
            "x-component": "Action.Link",
            "x-action": "destroy",
            "x-decorator": "ACLActionProvider",
          },
        },
      ],
    },
  ];

  if (name === "products") {
    items.push({
      type: "itemGroup",
      title: t("自定义"),
      children: [
        {
          type: "item",
          title: t("同步"),
          component: "ActionInitializer",
          schema: {
            title: "同步",
            "x-component": "Action.Link",
            "x-action": "product:sync",
            "x-designer": "Action.Designer",
            "x-decorator": "ACLActionProvider",
            "x-component-props": {
              confirm: {
                title: "{{t('同步确认')}}",
                content: "{{t('是否开始同步?')}}",
              },
              useAction: "{{useSubmit}}",
            },
          },
        },
      ],
    });
  }

  return (
    <SchemaInitializer.Button
      insertPosition={"beforeEnd"}
      insert={(schema) => {
        const spaceSchema = fieldSchema.reduceProperties((buf, schema) => {
          if (schema["x-component"] === "Space") {
            return schema;
          }
          return buf;
        }, null);
        if (!spaceSchema) {
          return;
        }
        const dn = createDesignable({
          t,
          api,
          refresh,
          current: spaceSchema,
        });
        dn.loadAPIClientEvents();
        dn.insertBeforeEnd(schema);
      }}
      items={items}
      component={<MenuOutlined style={{ cursor: "pointer" }} />}
    />
  );
};
```

在 index.tsx 引入：

```ts
..
const useSubmit = () => {
  return {
    run() {
      // TODO 自定义 action 的提交处理
    },
  };
};
..

const providers = [
..
  [
    SchemaComponentProvider,
    {
      scope:{useSubmit }, // 引入自定义 action 的提交处理
      components: { Slate, Link, NavLink },
    },
  ],
  // RemoteCollectionManagerProvider,
  [
    SchemaInitializerProvider,
    {
      initializers: {
        MenuItemInitializers,
        TableActionColumnInitializers, // 引入 TableActionColumnInitializers
      },
      components: {
        CustomerBlockInitializer,
        CustomerVideoInitializer
      },
    },
  ],
```

不过后面发现目前还不能通过界面授权一般角色用户使用这个自定义操作（root角色是可以的），见 #372 

还是期待官方的后续实现，😄

**Comment by zhudameng** [comment]
我也在期待这个功能

**Comment by zhudameng** [comment]
> 目前已经能基本实现这个功能（临时性的解决方式）：
> 
> ![image](https://user-images.githubusercontent.com/931976/167838592-ef40b337-04c0-4a65-8854-affb960e5e09.png)
> 
> nocobase 架构的扩展能力还是挺强的，只需要用自己的 TableActionColumnInitializers.tsx，覆盖内置的 `TableActionColumnInitializers`:
> 
> ```ts
> import { MenuOutlined } from "@ant-design/icons";
> import { useFieldSchema } from "@formily/react";
> import { useTranslation } from "react-i18next";
> import {
>   createDesignable,
>   useDesignable,
>   useAPIClient,
>   SchemaInitializer,
>   useCollection,
>   SchemaInitializerItemOptions,
> } from "@nocobase/client";
> 
> export const TableActionColumnInitializers = (props: any) => {
>   const fieldSchema = useFieldSchema();
>   const api = useAPIClient();
>   const { refresh } = useDesignable();
>   const { t } = useTranslation();
>   const { name, title } = useCollection();
> 
>   const items: SchemaInitializerItemOptions[] = [
>     {
>       type: "itemGroup",
>       title: t("Enable actions"),
>       children: [
>         {
>           type: "item",
>           title: t("View"),
>           component: "ViewActionInitializer",
>           schema: {
>             "x-component": "Action.Link",
>             "x-action": "view",
>             "x-decorator": "ACLActionProvider",
>           },
>         },
>         {
>           type: "item",
>           title: t("Edit"),
>           component: "UpdateActionInitializer",
>           schema: {
>             "x-component": "Action.Link",
>             "x-action": "update",
>             "x-decorator": "ACLActionProvider",
>           },
>         },
>         {
>           type: "item",
>           title: t("Delete"),
>           component: "DestroyActionInitializer",
>           schema: {
>             "x-component": "Action.Link",
>             "x-action": "destroy",
>             "x-decorator": "ACLActionProvider",
>           },
>         },
>       ],
>     },
>   ];
> 
>   if (name === "products") {
>     items.push({
>       type: "itemGroup",
>       title: t("自定义"),
>       children: [
>         {
>           type: "item",
>           title: t("同步"),
>           component: "ActionInitializer",
>           schema: {
>             title: "同步",
>             "x-component": "Action.Link",
>             "x-action": "product:sync",
>             "x-designer": "Action.Designer",
>             "x-decorator": "ACLActionProvider",
>             "x-component-props": {
>               confirm: {
>                 title: "{{t('同步确认')}}",
>                 content: "{{t('是否开始同步?')}}",
>               },
>               useAction: "{{useSubmit}}",
>             },
>           },
>         },
>       ],
>     });
>   }
> 
>   return (
>     <SchemaInitializer.Button
>       insertPosition={"beforeEnd"}
>       insert={(schema) => {
>         const spaceSchema = fieldSchema.reduceProperties((buf, schema) => {
>           if (schema["x-component"] === "Space") {
>             return schema;
>           }
>           return buf;
>         }, null);
>         if (!spaceSchema) {
>           return;
>         }
>         const dn = createDesignable({
>           t,
>           api,
>           refresh,
>           current: spaceSchema,
>         });
>         dn.loadAPIClientEvents();
>         dn.insertBeforeEnd(schema);
>       }}
>       items={items}
>       component={<MenuOutlined style={{ cursor: "pointer" }} />}
>     />
>   );
> };
> ```
> 
> 在 index.tsx 引入：
> 
> ```ts
> ..
> const useSubmit = () => {
>   return {
>     run() {
>       // TODO 自定义 action 的提交处理
>     },
>   };
> };
> ..
> 
> const providers = [
> ..
>   [
>     SchemaComponentProvider,
>     {
>       scope:{useSubmit }, // 引入自定义 action 的提交处理
>       components: { Slate, Link, NavLink },
>     },
>   ],
>   // RemoteCollectionManagerProvider,
>   [
>     SchemaInitializerProvider,
>     {
>       initializers: {
>         MenuItemInitializers,
>         TableActionColumnInitializers, // 引入 TableActionColumnInitializers
>       },
>       components: {
>         CustomerBlockInitializer,
>         CustomerVideoInitializer
>       },
>     },
>   ],
> ```
> 
> 不过后面发现目前还不能通过界面授权一般角色用户使用这个自定义操作（root角色是可以的），见 #372
> 
> 还是期待官方的后续实现，😄

请问index.tsx指的是哪个目录下的

**Comment by MarshalW** [comment]
@[zhudameng](https://github.com/zhudameng)

抱歉今天才看到，就是 `./packages/app/client/src/pages/index.tsx`

如果你只是简单的自定义action，目前版本已经实现了。

我需要能和第三方api交互的，还需要类似这样的处理。

**Comment by zhouyanliang** [comment]
目前已支持“打开弹窗”和“保存数据”两种自定义操作。近期会支持 请求 API 的操作，后续也会有触发工作流。

**Comment by MarshalW** [comment]
那太好了，我就不自行处理了。😄
