### ISSUE TITLE
Tables cannot be sorted by association fields

### ISSUE THREAD

**Issue by BeatLink** [nocobase/nocobase#3344]
## Describe the bug

When a table view is created for a collection that has association fields, when showing fields those fields in the table, there are no options for them to be sorted

## Version

Version 0.18.0-alpha.9.20240107115255

## How To Reproduce

1. Create a collection ("Collection A") with an association field to another collection ("Collection B")
2. Create a table view for Collection A
3. Under Configure Columns, enable the association field for Collection B
4. Click on the column settings for the association field
5. Note that there is no "Sortable" switch to sort the column

## Expected behavior

There should be a sortable switch to sort the column

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
This is not a bug and is not currently supported
