### ISSUE TITLE
0.18 升级 0.19 报错

### ISSUE THREAD

**Issue by guanzhao** [nocobase/nocobase#3347]
0.18 升级 0.19 执行  yarn nocobase upgrade
报错

![image](https://github.com/nocobase/nocobase/assets/4636457/ee8f2273-7d11-46f8-aa0a-4284bbb1ab48)

**Comment by jor2003** [comment]
我刚刚也遇到这个了，
重新git pull一下代码，顺便做个yarn clean，再做upgrade就好了。

**Comment by guanzhao** [comment]
我全过程测试了 好多遍还是这个

**Comment by guanzhao** [comment]
代码全部删除在拉取好了~
