### ISSUE TITLE
批量更新缺少zh-cn

### ISSUE THREAD

**Issue by jor2003** [nocobase/nocobase#3348]
## Describe the bug

中文环境下，“批量更新” 按钮显示的是英文

如下图：

## Version

Version 0.19.0-alpha.2

## How To Reproduce

界面配置--配置操作--自定义--批量更新

## Desktop (please complete the following information)

- OS: [e.g. iOS] windows10
- Browser [e.g. chrome v102, safari] chrome

**Comment by jor2003** [comment]
![image](https://github.com/nocobase/nocobase/assets/29227168/a142bab6-72a7-4850-a035-b605435bb339)

**Comment by hongboji** [comment]
已经修复 可以使用最新版
