### ISSUE TITLE
Service characters are displayed in the browser bar

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3361]
It would be good to remove them

<img width="217" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/7348f9bf-80f8-49f0-9561-93573c740b02">

**Comment by Xilesun** [comment]
Hi, alex. What page is it? How the URL look like? Is the title generated automatically or set manually?

**Comment by alexkash** [comment]
I guess I should flag this ticket, it worked. Maybe it was something with the cache. Thanks for the response.
By the way, I have all URLs generated automatically (e.g. http://localhost:13000/admin/cs96i11kelv). Is there any possibility of giving them normal names, I didn't find how to do it.

**Comment by Xilesun** [comment]
URL customization is currently not supported.
