### ISSUE TITLE
Error in displaying an associated field from a tree collection in a form

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3374]
You cannot disable the creation of new entities in a field form from a collection tree. The Allow Multiple switch does not work either. I don't want to be able to create new entities, only selections.

![2024-01-11_12-15-37 (1)](https://github.com/nocobase/nocobase/assets/2558467/cc1b1c4e-1bcc-4fb0-826c-7184c86b03ab)

**Comment by hongboji** [comment]
This is not a bug, this is how Cascade Select is used.
