### ISSUE TITLE
Any type of Custom Request button does not work

### ISSUE THREAD

**Issue by jfelipesjc** [nocobase/nocobase#3375]
## Describe the bug

Any type of Custom Request button does not work if you do not have UI Editor permission

## Version

Version 0.19.0-alpha.3

## How To Reproduce

1. Go to 'Any user who does not have permission to edit the layout (UI editor)'
2. Click on 'tries to click a custom request button'
3. See error

https://github.com/nocobase/nocobase/assets/60535792/b4bae395-67cf-42b7-9ab8-92e5575defd0

## Desktop (please complete the following information)

- OS: Windows 10
- Browser Chrome

## Additional context

I noticed that only roles that have loyout editing permission provide activating this mentioned button

PS: (I apologize if there are spelling errors, as I am using Google Translate from Portuguese to English)

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3306
