### ISSUE TITLE
The "Contains" filter is not working correctly

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3376]
It used to be possible to search by word part in a text field. Now when I enter a part of a word, it doesn't filter. Now it works like "is" - only a full match is possible

![2024-01-11_16-51-17 (1)](https://github.com/nocobase/nocobase/assets/2558467/c4a9159c-535d-4658-9b81-0101a9a5500e)

**Comment by hongboji** [comment]
Operators depending on field configuration
![image](https://github.com/nocobase/nocobase/assets/116709317/786529a5-0fc7-440e-a61d-c1f8a021a254)

**Comment by alexkash** [comment]
I need Contains and to be able to search by word part. I have it set up that way now, but it doesn't search by word part, only by whole word. Now "contains" works like "is"

**Comment by alexkash** [comment]
![2024-01-11_18-34-30 (2)](https://github.com/nocobase/nocobase/assets/2558467/56f94015-73f8-49e6-a9cd-0c9b5010b32a)
