### ISSUE TITLE
moving fields in a form does not work correctly

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3377]
When I want to put the fields next to each other, it doesn't work
![2024-01-11_18-34-30 (1)](https://github.com/nocobase/nocobase/assets/2558467/040c22c2-9919-459a-94fa-521be55d6e69)

**Comment by hongboji** [comment]
Component drag-and-drop layouts generate groupings, which can be ungrouped with the

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/assets/116709317/ba01d799-380b-402e-833b-9c5998811d5c
