### ISSUE TITLE
系统设置中未有数据库备份和恢复的功能

### ISSUE THREAD

**Issue by recallDel** [nocobase/nocobase#3378]
文档有介绍目前是还未更新到新版本还是显示存在的 bug
![image](https://github.com/nocobase/nocobase/assets/1772343/29431cd3-f823-4681-8d32-2109bcfa9865)

**Comment by hongboji** [comment]
版本号是多少 需要更新到最新版

**Comment by chenos** [comment]
需要点击「+ New backup」进行备份，具体参考文档
https://docs-cn.nocobase.com/plugins/backup-restore

**Comment by recallDel** [comment]
> 版本号是多少 需要更新到最新版
版本号是Version 0.18.0-alpha.9
<img width="971" alt="image" src="https://github.com/nocobase/nocobase/assets/1772343/72fc6bcb-f8e1-40db-9864-9072793778f5">

**Comment by hongboji** [comment]
更新到最新版
