### ISSUE TITLE
The "Contains" filter is not working correctly - 2

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3385]
The "Contains" filter is not working correctly
It used to be possible to search by word part in a text field. Now when I enter a part of a word, it doesn't filter. Now it works like "is" - only a full match is possible

https://github.com/nocobase/nocobase/assets/2558467/c8d4e8df-3836-4cfb-8d1a-88b6e137c85e

<img width="709" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/2599d159-ad50-494d-b4ad-708645ab0006">

**Comment by hongboji** [comment]
Validated to filter data correctly, you can eliminate interference, recreate it as well, use a field alone to see if there is a problem

**Comment by alexkash** [comment]
Hi hongboji! Yes, if you leave only one field, it works. Why can this be, what did I do wrong?

**Comment by hongboji** [comment]
It's possible that the problem is not caused by the feedback field, but by some other setting, which I can't tell based on the current information.

**Comment by alexkash** [comment]
I removed the current filter block, it didn't work even if I changed all the fields. Then I created a new one and it works there. But if I add some fields, it stops working. So far I have made the minimum number of fields and it works. If you need any additional information - tell me, I will provide it. If you need - I can provide access to my sandbox.

**Comment by hongboji** [comment]
After clicking Filter, provide the request information from network in the Browser Development Tools.

**Comment by alexkash** [comment]
<img width="1679" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/d9a0b9c7-6e89-41b8-b60f-ec4046b63aea">
<img width="1663" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/65a27c46-fbf3-4538-9bd0-bf7e531110c4">
<img width="1661" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/a98cb215-77bf-4c6b-a0f5-7ef4b2382b44">

**Comment by alexkash** [comment]
Is that what you need?

**Comment by hongboji** [comment]
Something like this :
https://github.com/nocobase/nocobase/assets/116709317/d8bb95e9-4bc6-4f7b-9be2-726175affafd

**Comment by hongboji** [comment]
Something like this :
https://github.com/nocobase/nocobase/assets/116709317/910e5305-0c00-4811-9f85-16c6fff6b1bd
