### ISSUE TITLE
Incorrect display of data in Statistics. 

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3391]
After running the query the result is displayed - 2, on the chart - 0

<img width="1379" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/25592127-5e41-497e-84b8-9dd51a53125c">

<img width="1124" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/3e240624-1b08-4aef-b450-2785b87ceee1">

**Comment by Xilesun** [comment]
#3798
