### ISSUE TITLE
No permissions showed when logging in

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#3413]
## Describe the bug

When I go to the loginpage I always get the notice "No permissions" up in the left corner, before I have had the posibility to enter any cerdentials. Everything works as it should, but the message can confuse user.

## Version

0.16.0 Alpha 6
## How To Reproduce

Go to the loginpage without being loged in in the browser

I use the url: https://app.tjanstekollen.se/signin?redirect=/admin

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/89129225/b5a83d00-cf1d-4f33-9ce1-d8ac0b472091)

## Desktop (please complete the following information)

Windows 10, Chrome Version 120.0.6099.130 (Officiell version) (64 bitar)

**Comment by chareice** [comment]
You can try again with the latest version, and if there are any issues, please open a new issue.
