### ISSUE TITLE
筛选组件bug

### ISSUE THREAD

**Issue by double-liu** [nocobase/nocobase#3414]
Version 0.19.0-alpha.3
<img width="654" alt="image" src="https://github.com/nocobase/nocobase/assets/11608034/61ec2f55-0495-4114-b65f-398c0c4f11ef">
<img width="808" alt="image" src="https://github.com/nocobase/nocobase/assets/11608034/eeb01a77-0fee-4021-996d-671820eb3188">
清空搜索条件后，请求依然有传过去

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3440
