### ISSUE TITLE
docker 部署后 nginx 代理主页几秒后提示就You're offline 

### ISSUE THREAD

**Issue by Cassuis** [nocobase/nocobase#3433]
## Describe the bug

docker 部署后 nginx 代理主页几秒后提示就You're offline  Please check the server status or network connection status

## Version

nocobase/nocobase:main

**Comment by sealday** [comment]
你需要处理一下 WebSocket 的逻辑，可以参考 docker 里面的 nginx 配置，在他们源文件中有，因为他们依赖这个来判断应用是否存活
