### ISSUE TITLE
OIDC plug-in redirecting to 127.0.0.1

### ISSUE THREAD

**Issue by mlh86** [nocobase/nocobase#3434]
We have set up an instance of nocobase at https://nocobase-dev.stratesfy.com and configured the OIDC plug-in for Google sign-in, but the redirect URL the app forwards to accounts.google.com is currently https://127.0.0.1:13001/api/oidc:redirect instead of using the configured domain-name. Is this an env file configuration issue or a functionality bug?

![oidc_redirect_url_issue](https://github.com/nocobase/nocobase/assets/98682530/a622725c-0932-4981-96c8-8520d33e47f8)

![google_oidc_redirect_issue](https://github.com/nocobase/nocobase/assets/98682530/c9477cc3-6a43-41d1-a346-ec2d927c2914)

**Comment by Xilesun** [comment]
Hi, @mlh86 .
What kind of method did you run your NocoBase application? Is in Docker, or using `yarn dev` or `yarn start`?
It seems that the Backend server is running separately from Frontend.

**Comment by mlh86** [comment]
@Xilesun We are currently using yarn dev to run the latest nocobase build from source. Can you suggest what the recommended setup is for enabling OIDC? Will switching to yarn build / yarn start help?

**Comment by Xilesun** [comment]
> @Xilesun We are currently using yarn dev to run the latest nocobase build from source. Can you suggest what the recommended setup is for enabling OIDC? Will switching to yarn build / yarn start help?

We will enhance it to support configuring the service domain if the frontend and backend services run separately. Before that, use `yarn build` and `yarn start` or using Docker image directly could be help.
