### ISSUE TITLE
No account can log in after update to 0.19.0 alpha 4

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#3452]
## Describe the bug

Nocobase was automatically updated to version 0.19.0 alpha 4 and after that none of the users I have in the installation can log in using the credentials assigned. I tried to go back to version 0.19.0 alpha 3, but it still did not work. I tried to use the backup from befor ethe automated version upgrade but that did not work either.

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by chenos** [comment]
Please provide the logs and screenshots.

**Comment by thomaswennersten** [comment]
Ok, I attach screnshot(that does not show anything hence I can not log in) and logs.

![image](https://github.com/nocobase/nocobase/assets/89129225/28d29b4e-259c-4ce1-ac51-796dc358b497)

[nocobase logs.zip](https://github.com/nocobase/nocobase/files/14080423/nocobase.logs.zip)

**Comment by thomaswennersten** [comment]
Hi again, I managed to solve this using a third user with admin rights that I fortunately had created.
