### ISSUE TITLE
Error when saving SQL collection - "uid 'xxxxxxxxxx' is invalid"

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3459]
<img width="420" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/2f40e175-fdfa-4167-a8cb-a7b7bb1e2465">

I made a script, but when saving the collection it gives an error.

I tried 2 ways:

1) I created SQL collection

2) I made a view in a database (psql) and attached this database to the view.
The data is displayed in the database creation window correctly, but when saving - an error.

This is the script itself:

```
SELECT
    v.title AS "Вакансія",
    COALESCE(MAX(tc.total), 0) AS "Total candidates",
    COUNT(CASE WHEN et.id = 1 THEN a.id END) AS "Assigned to vacancy",
    COUNT(CASE WHEN et.id = 2 THEN a.id END) AS "Screening",
  	COUNT(CASE WHEN et.id = 3 THEN a.id END) AS "Interview",
  	COUNT(CASE WHEN et.id = 4 THEN a.id END) AS "Presentation to the customer",
  	COUNT(CASE WHEN et.id = 5 THEN a.id END) AS "Interview with the customer",
  	COUNT(CASE WHEN et.id = 6 THEN a.id END) AS "Testing/Case",
  	COUNT(CASE WHEN et.id = 7 THEN a.id END) AS "Collection of recommendations",
  	COUNT(CASE WHEN et.id = 8 THEN a.id END) AS "SB check",
  	COUNT(CASE WHEN et.id = 9 THEN a.id END) AS "Sent offer",
  	COUNT(CASE WHEN et.id = 10 THEN a.id END) AS "Accepted offer",
  	COUNT(CASE WHEN et.id = 11 THEN a.id END) AS "Not suitable",
  	COUNT(CASE WHEN et.id = 12 THEN a.id END) AS "Refused",
  	COUNT(CASE WHEN et.id = 13 THEN a.id END) AS "Cannot be reached",
  	COUNT(CASE WHEN et.id = 14 THEN a.id END) AS "Added to the reserve",
  	COUNT(CASE WHEN et.id = 15 THEN a.id END) AS "Added to blacklist"
FROM 
    vacancies v
LEFT JOIN (
    SELECT
        f_o69fha3awv5,
        COUNT(*)
 AS total
    FROM 
        t_ac2mdgfvzvz
    group by 
        f_o69fha3awv5
) tc ON tc.f_o69fha3awv5 = v.id
left JOIN
  activity a ON v.id = a.vacancy_key
left JOIN
  event_types et ON a.activity_type_key = et.id
WHERE
    v.is_active = true
GROUP BY
   v.title
ORDER BY 
   v.title;
```

**Comment by alexkash** [comment]
Found another case when it gives an error in the interface and executes directly in postgres

<img width="801" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/878c6c4c-61f0-489f-8626-9cbfda56edee">

**SQL:**
SELECT 
    cr.name AS "Criteria",
    STRING_AGG(DISTINCT sc.title, '; ') AS "Score Cards",
    STRING_AGG(DISTINCT cand.full_name, '; ') AS "Candidate",
    ROUND(CAST(AVG(cs.score) AS NUMERIC), 2) AS "Average Score",
    STRING_AGG(u.full_name || ': ' || cs.comments, E'\n' ORDER BY u.full_name) AS finalComments
FROM 
    criteria cr
LEFT JOIN 
    "CandidateScores" cs ON cr.Id = cs.criteria_key
LEFT JOIN 
    "ScoreCards" sc ON cr."scoreCard_key" = sc.Id
LEFT JOIN 
    Users u ON cs.rater_key = u.Id
LEFT JOIN 
    Candidates cand ON cs.candidate_key = cand.Id
GROUP BY 
    cr.name;

**Comment by alexkash** [comment]
The same error when connecting to view in the database. (the view was created normally, without errors)

<img width="794" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/d2e4443e-45a2-435b-b385-010393ecc463">

**Comment by Xilesun** [comment]
Hi @alexkash , it is because field names can not include space characters currently. We have enchanced the error message in #3489
