### ISSUE TITLE
The mariadb dialect is not supported

### ISSUE THREAD

**Issue by AnryHedgehog** [nocobase/nocobase#3466]
## Describe the bug

When trying to install my-nocobase-ap says that the mariadb dialect is not supported

## Version

attempt to install 0.19-alpha,4

## How To Reproduce

1. Follow the instructions to go to the step of creating a project and copy the part from mariadb
2. Run the copied command3. Scroll down to '....'
3. See error

## Expected behavior

installing nocobase

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/146196537/95b05071-f6f9-4ba3-8743-e2a14d0bc062)

## Desktop (please complete the following information)

- OS: [e.g. AstraLinux]
- Browser [e.g. chrome v121.0.6167.86 ]

**Comment by chenos** [comment]
Fixed [v0.19.0-alpha.5](https://github.com/nocobase/nocobase/commit/87652080166248708f918401a92a4afec8e42bc9)

**Comment by AnryHedgehog** [comment]
Thanks, it's all gone
