### ISSUE TITLE
Sometimes the Drawers overlaps the dialog box

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3470]
In some cases, a second-level drawer overlaps a dialog box for the user.

![drawer](https://github.com/nocobase/nocobase/assets/2558467/9e2db2a8-c047-4939-8dd5-42b7c66f651b)

![drawer2](https://github.com/nocobase/nocobase/assets/2558467/6bfd0308-0096-4aba-a947-a183df1421c2)

![2024-01-30_18-49-23](https://github.com/nocobase/nocobase/assets/2558467/a1057c24-e095-4231-adfe-d179f71cb339)

**Comment by hongboji** [comment]
What is the version number of nocobase?

**Comment by alexkash** [comment]
Hi! I apologize for not pointing that out right away.
Version 0.19.0-alpha.5.20240130130126

**Comment by hongboji** [comment]
Try clearing your browser cache or operating in no-trace mode to see if the problem still exists
