### ISSUE TITLE
角色单独配置权限数据查询不正确

### ISSUE THREAD

**Issue by wulianyougithub** [nocobase/nocobase#3479]
## Describe the bug

给角色单独配置表权限，查询时数据查不出来

## Version

Version 0.19.0-alpha.5
## How To Reproduce

1. 表结构设计
新建“站点”表，添加name字段
<img width="1431" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/f1c53c20-e9f8-4bb2-a980-95ac9ae61be1">
   新建计划表，添加name字段，并且添加一对一（belongs to）关系，计划属于某个站点
   
<img width="1423" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/083762dc-1524-4249-99ef-955dea236653">
  给用户表添加一对一关系（belongs to），某个用户属于某个站点
  
<img width="1427" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/0f408a98-0f7e-4efa-8d55-8829e2d31fb9">
添加”质检角色“，“计量站角色”，并单独配置“计划”表权限为“站点/ID=当前用户/站点/ID“
添加角色
<img width="1211" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/be63d173-f281-4122-85e9-3a0701ca6ffe">
设置角色”质检站权限“，”计量权限“的“计划”表权限为“站点/ID=当前用户/站点/ID“
<img width="1426" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/7d919cc6-afcd-4b54-abaf-1d14a801a6a1">

<img width="896" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/6682a654-5547-44b5-a946-fe29a1d60080">
添加站点“质检站”，“计量站“
<img width="1421" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/b97e90e5-10d3-400e-834d-0ef82155021f">

添加用户“质检站工作人员”，“计量工作人员”账号，并且设置权限分别为“质检站权限”、“计量权限”，所属站点分别为“质检站”，“计量站”
<img width="1420" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/21c5bf10-174b-4abb-baef-f93441d420f5">

2. 功能设计
添加计划管理，当使用不同的用户登录并添加计划时，该计划所属站点为登录用户的站点
<img width="1426" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/9d20fabb-6461-454d-8971-4c638643f6b7">
3. 应用：使用”质检站工作人员“账号登录系统并添加数据
<img width="1423" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/97d66076-fa62-4232-98b5-1f358d112111">

4. 错误：”质检站工作人员“账号添加的数据查看不到，但在超管的账号下能看到该数据已经添加，并且站点为质检站
<img width="1422" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/778296b6-76b8-4b01-9c68-3b0b3ee42c29">
超管账号
<img width="1431" alt="image" src="https://github.com/nocobase/nocobase/assets/20044528/bb866841-e5ad-43f2-a683-f55f2137613a">

## Expected behavior
账号登录人能看到该账号所属站点的数据

**Comment by chareice** [comment]
@wulianyougithub 请更新到最新版本，确认问题是否已解决

**Comment by wulianyougithub** [comment]
> @wulianyougithub 请更新到最新版本，确认问题是否已解决
解决了
