### ISSUE TITLE
git安装下，dev启动时api/app:getLang?locale接口404

### ISSUE THREAD

**Issue by RyzenPan** [nocobase/nocobase#3495]
## Describe the bug
通过Git源码下载，严格按照了官方文档的安装教程装包，dev启动之后，第一个getLang接口报错404

控制台打印如下
`
2024-02-06 22:39:36 [info ] app has been started  
cevent - [Webpack] Compiled in 14657 ms (11397 modules)
2024-02-06 22:39:59 [info ] request GET /api/app:getLang?locale          method=GET path=/api/app:getLang?locale req={"header":{"x-role":"anonymous","x-hostname":"localhost","x-timezone":"+08:00"}} app=main reqId=c7d75c45-e080-4295-95a8-ceeb73488154
2024-02-06 22:39:59 [warn ] response /api/app:getLang?locale             method=GET path=/api/app:getLang?locale status=404 cost=12 app=main reqId=c7d75c45-e080-4295-95a8-ceeb73488154
new client connected fhEOdqQlUSYzT2OU1RY8L
client tags: app#main
`

## Version
最新的main分支
数据库：sqlite
node：18+

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by RyzenPan** [comment]
> ## Describe the bug
> 通过Git源码下载，严格按照了官方文档的安装教程装包，dev启动之后，第一个getLang接口报错404
> 
> 控制台打印如下 `2024-02-06 22:39:36 [info ] app has been started cevent - [Webpack] Compiled in 14657 ms (11397 modules) 2024-02-06 22:39:59 [info ] request GET /api/app:getLang?locale method=GET path=/api/app:getLang?locale req={"header":{"x-role":"anonymous","x-hostname":"localhost","x-timezone":"+08:00"}} app=main reqId=c7d75c45-e080-4295-95a8-ceeb73488154 2024-02-06 22:39:59 [warn ] response /api/app:getLang?locale method=GET path=/api/app:getLang?locale status=404 cost=12 app=main reqId=c7d75c45-e080-4295-95a8-ceeb73488154 new client connected fhEOdqQlUSYzT2OU1RY8L client tags: app#main`
> 
> ## Version
> 最新的main分支 数据库：sqlite node：18+
> 
> ## How To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> ## Expected behavior
> ## Screenshots
> ## Desktop (please complete the following information)
> * OS: [e.g. iOS]
> * Browser [e.g. chrome v102, safari]
> 
> ## Smartphone (please complete the following information)
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> ## Additional context

![image](https://github.com/nocobase/nocobase/assets/56830619/5a12974b-af16-43bc-978e-42ae22929445)

**Comment by moiscye** [comment]
I've got the same error, any updates or workaround on this?

**Comment by chenos** [comment]
@RyzenPan 用的是什么操作系统？
@moiscye  What OS are you using?

**Comment by hongboji** [comment]
@RyzenPan  每一步骤的控制台打印贴一下 看看是什么流程步骤 是否存在错误

**Comment by RyzenPan** [comment]
> @RyzenPan 用的是什么操作系统？ @moiscye What OS are you using?

我是在windows下本地运行的，按照官方文档的Git源码安装指导一步步安装的

**Comment by RyzenPan** [comment]
> @RyzenPan 每一步骤的控制台打印贴一下 看看是什么流程步骤 是否存在错误

浏览器的控制台只有：

**Comment by moiscye** [comment]
@RyzenPan Windows11 Pro

**Comment by chenos** [comment]
@RyzenPan @moiscye  Try running PowerShell or CMD as an administrator.

![image](https://github.com/nocobase/nocobase/assets/2993310/92eb6e9d-3124-426e-90f2-b33f5657584b)

**Comment by RyzenPan** [comment]
> @RyzenPan @moiscye Try running PowerShell or CMD as an administrator.
> 
> ![image](https://private-user-images.githubusercontent.com/2993310/302968059-92eb6e9d-3124-426e-90f2-b33f5657584b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjQyMDIsIm5iZiI6MTcwODIyMzkwMiwicGF0aCI6Ii8yOTkzMzEwLzMwMjk2ODA1OS05MmViNmU5ZC0zMTI0LTQyNmUtOTBmMi1iMzNmNTY1NzU4NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDIzODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJiYzNlZTI1NmIyMzgyOTRkZWJkMzE0YjRjMTQwNmRmYmNhNTBhZDBjMDM0ZTU2ZDZjZjg4MWQyMTcxNTRmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oeIy0Wemn82ye4MsApMTBQx9u3tI5bYgB1TLzLLrAsU)

我已经使用管理员来运行项目了，但是还是一样的404哦！！
![image](https://github.com/nocobase/nocobase/assets/56830619/45885ba2-956b-48a6-a227-4fb85642e614)

**Comment by chenos** [comment]
@RyzenPan 提供一下安装过程的完整日志，可以用下面这个命令重装一下，看看完整日志里是什么报错

```bash
yarn nocobase install -f 
```

**Comment by RyzenPan** [comment]
> @RyzenPan 提供一下安装过程的完整日志，可以用下面这个命令重装一下，看看完整日志里是什么报错
> 
> ```shell
> yarn nocobase install -f 
> ```

我重新拉取项目安装后可以了！

**Comment by sxcooler** [comment]
> @RyzenPan 提供一下安装过程的完整日志，可以用下面这个命令重装一下，看看完整日志里是什么报错
> 
> ```shell
> yarn nocobase install -f 
> ```

我也遇到同样的问题，使用install -f后解决了，但是进入是英文版，应该是教程里的yarn nocobase install --lang=zh-CN 命令有问题，因为之前的报错是getLang 404

**Comment by liujunning** [comment]
> @RyzenPan 用的是什么操作系统？ @moiscye What OS are you using?

我也遇见了这个错误 接口是504 ，系统是macos 13.6.9 (22G830)，node：22.4.1，代码是main分支，执行 yarn nocobase install -f 日志如下
`2024-09-13 10:12:15 [debug] create database instance: {"sync":{"alter":{"drop":false},"force":false},"logging":false,"dialect":"postgres","username":"nocobase","database":"nocobase","port":"3306","timezone":"+08:00","tablePrefix":"","underscored":false,"migrator":{"context":{"app":{"appName":"main","name":"main"}}},"logger":{}} meta={"databaseInstanceId":"j9IqP6dbIFy8WtlkwFDOR"} module=database app=main reqId=16d0aafb-2315-4cbb-9f30-5c4f7de9cfc3 dataSourceKey=main
2024-09-13 10:12:15 [info]  add app main into supervisor                 module=application submodule=supervisor method=addApp app=main reqId=16d0aafb-2315-4cbb-9f30-5c4f7de9cfc3 dataSourceKey=main
node:assert:173
  throw err;
  ^

AssertionError [ERR_ASSERTION]: unknown message code: 4a
    at Parser.handlePacket (/Users/liujunning/OwnProject/my-nocobase/node_modules/pg-protocol/src/parser.ts:202:16)
    at Parser.parse (/Users/liujunning/OwnProject/my-nocobase/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/liujunning/OwnProject/my-nocobase/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: 'fail'
}

`
，

**Comment by TechQuery** [comment]
> > [@RyzenPan](https://github.com/RyzenPan) 提供一下安装过程的完整日志，可以用下面这个命令重装一下，看看完整日志里是什么报错
> > yarn nocobase install -f
> 
> 我也遇到同样的问题，使用install -f后解决了，但是进入是英文版，应该是教程里的yarn nocobase install --lang=zh-CN 命令有问题，因为之前的报错是getLang 404

@chenos 用上述命令强制重装后，同一 API 又 503 了……
