### ISSUE TITLE
Filter-Blocks don´t work on asociation-Fields

### ISSUE THREAD

**Issue by MSPJuan** [nocobase/nocobase#3500]
## Describe the bug

If I put Filter-Blogs, it doesn´t show the form fields in case of associated collections. Before we used Version 13 and it was possible to show also the fields of the associated collection by selecting the integer field that in the selected colletion.

## Version

Version 0.19.0-alpha.5

## How To Reproduce

1. Connect 2 collections by one-to-many or One to one (belongs to) relation
2. Put a new page
3. Table on main collection
4. Put Filter-Block on main collection
5. Switch on field for associated collection
6. before it was a sub-form, now field of asociated collections can´t be selected and are not editable

## Expected behavior
Field of asociated collection should be selectable en editable

## Screenshots

![grafik](https://github.com/nocobase/nocobase/assets/120518787/699f83cc-db87-4bc6-85d1-a37c1c407b39)

## Desktop (please complete the following information)

- OS: MacOS Somona 14.2.1

## Smartphone (please complete the following information)
none

**Comment by hongboji** [comment]
Use the fields in Display association fields.
Do not use subform components for relationship fields.
![image](https://github.com/nocobase/nocobase/assets/116709317/b80190f6-b8bf-422c-9b93-ff3af553a9a3)
