### ISSUE TITLE
Difficulties with using dates in workflow

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3509]
We have a field to which the date is written. In Postgres it looks like this:

<img width="281" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/44a79513-3f15-472c-b174-994f3689193b">

In the interface, it's like this:

<img width="170" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/e6e3aa5b-814b-4d1e-afd1-5552430f5a79">

But when we do query in workflow, it shows this result:

<img width="415" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/26ad9811-d9e3-4418-ad87-819f6b36cf9e">

Because of this, we are having difficulty utilizing this field. A bug?

**Comment by mytharcher** [comment]
> But when we do query in workflow, it shows this result:
> 
> <img alt="image" width="415" src="https://private-user-images.githubusercontent.com/2558467/305072687-26ad9811-d9e3-4418-ad87-819f6b36cf9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMDI5NTQsIm5iZiI6MTcwODAwMjY1NCwicGF0aCI6Ii8yNTU4NDY3LzMwNTA3MjY4Ny0yNmFkOTgxMS1kOWUzLTQ0MTgtYWQ4Ny04MTlmNmIzNmNmOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTMxMDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk0MzNmYjUyZTE2MzdkMzAxODEyNzk2OGUwYTU0YmQyNzU4YWQ1ZjEwOWY4ZDFjYjljMDg1ZmJlNDg4ZGVkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WIqogfVJBJ0qeNIUJL9TV9dcTWKNFcL-SVjjIhFZqIU">

This is not a bug. In node result (JSON) in workflow, values of date fields are always showed in UTC string. Your values of date field "2024-02-15 00:00:00.000 +0200", "15/02/2024" (in frontend) and "2024-02-14T22:00:00:000Z" are all equal to each other. Which means any of them is correct.

P.S.

When you try to use date value in workflow as a variable, you'd better change it to `Date` type in any calculations (like in Formula.js function `DATEVALUE(yourDateField)`). Directly use the date string is not recommended.

**Comment by alexkash** [comment]
Thanks for the quick reply, it made more clear.

**Comment by alexkash** [comment]
I posted in the discussion such a question, maybe you can tell me how it can be solved?

I am making a process that should run at night, compare the date in the table with today's date and if they are equal (any other condition), do a mailing using HTTP Request.

Here is the difficulty: I have the date in the table in this format - 2024-02-15 00:00:00:00.000, without time. And the date for now is always with time.

How do I compare them for equality of dates, that this event was on the same day?

**Comment by mytharcher** [comment]
You can use functions from [formula.js](https://formulajs.info/functions) to get only `year-month-day` from a Date value, then use the new value to compare with the value of your date-only field.

Or you could use "Advance" repeat mode (which is equal to Cron), It will work.
