### ISSUE TITLE
特殊格式文本在表格视图、编辑视图无法显示 / Text with special characters cannot be shown in table view / edit view

### ISSUE THREAD

**Issue by sxcooler** [nocobase/nocobase#3554]
## Describe the bug

我有一个字段内容是这样的：
I have a field like this:
![image](https://github.com/nocobase/nocobase/assets/3192045/a037e376-df35-49db-b7dd-31707ab3b560)
这是一种EL语言 / It's a expression language.

无论我在数据表管理里面选择“单行文本”、“多行文本”还是“json”，这个字段都无法在表格视图、编辑视图展示，却能在查看视图展示，猜测是触发了某个xss过滤。
No matter how I config this field in collection management, it can't be shown in table view / edit view, but can be shown in "View" view, maybe some kind of xss filter cause this.

## Version

latest main branch

## How To Reproduce

新建一个数据表，以及一个字符串类字段，加入我截图中的文字，添加表格区块并打开“编辑”、“查看”，然后查看。
create a collection with a string field, add a page with table block & enable "edit", "view", add the text below, try.
```
[
"result.score += 10;",
"result.resultStringList.add(String.format(\"A00001触发, sum: %s, score: %s\", aggLog.sum, result.score));"
]
```

## Expected behavior

应该正常显示
the text should be shown in table, edit.

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/3192045/867a3ff2-3b3f-485d-8167-907cc6628abd)

## Desktop (please complete the following information)

- OS: Windows 11
- Browser Chrome 122.0.6261.57

## Smartphone (please complete the following information)

N/A

**Comment by mytharcher** [comment]
<img width="836" alt="image" src="https://github.com/nocobase/nocobase/assets/525658/dc1a2894-f2d6-41a8-822b-c3b2c587962c" />

对单行文本字段测试了你的字符串，未能复现。

**Comment by sxcooler** [comment]
> <img alt="image" width="836" src="https://private-user-images.githubusercontent.com/525658/306933831-dc1a2894-f2d6-41a8-822b-c3b2c587962c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTI3NDUsIm5iZiI6MTcwODY1MjQ0NSwicGF0aCI6Ii81MjU2NTgvMzA2OTMzODMxLWRjMWEyODk0LWYyZDYtNDFhOC04MjJiLWMzYjJjNTg3OTYyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwMTQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTIzNDc4ZGUyNGE4MGJhN2M3YzY0MGJkYTg2N2FiNjBlYWYzY2FkMDVkNzY3NThmY2VkOWViMTdjYTk0MmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9LwPAir0G86DAZ6wLIncM1_EwhhJUL48rq2HMRNEcX8">
> 对单行文本字段测试了你的字符串，未能复现。

我用的MySQL 8.0.32（docker版）作为数据库，使用教程中“git源码安装”方式进行初始化，即运行在Windows环境，是否与此有关？

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3570
