### ISSUE TITLE
表格中多行文本后日期/时间被遮挡

### ISSUE THREAD

**Issue by sxcooler** [nocobase/nocobase#3558]
## Describe the bug

表格区块中，如果前一个字段是多行文本，后一个字段是日期/时间（其他没有尝试），多行文本会超宽，遮挡住后面的字段。

![image](https://github.com/nocobase/nocobase/assets/3192045/e0a26f12-d9c6-4ec8-9deb-6830161261e9)

## Version

latest main branch

## How To Reproduce

创建一个数据表、添加一个多行文本字段，再添加两个日期/时间字段，灌入一些数据。
创建一个页面，添加表格区块并关联上述数据表，查看效果。

## Expected behavior

多行文本应该显示正常宽度，不应该遮挡后续字段

## Screenshots

如上图

## Desktop (please complete the following information)

- OS: Windows 11 专业版 22621.3155
- Browser Chrome 122.0.6261.58

## Smartphone (please complete the following information)

N/A

## Additional context

使用MySQL作为数据库，使用源码安装方式，dev环境

**Comment by hongboji** [comment]
请问nocobase版本号多少

**Comment by hongboji** [comment]
数据表自动类别截图看看

**Comment by katherinehhh** [comment]
可以升级到新版本，这个问题之前修复过
