### ISSUE TITLE
将某个字段的默认值设置成日期变量，保存表单时出现错误提示。

### ISSUE THREAD

**Issue by yaocanke** [nocobase/nocobase#3561]
当给一个字段设置日期变量时，例如设置成上月。
![image](https://github.com/nocobase/nocobase/assets/89123307/e3171dfd-47d1-4434-ad4a-791deb859c36)
在保存表单时候，提示一下错误信息。
![image](https://github.com/nocobase/nocobase/assets/89123307/b757edca-1fa7-4778-81f3-2b3a38fa5f13)

**Comment by hongboji** [comment]
日期变量中 除开当前时间， 其他都是范围，不能用于赋值
