### ISSUE TITLE
Possible bug in data scope

### ISSUE THREAD

**Issue by zhouyanliang** [nocobase/nocobase#3582]
### Discussed in https://github.com/nocobase/nocobase/discussions/3581

<div type='discussions-op-text'>

<sup>Originally posted by **pehua** February 28, 2024</sup>
Hi.

- When I set data scope in a table I get this error

![image](https://github.com/nocobase/nocobase/assets/41135285/bcf864d4-bbf0-4cac-9c37-bafb33b9951c)

- Data scope is a filter for records with a field like due date = today

![image](https://github.com/nocobase/nocobase/assets/41135285/50e362fc-e988-46c7-8b20-3a093855a89f)

- And the records are thoses

![image](https://github.com/nocobase/nocobase/assets/41135285/2561d219-8a90-4bbf-973c-7c98d84afa05)

thanks

</div>

**Comment by pehua** [comment]
Same as #3426, #1767 and #1771.

Can anyone join them?

Thanks

**Comment by thiago** [comment]
I think it was solved by https://github.com/nocobase/nocobase/pull/3732

**Comment by pehua** [comment]
Yes, close it
