### ISSUE TITLE
git升级到最新版（ v0.19.0-alpha.9）, 安装sqlite版,  报错“SQLITE_ERROR: Cannot add a UNIQUE column”

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3588]
## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/f0e939c7-48cc-40c8-a22e-75a2ce059128)

**Comment by hongboji** [comment]
用最新的v0.20 看看，我这边不报错

**Comment by hongboji** [comment]
Issues will be closed, please continue to give feedback if you have questions!
