### ISSUE TITLE
git升级到最新版（ v0.19.0-alpha.9），重启服务器，进入死循环 一直打印错误，急

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3590]
删除node_modules 重新install 不行
删除storage/log 也不行
## Screenshots
![screenshots](https://github.com/nocobase/nocobase/assets/900786/534cc0c1-d1a7-4cab-ad13-94b058ea183e)

![image](https://github.com/nocobase/nocobase/assets/900786/3ef6028e-ce31-445a-8721-816934d27a95)

**Comment by mytharcher** [comment]
试试 main 最新的是否已经正常了？

**Comment by baiheinet** [comment]
> 试试 main 最新的是否已经正常了？

ok 感谢
