### ISSUE TITLE
还原功能错误，提示error: unknown command 'restore'

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3591]
## Screenshots
![image](https://github.com/nocobase/nocobase/assets/900786/2dddaf63-7731-4667-8824-24577f81ac41)

![image](https://github.com/nocobase/nocobase/assets/900786/9c614001-73cb-4c09-8d5d-a7fbcf5d70f0)

**Comment by chenos** [comment]
什么版本，是怎么的操作步骤？

**Comment by baiheinet** [comment]
![screenshots](https://github.com/nocobase/nocobase/assets/900786/b6966c41-d1ee-4f60-bf95-9f8fa51fdb01)

**Comment by hongboji** [comment]
不支持跨数据库类型恢复
