### ISSUE TITLE
workflow插件 定时任务 时间现在乱了 不按设定执行

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3594]
## Screenshots
![image](https://github.com/nocobase/nocobase/assets/900786/4218c4e6-b44d-450b-8bf2-ae28968dcbb0)

![image](https://github.com/nocobase/nocobase/assets/900786/6a5f53af-6a95-4852-8c8a-7c53ce38f333)

**Comment by mytharcher** [comment]
看看新的修复有没有解决？

**Comment by baiheinet** [comment]
> 看看新的修复有没有解决？
好像还是不对 理论上应该是02:50执行
https://github.com/nocobase/nocobase/issues/3594#issuecomment-1974393269

**Comment by baiheinet** [comment]
还是不行
![image](https://github.com/nocobase/nocobase/assets/900786/3b27c362-5fa3-4cb9-8fc1-0f43bef6c065)

**Comment by baiheinet** [comment]
另外 我就是停用了流程 他照样执行
![image](https://github.com/nocobase/nocobase/assets/900786/7d9a6122-bd88-445c-95d0-ac2049bfb945)
![image](https://github.com/nocobase/nocobase/assets/900786/d850a483-f3ce-4076-a1a2-8d5ac88d5c77)

**Comment by mytharcher** [comment]
@baiheinet 可以更新 main 再试试。

**Comment by baiheinet** [comment]
时间ok 但是会执行两次
![image](https://github.com/nocobase/nocobase/assets/900786/11c815dd-c23c-41ef-a67d-a2b44cee36e2)

**Comment by mytharcher** [comment]
> 时间ok 但是会执行两次

有复现步骤么？我本地测试没观察到这种情况。

**Comment by baiheinet** [comment]
没法复现 等我复现了再说

**Comment by baiheinet** [comment]
我复现了  发现规律了 复制到新版本一次 就会增加一次
![image](https://github.com/nocobase/nocobase/assets/900786/3b7a474e-3f17-452f-a99d-634960a98c76)

**Comment by mytharcher** [comment]
> 我复现了 发现规律了 复制到新版本一次 就会增加一次

更新到最新 main 试试，已经有一个相关的修复。

**Comment by mytharcher** [comment]
修复后未能复现，先关闭了，更新还有问题的话再打开。
