### ISSUE TITLE
plugin migration not working with pluginVersion field.

### ISSUE THREAD

**Issue by sealday** [nocobase/nocobase#3596]
## Expected behavior

when we set pluginVersion in migration files, it will check plugin version.

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
Can you please specify the exact issue you are encountering? Is there any error message? Feel free to provide a screenshot if possible

**Comment by sealday** [comment]
I write a plugin, hope pluginVersion can be used in migration process, but it can not.
