### ISSUE TITLE
对用户（user）表的权限控制 不起作用

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3607]
v0.20.0-alpha.4

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/e0ae2290-40df-45d7-afea-fe3e81179479)
![image](https://github.com/nocobase/nocobase/assets/900786/d6de9e6c-e367-4b53-b5a1-67baaf0c6bb9)

**Comment by chareice** [comment]
@baiheinet 已处理完成，请更新代码重试
