### ISSUE TITLE
树表格使用 子记录（children）会报错

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3617]
message
: 
"column \"records.date\" must appear in the GROUP BY clause or be used in an aggregate function"
## Screenshots

![screenshots](https://github.com/nocobase/nocobase/assets/900786/6b4e766b-956b-4bda-ae59-11877e5bc80d)

**Comment by hongboji** [comment]
是否存在特殊的关系字段  列出信息在表格上？

**Comment by baiheinet** [comment]
上个版本还好使
