### ISSUE TITLE
Quick search in formula field

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#3624]
## Describe the bug

Quick search in formula field doesn't work, while you are tipping, all rows disappear

## Version

0.20-alpha-4

## How To Reproduce

1. Create a formula field for concatenate 2 string fields
2. Show formula field in a form
3. Press some key inside formula field in form.

## Expected behavior

When I press one or more key the form dropbox show onli rows with my text

## Desktop (please complete the following information)

Node 16.1
Chrome latest
Edge latest

**Comment by hongboji** [comment]
Please provide a screenshot of the error process

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3573
