### ISSUE TITLE
附件字段没有新增到数据库，报告了BUG

### ISSUE THREAD

**Issue by piratekingtom** [nocobase/nocobase#3637]
![image](https://github.com/nocobase/nocobase/assets/17740201/2a04d53f-1118-4876-a615-2106dbcd0343)
上传的时候报
![image](https://github.com/nocobase/nocobase/assets/17740201/382a1c7a-d8a1-477c-8d32-7607aa41b100)

我尝试了MarkDown是可以成功添加到数据库表字段
上传文件的权限也是有的
版本v0.2

**Comment by chenos** [comment]
fix: https://github.com/nocobase/nocobase/commit/ed224cfa139de87eb8cc4e895a3765d8add8ef91

**Comment by hongboji** [comment]
更新到最新的代码，看是否解决

**Comment by piratekingtom** [comment]
更新最新版解决
