### ISSUE TITLE
Cascade field does not load actual value

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#3639]
## Describe the bug

When I activate a popup to edit a record, the popup form does not load values ​​into the cascading field

## Version

0.20.0-alpha-4

## Screenshots

https://github.com/nocobase/nocobase/assets/41135285/7b1d6167-36b6-43bf-92ae-d4e7a4fd2931

## Desktop (please complete the following information)

Chrome 122.0.6261.95 (Build oficial) (64 bits)
Win 10 pro 19045.3570

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3649
