### ISSUE TITLE
Deleted field can´t be removed from form

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#3641]
## Describe the bug

Whe I delete a field from a collection, is lost the availability to remove the field from a popup, it is reemplaced with a text
"The field "Plan de Mantenimiento > valorperioricidad" may have been deleted. Please remove this Field."

## Version

0.20.0-alpha- 4

## Expected behavior

Is provided a way to delete the field block form form

## Screenshots

https://github.com/nocobase/nocobase/assets/41135285/14ae73f7-dcc9-4374-8e55-0d9b873bcd33

**Comment by baiheinet** [comment]
me too
最新版还没修复
![image](https://github.com/nocobase/nocobase/assets/900786/281ad54e-b38f-478c-91cc-f3405d841f47)

**Comment by hongboji** [comment]
Fixed, please use the latest code and check if it is resolved
