### ISSUE TITLE
The Title Field is not respected on new block

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#3642]
## Describe the bug

Whe I insert a new block in a popup, the Title Field for that field is not used but the ID field.

## Version

- Node 16.1
- NocoBase v0.20.0-alpha.4

## Expected behavior

- The "Title Field" is set same to "Title Field " in collection.

## Screenshots

https://github.com/nocobase/nocobase/assets/41135285/0261ae4e-2a4d-4135-8911-72268a4e66de

## Desktop (please complete the following information)

- Chrome 122.0.6261.95 (Build oficial) (64 bits)
- Win 10 pro 19045.3570

**Comment by hongboji** [comment]
Refresh your browser and see if it resolves.
It is recommended not to use browser multi-tabs.

**Comment by hongboji** [comment]
Issues will be closed, please continue to give feedback if you have questions!
