### ISSUE TITLE
没有创建外部数据源的菜单

### ISSUE THREAD

**Issue by wengad82** [nocobase/nocobase#3644]
## Describe the bug

没有创建外部数据源的菜单
![图片](https://github.com/nocobase/nocobase/assets/19250813/911c0c3b-365e-4bae-a51a-f43d2aff46ff)

## Version
![图片](https://github.com/nocobase/nocobase/assets/19250813/5b22cfb6-3d48-45f7-96c9-4f13cdf70653)

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
https://cn.nocobase.com/plugins-cn.html
