### ISSUE TITLE
workflow 数据库预加载 <创建人>不起作用 只返回id

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3657]
## Screenshots
![image](https://github.com/nocobase/nocobase/assets/900786/66c51430-a730-49ae-8b9c-b835b6a40a3a)

老版本
![image](https://github.com/nocobase/nocobase/assets/900786/1b6a36d6-1a6e-4dc5-a64f-7852dec6d22e)
新版本
![image](https://github.com/nocobase/nocobase/assets/900786/fd53dcb1-1eb0-4dad-9791-1ca08f24f7ba)

**Comment by mytharcher** [comment]
是绑定在什么按钮上的操作？

**Comment by baiheinet** [comment]
最新功能 单行数据

**Comment by mytharcher** [comment]
修复了，可以更新 main 再试试。
