### ISSUE TITLE
workflow工作流超过1000+会卡死，内存 CPU都正常

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3662]
重启服务器，这些工作流会分分钟运行完毕。

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/eb2eefca-70f6-4ec1-9214-6dfec9f42fc2)
![image](https://github.com/nocobase/nocobase/assets/900786/d6b33d2d-00e5-4215-b22e-6dde91e9ad35)

![image](https://github.com/nocobase/nocobase/assets/900786/d6059764-23ed-47d2-b53d-dbed0c336ad7)

**Comment by mytharcher** [comment]
是说执行次数超过 1000+ 还是其他？

**Comment by baiheinet** [comment]
我的意思是队列中超过1000+就卡死

**Comment by mytharcher** [comment]
“卡死”指的是整个应用服务端无法工作？还是说工作流开始排队，不能正常进入执行状态？

如果是后者的话，可能得继续观察下什么情况导致排队的，可以看看 893454 前后的 log 情况。
