### ISSUE TITLE
Sub Tables not allways populates

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#3693]
## Describe the bug

I Use a Sub Table(collection undercontractors) in a form to enter one or many entries in a linked collection a many-one relatiship.

Sometimes when I view or try to edit a record in the main collection called resources the already entered records in the subtale do not show. If I do something else and go back to the same main record, the records in the subTable shows. I have not been able to see any logic in this, it seems random.

## Version

Experienced in both 0.14.0 alpha 6 and the version I currently run that is 0.20.0 alpha 7

## Screenshots

I pic 1 there is no records in the sub tale, in pic 2 they suddenly appear after I closed to form and opens it again.
![subtables2](https://github.com/nocobase/nocobase/assets/89129225/e63544f9-82fc-4a2b-825e-6796d8cd2d5c)
![subtables1](https://github.com/nocobase/nocobase/assets/89129225/9b1422f2-82e1-4082-8b56-e2829cde3f9e)

## Desktop (please complete the following information)

Widnows 10
Chrome Version 122.0.6261.112 (Officiell version) (64 bitar)

**Comment by eslafur** [comment]
I have encountered this behaviour too.
pullin information from Many to Many or one to many relationships seems to sometimges fail on the first load of an item.

looking closer and trying to fix this behavior i found out that this only happens to Block Templates.

to reproduce:
- Have 2 Tables with a many to many relationship
- in table 1 have a view that lists the occurences / references in table 2
- turn that view into a Block Template.
- exit ui edit mode and refresh the page.
- show an item in Table 1 -> the references to Table 2 did not populate
- close the view and open it again -> the references to Table 2 populated

- go to ui edit mode and convert the template reference to a duplicate
- exit ui edit mode and refresh the page
- view a item in Table 1 -> all fields populated.

Video of Behaviour.
https://github.com/nocobase/nocobase/assets/16470950/25cd3633-27fc-4dc9-bb3a-618b4c2c7a9e

**Comment by zhouyanliang** [comment]
@thomaswennersten @eslafur please update to the latest version and it should has been fixed.

**Comment by eslafur** [comment]
redeployed my container, it is now on v0.21.0-alpha.11
the sub tables and queries now work as expected on first try no matter if a template or not.
Docker didn't pull the latest image before I started investegating this behaviour, sorry for that and thanks for the fast pointer.
