### ISSUE TITLE
筛选中使用富文本，无法正常命中结果

### ISSUE THREAD

**Issue by hellofreud** [nocobase/nocobase#3698]
## Describe the bug

在筛选中使用富文本，会导致无法正常检索。例如本身有100条数据，富文本设置包含内容，即使内容为空并且直接检索，也只能检索出几条内容

在检索出来的结果中，即使包含了关键字，也无法检索出结果

## Version

v0.20.0-alpha.6

![image](https://github.com/nocobase/nocobase/assets/17267947/5fd9c799-2b64-4b24-8a27-6d9dc1858f33)

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4888

**Comment by hongboji** [comment]
请使用最新的代码，在筛选中富文本字段删除再启用 ，确认是否正确筛选数据
