### ISSUE TITLE
批量编辑/更新插件 选择<所有>时，有bug,会清空默认设置的数据范围

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3715]
默认数据范围
![image](https://github.com/nocobase/nocobase/assets/900786/f30a52f7-032f-4d28-9dd3-2128da0ac5a3)
选择<所有>时，丢失filter
![image](https://github.com/nocobase/nocobase/assets/900786/827e17b6-74f9-4fcd-9fc1-4da6445d2d38)

**Comment by hongboji** [comment]
这不是一个缺陷
