### ISSUE TITLE
error: unknown command 'restore'

### ISSUE THREAD

**Issue by netssfy** [nocobase/nocobase#3746]
## Describe the bug

在backup restore界面restore失败

## Version

0.20.0-alpha.13

## How To Reproduce

1. 创建一个backup
2. 还原这个backup

## Expected behavior

backup被成功还原

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/6095138/a3c4dff8-b73e-4477-b978-17b4cb72d7ab)

## Desktop (please complete the following information)

- OS: windows
- Browser: edge

## Additional context
看上去像addRestoreCommand这个函数没有执行，或者执行失败
packages\plugins\@nocobase\plugin-backup-restore\src\server\commands\restore-command.ts

**Comment by baiheinet** [comment]
https://github.com/nocobase/nocobase/issues/3591

**Comment by netssfy** [comment]
> #3591

我不是跨数据库，都是sqlite

**Comment by netssfy** [comment]
@baiheinet 我不是跨数据库，都是sqlite

**Comment by netssfy** [comment]
@baiheinet 我在packages\plugins\@nocobase\plugin-backup-restore\src\server\commands\restore-command.ts的addRestoreCommand加了条调试的日志，然后yarn dev启动时并没有看到这条LOG。感觉应该就是这个command没被注册到app里。我刚接触，对底层框架不太了解，不清楚core是如何加载plugin的command

**Comment by netssfy** [comment]
@baiheinet 
![image](https://github.com/nocobase/nocobase/assets/6095138/486df5d6-878c-4d69-a40d-ca651850d05e)
加了一下这个，就可以了。不知道对不对，我先提个PR吧

**Comment by baiheinet** [comment]
非常完美 ，跨数据库真正的错误是这样的，
![image](https://github.com/nocobase/nocobase/assets/900786/c2080303-e577-4fb7-bff6-96e2eab79741)

**Comment by netssfy** [comment]
@baiheinet，谁能帮忙review一下PR？

**Comment by chenos** [comment]
@netssfy 升级到最新版本了么，commands 是自动处理的，不需要在 beforeLoad 里再加了

**Comment by chenos** [comment]
fix: https://github.com/nocobase/nocobase/pull/3858
