### ISSUE TITLE
Search not working in rich text field

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#3755]
## Describe the bug

Searching within a rich text field returns an empty result.

## Version

v0.20.0-alpha.13

## Expected behavior

The search only displays records with the searched value in the search field.

## Screenshots

https://github.com/nocobase/nocobase/assets/41135285/b3dac06b-8a4e-4730-ba7c-57f4707da72a

## Desktop (please complete the following information)

Chrome Versión 122.0.6261.129 (Build oficial) (64 bits)
Win 10 19045.4170

**Comment by pehua** [comment]
Hi. Any update?

Thanks

**Comment by pehua** [comment]
Hi, news?

**Comment by zhouyanliang** [comment]
No updates by now.

**Comment by miladhatami1393** [comment]
No updates by now

**Comment by zhanghongnian** [comment]
<img width="600" alt="image" src="https://github.com/nocobase/nocobase/assets/9982100/a6bec12a-8c7f-4df8-a75c-9ffd5882aad5">
It seems that the rich text search included the tags <p></p>. Why not use single-line text instead?

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4888

**Comment by hongboji** [comment]
Please use the latest code, in the filter form, the rich text field is deleted and then enabled to confirm that the data is filtered correctly.
