### ISSUE TITLE
Can't update one-to-one relations

### ISSUE THREAD

**Issue by jakob1379** [nocobase/nocobase#3758]
## Describe the bug

I have two collections, Documents and Versions. The Documents have a one-to-one (has one) relation to versions called “active_version”, this can't be updated through the edit forms as only the current “active_version” is shown in the dialogue. 

## Version

v0.20.0-alpha.14

## How To Reproduce

 1. Create two models where one have a one-to-one (has one) relation to the other
 2. create a view with data-block table and setup an edit form like in the screenshots

## Expected behavior

That all all the entries from the "versions" table would be accessible in the dropdown/selection menu.

## Screenshots

<details>
  <summary>Click to see screenshots</summary>
  
  
![image](https://github.com/nocobase/nocobase/assets/17257805/7c4c189d-6256-436e-8153-35c35c355c19)

![image](https://github.com/nocobase/nocobase/assets/17257805/0bf6f453-b996-47da-bd97-6fc6d7de84cf)

</details>

## Desktop (please complete the following information)

```bash
❯ neofetch 
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            jga@nixos 
          ▜███▙       ▜███▙  ▟███▛            --------- 
           ▜███▙       ▜███▙▟███▛             OS: NixOS 24.05.20240309.3030f18 (Uakari) x86_64 
            ▜███▙       ▜██████▛              Host: LENOVO 20NYSD4R05 
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.6.21 
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 20 mins 
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 1156 (nix-system), 6300 (nix-user) 
          ▟███▛             ▜██▛ ▟███▛        Shell: bash 5.2.26 
         ▟███▛               ▜▛ ▟███▛         Resolution: 3440x1440 
▟███████████▛                  ▟██████████▙   DE: Plasma 5.27.10 
▜██████████▛                  ▟███████████▛   WM: KWin 
      ▟███▛ ▟▙               ▟███▛            Icons: breeze [GTK2/3] 
     ▟███▛ ▟██▙             ▟███▛             Terminal: .konsole-wrappe 
    ▟███▛  ▜███▙           ▝▀▀▀▀              CPU: Intel i7-8665U (8) @ 4.800GHz 
    ▜██▛    ▜███▙ ▜██████████████████▛        GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
     ▜▛     ▟████▙ ▜████████████████▛         Memory: 8672MiB / 15662MiB 
           ▟██████▙       ▜███▙
          ▟███▛▜███▙       ▜███▙                                      
         ▟███▛  ▜███▙       ▜███▙                                     
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘
```

**Comment by hongboji** [comment]
Using relational fields: Many to one

**Comment by jakob1379** [comment]
> Using relational fields: Many to one

Could you elaborate on this as the comment comment itself  doesn't explain anything?

**Comment by BenCherif** [comment]
any update about this issue ?
