### ISSUE TITLE
Random image in upper left corner after uploading file

### ISSUE THREAD

**Issue by jakob1379** [nocobase/nocobase#3782]
## Describe the bug

A file I uploaded to one of my collections shows in the left corner for no reason? It stays even after being deleted and restarting the stack, so it must be saved somewhere else and then used as “thumbnail”. 

Additional “feature”: It works with GIFs, hehe.

## Version

v0.20.0-alpha.15.20240320064834

## How To Reproduce

1. create a file collection
2. create upload a file in a view
4. the first file uploaded will show in the corner.

## Expected behavior

No image should be used anywhere without being defined

## Desktop (please complete the following information)

Running in docker,
Firefox: 123.0.1 (64-bit)

```
OS: NixOS 24.05.20240316.c75037b (Uakari) x86_64
Host: LENOVO 20NYSD4R05 
Kernel: 6.6.22 
Uptime: 6 hours, 1 min 
Packages: 1156 (nix-system), 6215 (nix-user) 
Shell: bash 5.2.26 
Resolution: 3440x1440 
DE: Plasma 5.27.10 
WM: KWin 
Icons: breeze [GTK2/3] 
Terminal: .konsole-wrappe 
CPU: Intel i7-8665U (8) @ 4.800GHz 
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
Memory: 9848MiB / 15662MiB 
```

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/17257805/d5bf84b1-0d8b-4d05-aa9e-931efe025fbb)

## additional 

The image has a valid reference to the file storage: https://nocobase.traefik.me/storage/uploads/a8c27a6233cc4ab3e314f24d2b6ea6e9.gif

**Comment by hongboji** [comment]
If you can't reproduce the problem, you can remove the image in the top left corner in system settings and try to use file collection to see if the problem occurs.

**Comment by jakob1379** [comment]
It was not available in the file collections or file-manager. I can't reproduce this error, though.
