### ISSUE TITLE
表格分页显示的数据顺序会乱

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3796]
比如第一页有一个人
![image](https://github.com/nocobase/nocobase/assets/900786/a897bdae-2cfb-48c4-b57e-c423a0999717)
第二页又会出现，随机的，这个bug出现好长时间了，一直忘了提issue，但是总行数是对的。
![image](https://github.com/nocobase/nocobase/assets/900786/5d7c674f-5d9c-4689-990d-936ce50c0025)

**Comment by zhouyanliang** [comment]
需要给它设置排序规则。

**Comment by baiheinet** [comment]
排序规则 设置了
![image](https://github.com/nocobase/nocobase/assets/900786/707695dd-d284-4d6a-8cf6-828898cd9e62)

**Comment by hongboji** [comment]
更新最新代码，已经修复

**Comment by baiheinet** [comment]
并没有
![image](https://github.com/nocobase/nocobase/assets/900786/fa23dc71-eba2-4070-8ac5-993201a19304)
![image](https://github.com/nocobase/nocobase/assets/900786/cc895116-ebba-4fa1-a3ff-5e888e40391a)

**Comment by hongboji** [comment]
再增加一个排序字段 ，状态后可以增加一个id 排序，因为状态内数据是重复的，就是无序的
