### ISSUE TITLE
工作流的查询数据操作目前是否可用？

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#380]
**Describe the bug**

定义了一个工作流，触发后直接更新数据（固定的数据），没有问题。

在更新数据操作前，增加一个查询数据操作，更新数据操作使用查询数据的值，没有效果（也没有监控到sql update语句）

查询数据操作即使条件为字段不为空（那么肯定应有查询结果），也无法正确更新数据操作

所以可能是我操作有误，或者查询数据操作目前还不可用？

**Version**

最新的 main 分支

**To Reproduce**

我操作的步骤如下：

- 创建名为产品的 collection ，有字段`价格`
- 创建名为订单的 collection，
   - 有字段`产品`，belongsToMany 关联到产品 collection
   - 有字段`单价`
- 创建产品记录
- 创建工作流
   - 触发设置：当`订单`表 `新增数据后` 触发
   - 查询数据：`产品`表，条件为：产品/订单/id=触发数据id
   - 更新数据：`订单`表，
       - 条件为：id=触发数据id
       - 字段值：`单价`=节点数据/查询产品价格/价格

**Expected behavior**

希望通过定制工作流，当订单创建后，自动将对应产品的价格，设置为订单的单价

**Screenshots**

产品表：

![image](https://user-images.githubusercontent.com/931976/168021498-0cde41b2-fad6-4636-aa7e-1adb360cb88e.png)

订单表：

![image](https://user-images.githubusercontent.com/931976/168021614-08474052-9ea4-490b-8f7f-9e5e03e31230.png)

产品和订单的关联关系：

![image](https://user-images.githubusercontent.com/931976/168021729-edf05f11-d5f3-44ad-96f7-a460195a36a0.png)

工作流整理流程：

![image](https://user-images.githubusercontent.com/931976/168021839-99da3f39-6e5a-4d08-85d1-809f8a24a05f.png)

触发器：

![image](https://user-images.githubusercontent.com/931976/168022036-547ed069-f8de-4e02-bd06-2d17936c4caf.png)

查询数据操作：

![image](https://user-images.githubusercontent.com/931976/168022119-4eaa44e0-5dc3-466f-ad8c-1c40055b6152.png)

更新数据操作：

![image](https://user-images.githubusercontent.com/931976/168022228-d01b26e8-4ef0-4294-bab0-91589d3d1770.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser chrome
 - Version 101.0.4951.54（正式版本） (x86_64)

**Comment by mytharcher** [comment]
@MarshalW 感谢反馈，可能是个 bug，最近应该会修复。
