### ISSUE TITLE
字段类型：关联，配置数据范围报错

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#381]
**Describe the bug**
1、关联字段设置数据范围，查询表错误
2、删除数据报错

**Version**
docker部署：nocobase/nocobase:latest

**To Reproduce**
1、定义两张表：t_server_info和t_sqoop_table_info
2、在表t_sqoop_table_info增加关联字段，数据表配置-配置字段-添加字段，类型为：关联，名称：关联服务器，关系表
：t_server_info，保存
3、界面配置时，添加-关联字段配置-设置数据范围，添加条件，确定，报字段不存在
4、点击删除按钮

**Expected behavior**
1、关联字段数据范围查询表t_server_info的数据
2、删除数据成功

**Screenshots**
![image](https://user-images.githubusercontent.com/82276246/168169818-6f0224af-d7c3-4868-b4d8-18102c9e5585.png)
![image](https://user-images.githubusercontent.com/82276246/168169694-6e62306b-617f-41e1-b2a9-ae82de5b6af5.png)
![image](https://user-images.githubusercontent.com/82276246/168169900-0ecd4481-f073-4f55-87ff-9cbad98ee2d7.png)
![image](https://user-images.githubusercontent.com/82276246/168169961-cd7d8dfb-26fd-492c-b55d-d94475a62078.png)
![image](https://user-images.githubusercontent.com/82276246/168170005-b44e2bee-5ab1-4f2d-bd8e-92945793d067.png)
![image](https://user-images.githubusercontent.com/82276246/168173186-774738e1-0176-4156-8de2-932aaea1be5c.png)

**Desktop (please complete the following information):**
 - OS: FerenOS 2022.04
 - Browser：Microsoft Edge
 - Version 101.0.1210.32 (正式版本) (64 位)

**Comment by chenos** [comment]
最新版已修复

```bash
docker-compose stop app
docker-compose rm app
docker-compose up -d app
docker-compose logs app
```

**Comment by 625412505** [comment]
使用最新master代码已验证，问题已修复。
什么时间可以推送一下docker镜像到dockerhub就更好了。
