### ISSUE TITLE
one-to-one relation not respected 

### ISSUE THREAD

**Issue by jakob1379** [nocobase/nocobase#3826]
## Describe the bug

In the NocoBase EDMS system, there appears to be an inconsistency in the relationship behavior. The `Documents` collection is expected to have a one-to-one relationship with the `Versions` collection via the `Active Version` field. However, I am able to associate multiple `Versions` with a single `Document` which contradicts the one-to-one relationship and effectively creates a one-to-many relationship from the `Documents` side. This allows multiple active versions of a document, which should not be possible.

## Version

NocoBase v0.20.0-alpha.16 running in Docker.

## How To Reproduce

1. Go to 'Graphical interface' under 'Data source manager'.
2. Create a new document in the `Documents` collection.
3. Add multiple versions in the `Versions` collection and associate them with the single document created in step 2.
4. Observe that the system allows multiple active versions to be linked to a single document.

## Expected behavior

The expected behavior is that only one version should be active and associated with a document at any given time, respecting the one-to-one relationship.

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/17257805/60cf1fc5-bc3c-4e8b-9f01-81da83499162)

![image](https://github.com/nocobase/nocobase/assets/17257805/02373ff1-412d-4617-9394-6e6c4a194af4)

## Desktop

```bash
❯ neofetch 
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            jga@nixos 
          ▜███▙       ▜███▙  ▟███▛            --------- 
           ▜███▙       ▜███▙▟███▛             OS: NixOS 24.05.20240316.c75037b (Uakari) x86_64 
            ▜███▙       ▜██████▛              Host: LENOVO 20NYSD4R05 
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.6.22 
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 3 hours, 2 mins 
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 1156 (nix-system), 6252 (nix-user) 
          ▟███▛             ▜██▛ ▟███▛        Shell: bash 5.2.26 
         ▟███▛               ▜▛ ▟███▛         Resolution: 3440x1440 
▟███████████▛                  ▟██████████▙   DE: Plasma 5.27.10 
▜██████████▛                  ▟███████████▛   WM: KWin 
      ▟███▛ ▟▙               ▟███▛            Icons: breeze [GTK2/3] 
     ▟███▛ ▟██▙             ▟███▛             Terminal: .konsole-wrappe 
    ▟███▛  ▜███▙           ▝▀▀▀▀              CPU: Intel i7-8665U (8) @ 4.800GHz 
    ▜██▛    ▜███▙ ▜██████████████████▛        GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
     ▜▛     ▟████▙ ▜████████████████▛         Memory: 11328MiB / 15662MiB 
           ▟██████▙       ▜███▙
          ▟███▛▜███▙       ▜███▙                                      
         ▟███▛  ▜███▙       ▜███▙                                     
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘
❯ firefox --version
Mozilla Firefox 124.0.1
```

**Comment by hongboji** [comment]
The Document field in the screenshot is a many to one relationship field, which is permitted

**Comment by jakob1379** [comment]
> The Document field in the screenshot is a many to one relationship field, which is permitted

You are referencing the 1-to-N relation between Document.Versions and Versions.Document i.e. a document have many versions.

Below you see that Document.active_verision has a 1-to-1 relation to Version.active_document. It is this attribute that is causing issues and is not respected in the edit view.

**Comment by jakob1379** [comment]
I finally understand what you meant, though I still think this is an error as rules regarding limiting foreign relations should only be gathered from the relevant field and not from other keys, no?

For anyone who stumbles on this:

The issue here is that I had defined both one-to-one relation AND a one-to-many relation between the same tables, albeit in different columns. Probably due to how the junction tables are implemented, the one-to-one relation is not respected and can is overruled be the other relation.
