### ISSUE TITLE
关联信息时，初次打开编辑页面100%无法关联

### ISSUE THREAD

**Issue by hellofreud** [nocobase/nocobase#3827]
## Describe the bug

我的所有表都关联到了商品表，例如我在编辑商品关联到的供应商信息时，字段中有主表中的商品名称进行关联，但是打开编辑时，这个字段100%无法自动加载，关闭窗口重新打开后，100%能自动加载
![image](https://github.com/nocobase/nocobase/assets/17267947/ca28872b-ab7b-486a-9392-1f38aa83fd96)

## Version
v0.20.0-alpha.6

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
请把数据表字段列表，关系字段编辑后属性截图，及页面操作流程截图，以便分析定位问题

**Comment by hellofreud** [comment]
> 请把数据表字段列表，关系字段编辑后属性截图，及页面操作流程截图，以便分析定位问题

你好，表相关的信息在wx群内反馈了，怀疑是因为机器性能（2核2g1M云服务）问题导致关联数据加载延时，数据未能一次加载成功所导致，因为第二次打开时可以正常加载，并且刷新网页后又会出现这个问题

**Comment by zhouyanliang** [comment]
已修复
