### ISSUE TITLE
Drag & Drop Bugs

### ISSUE THREAD

**Issue by foxpcteam** [nocobase/nocobase#383]
**Describe the bug**
The First bug is when you want to change the menu order.
When dragging some item, the item background become "blue light" and the text become "dragging" with black color.
This is not the behaved that should be. Second, you don't really see and understand the position of the draggable item, so you need to guess when and where to drop the item.
The solution is: we should see what item is dragged and of course his position

The Second bug is when you double-click on "dragging" icon inside some block, this block will disappear.

The Third bug, "filter button" have "Drag & Drop" option, but this is not working.

**Version**
demo version from NocoBase website.

**To Reproduce**
watch the video
https://app.birdeatsbug.com/sessions/uv2haHWtF-wxvVpaGXUtNXxql-sybpt6RNeqKfUGRd0x

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version last

**Comment by zhouyanliang** [comment]
Thanks. They were known bugs.
