### ISSUE TITLE
从0.16升级到0.19后，之前版本创建的数据库中无法再加入新字段

### ISSUE THREAD

**Issue by Mykeyb2004** [nocobase/nocobase#3846]
## bug重现：
- 原来v0.16中创建的数据表，在升级到v0.20后，加入新字段时，报错信息为“txxx_project 字段值是唯一的”。数据表结构实际已经添加了该字段，但在该字段配置到界面中时该字段数据无法编辑、保存。
- 但用v0.20创建的数据表，则无此问题。

**Comment by hongboji** [comment]
添加字段报错截图看看

**Comment by Mykeyb2004** [comment]
<img width="1261" alt="image" src="https://github.com/nocobase/nocobase/assets/23111338/17db3016-dee6-49bc-922f-ea8395010ee1">

**Comment by zhangzhonghe** [comment]
因该 Issue 长时间没有新的回复，暂时关闭。如需继续讨论，请到我们的中文社区进行：https://forum.nocobase.com/c/chinese-forum/6
