### ISSUE TITLE
字段类型：子表格，添加：选择类型字段，页面无法选中

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#385]
**Describe the bug**
1、添加字段类型为：子表格
2、增加选择类型字段，页面控件无法选择

**Version**
docker部署：nocobase/nocobase:latest

**To Reproduce**
1、新增子表格类型字段
2、在子表格中新增选择类型字段
3、配置页面
4、新增数据

**Expected behavior**
选择类型可以正常选择

**Screenshots**
![2022-05-13_17-43_1](https://user-images.githubusercontent.com/82276246/168259839-675b535d-3aeb-4ce1-bcb3-14538aae441b.png)
![2022-05-13_17-44](https://user-images.githubusercontent.com/82276246/168259891-56803a43-b1dd-4423-b5b0-d0f8c3e94a62.png)
![2022-05-13_17-43](https://user-images.githubusercontent.com/82276246/168260034-199c9867-7232-409b-9b33-b125bbbaebd9.png)
![2022-05-13_17-42](https://user-images.githubusercontent.com/82276246/168260085-45c0bea9-d7c1-4cf5-862b-1fe5f4817369.png)

**Desktop (please complete the following information):**
 - OS: FerenOS 2022.04
 -  Browser：Microsoft Edge
 - Version 101.0.1210.32 (正式版本) (64 位)

**Comment by chenos** [comment]
问题已修复 https://github.com/nocobase/nocobase/issues/427
