### ISSUE TITLE
Gird Card ui bug  , when setting the count of columns  displayed in  a  row 

### ISSUE THREAD

**Issue by mz0in** [nocobase/nocobase#3851]
when setting the count of columns  displayed in  a  row , a non related ui appears 

<img width="560" alt="image" src="https://github.com/nocobase/nocobase/assets/5844695/8142b246-052c-4710-885f-65120fb78b42">

**Comment by hongboji** [comment]
This is not a bug, it can be used in the mobile configuration interface.

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3960
