### ISSUE TITLE
页面中增加版本号

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#386]
建议在页面中增加版本号
![image](https://user-images.githubusercontent.com/82276246/168407055-133601c6-6bef-47ce-815e-396832b21853.png)

**Comment by zhouyanliang** [comment]
已在计划中

**Comment by 625412505** [comment]
已添加版本号
![image](https://user-images.githubusercontent.com/82276246/169505656-da0a9ac6-4213-4726-b1bd-e13fbd81f2a5.png)
