### ISSUE TITLE
开发插件，build不了

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3869]
## Describe the bug

开发插件，build不了

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/ace89b8a-b7ad-44a7-9456-d25888298a00)

**Comment by hongboji** [comment]
尝试：先 yarn build 全部 ，再build 单个插件

**Comment by baiheinet** [comment]
yarn build  core\test挡住了 ，plugin-hello确实安全通过😲
![image](https://github.com/nocobase/nocobase/assets/900786/ab3705e3-7035-4403-9628-3dbe74c6d763)

**Comment by dream2023** [comment]
@baiheinet 需要先全量 build  `yarn build`
