### ISSUE TITLE
Yarn start如何自定义端口

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#387]
yarn start 如何修改默认端口8000，比如自定义端口：8811。

**Comment by MarshalW** [comment]
可以带通过环境变量的命令指定（macOS/Linux）：

```bash
PORT= 8811 yarn start
```

Windows下使用 PowerShell:

```powershell
$env:PORT= 8811 yarn start
```

不过如果用 `yarn start` 一般不是为了正式部署，是为了开发中的动态调试，指定端口的作用不大。

正式部署一般是用 HTTP Server，比如 Nginx，端口在 HTTP Server 上设置，或者再通过 docker 做端口映射。

**Comment by 625412505** [comment]
好的，谢谢。
