### ISSUE TITLE
Workflows stopped working

### ISSUE THREAD

**Issue by alexkash** [nocobase/nocobase#3875]
New ones are not being created:
<img width="920" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/a7016972-6d72-47ee-8dc2-209a7129df6b">

The old ones that worked before hang up:
<img width="827" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/68857751-9ec4-4780-b452-e1cfc84fd494">

Blocks in the workflow itself disappear somewhere. It was like this (old version)
<img width="1656" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/593b87a4-9d45-4fc7-99a3-b1e9d07c6a90">

Now it looks like this (Nothing was done to workflow, users were working):
<img width="1603" alt="image" src="https://github.com/nocobase/nocobase/assets/2558467/f4760adf-486d-4a60-8ab0-38e3b5b4141c">

v0.19.0-alpha.9.

**Comment by mytharcher** [comment]
Could you help to provider more information, like server logs on when creating failed?
