### ISSUE TITLE
通过添加文本 加入的markdown ,members没有权限

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#3878]
## Describe the bug

通过添加文本 加入的markdown ,members没有权限看见

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/900786/42e2e1f4-92bd-4979-9d29-64e99cb56f85)

**Comment by zhouyanliang** [comment]
测试没有复现。需要提供更详细的信息。

**Comment by baiheinet** [comment]
我也复现不了了😥

**Comment by beehee** [comment]
我也是这个问题，root加的“添加文本”，但其他角色的账号登录进去是看不到添加的文本的
