### ISSUE TITLE
Switching language to Swedish generates error with Charts

### ISSUE THREAD

**Issue by MBHorne** [nocobase/nocobase#3904]
## Describe the bug

When Switching language to Swedish generates error with Charts with currency

## Version

0.21-alpha1

## How To Reproduce

1. Go to Switch Language and switch to Swedish after enabling it

2. See error

## Expected behavior

The currency should be "SEK" or "kr" instead of $

## Screenshots

https://ibb.co/9nwPy0h

![Screenshot 2024-04-02 at 11 56 09](https://github.com/nocobase/nocobase/assets/87115808/698a9a7c-827c-417d-a7ea-0bfc3ad3ab4e)

## Desktop (please complete the following information)

- OS: macOS
- Browser Safari

## Additional context

NumberFormat@[native code] Currency@http://172.17.1.89:13000/static/plugins/@nocobase/plugin-data-visualization/dist/client/index.js:1:18789 @http://172.17.1.89:13000/static/plugins/@nocobase/plugin-data-visualization/dist/client/index.js:26:5757 map@[native code] @http://172.17.1.89:13000/static/plugins/@nocobase/plugin-data-visualization/dist/client/index.js:26:5539 map@[native code] getProps@http://172.17.1.89:13000/static/plugins/@nocobase/plugin-data-visualization/dist/client/index.js:26:5512 Ty@http://172.17.1.89:13000/static/plugins/@nocobase/plugin-data-visualization/dist/client/index.js:1:11300 Zr@http://172.17.1.89:13000/umi.5329f5d8.js:13:20337 sl@http://172.17.1.89:13000/umi.5329f5d8.js:15:3154 Cc@http://172.17.1.89:13000/umi.5329f5d8.js:15:40196 rf@http://172.17.1.89:13000/umi.5329f5d8.js:15:40124 Fs@http://172.17.1.89:13000/umi.5329f5d8.js:15:39978 Rl@http://172.17.1.89:13000/umi.5329f5d8.js:15:36281 Rc@http://172.17.1.89:13000/umi.5329f5d8.js:15:35232 U@http://172.17.1.89:13000/umi.5329f5d8.js:16:21147 Z@http://172.17.1.89:13000/umi.5329f5d8.js:16:21513 @http://172.17.1.89:13000/umi.5329f5d8.js:7:3386 Z@http://172.17.1.89:13000/umi.5329f5d8.js:7:3145 q@http://172.17.1.89:13000/umi.5329f5d8.js:7:3205

**Comment by Xilesun** [comment]
Hi, @MBHorne 
Please upgrade to the latest version.  #4013 
`Currency` is now deprecated, use `Precision` and `Prefix` instead.
<img width="553" alt="image" src="https://github.com/nocobase/nocobase/assets/3250534/5e87ad12-349d-4360-b6a6-fc0ab3aa57c0">
