### ISSUE TITLE
need to manually run yarn install in container before it works properly

### ISSUE THREAD

**Issue by thinkbig1979** [nocobase/nocobase#3914]
After installing using docker,  following the instructions in the docs, the app starts without errors in the log, and presents the login screen.
Login as admin with the default admin user works, as does creating a new user, but in both cases this is what shows up in the browser:
![image](https://github.com/nocobase/nocobase/assets/18327273/d4a74233-3afd-4a69-b1f4-e302042dcd97)

To resolve this, I had to go into the container and run yarn install, then restart the container. Only then did it work properly.

**Comment by zhouyanliang** [comment]
This interface is normal. It's just a blank NocoBase application, and you need to use the Admin user to configure it.

**Comment by thinkbig1979** [comment]
There was no option to configure anything, but after running yarn install and restarting the container, the UI looked like this:
![image](https://github.com/nocobase/nocobase/assets/18327273/7d5c2fd2-04d9-4b45-aa5a-6e53a696b0bf)

From there I could access all the configuration settings etc, which were not available in the first screenshot.

**Comment by thinkbig1979** [comment]
Also, even now, I don't see a way to create collections.
![image](https://github.com/nocobase/nocobase/assets/18327273/bc538597-da77-44bb-8e5d-a06ad7c3a624)

**Comment by zhouyanliang** [comment]
> Also, even now, I don't see a way to create collections. ![image](https://private-user-images.githubusercontent.com/18327273/319124098-bc538597-da77-44bb-8e5d-a06ad7c3a624.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzY1NjcsIm5iZiI6MTcxMjEzNjI2NywicGF0aCI6Ii8xODMyNzI3My8zMTkxMjQwOTgtYmM1Mzg1OTctZGE3Ny00NGJiLThlNWQtYTA2YWQ3YzNhNjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA5MjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MGY3NjBiN2QzMTc0MjMxZjQ0OTY2MDc3ODQ0M2YyMzMzZjIyNGI3YWZkYzYxNzhiMTIyZGZjMDdlZDVlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JejE4AQzhr4N7falRgEmJJ5O0dAm2y2NcsNlsIt1xZc)

<img width="898" alt="image" src="https://github.com/nocobase/nocobase/assets/1267426/5989fc67-5bc2-4e13-b54a-7ca18c042877">

**Comment by thinkbig1979** [comment]
Ah, I see, in an online tutorial adding a collection was a menu item on the main menu, but I now see where you can do it under Data Sources. Thanks. :-)

**Comment by zhouyanliang** [comment]
<img width="975" alt="image" src="https://github.com/nocobase/nocobase/assets/1267426/147c4b55-cdba-4d2c-9c79-f5486e52050f">

Switch role  to root here.
