### ISSUE TITLE
页面显示创建时间比数据库晚8小时

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#393]
**Describe the bug**
页面显示创建时间比数据库晚8小时

**Version**
v0.7.0-alpha.34+mysql 8.0

**To Reproduce**
1. 将createdAt字段设置为显示时间
2. 配置页面创建时间字段

**Expected behavior**
时间与数据库一致

**Screenshots**
![image](https://user-images.githubusercontent.com/82276246/168459142-15aaebbc-c74d-4f47-ab21-4a031b410ed5.png)
![image](https://user-images.githubusercontent.com/82276246/168459168-dd8246ac-9355-4d20-b96e-19ff28cfd52f.png)
![image](https://user-images.githubusercontent.com/82276246/168459173-22f4fd71-f62e-4eb1-8cf6-36566535bd70.png)

**Comment by MarshalW** [comment]
这是时区问题吧？

mysql数据库记录的是 utc（世界协调时），相当于格林尼治时间。

界面显示的时候，可能根据浏览器/操作系统 locale 设置，猜测作者也在东八区，因此将时间增加了8个小时。

**Comment by 625412505** [comment]
> 看起来你用的那个数据库客户端把时区信息给省略了，实际上数据库保存的 date 是这样的，带时区的
> 
> <img alt="image" width="390" src="https://user-images.githubusercontent.com/2993310/171203654-10b9da97-e325-449a-8f00-9d54e6e53cbd.png">
> 
> 不过在表单里，日期显示的确有点问题，修复了 [94a4d39](https://github.com/nocobase/nocobase/commit/94a4d391c7909c96bac5f5993698499fddc6359d)
> 
> 关于时区，更多信息可以看 sequelize 的 issues
> 
> [sequelize/sequelize#854](https://github.com/sequelize/sequelize/issues/854) [sequelize/sequelize#2572](https://github.com/sequelize/sequelize/issues/2572)

代码是最新的，时间显示还是多8个小时
![image](https://user-images.githubusercontent.com/82276246/171382157-a32b7dc3-9bf0-48a2-8318-d3dda7e25188.png)
mysql数据库时区：
![image](https://user-images.githubusercontent.com/82276246/171387969-f38df42b-4856-4011-a7c4-6c260d0a66fe.png)

**Comment by budnail** [comment]
Google Translation to English:
Title: The page shows that the creation time is 8 hours later than the database

**Comment by 625412505** [comment]
> 日期问题已修复 [1c03fbb](https://github.com/nocobase/nocobase/commit/1c03fbb853b5885547835f50fc9a0932f63c363b)
> 
> 日期是随着时区变动的，如果需要统一时间，勾选 GMT
> 
> <img alt="image" width="771" src="https://user-images.githubusercontent.com/2993310/174101797-7cec6d41-0fa1-47d1-8bb8-35d64a438bbd.png">

我用最新的代码自己编译，没有出现GMT选项
![image](https://user-images.githubusercontent.com/82276246/174275460-5c046250-7c1d-4641-b77a-1adddd9a863e.png)

**Comment by chenos** [comment]
@625412505  CreatedAt 和 UpdatedAt 的日期是有时区的，没有 GMT 选项，Datetime（日期）字段才有 GMT 选项
