### ISSUE TITLE
Form (add new) Associated get undefined error 

### ISSUE THREAD

**Issue by nguyenhan-se** [nocobase/nocobase#3933]
## Describe the bug

When add block: Form (add new)  -> Associated records
-> get error: invalid input syntax for type bigint: "undefined"
## Version

v0.21.0-alpha.2

## How To Reproduce

1. Go to view detail record
2. Click on "popup" action on block detail
3. Add block Form (add new)  -> Associated records

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
Please use the latest version to check if it is resolved
