### ISSUE TITLE
Cannot create new field in collection on v0.21.0-alpha.1

### ISSUE THREAD

**Issue by okcodey** [nocobase/nocobase#3935]
## Describe the bug

I cannot create a new field of any type in my collections. I am getting the error in the screenshot below. I am currently on v0.21.0-alpha.1 on the test rig I am using. 

## Version
v0.21.0-alpha.1

## How To Reproduce
1. Go to 'Data Sources'-> Click on 'Configure'
2. Click on 'Configure fields' on one of your old Collections and choose any type of field
3. Fill in the necessary field details and click on 'Submit'
4. See the error below:
![unnamed](https://github.com/nocobase/nocobase/assets/147355081/e96b2836-5d8e-42f9-b41f-085f1b9e3422)

## Expected behavior
The expected behavior is for the field to be saved as part of the collection by clicking on the 'Submit' button

## Desktop (please complete the following information)

- OS: - Windows 11
- Browser - Firefox v124.0.2 (64-bit)

## Additional context
I have another rig that is running  v0.19.0-alpha.6, and I can create the field in my collections without any issues. This is probably a bug that has been carried down from this version to the current one.
I get the error also trying to create any type of field on the collection. 

This means that if you updated to v0.21.0-alpha.1, you will not be able to create additional fields in your previous collections in case you need to update whatever solution that you have created.

**Comment by chareice** [comment]
Hi @okcodey , To further troubleshoot the error, please provide the complete error message that is output in the server logs for this error

**Comment by okcodey** [comment]
> Hi @okcodey , To further troubleshoot the error, please provide the complete error message that is output in the server logs for this error

[logs.tar.gz](https://github.com/nocobase/nocobase/files/14901710/logs.2.tar.gz)

**Comment by chareice** [comment]
> > Hi @okcodey , To further troubleshoot the error, please provide the complete error message that is output in the server logs for this error
> 
> [logs.tar.gz](https://github.com/nocobase/nocobase/files/14901710/logs.2.tar.gz)

@okcodey 
1. What database do you use
2. After setting the environment variable DB_LOGGING=on, trigger the error again and inform me of the SQL statement that triggers the error

**Comment by okcodey** [comment]
This is all the logs in the system.

I wasn't trying to run any SQL statement. As stated in the initial email, I
was trying to create a new field in my old collections and i was getting
that error.

DB in use is Postgres.

**Comment by okcodey** [comment]
This is all the logs in the system.
I wasn't trying to run any SQL statement. As stated in the initial error message i sent, I was trying to create a new field in my old collections and i was getting that error.
DB in use is Postgres.

[logs.tar.gz](https://github.com/nocobase/nocobase/files/14943159/logs.4.tar.gz)

**Comment by okcodey** [comment]
> This is all the logs in the system. I wasn't trying to run any SQL statement. As stated in the initial error message i sent, I was trying to create a new field in my old collections and i was getting that error. DB in use is Postgres.
> 
> [logs.tar.gz ](https://github.com/nocobase/nocobase/files/14943159/logs.4.tar.gz)

I didn't get any acknowledgement on the latest reply I sent. Just want to make sure you got this @chareice

**Comment by chareice** [comment]
You can try again with the latest version, and if there are any issues, please open a new issue.
