### ISSUE TITLE
Error href tags for apps custom name

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#3948]
## Describe the bug

When I setup custom name for applications, menu links dosnt work.
Html href is setup with double slash "//my app custom name", instead of one slash "/my app custom name"

## Version

NocoBase
v0.21.0-alpha.2

## Screenshots
![image](https://github.com/nocobase/nocobase/assets/41135285/02518d57-8b8a-4cbc-a78a-916aebbab342)
App custom name 

![image](https://github.com/nocobase/nocobase/assets/41135285/3f7dfb11-5b8a-478c-b1bd-8da86b0c86cb)
App href in html

## Desktop (please complete the following information)

- Browser [e.g. chrome v102, safari]

**Comment by hongboji** [comment]
Complete domain name required

**Comment by pehua** [comment]
> Complete domain name required

Hi.

Here you can see that when I change to one slash, the short link work well.

https://github.com/nocobase/nocobase/assets/41135285/0e9da839-ae8e-497f-bf2c-1b8522966089

**Comment by pehua** [comment]
News?

**Comment by pehua** [comment]
Hi, any update?

**Comment by hongboji** [comment]
Issues will be closed, please continue to give feedback if you have questions!
