### ISSUE TITLE
After the Gantt chart is refreshed, the time display area is not refreshed and the previous time block is still retained

### ISSUE THREAD

**Issue by marsal1212** [nocobase/nocobase#3954]
## Version
v0.21.0-alpha.4

## How To Reproduce
After the Gantt chart is refreshed, the time display area is not refreshed and the previous time block is still retained

## Expected behavior
Correct refresh

## Screenshots
![image](https://github.com/nocobase/nocobase/assets/20449902/b8eeec35-1ff8-4487-a200-1d05d586b298)

## Desktop (please complete the following information)

- OS: [windows 11 ]
- Browser [Chrome/123.0.0.0]

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/3982
