### ISSUE TITLE
Duplicate record same when we set data scope on table

### ISSUE THREAD

**Issue by nguyenhan-se** [nocobase/nocobase#3961]
## Describe the bug

when use table collection has association, config data-scope add field createBy is current user => table duplicate record same data

## Version

v0.21.0-alpha.2

## How To Reproduce

1. Go to table has association
2. Click on 'Set the data scope'
3. Add condition: createBy/id is currentUser/id
4. Back to table and reload data
5. See error

## Expected behavior

one record instead duplicate record

## Screenshots
![Screenshot 2024-04-08 at 10 25 45](https://github.com/nocobase/nocobase/assets/51753522/65ae8d31-a2f7-44d5-b7af-15ff5708cbe4)

## Desktop (please complete the following information)

- OS: macos
- Browser chrome

**Comment by hongboji** [comment]
Please do the following to provide more information in order to locate the solution to the problem
1、Please upgrade to the latest version to check if this problem exists
2、May I know how to deploy, git docker?
3、What type of data table is it: normal table, view?
4、Please do not set the data scope, check whether the data is duplicated?

**Comment by nguyenhan-se** [comment]
Please do the following to provide more information in order to locate the solution to the problem
1、newest version
2、git deployment
3、block: normal table, workflow todos 
4、Just duplicated when data-scope add field createBy is current user, if dont have 'createBy' -> no duplicated

**Comment by nguyenhan-se** [comment]
> Please do the following to provide more information in order to locate the solution to the problem 1、Please upgrade to the latest version to check if this problem exists 2、May I know how to deploy, git docker? 3、What type of data table is it: normal table, view? 4、Please do not set the data scope, check whether the data is duplicated?

1、newest version
2、git deployment
3、block: normal table, workflow todos
4、Just duplicated when data-scope add field createBy is current user, if dont have 'createBy' -> no duplicated

**Comment by hongboji** [comment]
Issues will be closed, please continue to give feedback if you have questions!
