### ISSUE TITLE
创建时提示C:\Program' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by shuangtoulanpang** [nocobase/nocobase#397]
**Describe the bug**
创建时提示C:\Program' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

**Version**
v1.22.18

**To Reproduce**
1. 执行“yarn create nocobase-app my-nocobase-app”命令
2. 提示C:\Program' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

**Expected behavior**
能创建成功

**Screenshots**
![企业微信截图_20220516101058](https://user-images.githubusercontent.com/105617249/168508394-19a8ad09-90bd-4599-b4fc-c4966a876109.png)

**Desktop (please complete the following information):**
 - OS: [win10]

**Comment by chenos** [comment]
nodejs 没安装好，也可能是环境变量问题，百度、google 搜一下相关解决方案。如果不知道怎么解决，推荐使用 Docker 安装

https://github.com/nocobase/nocobase#docker-recommended
