### ISSUE TITLE
0.21.a.6编译错误

### ISSUE THREAD

**Issue by jor2003** [nocobase/nocobase#3987]
## Describe the bug
执行yarn build时，提示报错

## Version

0.21.a.6

## How To Reproduce

git pull代码后，重新执行build

## Screenshots

@nocobase/cache: core/cache build start
@nocobase/cache: build cjs
@nocobase/cache: build declaration
packages/core/cache/src/bloom-filter/redis-bloom-filter.ts(14,3): error TS2742: The inferred type of 'getStore' cannot be named without a reference to 'cache-manager-redis-yet/node_modules/redis'. This is likely not portable. A type annotation is necessary.
TypeScript: 1 declaration error
TypeScript: emit failed
/opt/nocobase/node_modules/gulp-typescript/release/output.js:131
            this.streamFull.emit('error', new Error("TypeScript: Compilation failed"));
                                          ^

Error: TypeScript: Compilation failed
    at Output.mightFinish (/opt/nocobase/node_modules/gulp-typescript/release/output.js:131:43)
    at /opt/nocobase/node_modules/gulp-typescript/release/output.js:44:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on CompileStream instance at:
    at /opt/nocobase/node_modules/gulp-typescript/release/output.js:117:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

## Desktop (please complete the following information)

chrome 123

**Comment by jor2003** [comment]
报错页面补充：
Node.js v21.2.0
/opt/nocobase/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: nocobase-build    
    at makeError (/opt/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/opt/nocobase/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/opt/nocobase/packages/core/cli/src/commands/build.js:30:7) {
  shortMessage: 'Command failed with exit code 1: nocobase-build    ',
  command: 'nocobase-build    ',
  escapedCommand: 'nocobase-build "" "" "" ""',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v21.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenos** [comment]
```bash
yarn nocobase clean
rm -rf node_modules # 或手动删除 node_modules
yarn install
yarn build
```

如果还有问题，排查一下 yarn.lock 是否被修改了，如果被改过，还原一下

**Comment by jor2003** [comment]
试过了，确实修复了。
非常感谢
