### ISSUE TITLE
Series of bugs when using a tree table connected to an associated record of the main entity inside an edit drawer of the main entity

### ISSUE THREAD

**Issue by CrineTech** [nocobase/nocobase#3988]
## Describe the bug

Please note that i've recorded all the videos with edit mode enabled to make more easy to seee where i'm clicking, but all the bugs are reproducible also with edit mode disabled.

I've discovered these bugs while trying to create an ui to create projects and add multi level tasks to the project itself, that i think is a common usage scenario for this tool.

1) When adding nodes in the tree table only the first level nodes can be added (from the add new button). When a n-th level is added using the add child button the error "Cannot read properties of null (reading 'createTask')" is displayed and the node is not created.

https://github.com/nocobase/nocobase/assets/108331742/190278ae-c3f4-4893-afb6-28b666ce7a3b

2. The tree table is displayed as a regular table, even if the tree table switch is activated. If the tree table switch is deactivated and reactivated the table is properly displayed as a tree list, but if the drawer is closed and reopened the table is again shown as a regular table.

https://github.com/nocobase/nocobase/assets/108331742/8d155f4e-5464-41ad-8981-5666a891e6cc

3. I've added an "Order" field to the Tasks collection, that is using the project id as grouping. If i enable the drag&drop sorting and select the corresponding field (and disable and re enable the tree list switch to get a correct view) when i try to reorder tasks i get the error "association tasks in projects is not sortable". 

I can undesrstand this error for normal sortings, but a special consideration should be used in cases like this, when the order column (the field of sort type) have a grouping field that is the same foreign key of the association. In this case there is no reason to prevent the ordering, since all the rows relevant to the ordering are part of the association collection.

https://github.com/nocobase/nocobase/assets/108331742/b846b5ab-a660-4000-a987-74c54416bb6f

## Version

Replicated on NocoBase v0.21.0-alpha.6 self hosted (docker) and NocoBase v0.21.0-alpha.6.20240408134846 online live demo

## How To Reproduce

1. Start from the base project of the online demo
2. Add a general collection named Projects to the standard datasource
3. Add a single text line field named Name to Project collection
4. Add a tree collection named Tasks to the standard datasource
5. Add a single text line field named Name to Tasks collection
6. Add a markdown field named Description to Tasks collection
7. Add a many to one relationship between Tasks ans Projects (adding association also in the target collection)
8. Add a sort field to Tasks collection, selecting the project foreign key as grouping column
9. Create a page with a standard table selecting Projects collection
10. Add the add new button and create a form with the name field and the submit button
11. Enable the edit button for the action column of the table
12. Configure the edit drawer as the add new, then add a second tab with a table pointing to the Tasks association
13. Enable the tree table flag and allow sorting selecting the corresponding field in the above table
14. Check videos, you should now be able to reproduce the same behaviors

I've made a backup of the online test project (NocoBase v0.21.0-alpha.6.20240408134846) used for the uploaded videos. I hope that this is helpful. I have to add the ".pdf" extension to be able to load it to github, once downloaded remove it, leaving only the .nbdump extension

[backup_20240409_065000_2488.nbdump.pdf](https://github.com/nocobase/nocobase/files/14914398/backup_20240409_065000_2488.nbdump.pdf)

## Desktop (please complete the following information)

- OS: Windows 10 X64
- Browser Edge 123.0.2420.81, Firefox 124.0.2

**Comment by hongboji** [comment]
Issues 1 and 2 have been fixed, issue 3 is not currently supported.
Please use the latest code and check if it is fixed
