### ISSUE TITLE
App error - Collection model roles has no primary key attribute

### ISSUE THREAD

**Issue by jamesgid-gc** [nocobase/nocobase#4037]
## Describe the bug

Hi team. I am very new to Nocobase, so my apologies if I have missed something basic. Using Portainer, I created a nocobase container and was able to use it. However, it was completely default with no env variables, so nothing was persistent. I have since created a contaner for MariaDB and then declared env variables for nocobase. However, upon starting the container I see 'App error - Collection model roles has no primary key attribute' error in the web interface. 
The data base connection is working because tables have been created. Not sure what else I have missed. 
The log file also has these entries:
`copying...
yarn run v1.22.19
$ nocobase create-nginx-conf
Done in 0.28s.
nginx started
yarn run v1.22.19
$ nocobase start --quickstart
2024-04-15T03:13:55: PM2 log: Launching in no daemon mode
2024-04-15T03:13:55: PM2 log: App [index:0] starting in -fork mode-
2024-04-15T03:13:55: PM2 log: App [index:0] online
Gateway IPC Server running at /app/nocobase/storage/gateway.sock
Gateway HTTP Server running at http://0.0.0.0:13000/
INF add app main into supervisor | meta={} module=application submodule=supervisor method=addApp app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:57
INF connection has been established successfully. | meta={} module=database submodule= method=auth app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:57
INF upgrading... | meta={} module=application submodule= method= app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:57
INF run upgrade | meta={} module=application submodule= method= app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:57
INF update built-in plugins | meta={} module=nocobase submodule= method= app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:57
new client connected ravcxOTIfoOjJZiv-e9xs
client tags: app#main
INF run upgrade | meta={} module=application submodule= method= app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:59
INF restarting... | meta={} module=application submodule= method= app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:59
INF app.reload() | meta={} module=application submodule= method=load app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:59
ERR Collection model roles has no primary key attribute | stack=Error: Collection model roles has no primary key attribute
    at _BelongsToManyField.bind (/app/nocobase/node_modules/@nocobase/database/lib/fields/belongs-to-many-field.js:107:13)
    at _Collection.<anonymous> (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:621:13)
    at _Collection.emit (node:events:517:28)
    at _Collection.emit (node:domain:489:12)
    at _Collection.setField (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:267:10)
    at EnsureAtomicity.descriptor.value (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:58:29)
    at /app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/models/field.js:45:25
    at async model.load (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/models/field.js:43:19)
    at async model.loadFields (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/models/collection.js:110:7)
    at async CollectionRepository.load (/app/nocobase/node_modules/@nocobase/plugin-collection-manager/dist/server/repositories/collection-repository.js:119:7) meta={} module=application submodule= method= app=main reqId=de4e2b6e-0a20-449d-a1e0-bb495b728856 timestamp=2024-04-15 03:13:59
client disconnected ravcxOTIfoOjJZiv-e9xs
WRN app is not running | meta={"status":"error"} module=gateway submodule= method=requestHandler app=main reqId=020b4b01-49e2-4af4-b680-05a0029d0b67 timestamp=2024-04-15 03:30:09
ERR Collection model roles has no primary key attribute | meta={"error":{"status":503,"message":"Collection model roles has no primary key attribute","code":"APP_ERROR","command":{"name":"start"},"maintaining":true}} module=gateway submodule= method=responseErrorWithCode app=main reqId=c358ad69-19b5-46cd-98eb-929da790364b timestamp=2024-04-15 03:30:09
new client connected ZswavY0BVM1OXWDFHLj_D
client tags: app#main`

## Version

18.20.2
## How To Reproduce

As above, launch new container, error presents upon start.

**Comment by Decapitares** [comment]
I have the same problem with mysql, it created the tables and the primary key is as it should be.

**Comment by Jackxwb** [comment]
The same issue occurred with the Docker+MySQL I used
(I am using the baota panel in MySQL, and I can see that many tables have been created.)
Docker error log:
```
client disconnected YvqEMwj_l-bHEc9DrK8-M
WRN app is not running | meta={"status":"error"} module=gateway submodule= method=requestHandler app=main reqId=1b78da36-981c-4e8d-8c37-17d225e6b555 dataSourceKey=main timestamp=2024-05-28 02:50:45
ERR Collection model roles has no primary key attribute | meta={"error":{"status":503,"message":"Collection model roles has no primary key attribute","code":"APP_ERROR","command":{"name":"start"},"maintaining":true}} module=gateway submodule= method=responseErrorWithCode app=main reqId=b408ab09-8aef-4fc8-aa85-6295244a275b dataSourceKey=main timestamp=2024-05-28 02:50:45

new client connected PpToxihV_LtTwmreGWCdB
client tags: app#main
yarn run v1.22.19
$ nocobase create-nginx-conf
Done in 8.53s.
nginx started
yarn run v1.22.19
$ nocobase start --quickstart
2024-05-28T02:51:23: PM2 log: Launching in no daemon mode
2024-05-28T02:51:23: PM2 log: App [index:0] starting in -fork mode-
2024-05-28T02:51:23: PM2 log: App [index:0] online
Gateway IPC Server running at /app/nocobase/storage/gateway.sock
Gateway HTTP Server running at http://0.0.0.0:13000/
INF add app main into supervisor | meta={} module=application submodule=supervisor method=addApp app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:03
new client connected 5vpkIkD86Jb07bRdmvRE0
client tags: app#main
INF connection has been established successfully. | meta={} module=database submodule= method=auth app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:03
INF upgrading... | meta={} module=application submodule= method= app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:03
INF run upgrade | meta={} module=application submodule= method= app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:03
INF update built-in plugins | meta={} module=nocobase submodule= method= app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:03
INF run upgrade | meta={} module=application submodule= method= app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:17
INF restarting... | meta={} module=application submodule= method= app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:19
INF app.reload() | meta={} module=application submodule= method=load app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:20
ERR Collection model roles has no primary key attribute | stack=Error: Collection model roles has no primary key attribute
    at _BelongsToManyField.bind (/app/nocobase/node_modules/@nocobase/database/lib/fields/belongs-to-many-field.js:116:13)
    at _Collection.<anonymous> (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:629:13)
    at _Collection.emit (node:events:517:28)
    at _Collection.emit (node:domain:489:12)
    at _Collection.setField (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:285:10)
    at EnsureAtomicity.descriptor.value (/app/nocobase/node_modules/@nocobase/database/lib/collection.js:68:29)
    at /app/nocobase/node_modules/@nocobase/plugin-data-source-main/dist/server/models/field.js:54:25
    at async model.load (/app/nocobase/node_modules/@nocobase/plugin-data-source-main/dist/server/models/field.js:52:19)
    at async model.loadFields (/app/nocobase/node_modules/@nocobase/plugin-data-source-main/dist/server/models/collection.js:128:7)
    at async CollectionRepository.load (/app/nocobase/node_modules/@nocobase/plugin-data-source-main/dist/server/repositories/collection-repository.js:131:7) meta={} module=application submodule= method= app=main reqId=685cafa0-5f0c-42ed-90d6-9287758d94c6 dataSourceKey=main timestamp=2024-05-28 02:52:21
```

web page
![image](https://github.com/nocobase/nocobase/assets/34720403/499e1240-8e6a-4d2a-8c4a-484924488c62)

database
![image](https://github.com/nocobase/nocobase/assets/34720403/89924eec-ecf3-4db3-94b5-4d05e66b7be9)

```
select version() from dual;
> 10.3.25-MariaDB-log
```

**Comment by zhouyanliang** [comment]
> Hi team. I am very new to Nocobase, so my apologies if I have missed something basic. Using Portainer, I created a nocobase container and was able to use it. However, it was completely default with no env variables, so nothing was persistent. I have since created a contaner for MariaDB and then declared env variables for nocobase. However, upon starting the container I see 'App error - Collection model roles has no primary key attribute' error in the web interface.
> The data base connection is working because tables have been created. Not sure what else I have missed.
> The log file also has these entries:

You are using MariaDB but DB_DIALECT=mysql

**Comment by genfild** [comment]
I also encountered this problem. My collection lost its primary key and therefore the application is throwing an error:

Target model collection* has no primary key attribute.
*collection - custom collection

I can see there's also a topic raised on the forum [Target model users has no primary key attribute](https://forum.nocobase.com/t/target-model-users-has-no-primary-key-attribute/9736)

As I can see, there's no solution yet.

**Comment by genfild** [comment]
DB_DIALECT=postgres
data base  postgres16

I tried changing APP_KEY

**Comment by genfild** [comment]
I corrected the value of the options column in the database for the id row of the problematic collection.
added
```
"autoIncrement": true,
  "primaryKey": true,
```

<img width="299" height="274" alt="Image" src="https://github.com/user-attachments/assets/97d20a11-d8bd-4fa2-b7f5-d02f6c5a1e78" />

was
```
{
    "isForeignKey": true,
    "uiSchema": {
        "type": "number",
        "title": "id",
        "x-component": "InputNumber",
        "x-read-pretty": true
    },
    "overriding": true
}
```
