### ISSUE TITLE
构建docker镜像的Dockerfile

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#404]
自己根据最新代码构建docker镜像，可否提供下Dockerfile文件和相关脚本，谢谢。

**Comment by MarshalW** [comment]
我做过，可以介绍下基本步骤。

server和client分别做 dockerfile

需要参考 `packages/app` 下的 `client` 和 `server`，分别实现自己的 client 和 server 项目。

然后是需要考虑怎么引入nocobase这些包。

我做的那会儿最新版本（main分支）还没有自动构建发布到npm registry，我就是简单粗暴的将子项目复制到`node_modules`下了，类似这样：

```bash
#!/bin/bash

nocobase_dir=$1

packages=(
    "utils"
    "server"
    "database"
    "resourcer"
    "actions"
    "acl"
)

rm -rf node_modules/@nocobase

mkdir node_modules/@nocobase

for package in ${packages[@]}; do
    cp -r $nocobase_dir/packages/core/$package node_modules/@nocobase
done

packages=(
    "acl"
    "users"
    "error-handler"
    "collection-manager"
    "ui-schema-storage"
    "ui-routes-storage"
    "file-manager"
    "system-settings"
    "china-region"
    "workflow"
    "client"
)

for package in ${packages[@]}; do
    cp -r $nocobase_dir/packages/plugins/$package node_modules/@nocobase/plugin-$package/
done
```

缺点是相关依赖包必须自己手动写入到`packages.json`中。

现在好了，每个更新都会自动发布到npm上，其实server端只需packages.json中声明就好了，不过我没有测试。

server端 dockerfile 基本步骤：

- 多阶段构建
- 第一阶段，clone并构建nocobase
- 第二阶段，复制第一阶段编译的文件，启动 server 
- 需要考虑的是目前server代码未对退出做处理会造成停止时等待10秒，我用`tini`解决的

类似这样：

```dockerfile
FROM node:16-alpine

RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN \
    apk --no-cache add \
    git \
    bash

WORKDIR /usr/src

RUN git clone https://github.com/nocobase/nocobase.git
RUN cd nocobase && git checkout nocobase-next

WORKDIR /usr/src/nocobase

RUN yarn
RUN yarn bootstrap
RUN yarn build

WORKDIR /usr/src/app

COPY package*.json .
RUN npm i

COPY tsconfig.json .
COPY ./src ./src

COPY ./cp-nocobase-packages.sh ./cp-nocobase-packages.sh
RUN /usr/src/app/cp-nocobase-packages.sh /usr/src/nocobase

RUN npm run build


FROM node:16-alpine

RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN \
    apk --no-cache add \
    tini 

WORKDIR /usr/src/app

COPY --from=0 /usr/src/app/node_modules ./node_modules
COPY --from=0 /usr/src/app/lib ./lib
COPY package*.json .

ENTRYPOINT ["tini","--","node", "lib/app.js"]
```

目前麻烦在client端，ts文件的 build，tsc不能自动将资源文件放置到对应目录下，会出现less文件或字体文件找不到的问题（我之前的简单copy没有这个问题，因为我也cp了这些文件）

我尝试给client端这个问题做了解决，发了 pull request，见：https://github.com/nocobase/nocobase/pull/403

client端另一个麻烦的事情是，`SERVER_BASE_URL`，这个环境变量会在umi编译时写死在生成的js代码中，因为前端代码是静态的，我是在dockerfile中启动时调用脚本做处理的。

这是 client端的dockerfile，使用nginx做 http server

```dockerfile
FROM node:16-alpine

RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN \
    apk --no-cache add \
    git \
    bash

WORKDIR /usr/src

RUN git clone https://github.com/nocobase/nocobase.git
RUN cd nocobase && git checkout nocobase-next

WORKDIR /usr/src/nocobase

RUN yarn
RUN yarn bootstrap
RUN yarn build

WORKDIR /usr/src/app

COPY package*.json .

COPY tsconfig.json .
COPY typings.d.ts .
COPY umi.cli.js .
COPY .umirc.ts .

COPY ./src ./src
COPY ./public ./public

RUN yarn

COPY ./cp-nocobase-packages.sh ./cp-nocobase-packages.sh
RUN /usr/src/app/cp-nocobase-packages.sh /usr/src/nocobase

COPY ./.env.docker ./.env
RUN yarn build


FROM nginx:alpine

COPY --from=0 /usr/src/app/dist /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
COPY ./start.sh .

CMD /usr/share/nginx/html/start.sh
```

**Comment by 625412505** [comment]
> 我做过，可以介绍下基本步骤。
> 
> server和client分别做 dockerfile
> 
> 需要参考 `packages/app` 下的 `client` 和 `server`，分别实现自己的 client 和 server 项目。
> 
> 然后是需要考虑怎么引入nocobase这些包。
> 
> 我做的那会儿最新版本（main分支）还没有自动构建发布到npm registry，我就是简单粗暴的将子项目复制到`node_modules`下了，类似这样：
> 
> ```shell
> #!/bin/bash
> 
> nocobase_dir=$1
> 
> packages=(
>     "utils"
>     "server"
>     "database"
>     "resourcer"
>     "actions"
>     "acl"
> )
> 
> rm -rf node_modules/@nocobase
> 
> mkdir node_modules/@nocobase
> 
> for package in ${packages[@]}; do
>     cp -r $nocobase_dir/packages/core/$package node_modules/@nocobase
> done
> 
> packages=(
>     "acl"
>     "users"
>     "error-handler"
>     "collection-manager"
>     "ui-schema-storage"
>     "ui-routes-storage"
>     "file-manager"
>     "system-settings"
>     "china-region"
>     "workflow"
>     "client"
> )
> 
> for package in ${packages[@]}; do
>     cp -r $nocobase_dir/packages/plugins/$package node_modules/@nocobase/plugin-$package/
> done
> ```
> 
> 缺点是相关依赖包必须自己手动写入到`packages.json`中。
> 
> 现在好了，每个更新都会自动发布到npm上，其实server端只需packages.json中声明就好了，不过我没有测试。
> 
> server端 dockerfile 基本步骤：
> 
> * 多阶段构建
> * 第一阶段，clone并构建nocobase
> * 第二阶段，复制第一阶段编译的文件，启动 server
> * 需要考虑的是目前server代码未对退出做处理会造成停止时等待10秒，我用`tini`解决的
> 
> 类似这样：
> 
> ```dockerfile
> FROM node:16-alpine
> 
> RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
> 
> RUN \
>     apk --no-cache add \
>     git \
>     bash
> 
> WORKDIR /usr/src
> 
> RUN git clone https://github.com/nocobase/nocobase.git
> RUN cd nocobase && git checkout nocobase-next
> 
> WORKDIR /usr/src/nocobase
> 
> RUN yarn
> RUN yarn bootstrap
> RUN yarn build
> 
> WORKDIR /usr/src/app
> 
> COPY package*.json .
> RUN npm i
> 
> COPY tsconfig.json .
> COPY ./src ./src
> 
> COPY ./cp-nocobase-packages.sh ./cp-nocobase-packages.sh
> RUN /usr/src/app/cp-nocobase-packages.sh /usr/src/nocobase
> 
> RUN npm run build
> 
> 
> FROM node:16-alpine
> 
> RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
> 
> RUN \
>     apk --no-cache add \
>     tini 
> 
> WORKDIR /usr/src/app
> 
> COPY --from=0 /usr/src/app/node_modules ./node_modules
> COPY --from=0 /usr/src/app/lib ./lib
> COPY package*.json .
> 
> ENTRYPOINT ["tini","--","node", "lib/app.js"]
> ```
> 
> 目前麻烦在client端，ts文件的 build，tsc不能自动将资源文件放置到对应目录下，会出现less文件或字体文件找不到的问题（我之前的简单copy没有这个问题，因为我也cp了这些文件）
> 
> 我尝试给client端这个问题做了解决，发了 pull request，见：#403
> 
> client端另一个麻烦的事情是，`SERVER_BASE_URL`，这个环境变量会在umi编译时写死在生成的js代码中，因为前端代码是静态的，我是在dockerfile中启动时调用脚本做处理的。
> 
> 这是 client端的dockerfile，使用nginx做 http server
> 
> ```dockerfile
> FROM node:16-alpine
> 
> RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
> 
> RUN \
>     apk --no-cache add \
>     git \
>     bash
> 
> WORKDIR /usr/src
> 
> RUN git clone https://github.com/nocobase/nocobase.git
> RUN cd nocobase && git checkout nocobase-next
> 
> WORKDIR /usr/src/nocobase
> 
> RUN yarn
> RUN yarn bootstrap
> RUN yarn build
> 
> WORKDIR /usr/src/app
> 
> COPY package*.json .
> 
> COPY tsconfig.json .
> COPY typings.d.ts .
> COPY umi.cli.js .
> COPY .umirc.ts .
> 
> COPY ./src ./src
> COPY ./public ./public
> 
> RUN yarn
> 
> COPY ./cp-nocobase-packages.sh ./cp-nocobase-packages.sh
> RUN /usr/src/app/cp-nocobase-packages.sh /usr/src/nocobase
> 
> COPY ./.env.docker ./.env
> RUN yarn build
> 
> 
> FROM nginx:alpine
> 
> COPY --from=0 /usr/src/app/dist /usr/share/nginx/html
> COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
> 
> WORKDIR /usr/share/nginx/html
> COPY ./start.sh .
> 
> CMD /usr/share/nginx/html/start.sh
> ```

感谢，我试试。

**Comment by isrehk** [comment]
> 我做过，可以介绍下基本步骤。
> 
> server和client分别做 dockerfile
> 
> 需要参考 `packages/app` 下的 `client` 和 `server`，分别实现自己的 client 和 server 项目。
> 
> 然后是需要考虑怎么引入nocobase这些包。
> 
> 我做的那会儿最新版本（main分支）还没有自动构建发布到npm registry，我就是简单粗暴的将子项目复制到`node_modules`下了，类似这样：
> 
> ```shell
> #!/bin/bash
> 
> nocobase_dir=$1
> 
> packages=(
>     "utils"
>     "server"
>     "database"
>     "resourcer"
>     "actions"
>     "acl"
> )
> 
> rm -rf node_modules/@nocobase
> 
> mkdir node_modules/@nocobase
> 
> for package in ${packages[@]}; do
>     cp -r $nocobase_dir/packages/core/$package node_modules/@nocobase
> done
> 
> packages=(
>     "acl"
>     "users"
>     "error-handler"
>     "collection-manager"
>     "ui-schema-storage"
>     "ui-routes-storage"
>     "file-manager"
>     "system-settings"
>     "china-region"
>     "workflow"
>     "client"
> )
> 
> for package in ${packages[@]}; do
>     cp -r $nocobase_dir/packages/plugins/$package node_modules/@nocobase/plugin-$package/
> done
> ```
> 
> 缺点是相关依赖包必须自己手动写入到`packages.json`中。
> 
> 现在好了，每个更新都会自动发布到npm上，其实server端只需packages.json中声明就好了，不过我没有测试。
> 
> server端 dockerfile 基本步骤：
> 
> * 多阶段构建
> * 第一阶段，clone并构建nocobase
> * 第二阶段，复制第一阶段编译的文件，启动 server
> * 需要考虑的是目前server代码未对退出做处理会造成停止时等待10秒，我用`tini`解决的
> 
> 类似这样：
> 
> ```dockerfile
> FROM node:16-alpine
> 
> RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
> 
> RUN \
>     apk --no-cache add \
>     git \
>     bash
> 
> WORKDIR /usr/src
> 
> RUN git clone https://github.com/nocobase/nocobase.git
> RUN cd nocobase && git checkout nocobase-next
> 
> WORKDIR /usr/src/nocobase
> 
> RUN yarn
> RUN yarn bootstrap
> RUN yarn build
> 
> WORKDIR /usr/src/app
> 
> COPY package*.json .
> RUN npm i
> 
> COPY tsconfig.json .
> COPY ./src ./src
> 
> COPY ./cp-nocobase-packages.sh ./cp-nocobase-packages.sh
> RUN /usr/src/app/cp-nocobase-packages.sh /usr/src/nocobase
> 
> RUN npm run build
> 
> 
> FROM node:16-alpine
> 
> RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
> 
> RUN \
>     apk --no-cache add \
>     tini 
> 
> WORKDIR /usr/src/app
> 
> COPY --from=0 /usr/src/app/node_modules ./node_modules
> COPY --from=0 /usr/src/app/lib ./lib
> COPY package*.json .
> 
> ENTRYPOINT ["tini","--","node", "lib/app.js"]
> ```
> 
> 目前麻烦在client端，ts文件的 build，tsc不能自动将资源文件放置到对应目录下，会出现less文件或字体文件找不到的问题（我之前的简单copy没有这个问题，因为我也cp了这些文件）
> 
> 我尝试给client端这个问题做了解决，发了 pull request，见：#403
> 
> client端另一个麻烦的事情是，`SERVER_BASE_URL`，这个环境变量会在umi编译时写死在生成的js代码中，因为前端代码是静态的，我是在dockerfile中启动时调用脚本做处理的。
> 
> 这是 client端的dockerfile，使用nginx做 http server
> 
> ```dockerfile
> FROM node:16-alpine
> 
> RUN set -eux && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
> 
> RUN \
>     apk --no-cache add \
>     git \
>     bash
> 
> WORKDIR /usr/src
> 
> RUN git clone https://github.com/nocobase/nocobase.git
> RUN cd nocobase && git checkout nocobase-next
> 
> WORKDIR /usr/src/nocobase
> 
> RUN yarn
> RUN yarn bootstrap
> RUN yarn build
> 
> WORKDIR /usr/src/app
> 
> COPY package*.json .
> 
> COPY tsconfig.json .
> COPY typings.d.ts .
> COPY umi.cli.js .
> COPY .umirc.ts .
> 
> COPY ./src ./src
> COPY ./public ./public
> 
> RUN yarn
> 
> COPY ./cp-nocobase-packages.sh ./cp-nocobase-packages.sh
> RUN /usr/src/app/cp-nocobase-packages.sh /usr/src/nocobase
> 
> COPY ./.env.docker ./.env
> RUN yarn build
> 
> 
> FROM nginx:alpine
> 
> COPY --from=0 /usr/src/app/dist /usr/share/nginx/html
> COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
> 
> WORKDIR /usr/share/nginx/html
> COPY ./start.sh .
> 
> CMD /usr/share/nginx/html/start.sh
> ```

关闭了还可以请教吗？

我直接采用 `yarn start` 的方式来启动~ image 很大~
