### ISSUE TITLE
Windows 环境下，无法clone项目

### ISSUE THREAD

**Issue by liusimon** [nocobase/nocobase#405]
文档目录有文件的名称不能在Windows环境下正确创建：
D:\projects\ap>git clone https://github.com//nocobase/nocobase.git
Cloning into 'nocobase'...
remote: Enumerating objects: 31266, done.
remote: Counting objects: 100% (1963/1963), done.
remote: Compressing objects: 100% (919/919), done.
remote: Total 31266 (delta 1055), reused 1751 (delta 961), pack-reused 29303
Receiving objects: 100% (31266/31266), 32.32 MiB | 4.59 MiB/s, done.
Resolving deltas: 100% (20385/20385), done.
error: invalid path 'docs/en-US/development/plugin-development/client/providers/?api-client.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by liusimon** [comment]
还有一个文件也是类似问题：
error: invalid path 'docs/zh-CN/development/plugin-development/client/providers/?api-client.md'

**Comment by liusimon** [comment]
还有一个文件也是一样的问题：

error: invalid path 'docs/zh-CN/development/plugin-development/client/providers/?api-client.md'




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nocobase/nocobase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nocobase/nocobase] Windows 环境下，无法clone项目 (Issue #405)





 
已修复，再试一下

**Comment by zhouyanliang** [comment]
已修复
