### ISSUE TITLE
通过Git源码方式安装启动：TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by haomiemie** [nocobase/nocobase#406]
版本信息：
  nodejs:12.20.0、15.8.0
  yarn: 1.22.18

执行过程：
  1、将.env.example文件内容复制到.env中并配置
  2、yarn install
  3、yarn nocobase install
  4、yarn build
  5、yarn start

问题描述：
  
![image](https://user-images.githubusercontent.com/49633891/169231394-12d80317-8290-479b-82c6-f2ffc818a719.png)

补充：.env文件详情
![image](https://user-images.githubusercontent.com/49633891/169231657-56c18211-cd9c-4938-9107-3cd5743a7f2b.png)

**Comment by chenos** [comment]
env 看起来有问题，可以按照最新版文档，再操作一遍
https://docs.nocobase.com/getting-started/installation/git-clone
