### ISSUE TITLE
Many to many Intermediate table not showing

### ISSUE THREAD

**Issue by luxwarp** [nocobase/nocobase#4061]
## Describe the bug
Created a relation many to many between collection Trainer and Team, through the intermediate table team_trainers. Works as expected, but i cannot see this table/collection in data sources collections list so i cannot add any more fields to it.

Am i missing something or is it not possible to edit an Intermediate table for many to many relations?

## Version

v0.21.0-alpha.8.20240416095740

## How To Reproduce
Create a many to many relation between two collections.
No new collection is visible in data sources collections list.

## Expected behavior

A collection  should be visible and you should be able to add more fields to it.

## Screenshots
![Screenshot_20240416_192013](https://github.com/nocobase/nocobase/assets/40615745/26333f91-b84f-457e-8972-caf1e94b3792)
![Screenshot_20240416_192100](https://github.com/nocobase/nocobase/assets/40615745/02d9d5e9-8e5a-48e0-87dc-f0309b8e4a72)

## Desktop (please complete the following information)

- OS: Manjaro Linux
- Browser Firefox

**Comment by hongboji** [comment]
1, add a new collection with the name abc
2, add a many-to-many relationship field, the middle data table select abc
