### ISSUE TITLE
Fields from related table - Nocobase Demo

### ISSUE THREAD

**Issue by RogerPenna** [nocobase/nocobase#407]
Hi. I am trying the Nocobase demo.

I noticed that because there is still no calculation field, when creating a new order, you have to manually (or mentally) multiply the item value by the quantity and type the total value.

The problem however starts there. 

When creating a new order, you can include several items in the order details and their quantity. So you click to add a product. 

Now you can click to add a product, where you see the name of the product, unit VALUE and photos.

I select a product. But the dropdown list only shows the NAME of the product. So I insert quantity. Insert more products and quantities. Submit and go back to main "new order" window. I have a list of products and quantities, but I can´t see the unitary values of each product.

When editing the forms, nowhere can I select to show BOTH item name and value. I can change the title field to "value", but then I only get the value without the name of the product.

Am I doing something wrong or is this a limitation right now?

**Comment by zhouyanliang** [comment]
Thanks for the feedback.

There are two plugins in our list which will be live in next few months

- Reference and copy data from other tables
- Formula

**Comment by chenos** [comment]
In the latest version(v0.7.2-alpha.1), you can display relationship table(association) fields in blocks.
