### ISSUE TITLE
Bug: Upload Service Error:  when uploading attachment to S3 

### ISSUE THREAD

**Issue by mz0in** [nocobase/nocobase#4097]
when uploading attachment 
<img width="462" alt="image" src="https://github.com/nocobase/nocobase/assets/5844695/e86a92aa-d24b-4f17-aca4-fd07d3d8038d">

**Comment by hongboji** [comment]
More information is needed to judge and analyse the problem:
1, what is the deployment method , such as git, docker?
2、Configuration file .env enable logging
DB_LOGGING=on
LOGGER_LEVEL=debug
 Provide detailed logs when reporting errors
3、Browser network request error message
