### ISSUE TITLE
【BUG】导出表格内容不完整

### ISSUE THREAD

**Issue by zhou-xh** [nocobase/nocobase#4106]
## 问题说明
当数据表存在“多对一”关系字段的时候，导出表格，字段内容均为“[object SequelizeInstance:users]”
导入的时候如多对一关系字段存在内容任何内容均会导入失败

## 问题版本
v0.21.0-alpha.11

## 复现步骤
1.创建一个多对一的关系字段
2.新建一些数据
3.表格-导出-查看导出数据

**Comment by hongboji** [comment]
复现步骤无法复现，请提供以下信息供排查问题：
1、部署方式 git源码、docker、 create-app ?
2、数据库是什么？
3、数据表字段列表截图，关系字段设置截图
4、页面配置过程截图
5、导出按钮右上角导出字段配置内容截图
6、可以提供导出时的日志
7、可以提供认为有帮助的信息
