### ISSUE TITLE
无法通过Docker方式启动

### ISSUE THREAD

**Issue by shotacon** [nocobase/nocobase#412]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/23590107/169777896-4b429299-de57-453f-b0d4-00f95803c79d.png">

会报上述错误, 不太能看得懂node, 所以提一个issue.
是跟着https://docs-cn.nocobase.com/getting-started/installation/docker-compose安装的

**Comment by chenos** [comment]
看起来是早先下载过 v0.5 版本的 nocobase，文档改进了一下，镜像不用 latest，改成具体的版本了，可以按照教程再试一遍。
