### ISSUE TITLE
调用接口登录成功页面依然是未登录状态

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#414]
使用场景：使用iframe嵌入到其它系统
1、调用登录接口后，
session = requests.session()
headers = {
     "Content-Type": "application/json"
}
login_params = {"email": f"{username}", "password": password}
res = session.post(url=f'{nocobase_url}api/users:signin', json=login_params, headers=headers)
---
发现cookie中currentRoleName并未写入，页面还是显示未登录，要怎么调用接口才可以正常访问页面？
![image](https://user-images.githubusercontent.com/82276246/169837870-cf3e17fa-25c2-46ae-8a43-5fca4f492af3.png)

**Comment by budnail** [comment]
Google Translation to English:  
Title: The login success page of calling the interface is still not logged in
Usage scenario: use iframe to embed into other systems
1. After calling the login interface,
It is found that the currentRoleName in the cookie is not written, and the page still shows that the page is not logged in. How can I call the interface to access the page normally?

**Comment by chenos** [comment]
试了一下，我这边 OK，跟 iframe 应该没问题，需要检查一下其他原因
