### ISSUE TITLE
iframe插件html模式下 404

### ISSUE THREAD

**Issue by pangff** [nocobase/nocobase#4185]
## Describe the bug

创建新页面block使用iframe插件，在html模式下添加html标签保存后，iframe展示404

## Version

VERSION:  0.21.0-alpha.15

## How To Reproduce

详见视频
https://github.com/nocobase/nocobase/assets/2368696/e20963a5-5f6f-498f-bfef-44db8276ab3f

## Expected behavior

期望展示保存的html页面内容

**Comment by yangdachaun** [comment]
最新版遇到同样的问题

**Comment by zhouyanliang** [comment]
是子应用吗？

**Comment by yangdachaun** [comment]
> 是子应用吗？

我就是写的普通的html代码

**Comment by dream2023** [comment]
已经解决，可以拉最新代码验证一下
