### ISSUE TITLE
Duplicate page turn data after list sorting

### ISSUE THREAD

**Issue by yangdachaun** [nocobase/nocobase#4208]
## How To Reproduce

1. Click to sort
2. flip
3. Duplicate list data

## Screenshots
![1](https://github.com/nocobase/nocobase/assets/66589008/14c79da8-f883-45fb-920f-9ab251ac9e0b)
![2](https://github.com/nocobase/nocobase/assets/66589008/cef09118-a6e1-4bb6-8fb7-f1e8c198e882)

**Comment by yangdachaun** [comment]
![3](https://github.com/nocobase/nocobase/assets/66589008/0c706409-6580-4cde-8017-15fdc8898433)
设置了排序规则，还是有重复

**Comment by yangdachaun** [comment]
按照默认显示20条，没有出现bug，如果设置为10条，就会出现

**Comment by zhouyanliang** [comment]
更新到最新版，已修复。

**Comment by yangdachaun** [comment]
> 更新到最新版，已修复。

最新版本 ifram 又报404

**Comment by zhouyanliang** [comment]
> > 更新到最新版，已修复。
> 
> 最新版本 ifram 又报404

iframe 404 的问题解决了。
