### ISSUE TITLE
v1.0.0-alpha.1 列表数据点击排序，数据重复bug依旧存在

### ISSUE THREAD

**Issue by yangdachaun** [nocobase/nocobase#4213]
## How To Reproduce

1. 前端点击排序
2. 翻页
3. 数据重复出现

## Expected behavior
数据不要重复出现

## Screenshots
![1](https://github.com/nocobase/nocobase/assets/66589008/0bad1ef1-f165-498f-9afe-613a2b76b6f7)
![2](https://github.com/nocobase/nocobase/assets/66589008/35750b5d-1bc1-4997-b22f-7d81d7fa1b3f)
![3](https://github.com/nocobase/nocobase/assets/66589008/f299c15d-8406-4c22-8a82-39bc78b7b90e)

**Comment by hongboji** [comment]
这个操作排序后，数据出现位置不同，不是重复 ，符合预期

**Comment by hongboji** [comment]
数据是正确的 ，相同状态，内部数据是无序的

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/issues/3796

**Comment by yangdachaun** [comment]
> 数据是正确的 ，相同状态，内部数据是无序的

我已经增加了排序规则，依然出现重复数据，请问这样是合理的吗？

**Comment by hongboji** [comment]
初始进入页面遵从设置排序规则，点击排序规则后会遵从点击的排序规则 ，排序规则不是累积 ，而是遵从后设置的

**Comment by yangdachaun** [comment]
> 初始进入页面遵从设置排序规则，点击排序规则后会遵从点击的排序规则 ，排序规则不是累积 ，而是遵从后设置的

您好，如果你是用户，请问您觉得合理吗？翻页看到重复数据，用户会认为系统有问题

**Comment by zhouyanliang** [comment]
@yangdachaun 从技术的角度来说目前是正常的，从产品的角度来说确实不合理。我们正在对这里的排序进行改进，会尽快发布新版本解决这个问题。
