### ISSUE TITLE
v1.0.0-alpha.1 设置每页显示100条数据，但点击排序以后，页面又只显示20条

### ISSUE THREAD

**Issue by yangdachaun** [nocobase/nocobase#4214]
## How To Reproduce

1. 设置每页显示100条
2. 点击翻页
3. 页面每页只显示20条

## Expected behavior

页面按照具体设置显示

## Screenshots
![1](https://github.com/nocobase/nocobase/assets/66589008/ef3340cb-b588-4b11-bb73-d13fd0414b02)
![2](https://github.com/nocobase/nocobase/assets/66589008/dad7f2a8-8b7f-4413-8924-e72695d27de2)
![3](https://github.com/nocobase/nocobase/assets/66589008/43ae155a-7f59-42c6-a0b4-9c1a099c0e0b)

**Comment by hongboji** [comment]
看不见分页 ，把整个操作过程录个屏看看 ，操作的时候在network下，payload页录进来

**Comment by yangdachaun** [comment]
> 看不见分页 ，把整个操作过程录个屏看看 ，操作的时候在network下，payload页录进来

[操作视频](https://www.bilibili.com/video/BV1Qr421u7jm/)

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4219
