### ISSUE TITLE
客户端点击排序后，分页数据会重复

### ISSUE THREAD

**Issue by e5460e** [nocobase/nocobase#4222]
## How To Reproduce

1. 一张表，记录30条，此图为记录表，每个name不重复，age有重复记录
![1](https://github.com/nocobase/nocobase/assets/43603031/469d05dd-ca28-4d66-8338-277763db9bcd)
2. 不点击排序情况下一切正常，每条记录得到呈现
![2](https://github.com/nocobase/nocobase/assets/43603031/01b6190a-4921-4f04-a577-5d76517131a3)
3. 但在前端客户端点击age排序后
![3](https://github.com/nocobase/nocobase/assets/43603031/2b6ba20b-aca2-4dbf-a307-df30ad452e26)
4. 翻页发现记录重复显示，而总记录却是对的，也就意味着有数据没显示，这在业务应用中非常致命。
![4](https://github.com/nocobase/nocobase/assets/43603031/ee9c722c-efe2-4856-9d30-813fbfb31f45)

**Comment by e5460e** [comment]
补充，每页10条时出现，20条时不出现

**Comment by e5460e** [comment]
这个无法理解，无序不代表记录可以重复，且总数是对的就意味着有记录没显示，比如学校档案列表，客户点击排序后，翻页记录一是重复，二是有记录找不到，这个问题应该认为很严重

**Comment by e5460e** [comment]
翻页就失去意义了！

**Comment by zhouyanliang** [comment]
@e5460e @从技术的角度来说目前是正常的，从产品的角度来说确实不合理。我们正在对这里的排序进行改进，会尽快发布新版本解决这个问题。

**Comment by e5460e** [comment]
OK,感谢！辛苦！

**Comment by zhouyanliang** [comment]
@e5460e 最新版本问题已解决。
