### ISSUE TITLE
执行 yarn nocobase upgrade 升级后启动出现这个问题，应该如何修改数据库

### ISSUE THREAD

**Issue by MarshallEriksen-shaomingyang** [nocobase/nocobase#4226]
![image](https://github.com/nocobase/nocobase/assets/59674455/733d4539-8f84-468a-a6ec-49231c7d8ee0)

**Comment by hongboji** [comment]
请提供以下信息供排查问题：
1、nocobase版本号，升级到什么版本？
2、部署方式 git源码、 create-app ?
3、数据库是什么？
4、升级流程是什么
5、可以提供更多日志
6、可以提供认为有帮助的信息

**Comment by MarshallEriksen-shaomingyang** [comment]
我从0.19.0-alpha.9 升级到1.0.0-alpha.2
create-app
postgresql
执行yarn nocobase upgrade
我看和最新创建的数据库有些表被删除有些表新增了数据 现在不知道该如何合并旧表的数据了
