### ISSUE TITLE
Placing a collapsed filter block in a tree collection causes a rendering error

### ISSUE THREAD

**Issue by y-o-u** [nocobase/nocobase#4252]
## Describe the bug

Placing a filter block with data from a tree collection causes a rendering error and prevents editing of that page.

## Version

v0.21.0-alpha.6

## How To Reproduce

1. Go to Created Own Page.
2. Click on 'Add Block'
3. Scroll down to 'a collapsed filter block' and Click on 'a tree collection'

## Expected behavior

A filter block is added to the page.

## Screenshots

<img width="1156" alt="スクリーンショット 2024-05-01 14 44 44" src="https://github.com/nocobase/nocobase/assets/18046108/b0237c6a-4c40-4787-b8f0-2f63c896f944">

## Desktop (please complete the following information)

- OS: MacOS Ventura 13.2.1
- Browser Chrome　124.0.6367.92

**Comment by hongboji** [comment]
The problem is not reproduced, please add a new page, add a collapsed filter block on the page to see if the error exists, please upload the video recording of the operation.

**Comment by hongboji** [comment]
Please recreate the block with the latest code.
Issues will be closed, please continue to give feedback if you have questions!
