### ISSUE TITLE
子表格字段复选框和下拉框多选不可用

### ISSUE THREAD

**Issue by Poorandy** [nocobase/nocobase#427]
![image](https://user-images.githubusercontent.com/63747977/170656703-32d773f1-abc8-4168-ae8d-472e514013b4.png)

products表有一个子表格infos，后者有一个多选下拉字段和一个复选框字段

![image](https://user-images.githubusercontent.com/63747977/170656872-c35cf9f1-8b54-4f87-b4fe-f272e3c3d409.png)
当配置添加按钮，
![image](https://user-images.githubusercontent.com/63747977/170657114-6f0eff54-d919-4788-b2c2-325466eed6f0.png)
点击复选框的时候，报错
![image](https://user-images.githubusercontent.com/63747977/170657201-fb56467c-e37c-40a6-836c-b22a1de974d9.png)
如果只点击下拉框，不报错，但是在添加过程中下拉选项不可点击。

docker-compose启动  选择mysql8

**Comment by chenos** [comment]
感谢 @wrightjin 提交的 PR，问题已修复 https://github.com/nocobase/nocobase/pull/431
