### ISSUE TITLE
Couldn't find package "@nocobase/preset-nocobase" on the "npm" registry.

### ISSUE THREAD

**Issue by qdriven** [nocobase/nocobase#428]
**Describe the bug**

Couldn't find package "@nocobase/preset-nocobase" on the "npm" registry.

**To Reproduce**

1. run command:
```sh
yarn create nocobase-app my-nocobase-app -d sqlite
```
3.  then go to my-nocobase-app folder
4. run:
```sh
yarn install
```
6. then See error:
```sh
error Couldn't find package "@nocobase/preset-nocobase" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Expected behavior**
install successfully

<img width="844" alt="image" src="https://user-images.githubusercontent.com/21341419/170701872-5ec9cf71-09f6-4a4d-8ccf-1c019e6d4c57.png">

**Desktop (please complete the following information):**
 - OS:  MACOS

**Comment by mytharcher** [comment]
Just had a check and seems ok on my mac. Maybe some network or cache issues. Could you make another try later to see if this remains?

**Comment by qdriven** [comment]
Retried today, it worked after cleaned all the cache. Thank you sir.
