### ISSUE TITLE
S3 file download issue

### ISSUE THREAD

**Issue by Lelenaic** [nocobase/nocobase#4323]
## Describe the bug

I'm using a compatilble S3 with nocobase. The file upload works like a charm, but then, I can't preview or download any file.
I tried with different S3 providers, I still get the same error. It works with the local storage, though.

## Version

v1.0.0-alpha.2

## How To Reproduce

Configure a compatible S3 storage, upload a file and then try to download it.

## Expected behavior

I should be able to preview and download the PDF.

## Screenshots

Here's the preview when I click on a PDF file:
![CleanShot 2024-05-12 at 19 49 52](https://github.com/nocobase/nocobase/assets/11456619/12c0b144-dc56-4d3c-8315-9809f2665506)

When I click on "Download", here's the download link opening in my browser: https://76431f2e30b8f03e70ed6c8c306356f8.pdf/

**Comment by zhouyanliang** [comment]
Please provide a screenshot of the anonymized configuration interface.
