### ISSUE TITLE
Image Attachments are not included in the excel export

### ISSUE THREAD

**Issue by crelocks** [nocobase/nocobase#4331]
## Describe the bug

When exporting the excel file, images are not included in the cell. 
![image](https://github.com/nocobase/nocobase/assets/141933932/1394091b-2356-44ab-b941-05db94c55d43)

## Version

Demo (v1.0.0-alpha.12.20240513042101)

## How To Reproduce

1. Go to any table which has attachments (in images)
2. Click on export button
3. See error as show above

## Expected behavior

It would be good to see the actual images
![image](https://github.com/nocobase/nocobase/assets/141933932/1394091b-2356-44ab-b941-05db94c55d43)

## Desktop (please complete the following information)

- OS: Mac and Chrome

**Comment by zhouyanliang** [comment]
Hi @crelocks it's not a bug and the export plugin does not yet support images. We will consider adding this feature in the future.
