### ISSUE TITLE
[Workflow: HTTPrequest Node] "Ignore failed request and continue workflow" option is not working

### ISSUE THREAD

**Issue by s1v** [nocobase/nocobase#4333]
## Describe the bug

HTTP request node option: "Ignore failed request and continue workflow" is not working.
Even if you enable this option, it will not continue if an error occurs.

## Version

v1.0.0-alpha.12

## How To Reproduce

1. create workflow.
2. add "HTTP request" node.
4. edit "HTTP request" node.
set "URL": [https://konmari.com/404]
set enable "Ignore failed request and continue workflow" option.
6. add any Follow-up node.
7. call this workflow. Follow-up node is not executed.

## Expected behavior

execute Follow-up node.

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/20382337/811bd1c8-28a1-4c54-82ad-d5ad41ae2c21)

![image](https://github.com/nocobase/nocobase/assets/20382337/ffc1d428-456f-4054-933b-2ce11e90d61a)

**Comment by mytharcher** [comment]
@s1v Please have a try on latest main branch, to see if it fixed in your case.

**Comment by s1v** [comment]
@mytharcher Thank you for your assistance. I have confirmed that this option functions in synchronous mode.

**Comment by s1v** [comment]
@mytharcher Thank you for the fix. I have confirmed that this option is functioning in synchronous mode.
