### ISSUE TITLE
The transition from docker 0.18.0-alpha.1 on app 1.0***, with the error "Unknown column 'triggerTitle' in 'field list' "

### ISSUE THREAD

**Issue by AnryHedgehog** [nocobase/nocobase#4347]
## Describe the bug

Hello, we wanted to switch from the joker to the application, and when restoring from the dump, it writes an error, is there any way to get around this?

## Version

Nocobase - 0.18.0-alpha.1.20231222020209
MySQL - 8.0.37

## How To Reproduce

Follow the instructions of my-nocobase-app, restore the database from the dump, and this error will appear when you start working

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/146196537/87b80828-bd12-438f-a27d-0b8c19b7047a)

## Desktop (please complete the following information)

- OS: AstraLinux -1.8/Debian 11
- Browser Chrome. Yandex

**Comment by hongboji** [comment]
Can you describe the whole process in full detail?

**Comment by AnryHedgehog** [comment]
1 have mysql installed on the astra linux system

2 went through the documentation for installing my-nocobase-app, until the moment of -yarn start

3 we did a database dump via dbeaver, restored the dump to a new machine(my-nocobase-app) and when trying to run it, it writes "Unknown column 'triggerTitle' in 'field list'"

**Comment by hongboji** [comment]
Try to start it with the following command:
# Execute the update command
yarn nocobase upgrade
# Start
yarn dev

**Comment by AnryHedgehog** [comment]
Is it possible for my-nocobase-app to specify which version I want? And tell me how to do it, please

**Comment by hongboji** [comment]
Try it : 
npx create-nocobase-app@1.0.0-alpha.1 my-nocobase-app -d sqlite
npx create-nocobase-app@1.0.0-alpha.1 my-nocobase-app -d mysql -e DB_HOST=localhost -e DB_PORT=3306 -e DB_DATABASE=test1 -e DB_USER=test1 -e DB_PASSWORD=test1

**Comment by AnryHedgehog** [comment]
This can be closed, because our database was still damaged, although everything worked, you can help with another one, please, we do not display logs at all, although they are enabled
