### ISSUE TITLE
[Workflow: HTTP request Node] Node result type not fixed

### ISSUE THREAD

**Issue by s1v** [nocobase/nocobase#4373]
## Describe the bug

The internal result type of the "HTTP request" node is not fixed.

If the response of the "HTTP request" node is HTML, node result is a string.
For error responses and JSON, it's an object.

This may cause "TypeError" when using the "String Operations" in subsequent "Condition Nodes".

## Version

v1.0.0-alpha.14

## How To Reproduce

1. create workflow.
2. add "HTTP request" node.
3. edit "HTTP request" node.
4. set "URL": [https://www.cloudflare.com/rate-limit-test/](https://www.cloudflare.com/rate-limit-test/)
5. set enable "Ignore failed request and continue workflow" option.
6. add any Follow-up "Condition" node.
7. set as below.
  ![image](https://github.com/nocobase/nocobase/assets/20382337/6e36c160-dddd-4d0f-be0d-70e9ebee61bb)
9. call this workflow 10 times in a row. get an error on the 10th run.

## Expected behavior

The internal result type of the "HTTP Request" node can always be treated as string and can use "String operations".

## Screenshots

Successfull case:
![image](https://github.com/nocobase/nocobase/assets/20382337/007e6e70-8ec7-4873-ab4d-6940f69dd1d8)

Failed case:
![image](https://github.com/nocobase/nocobase/assets/20382337/d07948c7-284b-4bf3-a12c-c415c7109ece)

**Comment by mytharcher** [comment]
Hi @s1v, We have made a fix about this, you can have another try.

**Comment by s1v** [comment]
@mytharcher I appreciate your fix.
But it hasn't improved yet.
If a 4XX HTTP status code is returned, the result of the "HTTP request" node is internally an "object", so if you use a "string operator" in a subsequent "condition" node, a "TypeError" will occur. ' will occur. occurs.

**Comment by s1v** [comment]
I confirmed that the issue is resolved in alpha15.
