### ISSUE TITLE
you are offline

### ISSUE THREAD

**Issue by dopamines-001** [nocobase/nocobase#4391]
the error occurs sometimes, and work again after F5

**Comment by ishaantaneja** [comment]
what was this about?

**Comment by dopamines-001** [comment]
it is hard to describe, maybe i do not operate the page for sometime, then page turns to off line 
![image](https://github.com/nocobase/nocobase/assets/163523055/d5c53ad7-e352-4d18-aec3-1b8e777db2e8)

**Comment by chenos** [comment]
This prompt is not friendly, we will improve it as soon as possible.
