### ISSUE TITLE
建议新功能：用户账户批量新增及管理

### ISSUE THREAD

**Issue by pandagxnu** [nocobase/nocobase#4396]
每一届新生入学，都有一个基本信息表，假设是表A，表中有身份证号码等一系列信息。
1、能否简单操作实现：设置A表中身份证号码为用户登录名称，密码为身份证号码后6位或者批量设置初始密码为统一密码、随机密码。
2、在学生毕业后，快速禁止该届学生账号登录

**Comment by zhouyanliang** [comment]
可以结合数据导入和工作流来实现
