### ISSUE TITLE
子表格实体表名称自定义

### ISSUE THREAD

**Issue by whataxxday** [nocobase/nocobase#440]
使用下来发现子表格创建时数据库自动生成随机表名的实体表，请问能否增加自定义子表格表名功能？

**Comment by chenos** [comment]
目前的「子表格」和「关联字段」会自动处理一些参数，对开发可能有些不友好，下一版会提供更适合开发使用的一对一、一对多、多对一、多对多的配置，可以解决你提到的这类问题。

**Comment by whataxxday** [comment]
感谢回复，期待下次版本更新~

**Comment by budnail** [comment]
Google Translation to English:
[whataxxday](https://github.com/whataxxday) After using it, I found that the database automatically generates an entity table with a random table name when the subtable is created. Can I add the function of customizing the table name of the subtable?

[chenos](https://github.com/chenos)The current "sub-table" and "related fields" will automatically process some parameters, which may be unfriendly to development. The next version will provide one-to-one, one-to-many, many-to-one, and many-to-many more suitable for development. Configuration can solve the kind of problems you mentioned.

[whataxxday](https://github.com/whataxxday)Thanks for the reply, looking forward to the next version update~

**Comment by lswencn** [comment]
什么时候更新这个功能。 现在功能满足不了。。。

**Comment by zhouyanliang** [comment]
下周发布新版本

**Comment by lswencn** [comment]
@chenos  版本什么时候发啊。等着用。。。

**Comment by lswencn** [comment]
子表中还有子表还有子表 5 6七八级的时候  添加 那不得死人，  得让字表也能单独展示并且能单独添加

**Comment by budnail** [comment]
Google Translate to English:
[zhouyanliang](https://github.com/zhouyanliang): New release next week

[lswencn](https://github.com/lswencn): There are also sub-tables in the sub-table and sub-tables 5 6 are added at the seventh or eighth level, so no one should die, and the word table must also be displayed and added separately.

**Comment by chenos** [comment]
@lswencn 这部分早之前已经合并到 main 主分支了，不过还没有最终发版，因为还有些测试没有通过，需要完善。如果着急的话，可以源码安装体验。https://docs-cn.nocobase.com/getting-started/installation/git-clone

**Comment by lswencn** [comment]
@chenos  老铁，  我要用源码能编译过我肯定用了。 关键是我启动不了。。。

**Comment by zhouyanliang** [comment]
新版本已支持。

**Comment by whataxxday** [comment]
> 新版本已支持。

感谢提示，我已经试用过新版了，发现了many to many类型的一个问题，详见#554
