### ISSUE TITLE
删除一张表后创建同名表时数据库表结构等问题

### ISSUE THREAD

**Issue by whataxxday** [nocobase/nocobase#441]
## Describe the bug

1. 页面操作删除创建错误的表后，数据库中删除了对应的collection和fields，但是没有删除关联表和子表格；在数据库中手动删除创建错误的关联表和子表格，一段时间后又会自动生成被删除的表格。

2. 在页面上操作删除创建错误的表（eg. t_product）后，重新生成同名表（新旧两张t_product字段不一样），实体表（t_product）字段还是旧表的字段，并且调用查询列表接口会报错

## Version
docker版
Version 0.7.0-alpha.78

## How To Reproduce

1. 数据表配置-->创建数据表-->创建一张数据表标识为t_product的表
2. 为该表添加字段：product_name【单行文本】、product_type【下拉菜单（单选）】、related_products【关联】、product_detail【子表格】
3. 删除刚才创建的t_product表
4. 数据表配置-->创建数据表-->重新创建一张数据表标识为t_product的表（同名表）
5. 为新表添加字段：product_name【单行文本】、related_products【关联】、product_detail【子表格】

## Expected behavior

1. 删除t_product后除删除collection和fields，同时能删除关联表或者子表；或者给与选择删除的权限
2. 重新创建同名表，在数据库中能更新同名表的表结构，插入新的关联表或子表
3. 新的同名表调用查询列表的接口时能正常显示且不报错

## Screenshots
![image](https://user-images.githubusercontent.com/39958768/171071598-e9065975-c481-4df9-9c5a-cd03bffc8096.png)

## Desktop (please complete the following information)

- OS: linux
- Browser chrome

**Comment by budnail** [comment]
Google Translation to English:
1. After the page operation deletes the wrongly created table, the corresponding collection and fields are deleted in the database, but the associated table and subtable are not deleted; if the wrongly created associated table and subtable are manually deleted in the database, the deleted one will be automatically generated after a period of time. sheet.
2. After deleting the wrongly created table (eg. t_product) on the page, regenerate the table with the same name (the old and new t_product fields are different), the entity table (t_product) field is still the field of the old table, and calling the query list interface will report an error

**Comment by chenos** [comment]
最新版 v0.7.2-alpha.1 已解决数据表和字段的删除问题。
