### ISSUE TITLE
建议在表格列表的字段上加上可以编辑的属性

### ISSUE THREAD

**Issue by ai-bytedance** [nocobase/nocobase#4425]
## * Describe the bug
建议在表格列表的字段上加上可以编辑的属性

## * Environment

NocoBase
v1.0.0-alpha.13
  

- OS: linux

## * How To Reproduce
系统实际截图：
![image](https://github.com/nocobase/nocobase/assets/28555655/c05adbaa-3431-4e60-a6f5-5ec38ddcdc17)
参考预期截图：
![image](https://github.com/nocobase/nocobase/assets/28555655/7009d0f1-d17f-437d-a4e5-02843d9693dd)

**Comment by zhouyanliang** [comment]
issue 仅供反馈 bug
