### ISSUE TITLE
错误，这是缺少文件吗？Failed to compile

### ISSUE THREAD

**Issue by SoMeTech** [nocobase/nocobase#4426]
Failed to compile
Module not found: Error: Can't resolve 'swagger-ui-dist/swagger-ui-bundle' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-api-doc\src\client'

**Comment by SoMeTech** [comment]
error - ./packages/plugins/@nocobase/plugin-api-doc/src/client/Document.tsx:19:0-64
Module not found: Error: Can't resolve 'swagger-ui-dist/swagger-ui-bundle' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-api-doc\src\client'
error - ./packages/plugins/@nocobase/plugin-api-doc/src/client/Document.tsx:20:0-40
Module not found: Error: Can't resolve 'swagger-ui-dist/swagger-ui.css' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-api-doc\src\client'
error - ./packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx:21:0-77
Module not found: Error: Can't resolve 'react-big-calendar' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-calendar\src\client\calendar'
error - ./packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Calendar.tsx:22:0-60
Module not found: Error: Can't resolve 'react-big-calendar/lib/utils/dates' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-calendar\src\client\calendar'
error - ./packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Nav.tsx:16:0-74
Module not found: Error: Can't resolve 'react-big-calendar/dist/react-big-calendar.esm' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-calendar\src\client\calendar'
error - ./packages/plugins/@nocobase/plugin-calendar/src/client/calendar/Today.tsx:15:0-74
Module not found: Error: Can't resolve 'react-big-calendar/dist/react-big-calendar.esm' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-calendar\src\client\calendar'
error - ./packages/plugins/@nocobase/plugin-calendar/src/client/calendar/utils.ts:12:0-39
Module not found: Error: Can't resolve 'solarlunar-es' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-calendar\src\client\calendar'
error - ./packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/dualAxes.ts:20:0-59
Module not found: Error: Can't resolve '@ant-design/plots' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-data-visualization\src\client\chart\g2plot'
error - ./packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/index.ts:10:0-69
Module not found: Error: Can't resolve '@ant-design/plots' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-data-visualization\src\client\chart\g2plot'
error - ./packages/plugins/@nocobase/plugin-data-visualization/src/client/chart/g2plot/pie.ts:21:0-49
Module not found: Error: Can't resolve '@ant-design/plots' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-data-visualization\src\client\chart\g2plot'
error - ./packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/components/Display.tsx:18:0-28
Module not found: Error: Can't resolve 'vditor' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-field-markdown-vditor\src\client\components'
error - ./packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/components/Edit.tsx:16:0-28
Module not found: Error: Can't resolve 'vditor' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-field-markdown-vditor\src\client\components'
error - ./packages/plugins/@nocobase/plugin-field-markdown-vditor/src/client/index.tsx:18:0-31
Module not found: Error: Can't resolve 'vditor/dist/index.css' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-field-markdown-vditor\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx:17:0-33
Module not found: Error: Can't resolve '@antv/x6' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx:18:0-50
Module not found: Error: Can't resolve '@antv/x6-plugin-minimap' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx:19:0-52
Module not found: Error: Can't resolve '@antv/x6-plugin-scroller' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx:20:0-54
Module not found: Error: Can't resolve '@antv/x6-plugin-selection' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx:21:0-52
Module not found: Error: Can't resolve '@antv/x6-plugin-snapline' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx:22:0-48
Module not found: Error: Can't resolve '@antv/x6-react-shape' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/GraphDrawPage.tsx:27:0-26
Module not found: Error: Can't resolve 'dagre' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client'
error - ./packages/plugins/@nocobase/plugin-graph-collection-manager/src/client/components/ViewNode.tsx:16:0-36
Module not found: Error: Can't resolve '@antv/x6' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-graph-collection-manager\src\client\components'
error - ./packages/plugins/@nocobase/plugin-map/src/client/components/AMap/Map.tsx:21:0-49
Module not found: Error: Can't resolve '@amap/amap-jsapi-loader' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-map\src\client\components\AMap'
error - ./packages/plugins/@nocobase/plugin-map/src/client/components/AMap/Map.tsx:22:0-32
Module not found: Error: Can't resolve '@amap/amap-jsapi-types' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-map\src\client\components\AMap'
error - ./packages/plugins/@nocobase/plugin-map/src/client/components/GoogleMaps/Map.tsx:25:0-51
Module not found: Error: Can't resolve '@googlemaps/js-api-loader' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-map\src\client\components\GoogleMaps'
error - ./packages/plugins/@nocobase/plugin-mobile-client/src/client/core/schema/components/header/Header.tsx:15:0-37
Module not found: Error: Can't resolve 'antd-mobile' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-mobile-client\src\client\core\schema\components\header'
error - ./packages/plugins/@nocobase/plugin-mobile-client/src/client/core/schema/components/menu/Menu.Item.tsx:17:0-35
Module not found: Error: Can't resolve 'antd-mobile' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-mobile-client\src\client\core\schema\components\menu'
error - ./packages/plugins/@nocobase/plugin-mobile-client/src/client/core/schema/components/menu/Menu.tsx:14:0-35
Module not found: Error: Can't resolve 'antd-mobile' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-mobile-client\src\client\core\schema\components\menu'
error - ./packages/plugins/@nocobase/plugin-mobile-client/src/client/core/schema/components/tab-bar/TabBar.tsx:21:0-37
Module not found: Error: Can't resolve 'antd-mobile' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-mobile-client\src\client\core\schema\components\tab-bar'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/ColorPanel.tsx:19:0-65
Module not found: Error: Can't resolve 'react-colorful' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/ColorPanel.tsx:20:0-35
Module not found: Error: Can't resolve 'tinycolor2' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/TokenInput.tsx:17:0-45
Module not found: Error: Can't resolve 'use-debouncy' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/component-demos/progress/danger.tsx:12:0-46
Module not found: Error: Can't resolve '@arvinxu/layout-kit' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer\component-demos\progress'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/component-demos/progress/success.tsx:12:0-46
Module not found: Error: Can't resolve '@arvinxu/layout-kit' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer\component-demos\progress'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/overviews/Error.tsx:12:0-46
Module not found: Error: Can't resolve '@arvinxu/layout-kit' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer\overviews'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/overviews/Success.tsx:22:0-46
Module not found: Error: Can't resolve '@arvinxu/layout-kit' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer\overviews'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/overviews/Warning.tsx:25:0-46
Module not found: Error: Can't resolve '@arvinxu/layout-kit' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer\overviews'
error - ./packages/plugins/@nocobase/plugin-theme-editor/src/client/antd-token-previewer/token-panel-pro/TokenContent.tsx:22:0-45
Module not found: Error: Can't resolve 'use-debouncy' in 'F:\NocoBase\my-nocobase-app\packages\plugins\@nocobase\plugin-theme-editor\src\client\antd-token-previewer\token-panel-pro'

**Comment by zhouyanliang** [comment]
所有不按照模版填写的 issue 将被关闭。
