### ISSUE TITLE
联动规则设置了多个条件，只有最后一个规则条件启作用，影响的是全局，不是每条数据不同的值的启用不同的规则

### ISSUE THREAD

**Issue by xjs1983boy** [nocobase/nocobase#4435]
## * Environment

- NocoBase version:

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce
<img width="1168" alt="image" src="https://github.com/nocobase/nocobase/assets/33441983/f10f79eb-8c9d-416e-a131-a9683c156d93">
<img width="1266" alt="image" src="https://github.com/nocobase/nocobase/assets/33441983/f064427e-3b10-440c-a12e-268759d57a96">
<img width="1496" alt="image" src="https://github.com/nocobase/nocobase/assets/33441983/74c1edda-a734-4b1e-b085-6e50f9751083">

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4436

**Comment by hongboji** [comment]
已经修复，使用最新代码检查是否解决

**Comment by xjs1983boy** [comment]
问题已解决
