### ISSUE TITLE
操作后工作流的触发器数据里不能选择新数据的id

### ISSUE THREAD

**Issue by blackwhite084** [nocobase/nocobase#4438]
## * Describe the bug
场景：创建某角色的用户时，顺便在某角色专用的资料表里创建一条数据，这个数据需关联users表
![image](https://github.com/nocobase/nocobase/assets/53146034/81e7f33e-6b73-4180-b125-563c31638911)

## * Environment

- NocoBase version:v1.0.0-alpha.15

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce
操作后工作流--新增数据--新字段--选择触发器数据--没有id选项

**Comment by blackwhite084** [comment]
查询数据节点查询的数据也无法提供id

**Comment by mytharcher** [comment]
Hi @blackwhite084 , the fixes have been merge to main. You could have a check.
