### ISSUE TITLE
macOS 本地 docker 安装之后，启动网页端，注册完进去之后，一片空白

### ISSUE THREAD

**Issue by tobemaster56** [nocobase/nocobase#4449]
## * Environment

- NocoBase version:

- Database type and version: 
  

- OS: MacOS

- Deployment Methods: Docker

- Docker image version: latest

- NodeJS version:

## Expected behavior

我看网站文档上的截图非常丰富

<img width="922" alt="image" src="https://github.com/nocobase/nocobase/assets/8998761/16b9a4ca-7cf5-4efd-9b40-dd955a16e05c">

## Screenshots

我的电脑是 m1 max 的 Mac studio，docker 用的是 orbstack。

<img width="985" alt="image" src="https://github.com/nocobase/nocobase/assets/8998761/26dc2b0f-43da-4861-b63e-c1bf58a137cf">

安装完，启动之后，注册完用户，进去一脸懵

<img width="991" alt="image" src="https://github.com/nocobase/nocobase/assets/8998761/e60d1e85-62b3-49e5-8c2c-554b37e74e70">

**Comment by hongboji** [comment]
截图中的内容是使用nocobase搭建的，安装后使用默认管理员账户登录进行搭建设置
https://docs-cn.nocobase.com/welcome/getting-started/installation/docker-compose
