### ISSUE TITLE
表格区块分页行数的下拉菜单存在的交互问题

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#445]
## Describe the bug

表格区块分页行数下拉列表存在的交互问题

## Version

Version 0.7.0-alpha.82

## How To Reproduce

存在2个问题，

1. 分页下拉列表-无法选择 20/page

![分页选择-无法选择20](https://user-images.githubusercontent.com/931976/171119569-b0f1db93-26eb-4297-a6fa-14dcea7073b7.gif)

2. 分页下拉列表被其他区块遮挡

![分页列表被其他区块遮挡](https://user-images.githubusercontent.com/931976/171120273-7abb06f0-cef0-45a9-a0b8-878760161db9.gif)

## Expected behavior

- 可以选中 20/page
- 分页下拉列表不被遮挡

## Desktop (please complete the following information)

- OS: MacOS 12.4
- Browser chrome
- Version 102.0.5005.61（正式版本） (x86_64)

**Comment by budnail** [comment]
Google Translation to English:
The interaction problem of the drop-down list of paging rows in the table block

**Comment by chenos** [comment]
最新版已修复
