### ISSUE TITLE
怎么将自研的插件，在服务启动的时候自动加载进插件列表并启动？

### ISSUE THREAD

**Issue by chakhsu** [nocobase/nocobase#4451]
## Describe the bug

不是bug，只是问一下怎么做到将自研的插件在服务启动的时候就加载进去，并且是启动状态。

目前插件是使用了新的目录，跟`@nocobase/plugin-`同级，为`@inner/plugin-`这种。

不希望使用 `yarn pm able plugin-name`这种方式，因为自研的插件有点多。

## Environment

- NocoBase version: 最新版

- Database type and version:  MySQL 8.x
  
- OS: MacOS

- Deployment Methods: Git source code

- NodeJS version: 20.x

## How To Reproduce

None

**Comment by Xilesun** [comment]
参考 https://docs-cn.nocobase.com/welcome/getting-started/env#%E5%AE%9E%E9%AA%8C%E6%80%A7%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F
