### ISSUE TITLE
数据库表需要设置必要的索引加快性能

### ISSUE THREAD

**Issue by ttmike2** [nocobase/nocobase#4462]
## * Describe the bug
数据库表需要设置必要的索引加快性能

## * Environment

- NocoBase version:v1.0.0-alpha.15.20240521033350
- Database type and version: mysql
- OS:
- Deployment Methods:
- Docker image version:
- NodeJS version:

## * How To Reproduce
1、在压测时工作流里面执行数十万jobs后，流程执行逐渐变慢
2、发现系统内置的数据表比如jobs未设置必要索引；比如工作流引擎最常见的场景（select * FROM jobs WHERE  jobs.execution_id = 123）会使用execution_id进行查询，建议对类似这些字段增加索引（包括系统数据表应内置必要的索引、以及用户新建的表也期望能在界面上配置索引）：
![image](https://github.com/nocobase/nocobase/assets/14071227/fdcf4cac-43d6-48ac-8929-355d22ada43a)

## Expected behavior

预期设置必要索引（包括系统数据表应内置必要的索引、以及用户新建的表也期望能在界面上配置索引）

## Screenshots

见复现步骤

**Comment by hongboji** [comment]
感谢反馈
