### ISSUE TITLE
角色权限配置后，无法显示查看按钮

### ISSUE THREAD

**Issue by hellofreud** [nocobase/nocobase#4463]
## * Describe the bug

前置条件：数据表和角色表做了多对多关联，角色权限中，对该数据表的查看权限进行了单独设定，数据范围筛选为关键角色/角色名称包含当前用户/角色/角色名称
问题：在页面中可以查看相关数据，但是操作中，无法展示查看按钮
![image](https://github.com/nocobase/nocobase/assets/17267947/a6300eca-d57b-40e7-9ded-3c1b3a4247f7)
![image](https://github.com/nocobase/nocobase/assets/17267947/9f3bfd51-e856-4a00-bf61-ad2659c9caab)
![image](https://github.com/nocobase/nocobase/assets/17267947/994ac197-d22a-4115-b9e3-b727e47bc0fc)

## * Environment

- NocoBase version:v1.0.0-alpha.14

- Database type and version: Sqlite
  

- OS:windows

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by chareice** [comment]
@hellofreud 无法复现了，可以用新版再试试
