### ISSUE TITLE
联动规则失效、变成了只判断第一条数据，而不是判断每条数据

### ISSUE THREAD

**Issue by blackwhite084** [nocobase/nocobase#4469]
## * Describe the bug
按规则来说，应该是一个禁用一个显示的、经过测试、很明显联动规则只判断第一个的处理结果，并且后面的联动都按第一个来显示，前两个版本不会这样。
![image](https://github.com/nocobase/nocobase/assets/53146034/dbae649f-7e4a-48d2-9abf-f767b038cbc9)

## * Environment

- NocoBase version:v1.0.0-alpha.15

- Database type and version: mysql
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce
所有联动规则都一样

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4436
