### ISSUE TITLE
No logs in the logger

### ISSUE THREAD

**Issue by AnryHedgehog** [nocobase/nocobase#4471]
## * Describe the bug

When trying to view the logs on nosobase, there is no display of these logs

## * Environment

- NocoBase version: v1.0.0-alpha.13

- Database type and version: 8.0.37
  

- OS:AstraLinux

- Deployment Methods: my-nocobase-app

- Docker image version: -

- NodeJS version:node v18.20.2

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/146196537/00b3a46a-2165-492e-940e-ea74a7a22739)

## Logs

They are not there

**Comment by hongboji** [comment]
Help with server console logs

**Comment by AnryHedgehog** [comment]
Please tell me the way

**Comment by Xilesun** [comment]
> Please tell me the way

Hi @AnryHedgehog 
Please check the environment variable `LOGGER_TRANSPORT`

https://docs.nocobase.com/welcome/getting-started/env#logger_transport
