### ISSUE TITLE
联动规则配置完成后出发，属性显示[object Object]

### ISSUE THREAD

**Issue by wilfzhao** [nocobase/nocobase#4478]
## * Describe the bug

在联动规则中配置当promotion_id为4时，Amount赋值0
<img width="793" alt="image" src="https://github.com/nocobase/nocobase/assets/48481525/bb206c0a-f329-4e1e-aac1-c5c7eb92c7f9">
在表单汇总promotion字段选中4（小红书抽奖），Amount显示[object Object]
<img width="836" alt="image" src="https://github.com/nocobase/nocobase/assets/48481525/c7feecdd-7313-4cd6-a5ad-a12b583420c2">

## * Environment

- NocoBase version:v1.0.0-alpha.15

- Database type and version: PostgreSQL 10
  

- OS: Apple M1 macOS Sonoma 14.4.1

- Deployment Methods:Docker

- Docker image version:nocobase/nocobase:latest

## Expected behavior

在表单汇总promotion字段选中4（小红书抽奖），Amount显示0.00

**Comment by wilfzhao** [comment]
在联动规则中配置Amount赋值为其他数值时正常（测试了1和-1），只有赋值为0时显示[object Object]

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4482

**Comment by hongboji** [comment]
拉取最新代码，检查是否修复
