### ISSUE TITLE
源码部署，修改代码并重新编译后，前端404（已配置nginx）

### ISSUE THREAD

**Issue by blackwhite084** [nocobase/nocobase#4480]
## * Describe the bug

nginx模板是直接复制的、只修改了域名，以及绝对路径
访问根目录后跳转到这个页面，但提示404（f12能看到全是200）
![image](https://github.com/nocobase/nocobase/assets/53146034/24e5747b-7dcf-464d-8ed0-06f904291192)

已切换到15分支

## * Environment

- NocoBase version:15

- Database type and version: mysql8.x
  

- OS:centos7

- Deployment Methods:Git source code

- Docker image version:

- NodeJS version: 18.x

## * How To Reproduce
设置生产环境、编译、部署nginx，访问前端根目录

**Comment by blackwhite084** [comment]
补充、访问根目录时后端api有日志输出、并且无报错，重定向后api无输出

**Comment by blackwhite084** [comment]
补充：create_app方式创建应用，并不通过nginx直接访问app端口正常运行，然后在nocobase根目录执行下面代码后，前端复现404

[root@xxx nocobase]# rm -rf my-nocobase-app/storage/.app-dev/dist/client
[root@xxx nocobase]# cp -r packages/core/app/dist/client my-nocobase-app/storage/.app-dev/dist/

**Comment by blackwhite084** [comment]
补充：create_app方式创建应用并不通过nginx正常访问，但执行下面代码更新前端后复现404，然后在my-nocobase-app内重新yarn start后再次恢复正常

[root@xxx nocobase]# rm -rf my-nocobase-app/storage/.app-dev/dist/client
[root@xxx nocobase]# cp -r packages/core/app/dist/client my-nocobase-app/storage/.app-dev/dist/

**Comment by chenos** [comment]
参考官方文档 https://docs-cn.nocobase.com/welcome/getting-started/deployment/create-nocobase-app
