### ISSUE TITLE
联动规则排序不生效

### ISSUE THREAD

**Issue by wilfzhao** [nocobase/nocobase#4487]
## * Describe the bug

点击联动规则的排序按钮，联动规则页面直接关闭，排序未生效

## * Environment

- NocoBase version:v1.0.0-alpha.15

- Database type and version: PostgreSQL 10
  

- OS:MacOS

- Deployment Methods:Docker

- Docker image version:nocobase/nocobase:latest

- NodeJS version:

## Expected behavior

正常排序

## Screenshots

<img width="1684" alt="image" src="https://github.com/nocobase/nocobase/assets/48481525/56b7e1d7-6ab2-4988-a728-00a79b207e43">

**Comment by zhangzhonghe** [comment]
我们这边没法复现。如果可以稳定复现可以提供下复现步骤，然后再打开这个 issue，我这边先关闭了，感谢。
