### ISSUE TITLE
数据源中的某个表定义的主键字段，在表格数据区块中找不到这个主键字段

### ISSUE THREAD

**Issue by Hongye1720** [nocobase/nocobase#4497]
## * Describe the bug
1、在数据库中创建数据表，定义了一个uuid为主键字段
![image](https://github.com/nocobase/nocobase/assets/116331684/ee1bf358-2236-4406-aa06-406f4fe5b5d3)
![image](https://github.com/nocobase/nocobase/assets/116331684/2adcaa6c-1382-4605-a8ec-7d60251ac8a8)
2、数据区块选择这个表后，想使用这个id的主键字典，发现在配置字段中找不到ID字段
![image](https://github.com/nocobase/nocobase/assets/116331684/ffa6f505-7c08-43c8-8902-27d8d76846cf)
![image](https://github.com/nocobase/nocobase/assets/116331684/ce329f2b-2dd9-4c8d-8586-4d4b556d5ac4)

## * Environment

- NocoBase version:v1.0.0-alpha.14

- Database type and version: MySQL 8.x
  

- OS:Windows

- Deployment Methods:Docker

- Docker image version:
![image](https://github.com/nocobase/nocobase/assets/116331684/fcfa75e8-27fa-4b2e-8ecf-5c9c3fcb3f5b)

- NodeJS version:

## * How To Reproduce

目前可提供迁移包环境，暂时无法复现，因为同样的建表方式，其他几个使用uuid表作为主键的，在数据区域里就可以找到id字段
## Expected behavior

在数据源中新建表中的主键id字段后，可以在配置字段以及工作流中找到此主键id字段

**Comment by hongboji** [comment]
与 https://github.com/nocobase/nocobase/issues/4438 问题相同

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4499 可以拉取最新代码，看看是否解决

**Comment by Hongye1720** [comment]
> #4499 可以拉取最新代码，看看是否解决

升级到v1.0.0-alpha.17版本后，还是无法显示id字段

**Comment by hongboji** [comment]
升级到最新，检查是否解决

**Comment by Hongye1720** [comment]
升级到nocobase-1.2.5-alpha版本后已解决，非常感谢
