### ISSUE TITLE
Dropdown boxes x not user friendly

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#4501]
## * Describe the bug

When you have entered several options that is presented in a dropdown box and you go back to edit this box, there is a x apearing, a delet x, so I have had users that have deleted to choise already made instaed of being able to choose a new option in the drop down. I understand that the dropdown apears when you click in the box itself, but users have complained that the do not understand how they should chose new options.

![image](https://github.com/nocobase/nocobase/assets/89129225/29236b9f-197f-4899-ac03-09c00260054a)

## * Environment

- NocoBase version:

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by hongboji** [comment]
This is not a bug, issues will be closed, keep the feedback coming with questions!
