### ISSUE TITLE
子表格中使用级联选择的样式错误

### ISSUE THREAD

**Issue by powerhyh** [nocobase/nocobase#4510]
## * Describe the bug
在子表格中, 添加一项数据, 某字段使用级联选择, 选择完成后, 再新增一项数据时, 上一个级联选择完成的就会发现第一级选择不显示

## * Environment

- NocoBase version: v1.0.0-alpha.15

- Database type and version: mariadb, 11.3
  

- OS: windows 10

- Deployment Methods: Git source code

- Docker image version:

- NodeJS version: 18.18.0

## * How To Reproduce
1. 创建一个树型结构表, 新增字段为name
2. 添加数据, 如 鱼, 父记录不选对, 然后再添加一个记录, 罗非鱼, 父记录为鱼, 这样就有了一个级联选择数据源
3. 创建2个表, A主表名为订单, B为副表名为订单产品, 关系为 B 多对一 A
4. 创建一个页面, 表单链接数据表源为订单, 然后添加订单产品字段, 字段组件为子表格, 配置字段选择产品规格
5. 在产品规格列中设置选项中把标题字段由ID改为名称
6. 然后选择字段组件为级联选择, 这时出现第一个错误:  字段组件选择列表会出现没数据选择, 只显示 CascadeSelect 字样
![微信截图_20240528203014](https://github.com/nocobase/nocobase/assets/39689160/02611d3a-0d6c-4f4d-845a-98aa5af76c5c)
7. 把列宽改为500, 因为如果不改宽, 在出现二级选择时不是并排显示, 这样不符合我的要求
8. 添加一项数据, 是正常显示
![1](https://github.com/nocobase/nocobase/assets/39689160/cd191723-6cab-4b4a-9b4d-fc885d8f3bc1)

9. 当再次添加新数据时, 就会出现显示混乱
![2](https://github.com/nocobase/nocobase/assets/39689160/61882f15-7230-4129-b38d-f26c04df9d54)
![3](https://github.com/nocobase/nocobase/assets/39689160/ada86771-d48a-47d3-9e7a-4efdcd3ad35b)

**Comment by LinSiwen** [comment]
多对一的字段，父表可以是树表吗？感觉会有问题。

**Comment by powerhyh** [comment]
建立数据表时内置的中国行政区的级联样式, 感觉就会好很多, 可惜不支持在区块中使用

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4517

**Comment by hongboji** [comment]
子表格中不支持级联，显示错误，已经修复
