### ISSUE TITLE
操作按钮的 "更新数据" 能否增强功能

### ISSUE THREAD

**Issue by m50046208** [nocobase/nocobase#453]
子表 提交,或者编辑数据 之后,将 子表的最后一条记录中指定字段的值,更新到母表的指定字段.

**Comment by budnail** [comment]
Google Translate to English:
After the child table is submitted, or the data is edited, the value of the specified field in the last record of the child table is updated to the specified field of the parent table.

**Comment by zhouyanliang** [comment]
We are planning a new feature that custom actions can trigger a workflow which will solve your problem.

**Comment by m50046208** [comment]
thank you! great job.
