### ISSUE TITLE
The import and export buttons are unavailable

### ISSUE THREAD

**Issue by yuqichou** [nocobase/nocobase#4545]
## * Describe the bug
The import and export buttons are unavailable

## * Environment
develop

- NocoBase version:  v1.0.0-alpha.15

- Database type and version:  MySQL 8.x
  

- OS: MacOS

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

## * How To Reproduce

所有数据表的导入导出功能不正常（之前可以）：编辑模式下按钮为不可用状态，非编辑模式下导入导出按钮也不可见，使用本地存储模式。
The import and export function of all data tables is abnormal (yes before) : The import and export buttons are unavailable in editing mode and invisible in non-editing mode. The local storage mode is used.

## Screenshots
<img width="435" alt="issue" src="https://github.com/nocobase/nocobase/assets/1728650/869ba4af-a94c-4802-923d-3164491f838a">

**Comment by hongboji** [comment]
Check the current role of the logged-in user to see if they have import/export privileges.

**Comment by yuqichou** [comment]
> Check the current role of the logged-in user to see if they have import/export privileges.

solved
