### ISSUE TITLE
There is a problem with the popup style of table import under the interactive menu in the online demo

### ISSUE THREAD

**Issue by dong-lufei** [nocobase/nocobase#4570]
As shown below

![微信截图_20240605214533](https://github.com/nocobase/nocobase/assets/63916062/19a2d5d7-9f6a-40f9-9352-3a293ec56401)

**Comment by hongboji** [comment]
Please use the latest version, delete the import button and re-enable it to check if it is s

**Comment by hongboji** [comment]
The issue will be closed. Please continue to give feedback if you have any questions.
