### ISSUE TITLE
图片字段（附件）在编辑form中会经常突然变得很大

### ISSUE THREAD

**Issue by panfu** [nocobase/nocobase#4572]
## * Describe the bug

图片字段（附件）在编辑form中会经常突然变得很大，其实我的图片很小，不知道为啥总被撑开。

## * Environment

- NocoBase version: v1.0.0-alpha.17

- Database type and version: SQLite
  

- OS: MacOS

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/17453/da65ba4d-a935-482b-971a-930f6d5cd31c)

**Comment by mytharcher** [comment]
可以考虑将 docker 镜像换成 nocobase/nocobase:main 试试，最新的文件管理器有更新，不存在该问题。
