### ISSUE TITLE
筛选表单中输入框类型输入空格筛选后的数据为空

### ISSUE THREAD

**Issue by TabbyTech** [nocobase/nocobase#4581]
## * Describe the bug

筛选表单中输入框类型筛选时没有trim掉前后空格

## * Environment

- NocoBase version: 1.0.0-alpha.6

- Database type and version:  MySQL 8.x
  

- OS: MacOS, Windows

- Deployment Methods: Git source code

- Docker image version:

- NodeJS version: 

## * How To Reproduce
一个最基本的增删改查，一个筛选表单，带输入框的，然后下面一个展示列表，筛选中输入框输入空格，点击筛选，下面的数据为空

## Screenshots

![f7a8283c8b422a4f8983cccee23b6e39](https://github.com/nocobase/nocobase/assets/26021047/287be34d-3ae1-4b53-82aa-1fe134f02339)

**Comment by hongboji** [comment]
输入空格可以筛选带空格的数据，如果下面的数据为空，检查数据中是否有匹配的数据
