### ISSUE TITLE
表格区块点击导入一直loading

### ISSUE THREAD

**Issue by TabbyTech** [nocobase/nocobase#4591]
## * Describe the bug
表格区块添加了导入功能，然后点击导入，弹出对话框，一直在loading，控制台打开报错了

## * Environment

- NocoBase version:

- Database type and version: 1.0.0-alpha.6
  

- OS: MacOS, Windows

- Deployment Methods: Docker

- Docker image version: 1.0.0-alpha.6

- NodeJS version: 

## * How To Reproduce
基本的增删改查，然后表格新增了几条数据，开放导入功能，点击导入就会出现

## Screenshots
![image](https://github.com/nocobase/nocobase/assets/26021047/67fb6600-cb63-4139-99c2-6c45baeac5eb)
![image](https://github.com/nocobase/nocobase/assets/26021047/307241ca-9c4f-4f21-a07b-9a1c21ca60cd)

**Comment by zhangzhonghe** [comment]
有可能是你本地的网络问题，检查下网络再试试呢？或者可以将 NocoBase 升级到最新版。

如还有问题可以随时打开该 issue，并补充上详细的复现步骤， 感谢。
