### ISSUE TITLE
OneToMany with FileCollection not working

### ISSUE THREAD

**Issue by spicter** [nocobase/nocobase#4604]
## * Describe the bug

If I try to create a one to many relation between a standard collection and a file collection the file collection does not show up in the  "target collection" drop down list

## * Environment

- NocoBase version:
alpha.17

- Database type and version: 
psql 12
  

- OS:
Mac

- Deployment Methods:
Docker

- Docker image version:

- NodeJS version:

**Comment by hongboji** [comment]
Supports only many-to-one and many-to-many
