### ISSUE TITLE
Print is not showing content

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#4611]
## * Describe the bug

When I trying to print, the content isnt sohwed.
Previously, in version [v1.0.0-alpha.17] was working ok.

NocoBase
v1.0.1-alpha.1

## * Environment

- NocoBase version:
NocoBase
v1.0.1-alpha.1

- Database type and version: 
  Postgres 16.2

- OS:
Win 10

- Deployment Methods:
Node 

- Docker image version:

- NodeJS version:

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/41135285/be2478c3-4c5b-460f-8dbb-dc7c2a0e9fa6)

**Comment by pehua** [comment]
Hi, news?.

thanks

**Comment by hongboji** [comment]
Use the latest and check if it resolves

**Comment by pehua** [comment]
> Use the latest and check if it resolves

Yes, it works again.

Thanks.
