### ISSUE TITLE
子表格删行，提交后，数据库表并没有删除行。

### ISSUE THREAD

**Issue by LinSiwen** [nocobase/nocobase#4625]
## * Describe the bug

子表格删行，提交后，数据库表并没有删除行。
## * Environment
windows，
create-nocobase-app 方式安装，
node v20.12.2，
npm v10.7.0
yarn v1.22.22

- NocoBase version:1.0.1

- Database type and version: PostgreSQL 12
  

- OS:Windows 11

- Deployment Methods:Create-nocobase-app

- Docker image version:

- NodeJS version:node v20.12.2，

**Comment by LinSiwen** [comment]
自己写了表触发器，解决了这个问题，但还是希望“子表格”组件本身可以实现。

**Comment by chenos** [comment]
关系数据是通过外键关联的，关系数据从子表格里删除，只是解除关联并不直接删除数据。
另外，解除关联的同时，删除关系数据风险较高，所以现在并没有直接删除，目前可以通过配置个工作流来解决删除数据的问题。

接下来会优先把关系删除的文案做一些改进和提示说明；
后续也可以增加个「解除关联的同时，删除数据」的配置项用于优化这类场景。
