### ISSUE TITLE
设置的工作流，没有按判断条件的节点的内容，更新结果

### ISSUE THREAD

**Issue by 0x22E09-8** [nocobase/nocobase#4628]
## * Describe the bug

在工作流的判断节点中加了判断条件，但是更新数据的时候没有按判断条件的内容执行

## * Environment

- NocoBase version:v1.0.1-alpha.1

- Database type and version: MySQL
  

- OS: linux

- Deployment Methods:Docker

- Docker image version:

- NodeJS version:latest 

## Screenshots

![1](https://github.com/nocobase/nocobase/assets/28555655/c0d3e5f1-0e02-40ff-8b1d-a06a3c654418)

![image](https://github.com/nocobase/nocobase/assets/28555655/e9aa0c29-436a-4c61-8719-88888bd65c4f)

![image](https://github.com/nocobase/nocobase/assets/28555655/3cb2301e-4c46-4d59-8893-c0711e0e8278)

![image](https://github.com/nocobase/nocobase/assets/28555655/3da87c33-1560-467b-9ef6-7c6930ea649f)

## Logs

ppends":["fields","category"],"sort":["sort","key"],"filter":{},"resourceName":"collections","actionName":"list"}},"userId":1,"status":200,"cost":21,"app":"main","reqId":"c602e416-3a24-47c6-9b97-e3595fe44e63","timestamp":"2024-06-11 09:27:41"}
{"level":"info","message":"request GET /api/roles:check","method":"GET","path":"/api/roles:check","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"5877c153-0dd1-4e43-bd72-7f15cae03bcc","timestamp":"2024-06-11 09:27:41"}
{"level":"info","message":"response /api/roles:check","method":"GET","path":"/api/roles:check","res":{"status":200},"action":{"actionName":"check","resourceName":"roles","params":{"resourceName":"roles","actionName":"check"}},"userId":1,"status":200,"cost":4,"app":"main","reqId":"5877c153-0dd1-4e43-bd72-7f15cae03bcc","timestamp":"2024-06-11 09:27:41"}
{"level":"info","message":"request GET /api/uiSchemas:getJsonSchema/nocobase-admin-menu","method":"GET","path":"/api/uiSchemas:getJsonSchema/nocobase-admin-menu","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"cbfc6ddc-cd03-481d-9e59-f36a47d34a53","timestamp":"2024-06-11 09:27:41"}
{"level":"info","message":"response /api/uiSchemas:getJsonSchema/nocobase-admin-menu","method":"GET","path":"/api/uiSchemas:getJsonSchema/nocobase-admin-menu","res":{"status":200},"action":{"actionName":"getJsonSchema","resourceName":"uiSchemas","params":{"filterByTk":"nocobase-admin-menu","resourceName":"uiSchemas","resourceIndex":"nocobase-admin-menu","actionName":"getJsonSchema"}},"userId":1,"status":200,"cost":1,"app":"main","reqId":"cbfc6ddc-cd03-481d-9e59-f36a47d34a53","timestamp":"2024-06-11 09:27:41"}
{"level":"info","message":"request GET /api/executions:get?appends%5B%5D=jobs&appends%5B%5D=workflow&appends%5B%5D=workflow.nodes&filter=%7B%22id%22%3A%22408%22%7D","method":"GET","path":"/api/executions:get?appends%5B%5D=jobs&appends%5B%5D=workflow&appends%5B%5D=workflow.nodes&filter=%7B%22id%22%3A%22408%22%7D","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"6b54eb23-4c55-44da-a83f-414ac885e8c8","timestamp":"2024-06-11 09:27:41"}
{"level":"info","message":"response /api/executions:get?appends%5B%5D=jobs&appends%5B%5D=workflow&appends%5B%5D=workflow.nodes&filter=%7B%22id%22%3A%22408%22%7D","method":"GET","path":"/api/executions:get?appends%5B%5D=jobs&appends%5B%5D=workflow&appends%5B%5D=workflow.nodes&filter=%7B%22id%22%3A%22408%22%7D","res":{"status":200},"action":{"actionName":"get","resourceName":"executions","params":{"appends":["jobs","workflow","workflow.nodes"],"filter":{"id":"408"},"resourceName":"executions","actionName":"get"}},"userId":1,"status":200,"cost":7,"app":"main","reqId":"6b54eb23-4c55-44da-a83f-414ac885e8c8","timestamp":"2024-06-11 09:27:41"}
{"level":"info","message":"request GET /api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"ab8e5441-fe14-4892-9aee-a47f9c7a6c72","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"request GET /api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"79449693-172e-4e8c-89f7-7d641154561c","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"response /api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","res":{"status":200},"action":{"actionName":"list","resourceName":"executions","params":{"sort":["-createdAt"],"pageSize":"10","fields":["id","status","createdAt"],"filter":{"key":"3n02nicgi76","id":{"$lt":408}},"resourceName":"executions","actionName":"list"}},"userId":1,"status":200,"cost":6,"app":"main","reqId":"ab8e5441-fe14-4892-9aee-a47f9c7a6c72","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"response /api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","res":{"status":200},"action":{"actionName":"list","resourceName":"executions","params":{"sort":["createdAt"],"pageSize":"10","fields":["id","status","createdAt"],"filter":{"key":"3n02nicgi76","id":{"$gt":408}},"resourceName":"executions","actionName":"list"}},"userId":1,"status":200,"cost":5,"app":"main","reqId":"79449693-172e-4e8c-89f7-7d641154561c","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"request GET /api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"28bcec78-f3fd-46c4-95e2-33236358b3ba","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"request GET /api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"684d5ae1-a947-4f3f-b357-bc1db80a43e5","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"response /api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=-createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24lt%22%3A408%7D%7D","res":{"status":200},"action":{"actionName":"list","resourceName":"executions","params":{"sort":["-createdAt"],"pageSize":"10","fields":["id","status","createdAt"],"filter":{"key":"3n02nicgi76","id":{"$lt":408}},"resourceName":"executions","actionName":"list"}},"userId":1,"status":200,"cost":6,"app":"main","reqId":"28bcec78-f3fd-46c4-95e2-33236358b3ba","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"response /api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","method":"GET","path":"/api/executions:list?sort=createdAt&pageSize=10&fields%5B%5D=id&fields%5B%5D=status&fields%5B%5D=createdAt&filter=%7B%22key%22%3A%223n02nicgi76%22%2C%22id%22%3A%7B%22%24gt%22%3A408%7D%7D","res":{"status":200},"action":{"actionName":"list","resourceName":"executions","params":{"sort":["createdAt"],"pageSize":"10","fields":["id","status","createdAt"],"filter":{"key":"3n02nicgi76","id":{"$gt":408}},"resourceName":"executions","actionName":"list"}},"userId":1,"status":200,"cost":4,"app":"main","reqId":"684d5ae1-a947-4f3f-b357-bc1db80a43e5","timestamp":"2024-06-11 09:27:42"}
{"level":"info","message":"request GET /api/workflows:list?sort%5B%5D=-createdAt&except%5B%5D=config&filter=%7B%22current%22%3Atrue%7D","method":"GET","path":"/api/workflows:list?sort%5B%5D=-createdAt&except%5B%5D=config&filter=%7B%22current%22%3Atrue%7D","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"6c89a20e-eb71-44dd-a317-e5eb5382998b","timestamp":"2024-06-11 09:27:46"}
{"level":"info","message":"response /api/workflows:list?sort%5B%5D=-createdAt&except%5B%5D=config&filter=%7B%22current%22%3Atrue%7D","method":"GET","path":"/api/workflows:list?sort%5B%5D=-createdAt&except%5B%5D=config&filter=%7B%22current%22%3Atrue%7D","res":{"status":200},"action":{"actionName":"list","resourceName":"workflows","params":{"sort":["-createdAt","id"],"except":["config"],"filter":{"current":true},"resourceName":"workflows","actionName":"list"}},"userId":1,"status":200,"cost":5,"app":"main","reqId":"6c89a20e-eb71-44dd-a317-e5eb5382998b","timestamp":"2024-06-11 09:27:46"}
{"level":"info","message":"request GET /api/logger:list","method":"GET","path":"/api/logger:list","req":{"header":{"x-role":"root","x-hostname":"10.10.3.57","x-timezone":"+08:00","x-locale":"zh-CN","x-authenticator":"basic"}},"app":"main","reqId":"432c1221-29a3-42b7-b753-a2dff69ec4e8","timestamp":"2024-06-11 09:27:50"}
{"level":"info","message":"response /api/logger:list","method":"GET","path":"/api/logger:list","res":{"status":200},"action":{"actionName":"list","resourceName":"logger","params":{"resourceName":"logger","actionName":"list"}},"userId":1,"status":200,"cost":2,"app":"main","reqId":"432c1221-29a3-42b7-b753-a2dff69ec4e8","timestamp":"2024-06-11 09:27:50"}

**Comment by hongboji** [comment]
不包含  fail,block  ,这种写法是一个字符串 ，看内容符合预期

**Comment by 0x22E09-8** [comment]
如果是看成一个字符串，那按照我的预期是不少是得把fail 和 block 写成两个条件，另外不包含不能直接读取下拉的值，可以支持读取下拉的值吗？

**Comment by hongboji** [comment]
下拉值使用字段：下拉单选、下拉多选

**Comment by 0x22E09-8** [comment]
![image](https://github.com/nocobase/nocobase/assets/28555655/94c1246a-101a-4e2f-a3d6-f347cbd78413)
图中这里实际上字段就是一个下拉框，但是试用的时候不能进行下拉，才用了手动输入的字符串。不过按照第一次的回答把字符串分开多个条件已经解决了问题。

**Comment by hongboji** [comment]
这个地方是表达式 ，现在不支持下拉
