### ISSUE TITLE
cannot add any field to formula field (formula.js) no field list presented

### ISSUE THREAD

**Issue by JSP6668** [nocobase/nocobase#4640]
Hi All,

what do i do wrong i cannot add any field to CONCATENATE('') no field-list is presented? 
(I saw on screenshots that there should be one)

Is there any Keystroke that I'm missing or similar

Thanks for your help!

**Comment by mytharcher** [comment]
Please use our issue template and follow the steps to create issue. Or no one could help you with your limited information.

**Comment by JSP6668** [comment]
OK, will do in the Future.

The Solution: 
The file list comes when you click on the "x" on the end of the field. Very missleading, I thought the "x" is to clear the 
field entry.

![image](https://github.com/nocobase/nocobase/assets/109982540/fb078d3b-6b6c-4f85-8793-82e1add746d9)
