### ISSUE TITLE
从备份中还原系统后，出现报错

### ISSUE THREAD

**Issue by 0x22E09-8** [nocobase/nocobase#4641]
## * Describe the bug

从系统备份还原系统后，出现表设计报错

## * Environment

- NocoBase version:v1.2.2-alpha

- Database type and version: MySQL 
  

- OS:Linux

- Deployment Methods:

- Docker image version:latest

- NodeJS version:

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/28555655/04ea1b44-4659-4fef-993c-612b961ea4bf)

## Logs

{"level":"error","message":"Unable to connect to the database","stack":"Error: Unable to connect to the database\n    at _AsyncEmitter.auth (/app/nocobase/node_modules/@nocobase/database/lib/database.js:656:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async _AsyncEmitter.authenticate (/app/nocobase/node_modules/@nocobase/server/lib/application.js:411:5)\n    at async Object.callback (/app/nocobase/node_modules/@nocobase/server/lib/application.js:736:9)\n    at async _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:5)\n    at async _AsyncEmitter.runAsCLI (/app/nocobase/node_modules/@nocobase/server/lib/application.js:498:23)","meta":{},"module":"application","submodule":"","method":"","app":"main","reqId":"75ca8364-b3bc-40da-80b1-16f1bf0e856c","dataSourceKey":"main","timestamp":"2024-06-12 13:33:15"}
{"level":"error","message":"connect ECONNREFUSED 172.23.0.2:3306","stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 172.23.0.2:3306\n    at ConnectionManager.connect (/app/nocobase/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)\n    at async /app/nocobase/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32\n    at async ConnectionManager.getConnection (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)\n    at async /app/nocobase/node_modules/sequelize/lib/sequelize.js:305:26\n    at async Sequelize.authenticate (/app/nocobase/node_modules/sequelize/lib/sequelize.js:457:5)\n    at async BackOff.authenticate [as request] (/app/nocobase/node_modules/@nocobase/database/lib/database.js:635:9)","app":"main","reqId":"75ca8364-b3bc-40da-80b1-16f1bf0e856c","timestamp":"2024-06-12 13:33:15"}
{"level":"error","message":"connect ECONNREFUSED 172.23.0.2:3306","meta":{"err":"SequelizeConnectionRefusedError: connect ECONNREFUSED 172.23.0.2:3306\n    at ConnectionManager.connect (/app/nocobase/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionManager._connect (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)"},"module":"app","submodule":"getLang","method":"error-handler","app":"main","reqId":"ac92cab9-5313-4629-b03f-4801ded73531","dataSourceKey":"main","timestamp":"2024-06-12 13:33:30"}
{"level":"error","message":"Incorrect table definition; there can be only one auto column and it must be defined as a key","stack":"Error\n    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)\n    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MySQLQueryInterface.createTable (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:98:12)\n    at async Restorer.importCollection (/app/nocobase/node_modules/@nocobase/plugin-backup-restore/dist/server/restorer.js:267:7)\n    at async importCollection (/app/nocobase/node_modules/@nocobase/plugin-backup-restore/dist/server/restorer.js:155:7)\n    at async Restorer.importCollections (/app/nocobase/node_modules/@nocobase/plugin-backup-restore/dist/server/restorer.js:185:9)\n    at async Restorer.restore (/app/nocobase/node_modules/@nocobase/plugin-backup-restore/dist/server/restorer.js:125:5)\n    at async _AppCommand.<anonymous> (/app/nocobase/node_modules/@nocobase/plugin-backup-restore/dist/server/commands/restore-command.js:72:5)\n    at async _AppCommand.parseAsync (/app/nocobase/node_modules/@nocobase/server/node_modules/commander/lib/command.js:935:5)","meta":{},"module":"application","submodule":"","method":"","app":"main","reqId":"3b640f8f-f4dd-4321-a2b4-3ec14fc41590","dataSourceKey":"main","timestamp":"2024-06-12 13:36:25"}

**Comment by hongboji** [comment]
请问备份文件是从什么版本的nocobase备份的，还原到 NocoBase version:v1.2.2-alpha ？

**Comment by 0x22E09-8** [comment]
从v1.0.1-alpha.1备份后 还原到v1.2.2-alpha
