### ISSUE TITLE
新的demo系统样式有问题

### ISSUE THREAD

**Issue by TabbyTech** [nocobase/nocobase#4645]
## * Describe the bug
新申请的demo系统，仪表盘页面，尝试加了一个工作台区块，然后把设计模式关闭，区块之间就没有间距了

## * Environment

- NocoBase version: v1.2.2-alpha.20240612155159

- Database type and version: 
  

- OS: MacOS, Windows

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce
仪表盘页面，尝试加了一个工作台区块，然后把设计模式关闭，区块之间就没有间距了

## Screenshots
![image](https://github.com/nocobase/nocobase/assets/26021047/cfde77d4-7837-45a6-9651-37dac54cf844)
![image](https://github.com/nocobase/nocobase/assets/26021047/c7d9848a-2702-4824-bb12-a717f69cf665)

**Comment by hongboji** [comment]
请提供下有问题的页面URL

**Comment by TabbyTech** [comment]
https://a_69pkpoi0qdo.v7.demo-cn.nocobase.com/admin/qr6akbz4dxy

**Comment by zhouyanliang** [comment]
已修复
