### ISSUE TITLE
Duplicate mode select all gives unique violation error

### ISSUE THREAD

**Issue by thomaswennersten** [nocobase/nocobase#4659]
## * Describe the bug

If I try to do a copy of a row in a table using the copy Action and under Duplicate mode option choses select All, I get an error. However if i manually select All fields and try to copy it works.

## * Environment

- NocoBase version: 0.21.0 alpha 6

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by zhangzhonghe** [comment]
Reproduction: https://main.test.nocobase.com/admin/1dt0ispgun2

**Comment by thomaswennersten** [comment]
I am not sure what to do with the link you published?

**Comment by zhangzhonghe** [comment]
> I am not sure what to do with the link you published?

You don't have to do anything; it's for our debugging purposes. Thanks for your feedback!

**Comment by thomaswennersten** [comment]
[like]  Thomas Wennersten reacted to your message:
________________________________

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4658

**Comment by zhangzhonghe** [comment]
> #4658

@hongboji  This isn't related to #4658.

**Comment by hongboji** [comment]
The data in the Unique Constraint field cannot be copied, exclude it when selecting the field.

**Comment by thomaswennersten** [comment]
I have no unique constrained fields in the collection I try to copy, except the ID and that is not visible in the choose fields. I get a different result if i chose to select all in the dialog then when I manually select all visible fileds.

**Comment by hongboji** [comment]
Is there a relational field, please?
Selecting all recursively selects the fields under the relationship field, while manual selection does not.
Please check if it is caused by selecting the field under the relationship field.
Please check the log file to see what data is not allowed.
