### ISSUE TITLE
MD字段H1比H2小的问题

### ISSUE THREAD

**Issue by lanbinshijie** [nocobase/nocobase#466]
如图
![image](https://user-images.githubusercontent.com/62149873/172000298-c951db90-e51b-495b-ba07-60780f7401d9.png)
![image](https://user-images.githubusercontent.com/62149873/172000302-c050ded7-0bc8-4c9f-a4d3-78502234e27d.png)
版本：Version 0.7.0-alpha.78
系统：Centos Docker
谢谢！

**Comment by zhouyanliang** [comment]
Fixed #469
