### ISSUE TITLE
区块与区块之间没有空隙

### ISSUE THREAD

**Issue by yaocanke** [nocobase/nocobase#4660]
v1.2.2-alpha
在页面配置模式下，区块与区块之间有间隙（见图1），但是完成页面编辑后，区块之间的间隙消失了（见图2）。
![image](https://github.com/nocobase/nocobase/assets/89123307/f717c8e5-6084-40ed-9226-1e696d1e66fb)

![image](https://github.com/nocobase/nocobase/assets/89123307/4101e973-7222-4c8e-984b-5b97ccb77587)

**Comment by hongboji** [comment]
最新版已经修复

**Comment by zhangzhonghe** [comment]
已修复：#4652
