### ISSUE TITLE
Application Unusable After Importing Backup File Due to Missing Plugin

### ISSUE THREAD

**Issue by generalistcodes** [nocobase/nocobase#4669]
**Description:**
After importing a backup file from a demo into NocoBase, I encountered an issue where the application became unusable due to a missing plugin. It would be beneficial to have a validation step before importing backup files to check for any required plugins.

**Steps to Reproduce:**
1. Create or obtain a backup file from a demo instance of NocoBase.
2. Attempt to import the backup file into a fresh instance of NocoBase.
3. Observe that the application fails to function properly due to a missing plugin.

**Expected Behavior:**
The application should either:
1. Import the backup file successfully and include all necessary plugins.
2. Perform a validation check before importing the backup file and notify the user of any missing plugins required for the import.

**Actual Behavior:**
The application becomes unusable after importing the backup file because it lacks the necessary plugin.
```js
Error: Request failed with status code 503
    at p.exports (npm.axios.f696c6e5.async.js:1:6358)
    at p.exports (npm.axios.f696c6e5.async.js:1:8848)
    at XMLHttpRequest.s (npm.axios.f696c6e5.async.js:1:1012) {code: 'ENOENT', status: 503, message: "ENOENT: no such file or directory, realpath '/app/…_modules/@nocobase/plugin-auth-saml/package.json'", command: {…}, maintaining: true}
```

**Screenshots:**
![image](https://github.com/nocobase/nocobase/assets/1046316/ca735290-d569-4e27-ab96-6ce9942bfffc)
![image](https://github.com/nocobase/nocobase/assets/1046316/5c9805e0-7b78-4c34-9f22-a937577b9935)

**Environment:**
- NocoBase latest

**Additional Context:**
(Add any other context about the problem here.)

**Possible Solution:**
Implement a validation step before importing backup files to check for required plugins and notify the user if any are missing.

**Comment by tuiliere** [comment]
I faced same issue and lost bunch of time to realize a plugin was missing on the new instance.
I confirm it would be use-full and very more friendly to have a check and error message in this situation.

**Comment by zhouyanliang** [comment]
In the latest `next` branch, the old plugin has been replaced with a new backup and restore plugin. The restoration process is more user-friendly.
