### ISSUE TITLE
用户角色配置问题

### ISSUE THREAD

**Issue by spencerswagger** [nocobase/nocobase#4680]
## Describe
运营侧的管理员无法自行分配用户角色

## Environment
NocoBase v1.2.4-alpha

## How To Reproduce
创建角色-运营管理员
仅勾选允许配置插件-用户与权限-用户

使用该角色的用户登录后，编辑用户资料时，角色下拉框提示无权限

## Expected behavior
这是一个很常见的场景，配置完表和界面后交由运营部门去操作平台。
开发者不希望运营部门改动配置好的内容，预设了一些角色交由运营部门自行分给给相应用户。
但目前无法做到仅开放用户管理功能时配置角色的需求。

BTW：即使实现了运营方配置角色的功能，如若他能配置admin角色，仍存在越权问题。

**Comment by hongboji** [comment]
角色权限中配置数据源中数据表（角色）的数据查看权限
