### ISSUE TITLE
在一个弹窗页面加了一个Markdown，但是Markdown 的变量使用的时候，当前记录、当前弹窗的记录是相同的内容，v1.2.2-alpha版本是正确的

### ISSUE THREAD

**Issue by 0x22E09-8** [nocobase/nocobase#4688]
## * Environment

- NocoBase version:v1.2.4-alpha

- Database type and version: MySQL 
  

- OS:linux

- Deployment Methods:

- Docker image version:

- NodeJS version:

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/28555655/eb19a6bb-e743-44c3-bb37-96b8c1f56d23)
![image](https://github.com/nocobase/nocobase/assets/28555655/e73d1621-9b76-4ac5-8839-ace2fb10a4ce)

**Comment by hongboji** [comment]
这不是缺陷，1.2.2-alpha也是这样，检查自己的配置
![image](https://github.com/nocobase/nocobase/assets/116709317/66a78a29-3084-4882-93fd-22ae0db8594d)
![image](https://github.com/nocobase/nocobase/assets/116709317/fbcc6c12-663c-4397-9f06-4123ca5fa928)
![image](https://github.com/nocobase/nocobase/assets/116709317/eb6e7ef7-6dc2-40e7-a23d-b9c38f7aa8bf)

**Comment by 0x22E09-8** [comment]
之前确实当前记录和当前弹窗的内容是不一样的，我设置的也是当前记录的值，之前是有数据的，现在没有数据
![image](https://github.com/nocobase/nocobase/assets/28555655/442c0a02-cb8f-46c8-90b7-5ca024b460fd)
![image](https://github.com/nocobase/nocobase/assets/28555655/ae0aab06-55fc-4668-877d-941fdfa79f1c)

**Comment by hongboji** [comment]
使用关系数据区块的时候  ，当前记录和弹窗记录不一样
