### ISSUE TITLE
Markdown 的引用的变量不能展示中文名称，时间希望展示时分秒，见图

### ISSUE THREAD

**Issue by 0x22E09-8** [nocobase/nocobase#4690]
## * Environment

- NocoBase version:v1.2.4-alpha

- Database type and version: 
  

- OS:linux

- Deployment Methods:

- Docker image version:

- NodeJS version:

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/28555655/0d885e3f-c515-4c57-9363-c6ad045716d4)
![image](https://github.com/nocobase/nocobase/assets/28555655/da7ad463-8d2f-4f51-9884-ac020e2a3cac)
![image](https://github.com/nocobase/nocobase/assets/28555655/ce1a798d-5149-4d14-b7be-b589d6826d1c)

**Comment by hongboji** [comment]
当前不支持Markdown 中变量数据的格式化 ，后续提供支持，这不是缺陷，我将关闭issues，请关注我们
