### ISSUE TITLE
工作流的人工处理的操作界面配置，数据区块表单，关系型字段，字段组件选子表格会渲染失败。

### ISSUE THREAD

**Issue by hwongxf** [nocobase/nocobase#4692]
## * Describe the bug
工作流的人工处理的操作界面配置，数据区块表单，关系型字段，选子表格会渲染失败。

## * Environment

- NocoBase version: v1.2.4-alpha

- Database type and version:  PostgreSQL 15
  

- OS:

- Deployment Methods:Docker

- Docker image version:nocobase/nocobase:latest

- NodeJS version:

## * How To Reproduce
工作流的人工处理的操作界面配置，数据区块表单，关系型字段，字段组件选子表格会渲染失败。。

**Comment by hongboji** [comment]
渲染失败的现象是什么 ，报错？，可以把工作流的全部配置  ，使用操作过程 出现界面全部截图说明

**Comment by hwongxf** [comment]
简单测试了一下，现象必现：
1、建一个销售订单表，一个销售订单明细表，一对多关系。
2、建一个工作流，数据表事件，直接添加人工处理，配置界面
3、配置界面配置关系型字段，选子表格，就报错。




销售订单明细选子表格，就报错








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nocobase/nocobase"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月18日(星期二) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nocobase/nocobase] 工作流的人工处理的操作界面配置，数据区块表单，关系型字段，字段组件选子表格会渲染失败。 (Issue #4692)





 
渲染失败的现象是什么 ，报错？，可以把工作流的全部配置  ，使用操作过程 出现界面全部截图说明

**Comment by hongboji** [comment]
link T-4602

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4719

**Comment by hongboji** [comment]
拉取最新的代码，检查是否解决

**Comment by hwongxf** [comment]
最新代码子表格已解决。但是子详情不显示内容。

**Comment by mytharcher** [comment]
> 最新代码子表格已解决。但是子详情不显示内容。

是说的在待办弹窗操作的时候么？看看是否已经配置了对应数据来源的“预加载关系数据”？

**Comment by hwongxf** [comment]
工作流的人工处理的操作界面配置，数据区块表单-关系型字段-字段组件选子详情。就是之前的子表格改成子详情，待办弹窗操作子详情没有数据，子表格有数据。

**Comment by mytharcher** [comment]
<img width="1042" alt="image" src="https://github.com/nocobase/nocobase/assets/525658/27d278b5-54a4-4125-a5a3-c922d55a1881">

我这测试子详情是有数据的，关键需要配置对应数据来源节点（或触发器）的“预加载关系数据”：

![image](https://github.com/nocobase/nocobase/assets/525658/f4d031fa-87f6-436f-b7cb-6394c1b1ad1c)

不知道你说的子详情是否是这种情况？或者把详细过程贴图我们看下？

**Comment by hwongxf** [comment]
![C(PU8V_X)V0FQ_@ZQ)%_FX4](https://github.com/nocobase/nocobase/assets/85606230/f3976a35-a234-4ce9-8b11-699fcb7490de)
人工处理操作界面：（触发数据上面是子表格，下面是子详情）
![U`J940U)2@ 0WUC `{SOQXE](https://github.com/nocobase/nocobase/assets/85606230/187d212c-77cc-4ec2-9113-917a9d2212e5)
结果：
![image](https://github.com/nocobase/nocobase/assets/85606230/9dc542bf-bb10-4eea-a4ab-6e7826ff85fc)

**Comment by mytharcher** [comment]
<img width="1389" alt="image" src="https://github.com/nocobase/nocobase/assets/525658/9f4ae70f-29b6-4c32-ae76-31c24121f4b8">

测试了没发现问题？

**Comment by hongboji** [comment]
请问切换到子详情后，子详情有设置字段吗？

**Comment by hongboji** [comment]
这个问题我先关闭 ，新的问题请重新提交下，可以提供下详细的配置过程、使用过程 截图或者视频谢谢
