### ISSUE TITLE
Markdown 的引用变量的时候，展示了两个值

### ISSUE THREAD

**Issue by 0x22E09-8** [nocobase/nocobase#4693]
## * Environment

- NocoBase version:v1.2.4-alpha

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## Screenshots

![image](https://github.com/nocobase/nocobase/assets/28555655/e217aab4-05bb-4ee2-a3b0-5181b5414b3d)
![image](https://github.com/nocobase/nocobase/assets/28555655/ba6a3b17-d77b-48e5-b1db-4fdbf9360ee4)

**Comment by hongboji** [comment]
看看是不是对多的关系字段，对多的就会出现多个

**Comment by 0x22E09-8** [comment]
> 看看是不是对多的关系字段，对多的就会出现多个

是一个多对多的字段，我想用的就是这个多对多字段表的修改人和修改时间

**Comment by hongboji** [comment]
这不是缺陷，数据需要根据需求去处理后再使用，或者设计的关系字段不合理
