### ISSUE TITLE
表单在提交的时候绑定了一个工作流，admin用户提交的时候执行工作流，登录另外普通账号提交表单不执行工作流

### ISSUE THREAD

**Issue by 0x22E09-8** [nocobase/nocobase#4695]
## * Describe the bug

表单在提交的时候绑定了一个工作流，admin用户提交的时候执行工作流，登录另外普通账号提交表单不执行工作流

## * Environment

- NocoBase version:v1.2.4-alpha

- Database type and version: MySQL 
  

- OS:linux

- Deployment Methods:

- Docker image version:

- NodeJS version:

## Expected behavior

所有用户都可以触发工作流

**Comment by hongboji** [comment]
请按照issues模板提交

**Comment by 0x22E09-8** [comment]
> 测试过，可以正常触发，请按照issues模板提交，尽量做到能够复现
图1 admin账号
![1](https://github.com/nocobase/nocobase/assets/28555655/cf26c66b-ed1f-4f47-8626-23578229d6c7)
图2 普通账号
![2](https://github.com/nocobase/nocobase/assets/28555655/3f0a5bd2-a78a-4c77-a222-ac6c2cc89ca7)
需要提供什么才能查呀

**Comment by hongboji** [comment]
官网申请一个demo， 在demo上复现后，提个下地址、页面地址、 账户信息

**Comment by 0x22E09-8** [comment]
> 触发是指工作流管理页面执行次数，日志的增加，不是图片中自定义模型的查询； 官网申请一个demo， 在demo上复现后，提供下地址、页面地址、 账户信息。

提供的图片是出先的现象，具体的工作流是绑定在了提交按钮上，因为涉及业务很多功能，demo上不能把全部功能都移过去，可以截图提供绑定的工作流 和工作流的日志

**Comment by 0x22E09-8** [comment]
![image](https://github.com/nocobase/nocobase/assets/28555655/d382cb45-f3a5-437e-a252-cb1f54277a75)
![image](https://github.com/nocobase/nocobase/assets/28555655/82a18729-610a-4022-80e9-bfef9defdce2)

**Comment by hongboji** [comment]
请问能否提供关键的复现信息，数据表模型字段详细配置信息 ，工作流详细配置信息（每个节点都需要），操作触发流程  ？

**Comment by hongboji** [comment]
没有关键的复现信息，issues我们将关闭，如果能够提供可以继续反馈
