### ISSUE TITLE
bug:（plugin-workflow）：定时执行两次的bug又出现了

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#4701]
## * Describe the bug

定时执行两次的bug又出现了

## * Environment

git最新版

## * How To Reproduce

git最新版

## Screenshots
![image](https://github.com/nocobase/nocobase/assets/900786/a138c913-aa42-4c4b-811b-2b2ee6722bf5)
![image](https://github.com/nocobase/nocobase/assets/900786/eb50c70d-7f61-4427-9153-19f33d2ded39)
![image](https://github.com/nocobase/nocobase/assets/900786/a257aad2-3750-41a8-a1a9-1e83bbb7bb5f)

## Logs

![image](https://github.com/nocobase/nocobase/assets/900786/dfaa8558-4ad7-4800-a97d-4d37659e206e)

**Comment by mytharcher** [comment]
根据日志看是应用启动前，初始化了两次定时任务。但是我在本地未能复现，可以回忆起来在该次启动前有什么特殊的操作么？

**Comment by baiheinet** [comment]
我想不起来了 这次的有点特殊
看执行历史 就一次
![image](https://github.com/nocobase/nocobase/assets/900786/038c56ba-f0ec-41d8-b6ac-263356b486f5)
但是跟我前面说的一样，其他节点都执行两次

**Comment by mytharcher** [comment]
> 我想不起来了 这次的有点特殊 看执行历史 就一次 ![image](https://private-user-images.githubusercontent.com/900786/340901431-038c56ba-f0ec-41d8-b6ac-263356b486f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njc2OTQsIm5iZiI6MTcxODc2NzM5NCwicGF0aCI6Ii85MDA3ODYvMzQwOTAxNDMxLTAzOGM1NmJhLWYwZWMtNDFkOC1iNmFjLTI2MzM1NmI0ODZmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMzIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDIwYTY3MTk3MGIzOTZlOTczMzZiOWE4ZjU3NzcxMjVkZmUxMDY4NWE2OThkNDhmOWFhZDI3NDUwNGYwZTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VfGCAbU64M5lUaZhRmQt8ZbtbN3SD1KSmX6jtMWDbI8) 但是跟我前面说的一样，其他节点都执行两次

意思是说这个图里的定时任务，虽然执行记录里只有一次，但是里面的节点都重复执行了？

**Comment by baiheinet** [comment]
> > 我想不起来了 这次的有点特殊 看执行历史 就一次 ![image](https://private-user-images.githubusercontent.com/900786/340901431-038c56ba-f0ec-41d8-b6ac-263356b486f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Njc2OTQsIm5iZiI6MTcxODc2NzM5NCwicGF0aCI6Ii85MDA3ODYvMzQwOTAxNDMxLTAzOGM1NmJhLWYwZWMtNDFkOC1iNmFjLTI2MzM1NmI0ODZmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMzIzMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDIwYTY3MTk3MGIzOTZlOTczMzZiOWE4ZjU3NzcxMjVkZmUxMDY4NWE2OThkNDhmOWFhZDI3NDUwNGYwZTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VfGCAbU64M5lUaZhRmQt8ZbtbN3SD1KSmX6jtMWDbI8) 但是跟我前面说的一样，其他节点都执行两次
> 
> 意思是说这个图里的定时任务，虽然执行记录里只有一次，但是里面的节点都重复执行了？

对头

**Comment by baiheinet** [comment]
有新发现，
历史记录显示一次，是假的，其实是两次 ，现在是有多少版本执行多少次，前面显示1次是因为我把老版本删除了
![image](https://github.com/nocobase/nocobase/assets/900786/92b03f6e-d09c-4062-9195-c2b7800ba0b1)

**Comment by mytharcher** [comment]
所以听起来是复制版本导致的？那我按这个方向排查一下。

**Comment by mytharcher** [comment]
> 所以听起来是复制版本导致的？那我按这个方向排查一下。

复制版本再启用新版也没有复现，还有其他环境条件么？

**Comment by mytharcher** [comment]
> 我有点新发现，写出来，看有没有启示
> 
> 如果每日备注的版本 比 每日重置 大几次 每日备注就会运行几次

我这边按你说的方式复制一个定时任务到新的工作流，然后启用。执行后也还是没有观察到重复触发，可以用我们的 demo 做一个最小复现么？另外看下当前的版本？
