### ISSUE TITLE
第一次登录系统，页面的编辑功能，选择框，级联组件等不能正常显示值，显示的是ID，再次点开时显示正常

### ISSUE THREAD

**Issue by xjs1983boy** [nocobase/nocobase#4711]
## * Environment

- NocoBase version:

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## Screenshots

第一次登录系统，点编辑出现的效果。
<img width="1058" alt="image" src="https://github.com/nocobase/nocobase/assets/33441983/1746c661-a1ea-4b99-b106-364feda503df">

<img width="1176" alt="image" src="https://github.com/nocobase/nocobase/assets/33441983/1031d3c4-dc19-4adf-aa75-0f6b76fd5cde">

关闭窗口再次点编辑按钮出现的正常的效果。
<img width="1066" alt="image" src="https://github.com/nocobase/nocobase/assets/33441983/5ec77e55-9296-4238-8a7a-45c57312412e">

**Comment by xjs1983boy** [comment]
版本 v1.0.1-alpha.1

**Comment by hongboji** [comment]
建议使用最新版本

**Comment by xjs1983boy** [comment]
最新版同样存在上边 的问题

**Comment by xjs1983boy** [comment]
<img width="889" alt="image" src="https://github.com/nocobase/nocobase/assets/33441983/64576b3c-eb1e-4f8d-8b18-4302a4a2c39e">
代码已更新为最新的版本

**Comment by hongboji** [comment]
请使用最新的代码帮忙检查是否解决 ，请问编辑弹窗区块是一个引用模板吗？

**Comment by hongboji** [comment]
issues先关闭，使用最新代码如果存在问题，可以继续反馈
