### ISSUE TITLE
编辑表单中，如果使用了子表格，同时子表格设置了描述信息，显示会出现重叠

### ISSUE THREAD

**Issue by hellofreud** [nocobase/nocobase#4712]
## * Describe the bug

编辑表单中，如果使用了子表格，同时子表格设置了描述信息，显示会出现重叠（编辑模式下正常，非编辑模式下异常）
![image](https://github.com/nocobase/nocobase/assets/17267947/d8410f96-374a-48c2-b5dc-418d93285dd6)

## * Environment
1.2.2升级1.2.4后开始出现此问题

- NocoBase version:1.2.4

- Database type and version: pgsql
  

- OS:windows

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by katherinehhh** [comment]
已修复合并，https://github.com/nocobase/nocobase/pull/4717
