### ISSUE TITLE
After updating fields in model with existing or deleted data - impossible to import data with new fields

### ISSUE THREAD

**Issue by Vadim1707** [nocobase/nocobase#4740]
## * Describe the bug
After creating collection and manipulating with fields, import doesn't show new fields in template.
More details in reproduction

## * Environment

- NocoBase version: v1.2.4-alpha

- Database type and version: postgres:10
  

- OS: Windows

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version: Node.js v20.14.0.

## * How To Reproduce

1. Create general collection
2. Create table with this collection, add import button
3. Import data according to collection's template
4. (Optional) delete some data, make any other manipulations with it
5. Create new fields in this exact collection
6. Get template from import button
7. This template doesn't show new fields.

## Expected behavior

I expect new fields to appear in import template

**Comment by Vadim1707** [comment]
sometimes it is fixed by deleting table with this exact collection and creating the new one, but this is not always the case

**Comment by hongboji** [comment]
Import button in the upper right corner to enter the field configuration interface to customize the field template
