### ISSUE TITLE
计算引用子表单的两个数相乘的总数 没有计算成功 并显示为空

### ISSUE THREAD

**Issue by zhangke0601** [nocobase/nocobase#4753]
## * Describe the bug
计算引用子表单的两个数相乘的总数 没有计算成功  并显示为空 
比如说在联动规则里填写 订单总金额等于订单明细的单价乘以数量的结果相加 
## * Environment

- NocoBase version:

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce

<img width="1198" alt="image" src="https://github.com/nocobase/nocobase/assets/39262241/48bc59c6-76f5-4a40-b1b6-7dca29dd5ef8">

**Comment by hongboji** [comment]
参考formula使用SUMPRODUCT

**Comment by zhangke0601** [comment]
> 参考formula使用SUMPRODUCT

谢谢 这个函数可以解决这个问题 那小计金额用那个函数呢 因为是在子表单里 不能在联动规则里面赋值 在默认值里面也不能使用函数

**Comment by gavenwan** [comment]
> > 参考formula使用SUMPRODUCT
> 
> 谢谢 这个函数可以解决这个问题 那小计金额用那个函数呢 因为是在子表单里 不能在联动规则里面赋值 在默认值里面也不能使用函数

在“订单明细”表格里新增“总价”字段，类别为“公式”，内容为“售价*数量”
