### ISSUE TITLE
请问近期计划是否有关于第三方接口的支持

### ISSUE THREAD

**Issue by haomiemie** [nocobase/nocobase#476]
我认真的查看了关于Nocobase的文档，发现有关于连接第三方数据库的计划，但是没有关于第三方接口/API相关信息。请问近期计划中是否有关于第三方接口的支持：

1、如数据区块中的表格等，从第三方接口获取值并回显。
2、如表单提交，提交到第三方接口，而非是Nacobase本身的数据库。

期待您的回复，感谢！

**Comment by chenos** [comment]
连接第三方数据库比较规范，之后会作为插件提供，但是第三方接口不确定因素有很多，需要自己去适配了。总的来说思路有几个：
- 自定义操作 -> 自定义请求，在这里对接第三方 api（2 的问题可以类似方式解决）
- 自己去扩展区块，区块组件里对接第三方接口

**Comment by haomiemie** [comment]
非常感谢您的回复！
请问关于【自定义操作 -> 自定义请求，在这里对接第三方 api】这部分，是否有相关文档进行参考。

**Comment by haomiemie** [comment]
我更新到最新版后看到这个功能了，再次感谢您的回复！
