### ISSUE TITLE
Out of sort memory, consider increasing server sort buffer size

### ISSUE THREAD

**Issue by chenyu1st** [nocobase/nocobase#4774]
## * Environment

- NocoBase version: 1.0.0

- Database type and version: Mysql.8.0.34
  

- OS:Linux

- Deployment Methods: Docker

- Docker image version: latest

- NodeJS version:

## Logs

{"level":"error","message":"response /api/executions:list?appends%5B%5D=workflow.id&appends%5B%5D=workflow.title&pageSize=20&sort%5B%5D=-createdAt&filter=%7B%22key%22%3A%22l9dsxikitsq%22%7D","method":"GET","path":"/api/executions:list?appends%5B%5D=workflow.id&appends%5B%5D=workflow.title&pageSize=20&sort%5B%5D=-createdAt&filter=%7B%22key%22%3A%22l9dsxikitsq%22%7D","res":[{"message":"Out of sort memory, consider increasing server sort buffer size"}],"action":{"actionName":"list","resourceName":"executions","params":{"appends":["workflow.id","workflow.title"],"pageSize":"20","sort":["-createdAt","id"],"filter":{"key":"l9dsxikitsq"},"resourceName":"executions","actionName":"list"}},"userId":4,"status":500,"cost":6,"app":"main","reqId":"2b4d1917-dc1d-4028-9581-a264c3d85be0","timestamp":"2024-06-28 06:13:07"}

**Comment by hongboji** [comment]
Trying to increase mysql database sort buffer size size
