### ISSUE TITLE
子表单里不能做算式计算

### ISSUE THREAD

**Issue by zhangke0601** [nocobase/nocobase#4775]
## * Describe the bug

在子表单里想做A字段和B字段的相乘合计等于C字段,没有办法做算术的应.请问可以开发出在联动规则里面编辑子表单的值计算或者在默认值中可以做算式计算

## * Environment

- NocoBase version:

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce

<img width="1142" alt="image" src="https://github.com/nocobase/nocobase/assets/39262241/4953b08c-5e5a-40cb-b801-a48b4191c21d">

**Comment by hongboji** [comment]
使用公式字段

**Comment by zhangke0601** [comment]
谢谢
