### ISSUE TITLE
当联动规则中使用了公式字段后，系统会变得异常缓慢

### ISSUE THREAD

**Issue by hellofreud** [nocobase/nocobase#4802]
## * Describe the bug
当联动规则中使用了公式字段后，系统会变得异常缓慢
具体体现在以下场景
1、使用了联动规则的页面会如下图所示，可能过几秒会加载完成，也可能不会
![image](https://github.com/nocobase/nocobase/assets/17267947/a51b2a33-5a33-439b-aef2-de7f3f290533)
2、切换数据源时，可能无法加载数据源，刷新后才会加载
![image](https://github.com/nocobase/nocobase/assets/17267947/9b3708c2-c4be-47c8-94eb-79be9680fb93)

联动规则的配置如下：
![image](https://github.com/nocobase/nocobase/assets/17267947/306594a0-132b-4a16-9212-444a4a5a92ed)
公式字段的配置如下：
![image](https://github.com/nocobase/nocobase/assets/17267947/5f8878f7-0a76-4627-b957-1b5c10dbe924)

## * Environment

- NocoBase version:v1.2.11-alpha

- Database type and version: PostgreSQL 16
  

- OS:Windows

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by hongboji** [comment]
能否在官网申请demo 帮忙配置复现下 ，提过复现的地址 ？

**Comment by hellofreud** [comment]
你好，已在demo进行了配置，地址：https://a_yupg2mztmlp.v7.demo.nocobase.com/
请查看新增的计算器菜单，上面描述的情况复现概率在80%以上 @hongboji 

> 没有复现，能否在官网申请demo 帮忙配置复现下 ，提供下复现的地址 ？

**Comment by hellofreud** [comment]
@hongboji 系统已经崩溃了

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4846

**Comment by hongboji** [comment]
已经修复，请拉取最新代码检查是否解决
