### ISSUE TITLE
windows系统中 附件上传设置了类型image，还是可以上传其他类型文件包括可执行文件脚本等

### ISSUE THREAD

**Issue by Pepsi33** [nocobase/nocobase#4812]
## * Environment

- NocoBase version: 1.2.11

- Database type and version: MySQL 8.x
  

- OS: Windows

- Deployment Methods: Create-nocobase-app

- Docker image version:

- NodeJS version:

## * How To Reproduce
新建附件表字段，创建当前表表单，表单中配置附件字段

**Comment by hongboji** [comment]
可以在文件管理器中设置 MIME 格式，约束文件后缀

**Comment by Pepsi33** [comment]
> 可以在文件管理器中设置 MIME 格式，约束文件后缀

是的，设置了image类型在Windows下无效。存在上述问题

**Comment by hongboji** [comment]
文件管理器中设置 MIME 格式，可以约束文件后缀，请再次检查
