### ISSUE TITLE
新增整数自增字段报错后再新建其他单行文本字段，，但是数据库没有落库

### ISSUE THREAD

**Issue by Pepsi33** [nocobase/nocobase#4814]
## * Describe the bug
新增整数自增字段报错后，再新建单行文本字段，报错。查看数据库字段实际没有落库，但页面显示有字段信息，配置表单/表格均有字段信息

## * Environment

- NocoBase version:1.2.11

- Database type and version: MySQL 8.x
  

- OS:MacOS

- Deployment Methods:Create-nocobase-app

- Docker image version:

- NodeJS version:20

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4839

**Comment by chareice** [comment]
https://github.com/nocobase/nocobase/pull/4951 已修复
