### ISSUE TITLE
在 multi-app 下面 API documentation 測試請求有一個小 bug

### ISSUE THREAD

**Issue by jayhsu5202** [nocobase/nocobase#4880]
環境版本宣告
Docker nocobase with mysql
NocoBase v1.2.15-alpha

![image](https://github.com/user-attachments/assets/49bd3378-8246-4392-898a-cf6d65265d6b)

這個問題是這樣 在 multi-app 底下 API documentation 登入 api-key 的狀況下 測試 
他不會送出標頭 X-app

![截圖 2024-07-15 上午12 34 50](https://github.com/user-attachments/assets/7d8c1018-d7c0-4196-bd98-baf1f4f51f66)

登入 api-key 的狀況 做測試 他不會出現 X-app 子 app 的標頭
所以會返回 404

![截圖 2024-07-15 上午12 32 16](https://github.com/user-attachments/assets/318b5428-f87b-4606-b414-73a2c859b9f2)
當在沒登入 api-key 時 他用系統預設的驗證
才會送出 X-app 去完成請求

所以需要修正這個 bug 在子 app 底下需要針對登入 api-key 時 他要知道目前是子 app 所以需要送出 X-app 去完成請求

雖然這是一個小 bug 不過對於剛接觸的開發者會很困擾

還好我無意間有很快的發現這個問題 不然又要團團轉 😩

**Comment by zhangzhonghe** [comment]
感谢反馈，不过 GitHub issues 这里推荐使用英文，或者可以在我们的[中文社区](https://forum.nocobase.com/c/chinese-forum/6)反馈你遇到的问题。

Thanks for the feedback, but English is recommended here at GitHub Issues, or you can give us feedback on the issues you're having in our [Chinese community](https://forum.nocobase.com/c/chinese-forum/6).
