### ISSUE TITLE
表格区块中行的自定义请求后续会支持传入字段数据么？

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#489]
## Is your feature request related to a problem (Better to describe the scenario you meet)?

目前已经支持自定义请求了，但是貌似还不支持字段数据作为请求参数传入 query string 和 request body.

![自定义请求还不支持字段参数](https://user-images.githubusercontent.com/931976/172605803-20e70987-4487-44ac-ab4c-ea3dc25554f1.gif)

我用的是 main 分支的最新版本。

## Describe the solution you'd like

估计是还没来及实现，我看代码应该在：

https://github.com/nocobase/nocobase/blob/892a7729880adc0d39eeba548bf9c6faa831e8f4/packages/core/client/src/block-provider/hooks/index.ts#L225-L238

目前从 json schema 中拿到 json 数据，直接设置给 apiClient 了，将来可以加入当作模版数据用当前行字段渲染的逻辑。

**Comment by zhouyanliang** [comment]
正在进行中：
- 支持当前用户和当前记录的动态数据
- 支持扩展的 action api
