### ISSUE TITLE
请求优化sql查询性能，不查询额外的列

### ISSUE THREAD

**Issue by blackwhite084** [nocobase/nocobase#4894]
## * Describe the bug
在数据区块-表格中，拉取数据的sql是所有列，这样在其他列数据很大的情况下很损耗性能

## * Environment

- NocoBase version:1.2.11

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce
界面正常添加表格

**Comment by zhouyanliang** [comment]
中文内容请在社区添加：https://forum.nocobase.com/
