### ISSUE TITLE
联动规则的action中的启用和显示失效

### ISSUE THREAD

**Issue by GavinSJW** [nocobase/nocobase#4896]
## * Describe the bug

在使用联动规则功能的时候，条件判断正确之后，如果action选择是禁用和隐藏是可以获得预期结果，但是调整为启用和显示则无效。

## * Environment

- NocoBase version:1.2.11&1.2.4

- Database type and version: mysql
  

- OS:Ubuntu

- Deployment Methods:docker

- Docker image version:

- NodeJS version:

## Screenshots
<img width="741" alt="截屏2024-07-18 09 19 18" src="https://github.com/user-attachments/assets/1097a697-2625-4571-bee5-330c6bd51853">
<img width="313" alt="截屏2024-07-18 09 45 25" src="https://github.com/user-attachments/assets/1e675944-fc3f-435f-b448-53792c8685b1">
<img width="716" alt="截屏2024-07-18 09 55 47" src="https://github.com/user-attachments/assets/8662a92b-58b7-4693-b84c-8790867f354a">
<img width="242" alt="截屏2024-07-18 09 52 54" src="https://github.com/user-attachments/assets/ff820029-f672-4504-8545-97130d414f1a">

**Comment by zhouyanliang** [comment]
中文内容麻烦在中文社区反馈：https://forum.nocobase.com/
