### ISSUE TITLE
Bug with HTTP workflow node

### ISSUE THREAD

**Issue by Paduber** [nocobase/nocobase#4902]
## * Describe the bug

I created workflow to send HTTP request, scheduled based on date field of collection. It triggers in time, but was pending for a few minutes on a HTTP request node. And after that it failed with this error: 

```
{
  "message": "_a.trim is not a function",
  "stack": "TypeError: _a.trim is not a function\n    at /app/nocobase/node_modules/@nocobase/plugin-workflow-request/dist/server/RequestInstruction.js:67:93\n    at Array.reduce (<anonymous>)\n    at request (/app/nocobase/node_modules/@nocobase/plugin-workflow-request/dist/server/RequestInstruction.js:64:40)\n    at RequestInstruction_default.run (/app/nocobase/node_modules/@nocobase/plugin-workflow-request/dist/server/RequestInstruction.js:137:5)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Processor.exec (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:140:13)\n    at async Processor.start (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Processor.js:121:7)\n    at async PluginWorkflowServer.process (/app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:467:7)\n    at async /app/nocobase/node_modules/@nocobase/plugin-workflow/dist/server/Plugin.js:448:11"
}
```

Only happens if I write something into params, body values are fine

## * Environment

- NocoBase version: v1.0.0-alpha.17

- Database type and version: PostgreSQL
  

- OS: Linux

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

## * How To Reproduce

Add HTTP node to scheduled workflow
Add parameters
![image](https://github.com/user-attachments/assets/4940c298-da25-4acf-b5ef-be5fcbfafa09)

## Screenshots

![image](https://github.com/user-attachments/assets/6653b81e-1ef6-45ac-86f0-a58b473b62fe)

**Comment by mytharcher** [comment]
This is a bug we fixed before (in #4354). Your version (`v1.0.0-alpha.17`) is a little out-dated, please update to latest and check if it exists.
