### ISSUE TITLE
Error when updating, last working version is 0.20.0-alpha.9

### ISSUE THREAD

**Issue by r-milioli** [nocobase/nocobase#4909]
## * Describe the bug

Error when updating, last working version is 0.20.0-alpha.9

## * Environment

- NocoBase version:

- Database type and version: PostgreSQL 16
  

- OS: Debian12

- Deployment Methods: Docker swarm

- Docker image version: Docker version 27.0.3

- NodeJS version:

## * How To Reproduce

version: "3.7"

services:
  nocobase:
    image: nocobase/nocobase:0.20.0-alpha.9
    volumes:
      - nocobase_storage:/app/nocobase/storage
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=postgres
      - DB_PASSWORD=MY PASSWORD POSTGRES
      - LOCAL_STORAGE_BASE_URL=/storage/uploads
      - APP_KEY=
      - API_BASE_URL=MY WEB ADDRESS
      - API_BASE_PATH=/api/
      - PROXY_TARGET_URL=MY WEB ADDRESS
      - INIT_ROOT_EMAIL=
      - INIT_ROOT_PASSWORD=@PASSWORD
      - INIT_ROOT_NICKNAME=Super Admin
      - INIT_ROOT_USERNAME=nocobase
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.nocobase.rule=Host(`MY WEB ADDRESS`)
        - traefik.http.services.nocobase.loadbalancer.server.port=80
        - traefik.http.routers.nocobase.service=nocobase
        - traefik.http.routers.nocobase.tls.certresolver=letsencryptresolver
        - traefik.http.routers.nocobase.entrypoints=websecure
        - traefik.http.routers.nocobase.tls=true

    networks:
        - network_public
networks:
  network_public:
    name: network_public
    external: true

volumes:
  nocobase_storage:
    external: true

## Expected behavior

 I would like to be able to update my app to the latest version, but I can't because the stack I have is bugged with versions higher than 0.20.0-alpha.9.

Would you be kind enough to correct the stack provided to run the latest versions?

## Screenshots

![Captura de tela 2024-07-19 212745](https://github.com/user-attachments/assets/5d1781c2-93c6-4c96-8a95-24ede1814704)

## Logs

ERR Validation error | meta={} module=application submodule= method= app=main reqId=bd423094-ad2a-4cc1-887d-91b97b40ede9 timestamp=2024-07-20 00:05:35
client disconnected 3W85yCScXoQ0CXGp4PyGa
WRN app is not running | meta={"status":"stopped"} module=gateway submodule= method=requestHandler app=main reqId=fe2393c1-57b0-4a2a-9d3d-eef9b6b87a11 timestamp=2024-07-20 00:06:38
ERR application main is stopped | meta={"error":{"status":503,"message":"application main is stopped","maintaining":true,"code":"APP_STOPPED"}} module=gateway submodule= method=responseErrorWithCode app=main reqId=c1ed1dcc-3cd8-4f44-847f-4cfd6b657179 timestamp=2024-07-20 00:06:38
new client connected byTUtZnMcnyD9BEnYTl4s
client tags: app#main

**Comment by hongboji** [comment]
Can you provide a complete startup log file？

**Comment by chareice** [comment]
You can try again with the latest version, and if there are any issues, please reopen this issue or open a new one.
