### ISSUE TITLE
右侧的菜单能不能开发一个隐藏、收折功能

### ISSUE THREAD

**Issue by zhangke0601** [nocobase/nocobase#4911]
## * Describe the bug

右侧的菜单能不能开发一个隐藏、收折功能. 这样界面的利用空间更大
## * Environment

- NocoBase version:

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## * How To Reproduce

<img width="222" alt="image" src="https://github.com/user-attachments/assets/b483cd5e-b2d0-4f19-aabe-4481cbbae227">

**Comment by 2013xile** [comment]
感谢你的建议，我们会认真考虑。

PS: 请用英文发布内容，或者在中文版块发布：https://forum.nocobase.com/
