### ISSUE TITLE
【子表格】字段无法在【表格】页面区块配置字段

### ISSUE THREAD

**Issue by whataxxday** [nocobase/nocobase#492]
## 遇到的问题
创建类型为【子表格】的字段后，无法在创建类型为【表格】的页面区块时配置字段，目前只能用创建【关联】类型的字段替代创建【子表格】类型的字段来解决问题。
![image](https://user-images.githubusercontent.com/39958768/172758451-d9630799-f74d-425e-90f3-ae8b0639c20c.png)
![description02](https://user-images.githubusercontent.com/39958768/172759027-9adfc7e7-47fc-44c9-a17d-d6b0d77d102d.png)

## 解决建议
类型为【子表格】的字段能否在创建类型为【表格】的页面区块时，使用与类型为【关联】的字段类似的方式配置？

**Comment by zhouyanliang** [comment]
由于子表格问题较多，近期的版本中将去掉子表格字段，改用关联表和相应的区块来实现。本质上子表格是一对多的关联关系，改用关联表之后将更清晰。

**Comment by whataxxday** [comment]
明白了，感谢回复！
