### ISSUE TITLE
Linkage rules set required bug

### ISSUE THREAD

**Issue by Paduber** [nocobase/nocobase#4922]
## * Describe the bug

If you set a rule to make field required at some condition (otherwise set it hidden), field will not be marked as required, only visible

## * Environment

- NocoBase version: v1.2.22-alpha

- Database type and version: PostgreSQL
  

- OS: Ubuntu

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

## * How To Reproduce

Make two rules:
1. If field A is option 1, make field B hidden
2. If fueld A is option 3, make field B required

## Expected behavior

Field should be set visible and required at the same time if switched from option 1 to 3

## Screenshots

![image](https://github.com/user-attachments/assets/ab2b60ff-0cd0-486d-9964-31da7d95e5a3)
![image](https://github.com/user-attachments/assets/f90cc3c6-90e7-4b76-8198-be2c690b099e)

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/4927

**Comment by hongboji** [comment]
Please pull the latest code and check if the issue is resolved
