### ISSUE TITLE
工作流触发条件选择任意匹配条件时失效

### ISSUE THREAD

**Issue by shenzebiao** [nocobase/nocobase#4923]
## * Describe the bug
使用工作流数据表事件创建工作流，配置触发器触发条件时候，选择任意组件条件任意匹配，这时候当编辑表单数据时候，不符合条件的数据也会触发工作流

## * Environment

- NocoBase version:
- 最新版本

- Database type and version: 
- mysql 8.1.36
  

- OS:
- windows

- Deployment Methods:
- git source code

- Docker image version:

- NodeJS version:
- 21.7.3

## * How To Reproduce
创建一个数据表类型的工作流，
![image](https://github.com/user-attachments/assets/01fe43f7-86b2-4945-b29a-7809671c9ebc)
然后新增一条数据，触发工作流，这时候使表中的workflow_current_step字段发生变化，使其不满足条件，例如变成workflow_current_step=audit，然后在人工审核节点中修改当前表单数据并且approve,这时候当前工作流会正常往下执行，但是还会产生一条新的工作流。这应该是属于bug吧，我看代码CollectionTrigger.ts代码中
![image](https://github.com/user-attachments/assets/a888c083-9b61-4f21-b9de-e74128f33102)

此处的判断不知道是不是有问题，只判断了and，并没有判断任意(or)的情况，希望官方能验证下

**Comment by hongboji** [comment]
Please submit the issue in English, or in the Chinese section of the community (https://forum.nocobase.com/), the issue will be closed.

**Comment by hongboji** [comment]
拉最新代码检查问题是否解决
