### ISSUE TITLE
富文本数据库字段修改后导出的备份还原会报错无法使用

### ISSUE THREAD

**Issue by kennnnnnnnnn** [nocobase/nocobase#4941]
## * Describe the bug

我使用的是mysql主数据库，富文本的手动变更为longtext后导出的备份还原到应用应用直接崩溃 即时修改了新应用的数据库也无济于事。

另外富文本这个插件挺好使的，docker容器里面的富文本编辑器功能都加上啊。

## * Environment

- NocoBase version:    docker部署下面3个都这样
    image: nocobase/nocobase:latest
    image: nocobase/nocobase:next
    image: nocobase/nocobase:1.2.4-alpha
本地git运行也一样

- Database type and version: MySQL 8.0
  

- OS:centos7.6

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by zhouyanliang** [comment]
为了便于用户搜索和沟通，请按照模版要求用英文发布 issue，或者发布到社区的中文版块：https://forum.nocobase.com/

**Comment by kennnnnnnnnn** [comment]
额，没法发布啊，我使用github登录，但是邮箱错了，然后没法改邮箱又没法登录，卡住了
