### ISSUE TITLE
工作流触发定时任务，未填写“结束于”报错

### ISSUE THREAD

**Issue by Pepsi33** [nocobase/nocobase#4949]
## * Describe the bug

定时任务未填写“结束于”字段

<img width="695" alt="image" src="https://github.com/user-attachments/assets/043e8b10-6d68-444d-8396-d8f24acf0f63">

这里的逻辑执行报错

## * Environment

- NocoBase version:1.2.24-alpha

- Database type and version: mysql
  

- OS:MacOS

- Deployment Methods: Create-nocobase-app

- Docker image version:

- NodeJS version: 20

**Comment by zhouyanliang** [comment]
为了便于用户搜索和沟通，请按照模版要求用英文发布 issue，或者发布到社区的中文版块：https://forum.nocobase.com/
