### ISSUE TITLE
配置自动编码字段无法修改自增规则

### ISSUE THREAD

**Issue by kevinyjn** [nocobase/nocobase#4959]
## * Describe the bug

配置自动编码字段无法修改自增规则，没有保存按钮，且该字段没有设置主键开关
<img width="838" alt="image" src="https://github.com/user-attachments/assets/b1e51d57-cccb-4412-b726-27850a1a8668">

## * Environment

- NocoBase version:

- Database type and version: 
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by zhouyanliang** [comment]
为方便所有用户交流，请按照模板要求用英文发布，或者在中文社区发布：https://forum.nocobase.com/

**Comment by hongboji** [comment]
请问nocobase版本号是多少，使用什么方式部署 ？
