### ISSUE TITLE
【Bug】关联表引用模版存在问题

### ISSUE THREAD

**Issue by hellofreud** [nocobase/nocobase#4965]
## * 描述问题
订单表与产品表存在关联关系，在订单表表格中引用产品表的关联字段，此时启动该关联字段的链接功能，点击蓝色字体打开弹窗，创建区块，选择表单（编辑），无法引用已创建的产品表相关模板（以前可以添加）

## * 运行环境

- NocoBase 版本:v1.2.25-alpha

- 数据库种类与版本: PostgreSQL 16
  

- 操作系统:Windows

- 部署方式:Docker

- Docker 镜像版本:nocobase/nocobase:latest

- NodeJS 版本:

## 如何重现
1、A与B表存在多对多关联，基于B表创建表格，并在表格中引用了A表关联字段
2、对A表关联字段启用链接
3、在A表关联字段点击的弹窗中创建区块时，表单（编辑）无法识别到A表已经创建的模板，以前是可以的

## 预期行为
A表字段链接弹窗可以引用A表已有的模板

## 截图
![image](https://github.com/user-attachments/assets/befb2379-4b28-4d67-afd0-3e93a8819fad)

**Comment by zhouyanliang** [comment]
感谢反馈，以后请按照模版要求用英文提交问题，方便全球用户搜索和交流。该 Issue 暂时关闭，不过会有同事跟进。
