### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by milogenius** [nocobase/nocobase#4979]
## * Describe the bug
There is no directory below in the source code
`cd my-nocobase-app`

## Expected behavior

Correct description

## Screenshots
![微信截图_20240802111023](https://github.com/user-attachments/assets/46fa06ed-cb83-4cbe-9c21-b3b3b0c84f4f)

**Comment by hongboji** [comment]
Sorry, please use: cd my-nocobase， and the documentation will be revised!

**Comment by pranshul7** [comment]
Hi @hongboji ,

Thanks for helping us out.
The changes in the docs have been made, and are live now. So I think we can close this issue. @hongboji @chenos
