### ISSUE TITLE
where is the package? "@nocobase/data-source-main"

### ISSUE THREAD

**Issue by signhuwei** [nocobase/nocobase#4984]
https://github.com/nocobase/nocobase/blob/c8b0ebb03e229199cb0d4ca5f2fca4f61f1126c6/packages/plugins/%40nocobase/plugin-data-visualization/package.json#L31

**Comment by 2013xile** [comment]
https://github.com/nocobase/nocobase/tree/main/packages/plugins/%40nocobase/plugin-data-source-main

**Comment by minosss** [comment]
> but that package's name is '@nocobase/plugin-data-source-main' yarn install cann't found '@nocobase/data-source-main'

Same error here.
Replace `@nocobase/data-source-main` to `@nocobase/plugin-data-source-main` and install again.
