### ISSUE TITLE
关联表缺失可筛选字段问题

### ISSUE THREAD

**Issue by whataxxday** [nocobase/nocobase#499]
## Describe the bug
实体表中存在【链接】字段，配置字段有【链接】选择，但是可筛选字段中无【链接】字段供筛选

## Version
docker版
Version 0.7.0-alpha.78

## Screenshots
![746fcafe9be992c3bd2d90c27708fac](https://user-images.githubusercontent.com/39958768/173171859-60eb6263-11fe-410c-977e-04c5cb1c6dba.png)
![7b85822b3342f94988d545e1c02aade](https://user-images.githubusercontent.com/39958768/173171864-2ad25752-fa57-4005-8630-7ae5a9d15e96.png)

## Desktop (please complete the following information)
OS: linux
Browser chrome

**Comment by whataxxday** [comment]
【链接】字段字段类型为【多行文本】

**Comment by chenos** [comment]
因为多行文本不是可筛选字段

**Comment by whataxxday** [comment]
好的，那我只能暂时先选择单行文本类型对应数据表varchar型去生成字段，再去手工修改数据库中的varchar长度了
