### ISSUE TITLE
can not save sql collection

### ISSUE THREAD

**Issue by shenzebiao** [nocobase/nocobase#5008]
## * Describe the bug
I want to create a sql type table, but an error message appears because there are relationship fields in the table field。

## * Environment

- NocoBase version: lastest version

- Database type and version: mysql 8.0.36
  

- OS: windows

- Deployment Methods: git srouce code

- Docker image version:

- NodeJS version: 21.7.3

## * How To Reproduce
Create a multi-table join sql, where some fields are relational fields
example: 
![QQ_1723015964599](https://github.com/user-attachments/assets/44c7f3a6-4a03-469b-98b5-707eb9d94816)

**Comment by hongboji** [comment]
Thanks for the feedback. Mapping relationship fields is not supported. We will optimize this option.

**Comment by shenzebiao** [comment]
> Thanks for the feedback. Mapping relationship fields is not supported. We will optimize this option.

Okay, looking forward to your optimization

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/5014
