### ISSUE TITLE
Collection event  for PostgreSQL Data source  can't work

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#5077]
## * Describe the bug

Collection event  for PostgreSQL Data source  can not work

## * Environment

- NocoBase version:v1.2.17-alpha

- Database type and version: PostgreSQL 15
  

- OS:linux

- Deployment Methods:Git source code

- NodeJS version:20

## * How To Reproduce

![image](https://github.com/user-attachments/assets/a2ebc059-150b-40d4-a756-2b03c63406ab)

**Comment by hongboji** [comment]
My workflow can be triggered normally, can you please request a demo on the official website and provide a reproduction address

**Comment by baiheinet** [comment]
what is you [plugin-data-source-external-postgres](https://docs.nocobase.com/handbook/data-source-external-postgres) rev?

**Comment by hongboji** [comment]
1.2.35
