### ISSUE TITLE
Render Failed

### ISSUE THREAD

**Issue by claragutierrezlibnova** [nocobase/nocobase#5087]
[logs.tar.gz](https://github.com/user-attachments/files/16670277/logs.tar.gz)
This is the log that appears: 
`{"level":"error","message":"Diagnosis, frontend error, Cannot read properties of null (reading 'name')","stack":"TypeError: Cannot read properties of null (reading 'name')\n    at m (https://workflowfor.memoriademadrid.es/p__index.f2b4ef1a.async.js:653:33209)\n    at z (https://workflowfor.memoriademadrid.es/p__index.f2b4ef1a.async.js:653:34703)\n    at https://workflowfor.memoriademadrid.es/p__index.f2b4ef1a.async.js:816:3482\n    at https://workflowfor.memoriademadrid.es/npm._at_formily.f9d0b213.async.js:100:201998\n    at g.track (https://workflowfor.memoriademadrid.es/npm._at_formily.f9d0b213.async.js:100:219765)\n    at yt (https://workflowfor.memoriademadrid.es/npm._at_formily.f9d0b213.async.js:100:201583)\n    at D (https://workflowfor.memoriademadrid.es/npm._at_formily.f9d0b213.async.js:100:201977)\n    at on (https://workflowfor.memoriademadrid.es/umi.1311458f.js:13:20332)\n    at dl (https://workflowfor.memoriademadrid.es/umi.1311458f.js:15:3152)\n    at tc (https://workflowfor.memoriademadrid.es/umi.1311458f.js:15:2364)","meta":{},"module":"logger","submodule":"collect","method":"","app":"main","reqId":"022c6acb-01f4-4aab-8a33-47866cf7650c","dataSourceKey":"main","timestamp":"2024-08-13 09:53:00"}`
![render failed](https://github.com/user-attachments/assets/ee443fc4-74f7-476b-a0be-d33011ce7fb1)

**Comment by hongboji** [comment]
Is it possible to submit an issue according to the issue template?
Please click the “Download logs” button to download the logs and provide the log files.

**Comment by claragutierrezlibnova** [comment]
Yes, here are the log files
[logs.tar.gz](https://github.com/user-attachments/files/16670276/logs.tar.gz)

**Comment by claragutierrezlibnova** [comment]
Any updates on this? Thank you!

**Comment by 2013xile** [comment]
Hi
1. Try to update to the latest version.
2. Please follow the issue template and provide more information, like reproduce steps, it would be better to provide a full web page screenshot.
3. I could't find the log messages include "Diagnosis" text in the log files you attached. Could your reproduce again and download the new log files? Or provide all the log messages include "Diagnosis" text.

**Comment by claragutierrezlibnova** [comment]
Hi: 
1. I believe we are already upgraded to the latest version.
2. The Render error box appears below the tables of this page. It appears whenever you open that menu page.
![image](https://github.com/user-attachments/assets/5ba23718-5409-4c4b-98a3-8f08ddb31ad3)
3. I upload again the log files.
[logs (3).tar.gz](https://github.com/user-attachments/files/16727851/logs.3.tar.gz)

**Comment by 2013xile** [comment]
Hi, @claragutierrezlibnova .
The log files you provided look a bit strange, they are from different dates. Could you download today's log files here?
<img width="1600" alt="image" src="https://github.com/user-attachments/assets/62e7e060-539f-4a05-82b8-7698c5b428b2">

Also, do you remember what data block it is?

**Comment by claragutierrezlibnova** [comment]
I add the logs downloaded from the Logger: 
[logs (4).tar.gz](https://github.com/user-attachments/files/16729116/logs.4.tar.gz)

How do I know which data block it is? It is a new block that did not appear before.
