### ISSUE TITLE
Upgrade Nocobase

### ISSUE THREAD

**Issue by farreledwin** [nocobase/nocobase#5132]
If i already deleted .git folder, can i update my nocobase?

**Comment by hongboji** [comment]
Yes, you can reinstall NocoBase in a new folder and copy the ".env" configuration file in the historical NocoBase installation directory to the new NocoBase installation directory.

**Comment by farreledwin** [comment]
how about the configuration on old nocobase and all data on old nocobase, can we bring that? @hongboji

**Comment by chareice** [comment]
Please refer to the document: https://docs.nocobase.com/welcome/getting-started/upgrading
