### ISSUE TITLE
树形表字段配置时，删除一个JSON字段后，无法再编辑已有的数据。当表单保存时报错：Cannot read properties of undefined (reading 'options') 

### ISSUE THREAD

**Issue by signhuwei** [nocobase/nocobase#5139]
## * Environment

- NocoBase version:1.0.0

- Database type and version: main database SQLite
  

- OS:Ubuntu

- Deployment Methods:

- Docker image version:

- NodeJS version:20.0.0

**Comment by hongboji** [comment]
Please submit issues in English. If you use Chinese, please submit at https://forum.nocobase.com/
