### ISSUE TITLE
Multiapp does not work

### ISSUE THREAD

**Issue by pehua** [nocobase/nocobase#5154]
## * Describe the bug

I can create apps but can´t run them
## * Environment

- NocoBase version:1.3.5

- Database type and version: 16.2
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

## Screenshots

This is the creation of apps
![image](https://github.com/user-attachments/assets/f722e3c4-881a-47c6-bb47-c4866a7068b5)

This is the noco error
![image](https://github.com/user-attachments/assets/400d6f92-cc60-44cb-9e26-f861a0568769)

This is the postgres db
![image](https://github.com/user-attachments/assets/f073eecf-e20e-4579-bacc-21813401aa93)

**Comment by hongboji** [comment]
If the database account does not have the privilege to add a database, and the database is not added successfully when adding a new sub-application, please use the database account with privileges to re-open the operation.

**Comment by pehua** [comment]
Thank you, it was my oversight
