### ISSUE TITLE
工作流判断节点的日期判断有误

### ISSUE THREAD

**Issue by ttmike2** [nocobase/nocobase#5210]
## * Describe the bug
工作流判断节点的日期判断有误。在导入多条数据时，触发工作流判断节点，期望将导入的日期字段与日期变量进行比较；但导入的第二条数据的日期字段会被解析为字符串，进而导致判断偏差。

## * Environment

NocoBase version:v1.2.35-alpha
Database type and version: Mysql
OS:windows
Deployment Methods:
Docker image version:
NodeJS version:

## * How To Reproduce
1、数据表和列表界面添加日期字段fDate
2、新增数据时触发工作流，工作流中设置判断节点：触发器变量 / 触发数据 / fDate > 系统变量 / 系统时间
![image](https://github.com/user-attachments/assets/d1b20f53-ad15-487d-b2bd-432a6edfbafb)
2、导入多条数据（比如2条）。fDate字段均为2026/8/26；目前系统时间为2024/9/5。即判断节点的内容为：2026/8/26>2024/9/5
3、预期应该是判断为true，实际上第二条会误判为false

**Comment by mytharcher** [comment]
麻烦提供一份用于导入的 excel 样例？
