### ISSUE TITLE
Custom plugin not able to read env variables.

### ISSUE THREAD

**Issue by rjoshi-sr** [nocobase/nocobase#5234]
I have created a custom plugin following [the develop the first plugin guide](https://docs.nocobase.com/development/your-fisrt-plugin) . I have declared the env variables in the .env file in the root directory. The builtin plugins are able to read the env variables but the custom plugins doesnot have access to env variables.  The output of process.env only shows two variables. 

` {NODE_ENV: 'development', PUBLIC_PATH: 'auto'} `

I tried to initialize dotenv but still it did not work. I am able to make db calls from my custom plugins that means builtin can read env variables .

Is there any thing extra I need to do to make env variable accessible?

**Comment by gchust** [comment]
@rjoshi-sr 

Have you restart your NocoBase main process after updating the .env file?

**Comment by rjoshi-sr** [comment]
yes @gchust  I restarted. You can see it is not picking default environment variable like DB_HOST etc.

**Comment by gchust** [comment]
@rjoshi-sr 
I guess you're trying to access the environment variables in client side. 

But the client's runtime is the user's browser, you have to do some env variable mapping to make it accessible in client side.

NocoBase uses `UmiJS` as client framework.  Two possible solutions for your use cases:
1. Prefix your env variable with `UMI_APP_`, such as `UMI_APP_ENV1`
2. Do some variable mappings, need to update the NocoBase core codes.

I recommand you try the solution#1 .

Check `UmiJS` docs here: https://umijs.org/en-US/docs/guides/env-variables#use-environment-variables-in-browser

**Comment by rjoshi-sr** [comment]
Yes I was trying to access in client side. 
Thanks, It is working now.
