### ISSUE TITLE
[Urgent] Tables in my postgresSQL database not being linked to one another 

### ISSUE THREAD

**Issue by aniruddhabagal** [nocobase/nocobase#5280]
## * Describe the bug

I am using Nocobase for something like CMS.
I have linked my postgres db to it, now I have created many fields in different forms which are related to each other.
When I see the graphical DB interface in the nocobase I see that tables are linked, but when actually see in PG Admin, I see that the tables are not linked with each other.

Is it normal or is there any option to link it?

**Comment by hongboji** [comment]
This is normal, the graphical interface to display relational data tables is a feature developed by NocoBase itself and has nothing to do with PG Admin.
This feature is for demonstration purposes only and does not affect your normal use of NocoBase and PostgreSQL.

**Comment by aniruddhabagal** [comment]
I think you didn't understand my question, i meant that the table are being
shown as linked in graphical interface, but in the postgres, the foreign
keys are not actually linked :)

**Comment by chareice** [comment]
Nocobase does not use database foreign keys, so it is normal that you do not see table relationships in your database management tool.
