### ISSUE TITLE
错误信息：没有可用的认证方式

### ISSUE THREAD

**Issue by chenjianjia100** [nocobase/nocobase#5282]
win10系统，国内网络环境，采用“Git 源码安装”的安装方法，
在命令提示符中，能成功执行以下命令：
```
cd my-nocobase
yarn config set disable-self-update-check true
yarn config set registry https://registry.npmmirror.com/
yarn config set sqlite3_binary_host_mirror https://npmmirror.com/mirrors/sqlite3/
yarn install --frozen-lockfile
yarn nocobase install --lang=zh-CN
yarn dev
```
数据库能通过.env文件成功配置，根据提示信息，有成功连上。
但是进入`http://localhost:13000/signin`时，无法进入登录界面，在网页上显示“没有可用的认证方式”，如下图
![image](https://github.com/user-attachments/assets/4022508a-903b-4760-9561-afa58d7eef34)

**Comment by zhouyanliang** [comment]
请按照模版要求用英文发布 Issue，或者在中文社区发布：https://forum.nocobase.com/
