### ISSUE TITLE
Style not changed according to conditional style when formula field result changes

### ISSUE THREAD

**Issue by tuiliere** [nocobase/nocobase#5324]
## * Describe the bug
Conditional styles (color, background color) are not updated accordingly when "formula" field got changed (after formula input change).

## * Environment

- NocoBase version: 1.3.20-Beta

- Database type and version: MySQL 8.x
  

- OS: Mac OS

- Deployment Methods: Docker

- Docker image version:  nocobase/nocobase:latest

- NodeJS version: N/A

## * How To Reproduce
- Create general collection
- Add number fields A and B
- Add formula field C =  A + B
- Create form block for the collection
- Configure block to display  A, B, C fields
- Set style for C Field as follow :
       - If C >= 10 Then set background to Red
       - If C <10 Then set background to green
 - Initially A and B are empty,  C is set to 0 (A+B formula) => C Background is correctly green
 - **Change A and B values to 8, C is correctly updated to 16 (A+B), but C Background remains green, it is not updated accordingly to defined conditional style (should turn red when C >= 10).**

## Expected behavior
Conditional style should be applied dynamically when formula fields value is changed

## Screenshots

<img width="690" alt="Capture d’écran 2024-09-26 à 00 00 53" src="https://github.com/user-attachments/assets/03ab41ea-4480-49a1-b10e-e7938577557f">

<img width="1194" alt="Capture d’écran 2024-09-25 à 23 46 50" src="https://github.com/user-attachments/assets/2510e87d-00b4-45fd-9ea1-4eea5da2d340">

<img width="900" alt="Capture d’écran 2024-09-25 à 23 45 21" src="https://github.com/user-attachments/assets/6d0ea59a-66af-469b-b41c-4837c197f846">

## Logs
N/A

**Comment by sheldon66** [comment]
Thank you for your feedback. We will follow up on this issue as soon as possible.

**Comment by sheldon66** [comment]
Hello @tuiliere,

We have resolved this issue with reference to #5539. Please feel free to give it a try.
