### ISSUE TITLE
Issue with the interface

### ISSUE THREAD

**Issue by mperochon** [nocobase/nocobase#5344]
## * Describe the bug

The interface seems broken and not usable.  Every forms seems to be in an Iframe (cf Screenshot of the data source manager)
![image](https://github.com/user-attachments/assets/0bcafe20-4ef0-433b-8ad3-bceafd11d756)

## * Environment

- NocoBase version: v1.4.0-alpha.20240929095739

- Database type and version:  PostgreSQL 16
  

- OS: Windows

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:next

**Comment by zhouyanliang** [comment]
It has been fixed.

**Comment by mperochon** [comment]
It works like a charm now, thanks a lot !

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
