### ISSUE TITLE
Blank Initial interface after standard docker install

### ISSUE THREAD

**Issue by MetricCreativeNola** [nocobase/nocobase#5354]
## * Describe the bug

After installing and logging in with standard creds, the interface loads with a blank screen. No options to explore any further. The navigation is present but it's empty and only has account functions.

## * Environment

- NocoBase version: v1.3.27-beta

- Database type and version:  PostgresSQL16
  

- OS: Windows 11

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

## * How To Reproduce

Install with docker. Here is my YAML :

version: "3"

networks:
  nocobase:
    driver: bridge

services:
  app:
    image: nocobase/nocobase:latest
    networks:
      - nocobase
    depends_on:
      - postgres
    environment:
      - APP_KEY=your-secret-key
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=nocobase
      - DB_USER=nocobase
      - DB_PASSWORD=nocobase
      - TZ=Asia/Shanghai
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"

  postgres:
    image: postgres:16
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: nocobase
      POSTGRES_DB: nocobase
      POSTGRES_PASSWORD: nocobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - nocobase

## Expected behavior

After logging in I'd hope to be greeted with setup and user functions. This is an empty app. 

## Screenshots
![Nocobase](https://github.com/user-attachments/assets/9817deab-f176-4c8f-b9be-304032afa4b7)

## Logs
No errors in logs or in console

**Comment by armgong** [comment]
try login with user admin and password admin123

**Comment by chareice** [comment]
Please try logging in using the browser's incognito mode to see if it works normally.

**Comment by baruchiro** [comment]
> try login with user admin (or [admin@nocobase.com](mailto:admin@nocobase.com) ) and password admin123. this is so called root user. kind of weird of this design

Worked for me
