### ISSUE TITLE
移动端表单添加关联文件表关系字段的时候报错

### ISSUE THREAD

**Issue by Cyx649312038** [nocobase/nocobase#5372]
![image](https://github.com/user-attachments/assets/5116a49d-0a4b-42dd-9e04-c72dfd4f6bab)
移动端添加关系字段(和文件数据表关联)的时候报错
![image](https://github.com/user-attachments/assets/28253254-0fe8-448f-894b-a15184936165)

**Comment by Cyx649312038** [comment]
可在在线demo中进行复现
![image](https://github.com/user-attachments/assets/cdbdd415-5e8d-40a4-be01-9b153baa3e70)

**Comment by zhouyanliang** [comment]
请按照 issue 模板添加详细信息。中文请发布在中文社区：https://forum.nocobase.com/
