### ISSUE TITLE
No notification: email plugin

### ISSUE THREAD

**Issue by injaan** [nocobase/nocobase#5386]
## * Describe the bug

in self hosted version there is no notification: email plugin, is it bug or self hosted version limitation? or am I just missing something?

## * Environment

- NocoBase version: v1.3.28-beta

- Database type and version: 
  

- OS: ubuntu 22.0.4

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

**Comment by zhouyanliang** [comment]
This plugin hasn't been released yet. You can use the Mailer node in the workflow.
