### ISSUE TITLE
Import button is not available

### ISSUE THREAD

**Issue by huynv9699** [nocobase/nocobase#5393]
![image](https://github.com/user-attachments/assets/489b142c-9bbb-4848-a4fc-ebbd49931adb)

When import the excel file to table. it is not availble.
Is it a bug, right ?

Could anyone help me??
Thanks so much

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/5397
Please use the latest code and check if the problem is solved

**Comment by chareice** [comment]
You can try again with the latest version, and if there are any issues, please reopen this issue or open a new one.
