### ISSUE TITLE
The workflow cannot set the attachment field of the record to empty.

### ISSUE THREAD

**Issue by xiamiko** [nocobase/nocobase#5406]
## * Describe the bug

**Issue:**

1. When setting an attachment field to null in the Workflow, it doesn't clear the field but keeps the original attachment.
2. In contrast, setting a multi-line text field to null works correctly and clears the content.
3. This results in inconsistent behavior.

**Suggestion:**

Modify the Workflow to allow clearing an attachment field when a user explicitly assigns it a null value.

## * Environment

- NocoBase version: 1.3.31-beta

- Database type and version: PostgreSQL
  

- OS: Linux

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest]

- NodeJS version:

## * How To Reproduce

1. Create data table A with attachment field a1.
2. Create workflow B, set it as a post-operation event, and manually bind the workflow to the create or update button of data table A.
3. Have workflow B set the attachment field a1 to null value.

**Comment by xiamiko** [comment]
Please allow me to add some information that may help with the repair:

We found in NocoBase, the URL of the attachment field isn't stored directly in user-created tables. Instead, it's kept in a dedicated attachment table and linked to user tables through an intermediary table, which starts with "t_". We suspect there may be flaws in the Workflow's proccess mechanism when dealing with fields in this intermediary table format, causing the issue.

As a temporary fix, we've identified the intermediary table for the attachment field (starting with "t_") from the fields table. We're executing SQL statements within the workflow to remove associations from this intermediary table, implement clearing the attachment fields.

**Comment by mytharcher** [comment]
Hi @xiamiko, without some screenshot provided, I can just guess you are using "Batch mode" in your update node, in which the associations could not be updated.

For a workaround, you could change the update mode to "One by one" mode, then it will work.

**Comment by xiamiko** [comment]
Hi @mytharcher

Your assessment and plan are very correct. **After we switched to the "One by one" mode, he was able to clear the fields correctly.**

This has helped our business a lot, thank you very much.

Currently, the UI interface only indicates performance differences and trigger differences between "Batch" mode and "One by one" mode but does not mention this distinction. I personally think this may still be considered a BUG.

You can handle this issue according to Nocobase's rules. Thank you again for your voluntary support.

**Comment by mytharcher** [comment]
@xiamiko, you are correct. We are working on this, and will change the hint to let users to know how to choose the mode.
