### ISSUE TITLE
字段类型：一对多，编辑时记录未保存

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#541]
## Describe the bug

字段类型：一对多，编辑时记录未保存

## Version

![image](https://user-images.githubusercontent.com/82276246/175871095-566f3a43-f24d-417d-874d-5ecc0fdff45d.png)

## How To Reproduce

1. 添加字段类型：一对多
2. 添加表格区域
3. 配置字段和编辑页面
4. 在编辑页面添加数据并提交
5. 提交后再次进行编辑

## Expected behavior

提交成功后保存的数据展示

## Screenshots
![image](https://user-images.githubusercontent.com/82276246/175871196-bf25633a-0a46-4492-8bad-265d9dee561f.png)
![image](https://user-images.githubusercontent.com/82276246/175871659-44614b9b-a9b7-45df-b3ab-1f370fb222be.png)
![image](https://user-images.githubusercontent.com/82276246/175871812-9caac333-72df-4e58-aeb9-f330ac5beebe.png)

**Comment by chenos** [comment]
最新版 v0.7.2-alpha.1 已修复
