### ISSUE TITLE
将语言设置为中文后，依然显示为英文

### ISSUE THREAD

**Issue by whataxxday** [nocobase/nocobase#544]
## Describe the bug

将语言设置为中文后，依然显示为英文

## Version

- docker版 Version 0.7.1-alpha.7

## Screenshots

![image](https://user-images.githubusercontent.com/39958768/176087146-862617b1-8c56-4079-b890-d55b6d2ab769.png)

## Desktop (please complete the following information)

- OS: linux
- Browser chrome

**Comment by aiwenForGit** [comment]
我也碰到类似问题，我是重新编译后再登录就可以了。

**Comment by whataxxday** [comment]
> 我也碰到类似问题，我是重新编译后再登录就可以了。

我是dockerhub上他们放出的docker版的，重启容器我看到内部代码是有重新编译过程的，但是重启后还是显示英文

**Comment by zhouyanliang** [comment]
此处是 bug，临时解决方案：在系统配置里启用中文和英文，然后在右上角用户名下拉面板里选择中文。

**Comment by whataxxday** [comment]
> 此处是 bug，临时解决方案：在系统配置里启用中文和英文，然后在右上角用户名下拉面板里选择中文。

已尝试临时解决方案，有用，感谢！

**Comment by chenos** [comment]
最新版已修复，设置可以参考这篇文档 https://github.com/nocobase/nocobase/blob/main/docs/zh-CN/user-manual/advanced-guide/language-settings.md
