### ISSUE TITLE
file fail to upload：Incomplete uploading files need to be resolved

### ISSUE THREAD

**Issue by Lance1102** [nocobase/nocobase#5465]
## * Describe the bug

file fail to upload：Incomplete uploading files need to be resolved

## * Environment

- NocoBase version:v1.3.33-beta

- Database type and version: MarialDB:11
  

- OS:Windows 11

- Deployment Methods:Docker 

- Docker image version:lastest (v1.3.33-beta)

- NodeJS version:

## * How To Reproduce

as Screenshots uploaded
every file upload field shows error message

## Screenshots

![Incomplete uploading files need to be resolved](https://github.com/user-attachments/assets/e5955e3f-be33-4fbe-b65e-5c8ba25b913a)

**Comment by MarekVigas** [comment]
@mytharcher 
I was unable to upload any files with version 1.3.33-beta and now I updated to v1.3.37-beta. With v1.3.37-beta I'm at least able to finish the upload but the error is still displayed during upload.

https://github.com/user-attachments/assets/b71a3a56-0040-45bf-b99b-ef625b64755c

**Comment by mytharcher** [comment]
That is correct for now. The error text during uploading is used for avoid to submit the form in mistake. We may consider to make the feedback (not error like) more friendly later.

**Comment by Jeesoong** [comment]
<img width="456" alt="Image" src="https://github.com/user-attachments/assets/730f2efa-16f7-4397-8a8e-68af71036c84" />
1.5.20还是有这个问题，请问该如何排查
上传280M的视频文件，存储用的CloudFlare R2
