### ISSUE TITLE
The "Set default value" option for Association fields is not available in the Edit element.

### ISSUE THREAD

**Issue by Lance1102** [nocobase/nocobase#5516]
## * Describe the bug

The "Set default value" option for Association fields is not available in the Edit element.

## * Environment

- NocoBase version:v1.3.40-beta

- Database type and version: MarialDB:11
  

- OS:Windows 11

- Deployment Methods:Docker

- Docker image version: main (v1.3.40-beta)

- NodeJS version:

## * How To Reproduce

as Screenshots uploaded

## Screenshots
as Screenshots uploaded

「Add new」
![Add new Page：Set default value_2024-10-26_10-05-47](https://github.com/user-attachments/assets/d84958d2-7d00-4cce-8955-d46fa7050da5)

「Edit」
![Edit Page：NO Set default value_2024-10-26_10-04-52](https://github.com/user-attachments/assets/67106a18-0011-4a16-b191-e7a24cb0393d)

**Comment by tuiliere** [comment]
Thanks @Lance1102 for pointing out this problem, didn't had time to open the issue before you did. I confirm setting default value for association fields is a mandatory feature for several use cases we plan to tackle with our app.
Have subscribed to this issue notifications and will carefully follow the resolution.

**Comment by hongboji** [comment]
Editing forms with existing data, the field component does not support setting default values, which is also an unnecessary setting
