### ISSUE TITLE
In linkage rules or Workflow, using Formula.js functions such as REGEXEXTRACT, REGEXMATCH, and REGEXREPLACE does not take effect.

### ISSUE THREAD

**Issue by Lance1102** [nocobase/nocobase#5517]
## * Describe the bug

In linkage rules or Workflow, using Formula.js functions such as REGEXEXTRACT, REGEXMATCH, and REGEXREPLACE does not take effect.

## * Environment

- NocoBase version:v1.3.40-beta

- Database type and version: MarialDB:11
  

- OS:Windows 11

- Deployment Methods:Docker

- Docker image version:main (v1.3.40-beta)

- NodeJS version:

## * How To Reproduce

A single text field for the complete company name.
A single text field for the shortened name.
Use REGEXREPLACE or REGEXEXTRACT function in linkage rules
as Screenshots uploaded

## Screenshots

![1729985896108](https://github.com/user-attachments/assets/42821409-d0a5-412a-bd21-305bf649686c)
![1729985917777](https://github.com/user-attachments/assets/ac0f499f-4680-435e-a51f-79ad3b4b903f)
![1729986020964](https://github.com/user-attachments/assets/1929ce14-fbf8-4bb7-83b3-50b892c27bf2)

**Comment by mytharcher** [comment]
They are not supported by formulajs officially. See: https://github.com/formulajs/formulajs/issues/79

**Comment by Lance1102** [comment]
> They are not supported by formulajs officially. See: [formulajs/formulajs#79](https://github.com/formulajs/formulajs/issues/79)

thanks, I'll use another function to make.
