### ISSUE TITLE
many to many类型字段对应的表单无法提交保存

### ISSUE THREAD

**Issue by whataxxday** [nocobase/nocobase#554]
## Describe the bug

- 【产品表】  字段：产品编号（单行文本）、产品明细（one to many 关联产品明细表）
- 【产品明细表】  字段：产品明细编号（单行文本）、明细文档（many to many 关联明细文档表）
- 【明细文档表】  字段：文档名称（单行文本）、文档附件（attachment）

当给【产品明细表】添加 明细文档 时 提交报错

## Version

docker hub image tag 0.7.1-alpha.7

## Screenshots

![cf83e477ff657f7dec4c6cdb03b52c1](https://user-images.githubusercontent.com/39958768/176369067-23b4a0f1-ce93-4b08-8da1-fe493e8f9ca9.png)

## Desktop (please complete the following information)

- OS: linux
- Browser: chrome

**Comment by chenos** [comment]
最新版 v0.7.2-alpha.1 已修复
