### ISSUE TITLE
数据表配置删除时，存在关联字段的表，删除报错，导致删除不成功

### ISSUE THREAD

**Issue by cgssve** [nocobase/nocobase#555]
数据表配置删除时，存在关联字段的表，删除报错，导致删除不成功
关联字段，也已经删除，
![3](https://user-images.githubusercontent.com/108384478/176472085-fc9e74c6-3f40-4ab3-b992-7e285e5b40d1.png)

**Comment by chenos** [comment]
最新版 v0.7.2-alpha.1 已修复。
