### ISSUE TITLE
The pie chart data is inaccurate

### ISSUE THREAD

**Issue by RumblefishV587** [nocobase/nocobase#5557]
## * Describe the bug

With my test data, I created a new pie chart. The test data has four categories, but the pie chart only shows data in three colors

## * Environment

- NocoBase version:1.3.40-beta

- Database type and version: MySQL 8.4.2
  

- OS: ubuntu

- Deployment Methods:Docker

- Docker image version:v1.3.40-beta

## * How To Reproduce

With my test data, I created a new pie chart. The test data has four categories, but the pie chart only shows data in three colors

## Expected behavior

Please fix this bug

## Screenshots
![bug](https://github.com/user-attachments/assets/92e9c2c5-4147-4e38-9a95-84b96aaae5f6)

**Comment by 2013xile** [comment]
If all data values are negative, each value will be adjusted by adding the absolute value of the smallest number, setting the smallest number to 0.
