### ISSUE TITLE
One-To-Many Dropdown on Form shows limited options

### ISSUE THREAD

**Issue by baruchiro** [nocobase/nocobase#5579]
## * Describe the bug

I created a table with One-To-Many relation. On that table forms, I want to show a dropdown/picker to select the "many" relations, but I get a very limited options there, and the dropdown doesn't list all the items in the other table!

## * Environment

- NocoBase version: v1.3.40-beta

- Database type and version: MySQL 8.x
  

- OS: MacOs + Android

- Deployment Methods: Docker

- Docker image version: `nocobase/nocobase:latest`

- NodeJS version:

## * How To Reproduce

- Create a `People` table with `first_name`, `last_name` and formula column `full_name`
- Create a calendar table `Events` with `title` and one-to-many relation to `People`, + inverse relation.
- Create a form to add a new `Events` item, with a dropdown or subform for selecting many `People`

## Expected behavior

List all the `People` on the dropdown

## Screenshots

![image](https://github.com/user-attachments/assets/0ce19707-023e-4083-b7b7-98ab16843b2b)

![image](https://github.com/user-attachments/assets/2ebcdad0-b19c-44b7-a8c0-7c1cee7a6c00)

![image](https://github.com/user-attachments/assets/fa61dcf4-e804-4ccd-8afa-09f0f578f487)

**Comment by hongboji** [comment]
A one-to-many relationship field where data that has already been associated cannot be associated again.
Please see the following documentation to understand the meaning of a one-to-many relationship field.
https://docs.nocobase.com/handbook/data-modeling/collection-fields/associations

**Comment by baruchiro** [comment]
Oh, you're right, I needed a Many-to-Many relation here.
