### ISSUE TITLE
Boolean Fields - Exported in Chinese

### ISSUE THREAD

**Issue by offbase-solutions** [nocobase/nocobase#5587]
## * Describe the bug

Checkbox/Boolean fields are being exported in Chinese Characters instead of English see 
否
--
是

## * Environment

- NocoBase version:
-v1.3.42-beta

- Database type and version:
- [Postgres ](postgres:15)
  

- OS: Linux

- Deployment Methods:
- Docker

- Docker image version:
- latest (28-10-2024)

- NodeJS version:

## * How To Reproduce
Do export on a table containing a boolean field.

## Expected behavior

Data to be exported in english.

## Screenshots

<img width="472" alt="Screenshot 2024-11-04 at 12 07 08 PM" src="https://github.com/user-attachments/assets/71d79262-6be4-4eb3-8a68-8ca1b8d6b15c">

**Comment by chareice** [comment]
fixed https://github.com/nocobase/nocobase/pull/5591
