### ISSUE TITLE
Failed to import value for many2many field

### ISSUE THREAD

**Issue by liunux4odoo** [nocobase/nocobase#5618]
## * Describe the bug

As described here: https://github.com/nocobase/nocobase/tree/main/packages/plugins/%40nocobase/plugin-action-import#%E5%85%B3%E7%B3%BB%E7%B1%BB%E5%9E%8B%E5%AD%97%E6%AE%B5
I tried to import to table with many2many field, but it raised:
```
failed to import row 7, invalid input syntax for type bigint: ",": invalid input syntax for type bigint: ",", rowData: {"id":6,"f_1w7kn639ot8":"TC589","f_uu1txxhuo5u":"dummy","f_vglsedg7ytf":null,"f_e18qv5onnom":"155,156,157,158,159"}: invalid input syntax for type bigint: ","
```

## * Environment

- NocoBase version: 1.3.46-beta

- Database type and version: Postgres 16
  

- OS: Windows

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

## * How To Reproduce

1. Create a table that stores person data
2. Create a table with many2many field named people that links to person table
3. Configure an import with field `people/ID`
4. An excel file with column `people/ID` that contains value `1,2,3` which is IDs of person table
5. Do import

It seems the split IDs are not cast to integers.

## Expected behavior

import successfully

**Comment by hongboji** [comment]
https://github.com/nocobase/nocobase/pull/5623 ，Please use the latest code and check if the problem is solved.

**Comment by liunux4odoo** [comment]
> #5623 ，Please use the latest code and check if the problem is solved.

Is this fix in latest docker or I should test it with the main branch source code?

**Comment by liunux4odoo** [comment]
> Docker is ok

Thanks. I will report test result later.

**Comment by liunux4odoo** [comment]
The problem has been fixed in latest docker image.
Thanks for your works again.
