### ISSUE TITLE
提交表单的报错在界面通知中显示了2次

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#562]
## Describe the bug

提交表单的报错在界面通知中显示了2次：

## Version

Version 0.7.1-alpha.7

## How To Reproduce

编写了一个服务器端校验，抛出错误，能确定被执行了一次。

通过浏览器查看到的 response 也只有一条：

```json
{"errors":[{"message":"藏品系列：booooooom 藏品总数 2262 超过上限 1500"}]}
```

但提交表单的报错在界面通知中显示了2次。

## Expected behavior

报错通知应只出现一次。

## Screenshots

![image](https://user-images.githubusercontent.com/931976/176619500-3646d860-84c3-4eae-8170-aafc60ee9927.png)

## Desktop (please complete the following information)

- OS: macOS 12.4 (21F79)
- Browser chrome
- Version 102.0.5005.115（正式版本） (x86_64)

**Comment by chenos** [comment]
如果之前是使用 yarn create 安装的 NocoBase 应用，需要重新 yarn create，再执行 yarn nocobase upgrade。

因为脚手架的代码有变更，具体查看这里
https://github.com/nocobase/nocobase/blob/main/packages/app/client/src/pages/index.tsx

**Comment by MarshalW** [comment]
按照你说的方法，已经没有问题了。

![image](https://user-images.githubusercontent.com/931976/176845615-8ef6dfb4-b2c8-440e-9cf5-a5e8883eec64.png)

这个过程操作比较多，记录下来：

```zsh
# 备份当前项目
cp -r ../my-nocobase-app /tmp/my-nocobase-app-bak

# 当前项目打个空分支
git checkout --orphan nft3
git rm --cached -r .

# 清空所有文件，除了.git 和 TODO.md
setopt extended_glob
rm -r ^(.git|TODO.md)(D)

# 创建新的my-nocobase-app，并确定可运行
cd /tmp
yarn create nocobase-app my-nocobase-app -d sqlite
cd my-nocobase-app
yarn
yarn nocobase install --lang=zh-CN
yarn dev

# 回到当前项目
cd ~/projects/my-nocobase-app

# 复制新生成的文件
cp -r /tmp/my-nocobase-app/. . 

# 复制之前数据库和上传的文件
rm -rf ./storage
cp /tmp/my-nocobase-app-bak/storage .

# 复制之前实现的插件
cp -r /tmp/my-nocobase-app-bak/packages/plugins/nft packages/plugins
```

还需要将插件加入到 `packages/app/server/src/config/plugins.ts` 中

然后执行：

```zsh
yarn
yarn nocobase upgrade
yarn dev
```
