### ISSUE TITLE
Unable to set default time using Current Time in Time field

### ISSUE THREAD

**Issue by offbase-solutions** [nocobase/nocobase#5629]
## * Describe the bug

When setting a Time field with the Current Time variable it fails with an error on submission of the Form.

## * Environment

- NocoBase version: v1.3.47-beta

- Database type and version:  PostgreSQL
  

- OS: Linux

- Deployment Methods: Docker

- Docker image version:

- NodeJS version:

## * How To Reproduce

Create a form in either Web/Mobile, add a Time field. Configure the Time Field default value to be the current time. On submission of the form it fails with an error - invalid input syntax for type time: "2024-11-11T14:07:55.660Z"

## Expected behavior

Form to be submitted with the default time set as the current time.

## Screenshots

<img width="1230" alt="Screenshot 2024-11-11 at 9 03 52 AM" src="https://github.com/user-attachments/assets/80dbf252-a845-4fa9-ae8a-cda1c70a921d">
<img width="1024" alt="Screenshot 2024-11-11 at 9 04 11 AM" src="https://github.com/user-attachments/assets/8c2dee5b-2b15-4fdb-b754-e9f522bc22cd">
<img width="680" alt="Screenshot 2024-11-11 at 9 04 28 AM" src="https://github.com/user-attachments/assets/3868fa6d-303f-4786-a031-976bc9aba79c">
<img width="783" alt="Screenshot 2024-11-11 at 9 04 46 AM" src="https://github.com/user-attachments/assets/a0598232-89d6-4535-bef5-e0c8af015887">
<img width="823" alt="Screenshot 2024-11-11 at 9 05 00 AM" src="https://github.com/user-attachments/assets/d3d065ac-9f64-4198-a568-dd77f0876404">

**Comment by offbase-solutions** [comment]
<img width="1146" alt="Screenshot 2024-11-11 at 11 30 06 AM" src="https://github.com/user-attachments/assets/a96d3563-15eb-420b-885a-e46738a095f0">

**Comment by offbase-solutions** [comment]
See additional information:
TypeError: _.locale is not a function
at Object.format (https://domain/npm.rc-picker.218fa2cc.async.js:1:2222)

**Comment by hongboji** [comment]
What is the field type of “start time”?

**Comment by offbase-solutions** [comment]
Field "start_time" is of type Time. Try also using the "Assign Field Values" from a button and you will get similar errors.

**Comment by hongboji** [comment]
1. Please ask which type of field is specific, as shown below:
![image](https://github.com/user-attachments/assets/0de58b98-1d22-42df-9b67-85b0dfafd36d)

2, if the field type is “Time”, the variable “Current time” is the time with the date, the contents of the two do not match, is a correct tip!

**Comment by offbase-solutions** [comment]
How do you set the default time when using the Time field?

**Comment by hongboji** [comment]
Use the block's linkage rules feature to assign a value to the time field with an expression that can be used with the appropriate function or calculated to match the requirements
