### ISSUE TITLE
Table with one-to-many relation column  configured as Field component Tag cannot take color from a collection with Single Select with colors set

### ISSUE THREAD

**Issue by Towerful** [nocobase/nocobase#5645]
## * Describe the bug

I have a collection & table showing Projects that has a one-to-many related collection of Tasks.  
Tasks have a Select Option field for status with colors assigned to each option.  
Displaying a Project's Tasks in a Project Table with the Tasks column Field component set to Tag does not allow setting the Tag color based on the Task->Status selection & related color.

Additionally a Workflow does not have access to a Select Options color. 
So I cannot create a Workflow that allows copying the Status field's option color to the Task.

## * Environment

- NocoBase version: v1.3.48-beta

- Database type and version:  Postgres 16
  

- OS: Debian 12

- Deployment Methods: Docker Compose

- Docker image version: nocobase/nocobase:latest

- NodeJS version:

## * How To Reproduce

- Create a General collection of Projects.
- Create a General collection of Tasks.
   - Add a field of Single Select
     - Add some options with colors
   - Add a field of Many-to-one and target the Projects collection
- Add a Projects Table to a page
  - Configure it to show Tasks
  - Change Tasks column Field component to Tag
  - **Cannot set the Tag color based on the option**

I suspect the workaround I need to use is:
 - Tasks collection with a Color field and a One-to-Many to a Statuses collection with Text/Color
 - When a Task's Status is updated, a Workflow would copy the related Status's Color to the Task.

## Expected behavior

A Table Column Field component of type Tags should be able to be colored based on a Select field's color.
A Select field's color should be exposed to Workflows.

## Screenshots

I can supply screenshots if required.

## Logs

N/A

**Comment by hongboji** [comment]
You need to add the “color” field to the table.
in order to select it in the settings。
![image](https://github.com/user-attachments/assets/005721e6-35c7-4076-8c94-e5e187d07f68)

**Comment by Towerful** [comment]
Thanks for getting back to me.  

The issue I am facing is that the "color" input when creating a Single Select isn't actually accessible anywhere.   
https://docs.nocobase.com/handbook/data-modeling/collection-fields/choices/select

So I can't color the Tags in a table based on the option selected on a relation (think project has-many tasks. task have a "status" Single Select field with text & color set for the various options).

I am currently working around this by having a Statuses collection.  
So Project one-to-many Tasks. Tasks many-to-one Statuses.  Statuses contain the text field and color field that I had previously put in the Single Select field on the Task.
I am then using a workflow that detects a Task being created/updated, and copying the related Status's Color field to the Tasks Color field.   
It seems a bit tedious, when the Single Select has a color input. But if thats the onoly way to do it, then I can accept the workaround.
