### ISSUE TITLE
 Hope for the field can be added multiple times in the table(希望表格里面,一个字段可以多次显示)

### ISSUE THREAD

**Issue by m50046208** [nocobase/nocobase#566]
### Hope for the field can be added multiple times in the table. So that the table can display more information from the relational table  can displayed in different columns ,  and the functions of action button can seperate to different column

希望表格里面,一个字段可以多次添加.用于显示关系表的不同字段,以及将操作里面的 不同的功能的按钮放在不同列里面显示

例如
![image](https://user-images.githubusercontent.com/64178494/176861091-5a54a6ff-c2f3-48fb-a4e7-d30dcb4a1c28.png)
例如 产品名称来源于与关系表,表格如果能添添加 " 产品名称" 字段三次, 则可以一列显示货号,一列显示名称,一列显示规格型号等不同的信息.

**Comment by zhouyanliang** [comment]
For one-to-one and many-to-one relationships, displaying each field of the relational collection in a table is now supported in the latest version.
![2022-07-01_18-29-40](https://user-images.githubusercontent.com/1267426/176878003-b1f89819-f41c-4d67-83c6-8757692054d3.jpg)

**Comment by MarshalW** [comment]
这个新特性大约何时能加入到发布的版本中呢？

我现在用的是 npm registry 发布的包，通过 `yarn create nocobase-app`的方式。

**Comment by 625412505** [comment]
> 这个新特性大约何时能加入到发布的版本中呢？
> 
> 我现在用的是 npm registry 发布的包，通过 `yarn create nocobase-app`的方式。

源码中已经包含这个特性了，可以使用源码部署。

**Comment by chenos** [comment]
最新版 v0.7.2-alpha.1 已发布
