### ISSUE TITLE
Add New action is blank

### ISSUE THREAD

**Issue by skippa** [nocobase/nocobase#571]
## Describe the bug

Add New standard action just shows a blank tab

## Version
0.7.1-alpha.7
db: mysql

## Steps to reproduce the behavior:

1. Create block of type 'table', select a collection (in my case it was Jobs) but it doesn't matter which collection you choose
2. Configure actions to enable 'add new'
3. Exit from UI editor
4. Click 'add new'
Add New tab appears which only has the word "Add New" on it, which is a clickable link, but it does nothing

## Expected behavior
A dialog showing fields to enter new data for a new record

## Desktop
- OS: Ubuntu 20.04
- Browser: Brave (same behaviour with Firefox)

Is it possibly some permissions issue with mysql...?  Also, where are the logs to debug issues like this?

**Comment by zhouyanliang** [comment]
Please don't exit from UI editor mode, you will find 'Add block' button in 'Add new' tab where you can add a form block.
![2022-07-04_09-13-22](https://user-images.githubusercontent.com/1267426/177065406-3f66aeb2-0414-4442-b0e8-e33c986b85fb.jpg)

**Comment by skippa** [comment]
aaaahh, excellent, thankyou!
