### ISSUE TITLE
 工作流 定时任务  查询数据 数据表为空,没有任何错误提示

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#573]
## Describe the bug
Docker 安装后 工作流 定时任务  查询数据 数据表为空，没有任何错误提示
![image](https://user-images.githubusercontent.com/900786/177103940-d5db98a7-04c9-4f12-8aaf-fc114f535630.png)

检查数据表没有任何问题，数据表事件 就没有任何问题
![image](https://user-images.githubusercontent.com/900786/177104416-0110864e-ac9c-4891-928a-fa3c28e2881e.png)

## Version

"Image": "nocobase/nocobase:0.7.1-alpha.7",
                "com.docker.compose.project": "app-sqlite",
                "com.docker.compose.project.config_files": "docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/lighthouse/nocobase/docker/app-sqlite",
                "com.docker.compose.service": "app",
                "com.docker.compose.version": "1.29.2"

**Comment by zhouyanliang** [comment]
已知问题，正在解决。

**Comment by chenos** [comment]
最新版 v0.7.2-alpha.1 已修复
