### ISSUE TITLE
导出的数据，再次导入 直接报主键错误

### ISSUE THREAD

**Issue by kill136** [nocobase/nocobase#5767]
![image](https://github.com/user-attachments/assets/9fa071ec-ca3b-4652-a2cb-ef3c25c50eca)

**Comment by hongboji** [comment]
已有数据代表已经存在，有些字段数据是不允许重复,故提示，如 id

**Comment by kill136** [comment]
> 已有数据代表已经存在，有些字段数据是不允许重复,故提示，如 id

有的时候，客户可能需要导入新增和修改都在一个Excel 上面进行，id 有值表示新增，id 空的表示修改原有记录
