### ISSUE TITLE
已有数据代表已经存在，有些字段数据是不允许重复,故提示，如 id

### ISSUE THREAD

**Issue by kill136** [nocobase/nocobase#5781]
已有数据代表已经存在，有些字段数据是不允许重复,故提示，如 id

_Originally posted by @hongboji in https://github.com/nocobase/nocobase/issues/5767#issuecomment-2511314378_

有的时候，客户可能需要导入新增和修改都在一个Excel 上面进行，id 有值表示新增，id 空的表示修改原有记录

**Comment by zhouyanliang** [comment]
导入 pro 版本会提供更新的功能。12 月发布
