### ISSUE TITLE
dev 启动报错，关于 --openssl-legacy-provider 

### ISSUE THREAD

**Issue by nielinjie** [nocobase/nocobase#579]
## Describe the bug

按照文档github源代码启动，yarn dev步骤报错。

/opt/homebrew/Cellar/node/18.4.0/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

## How To Reproduce

按照文档github源代码启动，yarn dev步骤报错。

## Screenshots

```
➜  nocobase git:(main) yarn dev
yarn run v1.22.19
$ nocobase dev
WAIT: TypeScript compiling...
/opt/homebrew/Cellar/node/18.4.0/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
/Users/nielinjie/Projects/nocobase/node_modules/execa/lib/error.js:60
                error = new Error(message);
```

**Comment by nielinjie** [comment]
下面这一段注释掉以后可以启动。

./packages/core/cli/bin/index.js
 ```   
    if ('v18' === process.version.split('.').shift()) {
        process.env.NODE_OPTIONS = '--openssl-legacy-provider';
    }
```

我的环境是
node = 18.4.0
Mac os = 12.4

经查 - 
--openssl-legacy-provider 是node v17.0.0 添加的，但没有找到有在后续版本禁用。可能跟系统的openssl版本有关。

**Comment by chenos** [comment]
```bash
NODE_OPTIONS=--openssl-legacy-provider
```

或使用 v16 版本的 node

**Comment by nielinjie** [comment]
> ```shell
> NODE_OPTIONS=--openssl-legacy-provider
> ```
> 

是多了一个--openssl-legacy-provider，不是少了一个--openssl-legacy-provider。去掉这个--openssl-legacy-provider就好了。

**Comment by chenos** [comment]
之所以加上是因为会报错

```
error:0308010C:digital envelope routines::unsupported
```

去掉了 https://github.com/nocobase/nocobase/commit/7c7fd1bb5e558cd27d39f86d6ce1f91d2afc8af9 如果有问题的自己加上

```
NODE_OPTIONS=--openssl-legacy-provider
```
