### ISSUE TITLE
Docker publish error

### ISSUE THREAD

**Issue by MickleWen** [nocobase/nocobase#580]
app-sqlite-app-1  | nginx started
app-sqlite-app-1  | copying...
app-sqlite-app-1  | tar: ./node_modules/fs-jetpack/node_modules/.bin: Directory renamed before its status could be extracted
....
tar: Exiting with failure status due to previous errors

**Comment by chenos** [comment]
能否提供更详细的信息，什么操作系统，docker 的版本。
这个 issue 是否可以帮你解决问题 https://github.com/docker/hub-feedback/issues/727

**Comment by MickleWen** [comment]
源码安装运行后，报错： no such file or directory, stat '/nocobase/pakages/app/client/dist/index.html'
安装过出现caniuse-lite is outdated

**Comment by MarshalW** [comment]
这个问题我碰到过：

```
no such file or directory, stat '/nocobase/pakages/app/client/dist/index.html'
```

https://github.com/nocobase/nocobase/blob/b848b9cd6774df6ed86acd30edb81ed6381c3555/docker/nocobase/Dockerfile#L8

要改为：

```sh
&& yarn install
```

原因大致是，加 `--production` 造成一些编译前端的包不被安装，`nocobase build` 构建前端的时候发现包未安装就不编译了（不报错，但是有警告提示信息）。

**Comment by chenos** [comment]
重新下载镜像可解决
