### ISSUE TITLE
每次docker compose 升级完成后，系统的logo image就会消失

### ISSUE THREAD

**Issue by toplinuxsir** [nocobase/nocobase#5897]
## * Environment

- NocoBase version:

postgresql 16.0

  

- OS:

- Deployment Methods:
docker compose

- Docker image version:  1.4.10

- NodeJS version:

## * How To Reproduce

docker compose pull && docker compose up -d

**Comment by zhouyanliang** [comment]
1. 发布 issue 页面有说明，使用英语以外的语言的话，请发布到社区 https://forum.nocobase.com/
2. 提供信息不足，大概率是 storage 配置问题
