### ISSUE TITLE
流程问题-触发数据带不出来&表单错误

### ISSUE THREAD

**Issue by fanft** [nocobase/nocobase#5904]
![image](https://github.com/user-attachments/assets/0a6e17cc-bd2e-4d20-a560-68585bb6fdc3)
![image](https://github.com/user-attachments/assets/2b4c3303-4c9a-4ab3-ad04-edfa9b9c2f68)
两个问题：
   1、触发数据带不出来，流程选择触发数据表单，流程启动后。审批节点看不到。
   2、审批表单布局会错位

**Comment by hongboji** [comment]
请去社区提问：https://forum.nocobase.com/
请尽量按照提问模板提交信息，以便快速定位解决问题
如果问题复杂，可以去官网申请demo，社区提问题，给出复现url，可以快速解决

**Comment by hongboji** [comment]
此issues关闭
