### ISSUE TITLE
How to debug "Validation error"?

### ISSUE THREAD

**Issue by Lelenaic** [nocobase/nocobase#5914]
## * Describe the bug

From today, without changing anything, the app is displaying a "Validation error" on every page and is inaccessible.
I activated the LOGGER_LEVEL=debug, I checked the error log file, but nothing is telling me exactly what is the error in the database. I tried to activate the DB_LOGGING=yes too, but the SQL log file is empty.
How can I find the database error precisely to fix it?

## * Environment

- NocoBase version:

- Database type and version: PostgreSQL 16
  

- OS: MacOS

- Deployment Methods: Docker

- Docker image version: nocobase/nocobase:next

## * How To Reproduce

Well, I don't really know.

## Expected behavior

The app should start.

## Screenshots

Nothing really useful.

## Logs

Here is the log from system_error:
```
{"level":"error","message":"Validation error","stack":"Error\n    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)\n    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:315:28\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PostgresQueryInterface.addIndex (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:250:12)\n    at async _SyncRunner.handleUniqueIndex (/app/nocobase/node_modules/@nocobase/database/lib/sync-runner.js:239:9)\n    at async _SyncRunner.runSync (/app/nocobase/node_modules/@nocobase/database/lib/sync-runner.js:94:5)\n    at async users.sync (/app/nocobase/node_modules/@nocobase/database/lib/model.js:57:12)\n    at async Sequelize.sync (/app/nocobase/node_modules/sequelize/lib/sequelize.js:377:9)\n    at async _AsyncEmitter.sync (/app/nocobase/node_modules/@nocobase/database/lib/database.js:575:20)\n    at async _AsyncEmitter.load (/app/nocobase/node_modules/@nocobase/server/lib/application.js:405:7)","meta":{},"module":"application","submodule":"","method":"","app":"main","reqId":"7843c884-c19d-4bb7-b218-4402a8095d77","dataSourceKey":"main","timestamp":"2024-12-19 11:02:52"}
```

**Comment by 2013xile** [comment]
Please set `DB_LOGGING=on`.

**Comment by Lelenaic** [comment]
It worked, I can see the SQL requests in the log, thanks, my issue is fixed.
