### ISSUE TITLE
列-样式-设置

### ISSUE THREAD

**Issue by 18906465111** [nocobase/nocobase#5932]
Unhandled Rejection (Error): Unrecognized operation undefined
(anonymous function)
.nocobase/packages/core/client/src/schema-settings/LinkageRules/useActionValues.ts:48:16
  45 |         } else setValueMap({});
  46 |       })
  47 |       .catch((err) => {
> 48 |         throw new Error(err.message);
     |              ^  49 |       });
  50 |   }
  51 | }, [variables, localVariables, styleRules, formValues]);

Unhandled Rejection (Error): Unrecognized operation undefined
(anonymous function)
http://180.184.54.167:13000/p__index.async.js:136609:15
  136606 |         setValueMap(valueMap);
  136607 |       } else setValueMap({});
  136608 |     })["catch"](function (err) {
> 136609 |       throw new Error(err.message);
         |             ^  136610 |     });
  136611 |   }
  136612 | }, [variables, localVariables, styleRules, formValues]);
View source
设置列样式-联动规则，可以不设置 值就能保存，保存后再修改出错误。

**Comment by zhouyanliang** [comment]
请发在中文社区 https://forum.nocobase.com/
