### ISSUE TITLE
当配置设置表前缀时,sql表在chart图表执行的时候报错表不存在

### ISSUE THREAD

**Issue by shenzebiao** [nocobase/nocobase#5933]
## * Describe the bug
项目配置文件设置了表前缀(n_)，当建立sql表，图表区块选择sql表数据后执行会报错表不存在，一定需要将sql表加上表前缀(n_)才行，否则就会报错

## * Environment

- NocoBase version:
- lastest

- Database type and version: 
- mysql 8
  

- OS:

- Deployment Methods:

- Docker image version:

- NodeJS version:

**Comment by hongboji** [comment]
是这样的，sql是直接查询数据库，NocoBase的数据表是业务层的，看到的表不一定等同于数据库的
