### ISSUE TITLE
升级到最新的0.7.2工作流菜单没有了？是下线了么？急需功能如何找回，请大师指点

### ISSUE THREAD

**Issue by aiwenForGit** [nocobase/nocobase#596]
升级到最新的0.7.2工作流菜单没有了？是下线了么？急需功能如何找回，请大师指点

**Comment by chenos** [comment]
升级前可以关注一下更新日志 breaking changes 的内容 https://docs-cn.nocobase.com/release-notes

之前使用 yarn create 安装的 NocoBase 应用，需要重新 yarn create，再执行 `yarn nocobase upgrade --raw`
