### ISSUE TITLE
Docker镜像重新下下载以后，无法运行了

### ISSUE THREAD

**Issue by qiuai** [nocobase/nocobase#609]
我一直都是用的latest镜像，今天抓取了一下最新的启动就会自动停止了。

Docker输出错误代码如下：
`node:internal/process/promises:279

            triggerUncaughtException(err, true /* fromPromise */);

            ^

Error

    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)

    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:311:28

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async PostgresQueryInterface.select (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)

    at async Function.findAll (/app/nocobase/node_modules/sequelize/lib/model.js:1134:21) {

  name: 'SequelizeDatabaseError',

  parent: error: column "allExecuted" does not exist

      at Parser.parseErrorMessage (/app/nocobase/node_modules/pg-protocol/dist/parser.js:287:98)

      at Parser.handlePacket (/app/nocobase/node_modules/pg-protocol/dist/parser.js:126:29)

      at Parser.parse (/app/nocobase/node_modules/pg-protocol/dist/parser.js:39:38)

      at Socket.<anonymous> (/app/nocobase/node_modules/pg-protocol/dist/index.js:11:42)

      at Socket.emit (node:events:527:28)

      at Socket.emit (node:domain:475:12)

      at addChunk (node:internal/streams/readable:315:12)

      at readableAddChunk (node:internal/streams/readable:289:9)

      at Socket.Readable.push (node:internal/streams/readable:228:10)

      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {

    length: 112,

    severity: 'ERROR',

    code: '42703',

    detail: undefined,

    hint: undefined,

    position: '130',

    internalPosition: undefined,

    internalQuery: undefined,

    where: undefined,

    schema: undefined,

    table: undefined,

    column: undefined,

    dataType: undefined,

    constraint: undefined,

    file: 'parse_relation.c',

    line: '3293',

    routine: 'errorMissingColumn',

    sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',

    parameters: undefined

  },

  original: error: column "allExecuted" does not exist

      at Parser.parseErrorMessage (/app/nocobase/node_modules/pg-protocol/dist/parser.js:287:98)

      at Parser.handlePacket (/app/nocobase/node_modules/pg-protocol/dist/parser.js:126:29)

      at Parser.parse (/app/nocobase/node_modules/pg-protocol/dist/parser.js:39:38)

      at Socket.<anonymous> (/app/nocobase/node_modules/pg-protocol/dist/index.js:11:42)

      at Socket.emit (node:events:527:28)

      at Socket.emit (node:domain:475:12)

      at addChunk (node:internal/streams/readable:315:12)

      at readableAddChunk (node:internal/streams/readable:289:9)

      at Socket.Readable.push (node:internal/streams/readable:228:10)

      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {

    length: 112,

    severity: 'ERROR',

    code: '42703',

    detail: undefined,

    hint: undefined,

    position: '130',

    internalPosition: undefined,

    internalQuery: undefined,

    where: undefined,

    schema: undefined,

    table: undefined,

    column: undefined,

    dataType: undefined,

    constraint: undefined,

    file: 'parse_relation.c',

    line: '3293',

    routine: 'errorMissingColumn',

    sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',

    parameters: undefined

  },

  sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',

  parameters: {}

}

/app/nocobase/node_modules/execa/lib/error.js:60

error = new Error(message);

        ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade

    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)

    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async exports.runAppCommand (/app/nocobase/node_modules/@nocobase/cli/src/util.js:125:5)

    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/upgrade.js:20:9) {

  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',

  command: 'node ./packages/app/server/lib/index.js upgrade',

  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',

  exitCode: 1,

  signal: undefined,

  signalDescription: undefined,

  stdout: undefined,

  stderr: undefined,

  failed: true,

  timedOut: false,

  isCanceled: false,

  killed: false

}

error Command failed with exit code 1.`

**Comment by qiuai** [comment]
nginx started
copying...
yarn run v1.22.18
$ nocobase db:auth --retry=30
Connection has been established successfully.
Done in 10.95s.
yarn run v1.22.18
$ nocobase install -s
Connection has been established successfully.
Done in 10.64s.
yarn run v1.22.18
$ nocobase upgrade -S
WAIT: TypeScript compiling...
upgrading...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.select (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Function.findAll (/app/nocobase/node_modules/sequelize/lib/model.js:1134:21) {
  name: 'SequelizeDatabaseError',
  parent: error: column "allExecuted" does not exist
      at Parser.parseErrorMessage (/app/nocobase/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/nocobase/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/nocobase/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/nocobase/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 112,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '130',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3293',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',
    parameters: undefined
  },
  original: error: column "allExecuted" does not exist
      at Parser.parseErrorMessage (/app/nocobase/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/nocobase/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/nocobase/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/nocobase/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 112,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '130',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3293',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',
    parameters: undefined
  },
  sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',
  parameters: {}
}
/app/nocobase/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.runAppCommand (/app/nocobase/node_modules/@nocobase/cli/src/util.js:125:5)
    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/upgrade.js:20:9) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
  command: 'node ./packages/app/server/lib/index.js upgrade',
  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (/app/nocobase/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /app/nocobase/node_modules/sequelize/lib/sequelize.js:311:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PostgresQueryInterface.select (/app/nocobase/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Function.findAll (/app/nocobase/node_modules/sequelize/lib/model.js:1134:21) {
  name: 'SequelizeDatabaseError',
  parent: error: column "allExecuted" does not exist
      at Parser.parseErrorMessage (/app/nocobase/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/nocobase/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/nocobase/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/nocobase/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 112,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '130',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3293',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',
    parameters: undefined
  },
  original: error: column "allExecuted" does not exist
      at Parser.parseErrorMessage (/app/nocobase/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/app/nocobase/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/app/nocobase/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/app/nocobase/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:527:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 112,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '130',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3293',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',
    parameters: undefined
  },
  sql: 'SELECT "id", "createdAt", "updatedAt", "key", "title", "enabled", "description", "type", "config", "useTransaction", "executed", "allExecuted", "current" FROM "workflows" AS "workflows" WHERE "workflows"."enabled" = true;',
  parameters: {}
}
/app/nocobase/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade
    at makeError (/app/nocobase/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/app/nocobase/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.runAppCommand (/app/nocobase/node_modules/@nocobase/cli/src/util.js:125:5)
    at async Command.<anonymous> (/app/nocobase/node_modules/@nocobase/cli/src/commands/upgrade.js:20:9) {
  shortMessage: 'Command failed with exit code 1: node ./packages/app/server/lib/index.js upgrade',
  command: 'node ./packages/app/server/lib/index.js upgrade',
  escapedCommand: 'node "./packages/app/server/lib/index.js" upgrade',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
nginx started
yarn run v1.22.18
$ nocobase db:auth --retry=30
Connection has been established successfully.
Done in 10.70s.
yarn run v1.22.18
$ nocobase install -s
Connection has been established successfully.
Done in 10.60s.
yarn run v1.22.18
$ nocobase upgrade -S
WAIT: TypeScript compiling...
upgrading...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenos** [comment]
升级之前是什么版本？可以试试：

```
docker-compose run app bash
yarn nocobase db:sync
exit
docker-compose up -d app
```

**Comment by qiuai** [comment]
0.7.0-alpha.62

**Comment by qiuai** [comment]
db:sync以后，所有数据丢失了.....

**Comment by qiuai** [comment]
root@9d2f5682ede1:/app/nocobase# yarn nocobase db:sync
yarn run v1.22.18
error Couldn't find a package.json file in "/app/nocobase"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chenos** [comment]
现在什么情况了？除非把数据库容器给删了，db sync 并不会删除数据，看起来是app容器没配置好，检查一下。

**Comment by qiuai** [comment]
折腾了好久都没找回来数据,于是直接删了重来吧.
