### ISSUE TITLE
所有操作记录列表的查看链接在非 admin角色 用户不可见

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#617]
## Describe the bug

所有操作记录列表的查看链接在非 admin 用户不可见

## Version

Version 0.7.2-alpha.7

## How To Reproduce

所有操作记录列表的查看链接在非 admin 用户不可见

## Expected behavior

希望能让非 admin 用户能访问到 `查看` 链接。

因为有时候要设置业务管理人员角色，他们并不能修改表结构或者界面，但是能对业务写操作做审计。

## Screenshots

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/931976/178263784-d4ef466d-856d-4b9a-92cf-aa2f39357c52.png">

## Desktop (please complete the following information)

- OS: macOS 12.4 (21F79)
- Browser chrome
- Version 版本 103.0.5060.114（正式版本） (x86_64)

**Comment by AydenGen** [comment]
和 #616 应该为同一个bug，这个我来看吧
