### ISSUE TITLE
图表json配置对应formmtter如何配置？目前好像不支持函数表示，请大师帮忙看下！

### ISSUE THREAD

**Issue by aiwenForGit** [nocobase/nocobase#634]
比如我在配置RadiaBar图表类型时，对应触发事件函数在json中如何表示，去掉引号json校验通不过，按下面的配置不起作用，鼠标放上去，无法触发显示数据事件，请帮忙看下。
{
  "data": [
    {
      "name": "X6",
      "star": 297
    },
    {
      "name": "G",
      "star": 506
    },
    {
      "name": "AVA",
      "star": 805
    },
    {
      "name": "G2Plot",
      "star": 1478
    },
    {
      "name": "L7",
      "star": 2029
    },
    {
      "name": "G6",
      "star": 7100
    },
    {
      "name": "F2",
      "star": 7346
    },
    {
      "name": "G2",
      "star": 10178
    }
  ],
  "xField": "name",
  "yField": "star",
  "radius": 0.8,
  "innerRadius": 0.2,
  "tooltip": {
    "formatter": "(datum) => {return { name: \"star数\", value: datum.star } "
  }
}

**Comment by chenos** [comment]
```ts
{
  "formatter": "{{ (datum) => {return { name: 'star数', value: datum.star } }}"
}
```

**Comment by aiwenForGit** [comment]
收到，谢谢！问下是否支持实时动态更新数据方式，如果是函数setinterval如何处理？
