### ISSUE TITLE
源码构建报错

### ISSUE THREAD

**Issue by 625412505** [nocobase/nocobase#636]
## Describe the bug

构建报错

## Version

提交commit：9df35933d281dcf62e6b699edbc616c77cea9bf7

## How To Reproduce

1. yarn nocobase upgrade;yarn install;yarn build

## Expected behavior

构建成功，无报错

## Screenshots
![image](https://user-images.githubusercontent.com/82276246/179163998-ed034804-a462-4eba-b296-05af9032ef9d.png)
![image](https://user-images.githubusercontent.com/82276246/179164179-6eaf1659-aa99-4403-bcd1-e8970bbd9656.png)

**Comment by chenos** [comment]
已修复 https://github.com/nocobase/nocobase/commit/600f13f4a06ccfed27df928d7435afa83391c18a
