### ISSUE TITLE
选项型 修改选项值以后 原来记录里的值不会更新 导致数据空白

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#643]
## Describe the bug
![image](https://user-images.githubusercontent.com/900786/179436582-2c436a3e-a814-4ff6-af2e-d3d2afbc8ab0.png)

![image](https://user-images.githubusercontent.com/900786/179436513-c7a254e5-536a-4944-882f-a376902cd280.png)
逻辑上来说 更新后 已记录的数据 应该批量update 一下

**Comment by hongboji** [comment]
修复能够正常显示
