### ISSUE TITLE
DB_TABLE_PREFIX doesn't get applied

### ISSUE THREAD

**Issue by n-sviridenko** [nocobase/nocobase#703]
DB_TABLE_PREFIX doesn't get applied.

Hey guys, seems like this variable doesn't really get considered by the app. At least by the CLI, when we run `yarn nocobase install`, so we have to clean all tables now.

How can we fix this?

**Comment by chenos** [comment]
fixed #710

**Comment by n-sviridenko** [comment]
thank you, guys 🙌
