### ISSUE TITLE
用户表users，自己添加的字段，删除不了

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#705]
## Describe the bug

用户表users，自己添加的字段，删除不了

比如 单位 和 飞书id是我后增加的

## Screenshots

![image](https://user-images.githubusercontent.com/900786/182051872-706290ce-cddd-43fe-a5ff-1e36ec55b460.png)
![image](https://user-images.githubusercontent.com/900786/182051892-3ce996fd-bd29-4ed2-8891-3e79f995005a.png)

**Comment by chenos** [comment]
是什么版本的，早期旧版本升级的吗？

**Comment by baiheinet** [comment]
对 最新版 早期版本一致升级来的

**Comment by chenos** [comment]
sqlite 数据库需要找个数据库管理工具，手动的把表的外键约束都删掉。
