### ISSUE TITLE
多对多情况下自定义弹窗创建对端实体对象，无法建立关联关系

### ISSUE THREAD

**Issue by MarshalW** [nocobase/nocobase#716]
## Describe the bug

多对多情况下自定义弹窗创建对端实体对象，无法建立关联关系

## Version

Version 0.7.4-alpha.1

## How To Reproduce

实体 `新闻热点` 和 `创意` 是多对多关系（下面有截图），未定义中间表（由系统自动生成）。

在 `新闻热点` 列表页，行操作，自定义打开弹窗，创建新的 `创意` 无法和当前行 `新闻热点` 关联。

有关设置见下面录屏：

![Kapture 2022-08-09 at 18 32 26](https://user-images.githubusercontent.com/931976/183627673-1b3fe200-4326-458b-968a-be88fc814412.gif)

## Expected behavior

希望，多对多情况下自定义弹窗创建对端实体对象，可以保存关联关系。

## Screenshots

实体间关联的设置：

![image](https://user-images.githubusercontent.com/931976/183627113-3ee4698f-23aa-4e94-9c75-fcfc943727e3.png)

## Desktop (please complete the following information)

- OS:  macOS 12.4 (21F79)
- Browser chrome
- Version 版本 103.0.5060.114（正式版本） (x86_64)

**Comment by chenos** [comment]
录了个视频，可以这样加

https://user-images.githubusercontent.com/2993310/184281094-6c38567d-5b53-49dd-99a6-466d04798c07.mp4

**Comment by MarshalW** [comment]
谢谢支持。

按照你的视频视步骤，在另外实例做了一个最简单的，是可以的。

但是同样步骤在我的实际情况下没有保存关联关系。

我删除了所有相关表再做一次，是可以的。

之前曾弹出报错，可能有关联关系。

找了下，有这2个。

```
original: Error: Duplicate entry 'clue_tags' for key 'collections.name'
    at Packet.asError (/usr/src/app/node_modules/mysql2/lib/packets/packet.js:728:17)
```

```
RangeError: Maximum call stack size exceeded
     at new Model (/usr/src/app/node_modules/sequelize/lib/model.js:78:14)
```

后面我再留意下，看能否重现问题。

我先关闭这个issue了。
