### ISSUE TITLE
求解答：图表从API获取数据相关

### ISSUE THREAD

**Issue by ly120ve980ly** [nocobase/nocobase#728]
参考g2plot里面的demo1.tsx 的写法，把图表配置里面的data从写死数据改成调用api：
`"data":"{{ requestChartData({ url: '/test' }) }}",` 

但是没有起到作用，查看网络请求里面也没有尝试发起/test请求，希望作者解答一下图表如何动态获取数据，谢谢

**Comment by s405168882** [comment]
![image](https://user-images.githubusercontent.com/28327901/185270891-b0c1ab10-e2f6-49c4-a872-ab5deb830722.png)
地址这样写，我这是外部系统接口

**Comment by ly120ve980ly** [comment]
> ![image](https://user-images.githubusercontent.com/28327901/185270891-b0c1ab10-e2f6-49c4-a872-ab5deb830722.png) 地址这样写，我这是外部系统接口

最新版本里面确实可以了~
