### ISSUE TITLE
表单重复提交

### ISSUE THREAD

**Issue by m50046208** [nocobase/nocobase#754]
![image](https://user-images.githubusercontent.com/64178494/185336765-5a9d26a0-e3ac-46d4-a82b-ea7d7bafb036.png)
通过页面创建的表单，提交后，没有自动关闭功能，继续点击提交，内容会被重复提交到数据库

**Comment by zhouyanliang** [comment]
这里是使用技巧的问题，这个场景下应该使用 自定义操作来提交表单，定义提交表单之后的行为。 我们会在后续的使用手册种说明。
