### ISSUE TITLE
可以支持打印吗？

### ISSUE THREAD

**Issue by praming** [nocobase/nocobase#77]
比如销售单，可以支持自定义尺寸、字段打印吗？

**Comment by zhouyanliang** [comment]
暂时还不支持详细的打印配置，只支持调用浏览器的打印

**Comment by praming** [comment]
> 暂时还不支持详细的打印配置，只支持调用浏览器的打印

好的，非常感谢。请问后续有支持的计划吗？

**Comment by zhouyanliang** [comment]
有的。第二季度我们会发布较大版本升级，以及后续的路线图。
