### ISSUE TITLE
请问能否支持匿名访问/基本身份认识或者HTTP Header认证

### ISSUE THREAD

**Issue by missyoyo** [nocobase/nocobase#786]
你好：
     因为想把Nocobase集成别的系统，不希望用户单独输入用户名和密码进行登录，请问Nocobase是否禁用身份认证(匿名访问)，或者使用基本身份认证或者使用HTTP Header认证，这些认证方法都可以非常方便的与第三方系统进行集成，有劳解答，非常感谢.

**Comment by mytharcher** [comment]
目前的用户插件（plugins/users）支持从代码层面扩展认证方法，具体可以对 `authenticators` 注册中心进行扩展。由于暂时没有整理文档，所以这块只能先看代码来理解。

考虑该场景，可以扩展出 access_token 等方式的认证方法，以供第三方系统集成。

**Comment by missyoyo** [comment]
好的，非常感谢，我又仔细看了一下，目前的版本应该可以从API获取信息然后写到cookie里然后实现认证的，不过还是需要写一点代码去实现，当然以后要是有access_token就方便了，不用代码就可以实现。
