### ISSUE TITLE
本地windows没问题，安装到 ubuntu服务器后总是不能build

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#787]
由于windows 不能 start

安装到了ali轻量应用服务器  ubuntu 20.04 

pm2 方式部署
![image](https://user-images.githubusercontent.com/900786/187365943-1d1ec330-66ee-428d-a965-86c56b020a20.png)

每次vscode Remote-SSH 后 修改代码 build 就会出现一下错误 ，重启服务器 有时就能成功，不知是何原因

![image](https://user-images.githubusercontent.com/900786/187364903-491c452d-2fbc-4b41-9695-6386182a5fb1.png)

**Comment by chenos** [comment]
线上全量的 build 需要较大内存，大概需要 2.5G，内存不足就会报错。建议先构建 docker 镜像，然后在线上使用。
