### ISSUE TITLE
关联后的日期格式不起总用

### ISSUE THREAD

**Issue by baiheinet** [nocobase/nocobase#818]
## Describe the bug
原表
![image](https://user-images.githubusercontent.com/900786/189026871-7fa8fe50-b6a4-4f2d-96ae-f032dbc0013e.png)

关联后

![image](https://user-images.githubusercontent.com/900786/189027020-6c9d2f73-cdd0-41f8-a79b-507964184d6f.png)

**Comment by cxl945** [comment]
你好，你这边有其他操作吗？我这边复现不出来这个问题

**Comment by baiheinet** [comment]
就是系统默认关联方式 没有做其他设置
![image](https://user-images.githubusercontent.com/900786/189040194-041e1a8b-4921-4f18-bdd4-03d8945ae9ab.png)
