### ISSUE TITLE
 npx nocobase db-init

### ISSUE THREAD

**Issue by arcoirisapp** [nocobase/nocobase#82]
hi 
mkdir my-nocobase-project && cd my-nocobase-project
npm init
npm i @nocobase/api @nocobase/app
cp -r node_modules/@nocobase/api/.env.example .env

but when excute command  :  npx nocobase db-init

![image](https://user-images.githubusercontent.com/75837492/132992881-ef9d4389-5af2-4988-bb71-c7151bf1506a.png)

**Comment by chenos** [comment]
The win cmd path does not support colons. e.g. `menus:list` You can try cmder (bash mode) or git bash

**Comment by arcoirisapp** [comment]
ok thanks
