### ISSUE TITLE
表格中的附件下载链接，无鉴权可直接下载

### ISSUE THREAD

**Issue by justwho** [nocobase/nocobase#831]
（git源码安装，源码同步升级到20220916）
如下图示例，在nocobase中表格中的附件，只要拥有相对应的附件链接地址，即可直接下载到对应的附件（已经测试在没有登录过nocobase的电脑上也可以用链接直接下载打开相应附件）。虽然附件的存储到数据库中是一个随机名称，但担心有黑客可以直接通过遍历或者其他方式方法直接获取系统中的附件等信息。感觉不是很安全，希望官方可以在后续的更新升级中进行修复，可以提高系统安全性。谢谢！
![image](https://user-images.githubusercontent.com/22259834/190586692-63e435e2-f017-4771-bd5c-5830a4ca0f7d.png)

**Comment by chenos** [comment]
本地存储不会考虑权限问题，如果需要权限可以用类似于阿里云 oss 服务之类，这部分基础版暂时不会提供支持。
