### ISSUE TITLE
saas版本试用发现2个问题

### ISSUE THREAD

**Issue by dfar2008** [nocobase/nocobase#84]
1）配置字段时，会把上一个字段的标签带到新字段里，如果没有修改就无法修改了；
2）新配置数据表，新增记录保存不正常，不能保存数据，字段包含客户名称，地址（省市县），附件，备注（多行文本），状态（单选下拉框）
3）配置界面刚开始正常，后面到新配置的数据表就进不去了。
4）在订单里增加子表格不成功，增加一个产品明细，包含产品名称（关联产品数据表），数量，价格和备注，价格不能把产品数据表里的价格带入到子表格里
5）列表里字段不能冻结，当字段比较多的时候可以左右拖动，冻结的字段不动
6）没有自动编号类型的字段，例如订单编号不能自动生成
7）列表设置每页多少条数据时无法点击，总点不到数字
8）列表无法设置默认排序规则

**Comment by chenos** [comment]
感谢反馈
1. bug，下个版本修复
2. 是因为某些数据表字段被删除了，但是表格列还在。要先删除列再删除字段，要谨慎直接删除数据表字段。后续这里的细节也会逐步完善
3. 同上
4. 子表格现在还处于开发阶段，不可用，下一版会先 disabled 处理
5. 冻结的可以考虑
6. 自动编号类型的字段
7. bug，下个版本修复
8. 默认启用拖拽排序，需要先取消拖拽排序之后就可以设置排序规则了

**Comment by chenos** [comment]
感谢反馈，早先反馈的 1、7 问题已经修复并发布
现在系统的报错提示还不太友好，1、2 都和这个相关，这部分会作为接下来的重点，持续优化并发布。
3、4 都是自定义操作，接下来会以接口的方式开放给开发者自己扩展。无论是导入、打印或者其他操作开发者都可以根据自己的需求扩展。核心插件体系更完善之后，也会陆续完善和收集大家写的各类插件。

**Comment by chenos** [comment]
拖拽是因为图标太小了吗？除了增大图标，有什么更好的建议吗？
View 的建议挺好的，这样初始化的区块就是丰满的，不用再去一个一个添加，只需要微调就可以。
但是有个问题，如果是新建的字段不想在区块里显示或者不在某些区块里显示，有好的建议吗？
