### ISSUE TITLE
[ERROR] 14:24:55 Error: Dialect needs to be explicitly supplied as of v4.0.0

### ISSUE THREAD

**Issue by wumiangithub** [nocobase/nocobase#88]
yarn nocobase init

[ERROR] 14:24:55 Error: Dialect needs to be explicitly supplied as of v4.0.0

![image](https://user-images.githubusercontent.com/23608098/137263349-8433df97-dc92-4b77-91a1-6389c8efc081.png)

**Comment by chenos** [comment]
> 申请的在线预览地址也一直转圈打不开，
> https://a0r0679c21w9.demo.nocobase.com/
> 
> 

你现在用的什么浏览器，推荐使用 chrome。

**Comment by wumiangithub** [comment]
> > 申请的在线预览地址也一直转圈打不开，
> > https://a0r0679c21w9.demo.nocobase.com/
> 
> 你现在用的什么浏览器，推荐使用 chrome。

用的就是chrome

**Comment by chenos** [comment]
> 我是windows运行，没有Docker  执行不了
> docker-compose up -d postgres
> 可以吗

暂时不可以，月底会发布一个兼容sqlite的版本，到时候就可以不用安装数据库了。

**Comment by chenos** [comment]
> > > 申请的在线预览地址也一直转圈打不开，
> > > https://a0r0679c21w9.demo.nocobase.com/
> > 
> > 你现在用的什么浏览器，推荐使用 chrome。
> 
> 用的就是chrome

能够提供更详细的信息吗？类似你刚才上面截图这种。
