### ISSUE TITLE
编辑个人资料报错

### ISSUE THREAD

**Issue by shensven** [nocobase/nocobase#897]
## Describe the bug

编辑个人资料报错

## Version

`nocobase:0.7.4-alpha.7` `postgres:10`

## How To Reproduce

1. docker 服务启动完成后，使用 `admin@nocobase.com` 和 `admin123` 登录
2. 点击个人资料
3. 填写新的昵称，然后提交
4. 右上角通知提醒框：`column "roles" of relation "users" does not exist`

## Screenshots
<img width="901" alt="Xnip2022-10-12_17-43-40" src="https://user-images.githubusercontent.com/16205980/195311753-ad4a638d-589d-4b21-a387-5f124ee001db.png">
<img width="585" alt="Xnip2022-10-12_17-43-53" src="https://user-images.githubusercontent.com/16205980/195311773-16a75ce0-d55b-4c35-a29b-c28ae46672b9.png">

**Comment by mytharcher** [comment]
`main` 分支未能复现，可以等稍后我们发布新版镜像。
