### ISSUE TITLE
Formula field for logical operation (AND/OR/NOT)

### ISSUE THREAD

**Issue by azriel46d** [nocobase/nocobase#900]
## Describe the bug

The current implementation of the formula field , filters out any columns which are not numeric. In this way a logical formula such as `@type != 'car'` cannot be used and returns an invalid formula.
These are supported by the underling library. https://mathjs.org/docs/expressions/syntax.html 

## Version

Version 0.7.4-alpha.7

## How To Reproduce

1. Create a collection
2. Add fields which are of type string
3. Add a formula
4. Attempt to create a formula on the column

## Expected behavior

Be able to use logical operators in a formula.

**Comment by azriel46d** [comment]
On this, it seems mathjs is expecting only numeric functionality. The idea of the functionality required is more in line to an Excel sheet functions. Maybe this woudl be more inline utilising something like https://formulajs.info/ as a separate component where its not just a numeric formula. 
Willl see if I manage to do a PR on if it is deemed as something which fits with NocoBase.

**Comment by azriel46d** [comment]
PR created for this: https://github.com/nocobase/nocobase/pull/906

**Comment by mytharcher** [comment]
Please checkout `formula` field through new formula plugin.
