### ISSUE TITLE
关联数据查询的时候,非常慢

### ISSUE THREAD

**Issue by bioermaf** [nocobase/nocobase#909]
系统运行有二十天左右,服务没有重启过.
突然运行卡顿
所有关联数据,选择的时候,数据查询都非常慢.
![image](https://user-images.githubusercontent.com/64178494/195758880-ebb2d68c-9cbd-4427-83b1-dc51b795237a.png)

 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2382 root      20   0 1295332 450116  21332 R 139.9  3.7  12:50.33 node /nocobase/
 1191 mysql     20   0 2505884 477844  16276 S  17.9  3.9   2:46.78 mysqld

终端报错,不知道是否相关
Error: write EPIPE
      at afterWriteDispatched (node:internal/stream_base_commons:160:15)
      at writeGeneric (node:internal/stream_base_commons:151:3)
      at Socket._writeGeneric (node:net:817:11)
      at Socket._write (node:net:829:8)
      at doWrite (node:internal/streams/writable:408:12)
      at clearBuffer (node:internal/streams/writable:569:7)
      at Socket.Writable.uncork (node:internal/streams/writable:348:7)
      at connectionCorkNT (node:_http_outgoing:797:8)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by chenos** [comment]
main 最新版优化了加载关系数据慢的问题，预计这周末发布 v0.7.5。

**Comment by bioermaf** [comment]
> > 
> 
> 请试一下 0.7.5 是否还有问题

yarn create 方式安装的,yarn nocobase upgrade 升级了,还是0.7.4-alpha.7

升级的过程中有很多warning和下面这些输出
>>
warning "workspace-aggregator-99fe0dff-5d62-4a28-bbdc-ba89dc2403d9 > @my-nocobase-app/app-client > @nocobase/client > antd > rc-tabs > rc-dropdown@3.6.2" has unmet peer dependency "react@>=16.11.0".
warning "workspace-aggregator-99fe0dff-5d62-4a28-bbdc-ba89dc2403d9 > @my-nocobase-app/app-client > @nocobase/client > antd > rc-tabs > rc-dropdown@3.6.2" has unmet peer dependency "react-dom@>=16.11.0".
warning "workspace-aggregator-99fe0dff-5d62-4a28-bbdc-ba89dc2403d9 > @my-nocobase-app/app-client > @nocobase/client > react-big-calendar > react-overlays > @restart/hooks@0.3.27" has unmet peer dependency "react@>=16.8.0".
[4/4] Building fresh packages...
$ nocobase postinstall
WAIT: TypeScript compiling...
@my-nocobase-app/app-server: Clean dist directory
@my-nocobase-app/app-server: Build cjs with babel
@my-nocobase-app/app-server: Clean lib directory
@my-nocobase-app/app-server: Transform to cjs for src/index.js
@my-nocobase-app/app-server: Transform to cjs for src/config/database.js
@my-nocobase-app/app-server: Transform to cjs for src/config/index.js
@my-nocobase-app/app-server: Transform to cjs for src/config/plugins.js
@my-nocobase-app/app-server: Transform to cjs for src/config/resourcer.js
VERSION:  0.7.4-alpha.7

✔ Webpack
  Compiled successfully in 2.93m

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 DONE  Compiled successfully in 175847ms                                                                     12:47:36 AM

 File                                         Size           Gzipped

 packages/app/client/dist/umi.c8268baf.j      6.3 MB         1.7 MB
 s
 packages/app/client/dist/umi.460c1ee5.c      604.0 KB       76.4 KB
 ss

  Images and other types of assets omitted.


The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://umijs.org/docs/load-on-demand
You can also analyze the project dependencies using ANALYZE=1

upgrading...
✨  NocoBase has been upgraded to v0.7.4-alpha.7
Done in 522.91s.

是哪里没操作对吗

**Comment by bioermaf** [comment]
> > 
> 
> 请试一下 0.7.5 是否还有问题

升级到了.0.7.7,内容不卡顿了,各种弹窗似乎没原来的版本丝滑
