### ISSUE TITLE
请问为什么编辑用户信息会丢失用户的密码？

### ISSUE THREAD

**Issue by wbwm** [nocobase/nocobase#915]
我根据系统user表做了一个用户管理，但是编辑资料的时候，密码那个字段不会自动读取之前添加的密码，而是当作空数据提交了，所以每次修改用户资料，都会把他的密码清空，但是超级管理员账号却不会，请问是什么原因呢？我检查了密码自动也没有特别的设置啊？

**Comment by zhouyanliang** [comment]
可以将密码字段与资料字段分开，编辑资料的表单里不要有密码字段。
