### ISSUE TITLE
表单tab切换问题

### ISSUE THREAD

**Issue by zhanghpro** [nocobase/nocobase#927]
## Describe the bug

表单按tab切换输入框时，按tab次数不定，且无法控制.

## Version

0.7.4-alpha.7.

## How To Reproduce

1. 定义表单页面
2. 填充多个输入框
3. 光标定位在第一个输入框
4. 点击tab键进行输入框跳转

## Expected behavior

按一次tab跳转一个输入框.

**Comment by zhouyanliang** [comment]
月底发布的0.8版本会修复这个问题
