### ISSUE TITLE
ARM64 docker image support

### ISSUE THREAD

**Issue by TarekMahran** [nocobase/nocobase#940]
Is it possible to deploy Nocobase docker image on ARM64 server?

**Comment by chenos** [comment]
As long as docker can be installed.
https://docs.docker.com/engine/install/

**Comment by TarekMahran** [comment]
Hi @chenos

Docker is installed. but when I tried to install nocobase image I get error related to server architecture arm64 not supposed by this image. I think nocobase image should be built against ARM64 servers as AMD servers.

**Comment by chenos** [comment]
@TarekMahran The latest version includes arm64.

https://hub.docker.com/r/nocobase/nocobase/tags

<img width="587" alt="image" src="https://user-images.githubusercontent.com/2993310/197489863-885637d2-f654-44a2-92d4-6df72a4cb0d0.png">

**Comment by TarekMahran** [comment]
Thanks @chenos. I will try the arm image and give you the feedback.
