### ISSUE TITLE
表格里面关联数据排序报错

### ISSUE THREAD

**Issue by bioermaf** [nocobase/nocobase#975]
![image](https://user-images.githubusercontent.com/64178494/198449767-ec73500d-9021-4da7-b58b-8bcc6829d9f8.png)
关联数据字段,点击排序报错.
不排序,或者报错刷新之后可正常使用.

**Comment by hongboji** [comment]
请问nocobase是什么版本，什么数据库 ，环境是新安装的还是从某版本升级到某版本的

**Comment by bioermaf** [comment]
> 请问nocobase是什么版本，什么数据库 ，环境是新安装的还是从某版本升级到某版本的

0.7.4升级到. 0.7.7.alpha1, mysql数据库

**Comment by hongboji** [comment]
浏览器缓存清理一下再试试

**Comment by hongboji** [comment]
暂不支持
