### ISSUE TITLE
有没有大佬重构了vue版本啊？没有思路TAT

### ISSUE THREAD

**Issue by xiaosatufu** [nocobase/nocobase#98]
请问有没有大佬重构了vue版本啊，简直一点重构的思路都没有TAT

**Comment by chenos** [comment]
因为维护成本较高，无代码平台的客户端还是以 React 为主，但是并不代表就不能用 Vue 了。客户端并不是强绑定的，可以用任意前端框架实现，NocoBase 可以只提供 REST API，客户端开发自己来实现。

除此之外，目前，NocoBase 提供的客户端，内核设计主要有三个概念：

- 客户端请求
- 路由
- Schema 组件

React 的可以看这里的文档思路，以后有空可以补充一下 Vue 的核心思路
https://docs.nocobase.com/zh-CN/guide/kernel-principle/client-side-kernel

- NocoBase 提供了一套方便客户端请求的 JavaScript 版的 SDK —— API Client，API Client 是通用的。
- 路由，React 是基于 React Router，Vue 也有自己的 Router，配置非常接近，兼容处理就可以了。
- Schema 组件是基于 Formily 的，支持适配 React 和 Vue 的组件，有现成的 Ant Design、Fusion Design、Element 这些组件可以参考。

NocoBase 为了更贴合无代码平台需要，基于 React 版的 Ant Design 实现了几十个组件，如果有其他需要，大家也可以自行扩展，包括用 Vue 的实现。

更多细节，如果需求量大，以后可以考虑补充一下文档。

**Comment by Sebastianyang666** [comment]
佬，2024年了，现在支持vue生态了吗～
